### ISSUE TITLE
Automatic geolocation lookup when no center attribute is given

### ISSUE THREAD

**Issue by rguldener** [allenhwkim/angularjs-google-maps#110]
Currently when a map is initialized without a center attribute the directive performs a geolocation lookup of the user and then centers the map based on that geolocation. So this example would automatically perform a geolocation lookup:

``` HTML
      <map zoom=10 street-view-control="false"></map>
```

whereas this will not:

``` HTML
      <map zoom=10 street-view-control="false" center="[10,10]"></map>
```

Now the problem is that if the center attribute of the map is set anytime between the initialization of the map and the finishing of the geolocation lookup the map recenters unexpectedly when the geolocation lookup is finished. This is not expected behavior given that ng-map sells itself as "Expose all original Google Maps V3 api to the user. No hiding, no wraping, or whatsoever" - the original google maps API does not perform a geolocation lookup if the center tag is missing and neither should an Angular wrapper that claims to be just stock Google maps V3 API.

I think the proper way to include this feature would be to mask it with an attribute, eg. center-to-geolocation, such that his would **not** prompt a geolocation lookup:

``` HTML
      <map zoom=10 street-view-control="false"></map>
```

whereas this would:

``` HTML
       <map zoom=10 street-view-control="false" center-to-geolocation="true"></map>
```

**Comment by kirstilynn** [comment]
Is there an event for when center="current-location" is resolved?
