### ISSUE TITLE
Support for dynamically removing various layers or objects

### ISSUE THREAD

**Issue by vincentsels** [allenhwkim/angularjs-google-maps#124]
It's a bliss to be able to use directives to add all sorts of layers and other objects, with the use of the `mapController.addObject()` function. However, it's a shame those layers/objects aren't removed again upon 'destruction' of the directive. That would allow, for instance, easily switching layers on/off using bound checkboxes and the `ng-if` directive. I noticed you already support this for `<marker>` directives.

I think it should be doable for any layer/object. What's your opinion on this ? Have you considered or tried this but stumbled upon problems which were hard to overcome ?

**Comment by allenhwkim** [comment]
Closing, if you have a simple solution or complete the code with this feature, please send me a pull request. Personally, I do not see other objects rather than marker need to be synced to DOM object, but I might be wrong.
