### ISSUE TITLE
Silencing console.log

### ISSUE THREAD

**Issue by bnns** [allenhwkim/angularjs-google-maps#128]
This might be a silly request, but could you comment out the various console logs?

Example from Chrome dev console:
```
marker options Object events Object
ng-map.js:152 setting attribute to observe position position {{theMap.center}}
ng-map.js:152 setting attribute to observe title title {{currentLocation.name}}
ng-map.js:163 Mj "attributes to observe" Array[2]
ng-map.js:1282 filtered Object mapOptions Object mapEvents Object
ng-map.js:152 setting attribute to observe center center {{theMap.center}}
ng-map.js:163 Jj "attributes to observe" Array[1]
```

Could you comment these extra logs out in the next release? Also, thanks very much for such an excellent library!

**Comment by allenhwkim** [comment]
Thanks for using this . Console logs are already silenced fir mini field version. Do you also want it silenced for non minefield version?

**Comment by bnns** [comment]
Yes I think the non-minified .js should also be silenced because it is the main file in your bower.json. My grunt tasks use that when it is looking for dependencies.

**Comment by allenhwkim** [comment]
commit 131956c6b77d96c936039571621ee6177625c1ae
Author: Allen Kim <allenhwkim@gmail.com>
Date:   Fri Jan 2 09:31:02 2015 -0500

    issue 128, slienced console.log on both ng-map.js and ng-map.min.js
