### ISSUE TITLE
First Start is not correct

### ISSUE THREAD

**Issue by wap4444** [allenhwkim/angularjs-google-maps#129]
Hi! I have problem with first start...
When I first call map I see just Ocean near Africa...
But when I call second time a map I can see my locations...
Data for locations I get from JSON...

       <map center="[{{phone.adress_lat}}, {{phone.adress_lng}}]">
            <marker
                position="[{{phone.adress_lat}}, {{phone.adress_lng}}]"
                title="Hello Marker"
                animation="Animation.BOUNCE" 
                visible="true" ></marker>
          </map>

How can I see correct position in first time

**Comment by allenhwkim** [comment]
Thanks for using it.
It points to 0,0 in default because you are initializing the map before you get JSON data.

You can initialize the map by your event. Please take a look at this example.

https://github.com/allenhwkim/angularjs-google-maps/blob/master/testapp/map_lazy_init.html

https://rawgit.com/allenhwkim/angularjs-google-maps/master/testapp/map_lazy_init.html

**Comment by quachtd** [comment]
Hi Allen,

I use '<map center="current-location"..>', then I tried to get back the center (current location) from '$scope.$on('mapInitialized', function(event, map) { ... }', with 'map.getCenter()' but I didn't work, always return undefined.

Could you please show me how to get 'center' in this situation without calling another 'navigator.geolocation.getCurrentPosition'?

Thank you!
Dai

**Comment by quachtd** [comment]
Hi Allen,

I use '<map center="current-location"..>', then I tried to get back the center (current location) from '$scope.$on('mapInitialized', function(event, map) { ... }', with 'map.getCenter()' but I didn't work, always return undefined.

Could you please show me how to get 'center' in this situation without calling another 'navigator.geolocation.getCurrentPosition'?

Thank you!
Dai

**Comment by allenhwkim** [comment]
What is your approach, 1) Lazy Init, or 2) Providing center?

If 1). Please follow the example
If 2). You need to have scope.phone.address_lat, scope.phone.address_lat before you call JSON.

If you provide me a plnkr and tell me your approach, I can make a fix for you.

**Comment by quachtd** [comment]
Thanks Allen for promptly reply. 
I'm using this '<map center="current-location" zoom="15" ...>' to initial my location. Don't use 'init-event'! It should be #2, right?

And in the controller, I'm using '$scope.$on('mapInitialized', function(event, map) { var loc = map.getCenter(); ...'. I want to reuse 'loc' to create marker, circle later, but 'loc' is always 'undefined'.

Do you have any suggestion?
Thanks.

**Comment by allenhwkim** [comment]
Can't tell before I see your example. Here is my guess

 1.  `center=''`, will invoke geo-location callback to google to get the current location
 2.  map is initialized without center
 3.  If permitted, you will get the map displayed with the current location

If you think this answer is not helpful, please provide a plnkr example. You can create it easily from ngmap.github.io.

**Comment by quachtd** [comment]
Thanks, Allen.
Here it's: http://plnkr.co/edit/mdB7y1OHzSFMEOyrZ7ml?p=preview

Please have a look.

**Comment by allenhwkim** [comment]
http://plnkr.co/edit/BwmWIOhJESqJamL3Nett?p=preview
First, you need to respond to the question "Browser want to use your location"

added geo-fallback-center

**Comment by quachtd** [comment]
Oh no, it's not what I mentioned.
Please look back my link, then see the my comment.
"
$scope.myloc = map.getCenter(); //DOESN'T work
$scope.myzoom = map.getZoom(); //but this works
"

**Comment by allenhwkim** [comment]
http://plnkr.co/edit/TlB06Ak2zpM3fYEQPoDA?p=preview

As long as you set center="current-location", you won't get center when map is initialized.
If you want to get an empty center, set center="0,0" or anything

**Comment by quachtd** [comment]
Allen,

Sorry my last link is not latest, it's missed. Please use this:
http://plnkr.co/edit/V0tNtRRKBoTCJK2e3LKN?p=preview

**Comment by allenhwkim** [comment]
http://plnkr.co/edit/S3g7NNY0upX1O7a422bn?p=preview

As I told you, current-location is available asynchronous basis, thus you have to wait.
If you want to use that current location as a marker, then you need to do all programing inside that $timeout block. It gets complex, right?

If you want to simply add a current-location as a marker, just add a marker as current location.

http://plnkr.co/edit/thmTgmVs90o2BVqwWFdl?p=preview

**Comment by wap4444** [comment]
Hi, Allen!
How can I initilized google maps before I get JSON data?

**Comment by allenhwkim** [comment]
@wap4444, map is  always initialized with map tag regardless of your json data unless you do lazy init.

**Comment by quachtd** [comment]
Thanks Allen,

I use Location to dynamically draw sharp and marker, so will not work with static tags.
Is there another way to get the location without timeout (timeout is not stable, it depends on other stuffs and be different every loading time)? Or can we reuse/get 'google.maps.Map' object from map tag?

**Comment by allenhwkim** [comment]
@quachtd thanks for not giving up. 

Using raw code is the main target of this module. Check out these two example.


1. Marker without using static tag(raw coding)
    https://rawgit.com/allenhwkim/angularjs-google-maps/master/testapp/marker_dynamic_raw.html

2. Starbucks Stores in the world. 
   https://rawgit.com/allenhwkim/angularjs-google-maps/master/testapp/map_app.html

For both, you only requires only map instance without any markers. You can control markers or map in Javascript,

**Comment by allenhwkim** [comment]
Closing, please reopen it if you have more questions

**Comment by kiempoturner** [comment]
Hi Allen,

Im trying to do something like this, hot location: 

Starbucks Stores in the world. 
https://rawgit.com/allenhwkim/angularjs-google-maps/master/testapp/map_app.html


But I cant seem to make the circles appear. Ive read through your Circle documentation, still cant find whats wrong. Here's my js:

````javascript
.controller('CircleSimpleCtrl', function($scope) {
    $scope.cities = {
      kualalumpur: {population:2714856, position: [3.139258, 101.687037]},
    }
    $scope.getRadius = function(num) {
      return Math.sqrt(num) * 100;
    }
  })
````

HTML:
````html
     <div ng-controller="CircleSimpleCtrl" class="ng-scope">
      <map center="3.9330876, 102.6204319" zoom="7" maytypeid="TERRAIN">
      </map>
    </div>
````
