### ISSUE TITLE
Do you plan to implement a fitBounds method?To zoom out to show all current markers.

### ISSUE THREAD

**Issue by naume** [allenhwkim/angularjs-google-maps#130]

**Comment by allenhwkim** [comment]
I think this is a callback of an event, and it should not be a part of directive.
We still can have that callback(fitToBounds) function registered into a directive, however it won’t be called automatically

The implementation will look like this

`<map .. on-zoom-changed=“fitToBounds()” ></map>`

If you have a good example of fitToBounds function, please let me know.

Allen
