### ISSUE TITLE
Multiple InfoWindow

### ISSUE THREAD

**Issue by theaqua** [allenhwkim/angularjs-google-maps#131]
Hello, thanks for your module!

I'm trying to use multiple InfoWindow (got code from http://ngmap.github.io/drawings.html#/infowindow-simple#infowindow-simple) with ng-repeat, but it doesn't work. How I can use multiple IW in my HTML?

Here's [my example](https://gist.github.com/theaqua/579241a0a2123002aefa).

Here's error: 
![screen shot 2015-01-19 at 18 25 30](https://cloud.githubusercontent.com/assets/775692/5802719/97c8f1a6-a008-11e4-8b22-3f54f2682e6b.png)

**Comment by allenhwkim** [comment]
info-window should not be used within ng-repeat, and for your case, info-window has unique contents and it can be called with marker info. Thus, please use one info-window, and use on-click method. i.e.,  `on-click=showInfoWindow('my-info-window`)". There are examples you can find in the testapp directory.

**Comment by theaqua** [comment]
I see the point. Thanks, I have an idea and will try!
