### ISSUE TITLE
When I include map with ng-if, map broken on second click

### ISSUE THREAD

**Issue by theaqua** [allenhwkim/angularjs-google-maps#132]
Hello again.

I have small bug.
1) I initialize map in background using ng-if

    <section ng-if="list.view.tab == 'view' && list.view.type == 'map'">
      <map zoom="11" center="[55.72310428213402, 37.12836326599118]" scrollwheel="false" street-view-control="false" max-zoom="16" class="map-full-list"></map>
    </section>
2) Then I go to map, it shown.
3) Then I hide map (using ng-if state, of course)
4) And when I show map another time, it center in somewhere, not my value in `center` attribute.

You can try this bug on http://dev.rublevka.ru/#/buy/
1) Click to pin.
![screen shot 2015-01-19 at 20 58 59](https://cloud.githubusercontent.com/assets/775692/5805245/35a8a9b0-a01e-11e4-8fdb-ae67e1258ff1.png)
2) Check out map — markers correctly loaded in center.
3) Then click back to cards view
![screen shot 2015-01-19 at 20 59 12](https://cloud.githubusercontent.com/assets/775692/5805255/589a73fe-a01e-11e4-8c76-932ffbfd0c0e.png)
4) And then go map again and saw this bug.

**Comment by allenhwkim** [comment]
This has been discussed several times. Unfortunately this is status quo of google map.  Please check this issue.

https://github.com/allenhwkim/angularjs-google-maps/issues/88

**Comment by allenhwkim** [comment]
Closing, if you think we can solve this problem in a directive level, please let me know or send me a pull request.  By the way, you have a wonderful site.
