### ISSUE TITLE
Streetview Panaroma with a marker.. 

### ISSUE THREAD

**Issue by rasekar2000** [allenhwkim/angularjs-google-maps#133]
Following https://github.com/allenhwkim/angularjs-google-maps/issues/40 , I am trying to add a marker on a StreetViewPanaroma , but the marker is not getting added ...

So, mixing up following two things into 
https://rawgit.com/allenhwkim/angularjs-google-maps/master/testapp/map_street_view.html , 
https://rawgit.com/allenhwkim/angularjs-google-maps/master/testapp/marker-remove.html

http://plnkr.co/edit/BrGzXVXAjh04aEYbwsvU?p=preview
   I see that this one is shared in View only mode.. Not sure how to share an editable mode..

Can you please let me know , how to fix this?

Thanks a ton in advance.

Regards,
Raj

**Comment by allenhwkim** [comment]
I don't think we can add a marker on a street view. marker requires lat/lng, and streetview does not have that concept. Let me know if you find any example that adds marker on a streetview.

**Comment by rasekar2000** [comment]
Please find the Example  ..
 http://plnkr.co/edit/MeQDKjHA34PcPa53Zr9o?p=preview
![statueofliberty 2](https://cloud.githubusercontent.com/assets/3443965/5888267/e9d13e52-a3ac-11e4-959a-4ec8c0441d97.png)

**Comment by allenhwkim** [comment]
Oh, I see. You want to show an exact spot as a marker on a street view.
It would be useful if you can show this is my store and that is your house on the streetview.
Let me see if it is possible.

**Comment by rasekar2000** [comment]
Thanks very much.. Yes.. Will be using some of the functionalities of StreetViewPanorama ..
Regards,
Raj

**Comment by allenhwkim** [comment]
Although I covered almost all of the google maps api, I haven't covered all the service sections. Streetview is one of them. I can see the example here, https://developers.google.com/maps/documentation/javascript/examples/streetview-overlays, and let me see I can do something about it.

**Comment by allenhwkim** [comment]
I made this based on the example, http://plnkr.co/edit/UqtOXx?p=preview.
This could be your good starting point. Let me know if you need more.

**Comment by rasekar2000** [comment]
Thanks for the quick answer .. Yes.. Given streetview-overlays example switches between StreetView and Panorama. But  I am looking forward more towards this example https://rawgit.com/allenhwkim/angularjs-google-maps/master/testapp/marker-remove.html on a StreetViewPanorama.. Appreciate your time on a weekend time.. 

Regards,
Raj

**Comment by allenhwkim** [comment]
I think it will work with that examples too. I think all you need to do is to switch to streetview. Please try it and let me know if it does not work.

**Comment by rasekar2000** [comment]
Sure.. Let me try and get back to you..
Thanks and Regards,
raj

**Comment by rasekar2000** [comment]
Hi Allen,

Great help.. I could move forward.. But one minor issue.. 
http://plnkr.co/edit/2C2Xvoj4MivbPq3LLQUl?p=preview is my working copy.

 On the Click, the GBView Pano behavior is overtaking the addMarker() function. can you please suggest a solution.

Thanks and Regards,
rAj

**Comment by rasekar2000** [comment]
If I toggle and add a marker and come back to street view, i could see the marker, but not in the street view directly .. Let me try double click etc.. 

Thanks and Regards,
Raj

**Comment by allenhwkim** [comment]
It seems all working fine for me.

**Comment by allenhwkim** [comment]
Closing, please reopen this issue if you think it's not resolved

**Comment by rasekar2000** [comment]
http://www.wenda.io/questions/5266797/google-streetview-location.html is the helpful answer .. Still not as simple as adding a marker on the MapView compared to this StreetViewPanorama.
Thanks and Regards,
Raj
