### ISSUE TITLE
Show multiple infoWindows at the same time

### ISSUE THREAD

**Issue by tomchambers2** [allenhwkim/angularjs-google-maps#134]
I see that I can have multiple infoWindows for markers by swapping out the contents as in #131, but I'd like to be able to have all the infoWindows appear on load. I tried various forms of ng-repeat like:

```
	<section ng-repeat="window in cinemaWindows">
		<info-window
		position="{{window.coords.latitude}},{{window.coords.longitude}}"
		id="bar"  visible="true">
		<div ng-non-bindable>
		  Window text
		</div>
		</info-window> 		
	</section>
```

but nothing shows up at all when doing that

**Comment by allenhwkim** [comment]
Try removing `id`, If that not working, please provide me a plnkr. I will look into it.

**Comment by tomchambers2** [comment]
Link to plunkr: http://plnkr.co/edit/CoJrqAUrc213HMOlGqOC?p=preview

**Comment by allenhwkim** [comment]
it seems info-window is not working within `ng-repeat`.
It only works under `map` tag, http://plnkr.co/edit/69KNhUMYNyZD54MYU6fQ?p=preview

As I discussed in #131, I did not have intention to repeat  info-window with the same contents.
Thus, please if you want to show multiple infoWindows, please do raw coding(google maps way) without considering this directive.

The examples are here, https://developers.google.com/maps/documentation/javascript/infowindows#open

and you can find several raw coding examples under testapp directory

**Comment by tomchambers2** [comment]
Ok thanks for the help
