### ISSUE TITLE
Markers that were added with ng-repeat not all shown on map

### ISSUE THREAD

**Issue by yupitomets** [allenhwkim/angularjs-google-maps#135]
I noticed that it shows me not more then 10 markers, but mappable array is around 25 items. Also mappable.LOCATION could be in two different languages, but its works fine when I have around 10 elements in array.

<div ng-repeat="mappable in mappables">
      <marker position="{{ mappable.LOCATION }}" animation="Animation.DROP"  on-click="showInfoWindow(event, 'bar')"></marker>
</div>

**Comment by allenhwkim** [comment]
I have tested with more than 25, and it worked. Please add me your example using plunker, so that I can take a look at your code.

**Comment by yupitomets** [comment]
Please try to open that page. http://yuppi.com.ua/#!/map 

Select "Одесса" фром Drop Down. And after that press "Фильтровать" blue button. Map will be loaded and you will see two markers in this area. But there are should be 12 markers in that area (Odessa city)

All markers that should be displayed on map are printed out next to the map. First line of text is the address. (Example of address: Ніжинська вул., 34, Одеса, Одеська область, Украина)

**Comment by allenhwkim** [comment]
I am not going to debugg your app. it's too much :).  please make a plunker.

**Comment by yupitomets** [comment]
THis is what I have http://plnkr.co/edit/vxdRjWujOHShufBRhA1F

**Comment by allenhwkim** [comment]
This happens because you are calling GeoCoding service too often. If you want to avoid, please use the exact location of each marker so that GeoCode is not called. Google is not happy with frequent service call. i.e. "Toronto, Canada" in location calls geo coding service, but "0,0" does not call the service.

**Comment by allenhwkim** [comment]
Closing, I also added ng-map.debug.js, so that you can see the geoservice call success/fail.
Please reopen this if it is not about Google geocoding service
