### ISSUE TITLE
Map doesn't center on maker when screen size changes or phone tilts

### ISSUE THREAD

**Issue by junerockwell** [allenhwkim/angularjs-google-maps#136]
I'm using your exact example on a $ionicModal. I took out **info-window** and used **marker** instead having the same values for maker.position as the map's center. When I click to load up the modal view on a browser after it has been newly refreshed, everything looks and works great. But when I close the modal, resize the window (either bigger or smaller) and then load up the modal view, the pin isn't visible anymore because the map isn't centering on the maker's position. I have to drag it to find the marker. The same thing happens when I installed this on an iPhone5S (iOS8) but since I can't resize the window, I tilted it or switched from portrait to landscape. Is this just a google maps v3 issue? Do you have any workarounds?

I've provided a gist: https://gist.github.com/junerockwell/6437dca42fdfe0f7c696

**Comment by allenhwkim** [comment]
Yes, we talked about it here few times, unfortunately I can't do much about it. It's google maps issue.
You can manually setCenter. I can't find the issue number at this time. If you can't find, I will be back to you later.

**Comment by junerockwell** [comment]
Are the map.center array values or strings? 
i.e. $scope.$on('mapInitialized', function(event, map) {
        map.setCenter([36.168930,-115.189049]);
});

or

$scope.$on('mapInitialized', function(event, map) {
        map.setCenter(36.168930,-115.189049);
});

Also, do I have to set the map's center value on the markup even if I'm setting the center programmatically in the controller? Because right now, it's not working. 

Thanks.

**Comment by allenhwkim** [comment]
map.setCenter take parameter as LatLng object as specified here, https://developers.google.com/maps/documentation/javascript/reference#Map

**Comment by junerockwell** [comment]
Hey. Would it help if I give you this CodePen? http://codepen.io/anon/pen/WbOjbv

This person uses the google maps v3 as well. When you click the button, it pops-up a $ionicModal. The map always centers itself without refreshing the browser. 

I think this code snippet does the job: 
google.maps.event.addListener(map, "idle", function () {
    google.maps.event.trigger(map, 'resize');
});

**Comment by allenhwkim** [comment]
Thank you for your code. I did look at the example that you gave me, but I did not look into it deeply. 

This is what I know,
1. `google.maps.event.trigger(map, 'resize');` does redrawing map, not centring it.
2. I might be wrong about it but the example creates the map every single time when it clicks. If you recreate the map it always work as like the first open of the map always work.  this module does not re-create the map unless you remove and re-create the DOM. 

Since I see this question third time, it's worthy to look for the solution. If you can suggest any, that would be wonderful while I find something good solution.

**Comment by allenhwkim** [comment]
I made a solution for you. Let me know if this solves your problem.

http://plnkr.co/edit/D2Ti9gF9YyJe4rcFcijV?p=preview

**Comment by junerockwell** [comment]
Hmm for some reason, the map doesn't appear anymore even when I copied and pasted your code from that Plnkr. I'll play around with it. Thanks for trying!
