### ISSUE TITLE
Google Map View Height Change

### ISSUE THREAD

**Issue by rasekar2000** [allenhwkim/angularjs-google-maps#137]
http://ngmap.github.io/basics.html#/map-simple#map-simple

http://plnkr.co/edit/o2ngjeJ0an9rzsCpAv2V?p=preview

Playing around to change the height in the DIV , but the resize is not happening after certain points.. 
Especially the Height ..

Can you please let me know, if I need to set any other fiedls in map Directive or so?

But in this example, i could see the heigh in the DIV is adjustable and reflecting properly.
http://www.w3schools.com/googleapi/tryit.asp?filename=tryhtml_map_controls_custom

 I mean this div height.. 

<p> <code>
<body>
<div id="googleMap" style="width:500px;height:500px;"></div>
</body>
</code></p>

Thanks in advance.

**Comment by allenhwkim** [comment]
if you are talking about div tag height, it's not related to this module.
If you are talking about map height, you need to specify the height of map to 100%

    <style>
      map {height: 100%;}
    </style>

**Comment by rasekar2000** [comment]
Yes.. https://github.com/allenhwkim/angularjs-google-maps/issues/13 helped me to resolve this ..
