### ISSUE TITLE
A <marker> inside the <map> causes browser to prompt user for geolocation consensus...

### ISSUE THREAD

**Issue by marcolino** [allenhwkim/angularjs-google-maps#139]
A <marker> tag inside the <map> tag causes browser to prompt user for geolocation consensus...
Is it avoidable with any attribute? Or is it indended behavoiur?
The prompt can be misleading...

I do not need user position (at the moment, at least): I just want to display a google map of a pre-fixed position (the map is in a bootstrap modal-dialog, shown upon user request, but this shouldn't be an issue, I suppose...).

**Comment by marcolino** [comment]
I did just solve the issue myself, sorry...
The problem was the marker's position wasn't yet set when the page is loaded, and map and marker tags evaluated... The marker position is set in a $http callback... Just initializing marker position to "[0, 0]" did the trick... :-)
Sorry for bothering...

**Comment by allenhwkim** [comment]
Yes, you can set marker position. If not set, the directive try to find the current location instead of raising exception.
