### ISSUE TITLE
add google drawing manager library

### ISSUE THREAD

**Issue by Fangmingdu** [allenhwkim/angularjs-google-maps#140]
do you have any plan to add the drawing manager to be a directive? That would be very convenient and helpful!!

**Comment by allenhwkim** [comment]
Please be specific. I am strictly following standard Google Maps API v3. if drawing is there, I will look into it.

**Comment by Fangmingdu** [comment]
https://developers.google.com/maps/documentation/javascript/drawinglayer#drawingmanager_options

it is an additional library provided by google and it allows users to choose what to draw on the map and it has a bunch of options and events associated with it.

I also saw the drawing manager is a directive in the other Angular Google Map library.
Please take a look at the link below and click "drawing-manager" in directives section.
http://angular-ui.github.io/angular-google-maps/#!/api

Thanks for looking into it.

**Comment by allenhwkim** [comment]
Very interesting. I will do it, but you need to wait. :)
Here is the brief design for this directive.

1. It must initialize drawing-manager properly accepting all these options and parsing properly
  * drawingMode
  * drawingControl
  * drawingControlOptions
  * markerOptions
  * circleOptions
  * polygonOptions
  * polylineOptions
  * rectangleOptions
2. it must handle all events properly by accepting callback function as a directive attribute
  * on-circlecomplete
  * on-polygoncomplete
  * on-polylinecomplete
  * on-rectanglecomplete
  * on-overlaycomplete
  * on-markercomplete
3.  When overlay is complete, it also must able to add to the collection of map objects
  * $scope.map.markers
  * $scope.map.shapes
4. In default, it does not provide removing overlays. For complete directive, it must provide the feature of removing overlays also. (http://stackoverflow.com/questions/11632402/removing-polygon-from-google-maps-drawingmanager-v3). When an overlay is removed, the collection of objects related to the map also has to be maintained.
  * $scope.map.markers
  * $scope.map.shapes
  
As you see, to get it done right, it requires lots of coding and test. Personally, I do not think ui-map has done it properly, and I don't want to go that way.

**Comment by Fangmingdu** [comment]
Looks great! Thanks for the comment!
It is a lot of coding to make a complete directive. I'm interested in contributing, when I have time on my end, as we want to use this directive :)

**Comment by Fangmingdu** [comment]
Hey Allen,

I just started looking into it today. Hopefully got part of it done.

**Comment by allenhwkim** [comment]
@Fangmingdu Nice, please feel free to copy/paste from the existing code.

**Comment by Fangmingdu** [comment]
Thanks!
I'll just post questions I got here. You can take a look when you have time.

I'm thinking about parsing the array attributes and complex options in the following way
array attributes like drawingModes can be 
```
drawing-modes="POLYGON,MARKER"
```
complex options can be parsed like  (similar to the style attribute in html)
```
circle-options="fillColor: '#ffff00';fillOpacity: 1;strokeWeight: 5"
```

```
<drawing-manager drawing-mode="MARKER" position="LEFT_BOTTOM" drawing-modes="POLYGON,MARKER" drawing-control="false" circle-options="fillColor: '#ffff00';fillOpacity: 1;strokeWeight: 5" ></drawing-manager>
```

Let me know what you think and I am trying to follow all the naming conventions and styles you use in your code.

**Comment by allenhwkim** [comment]
@Fangmingdu there is a parser inside Attr2Options. You should use that instead of building your own.

**Comment by allenhwkim** [comment]
You can add me on your IM and send me an invitation, allenhwkim AT gmail.com

**Comment by Fangmingdu** [comment]
Found a few options wont pass your attr2_options.js. I'll list them.

1. it wont pass ControlPosition.TOP_CENTER
fix it by change the regex to accept _ in the second part. (line 79)

2. it wont pass drawing.OverlayType.POLYGON.
it is assuming all object defined in google is google.maps.xx.xx, but sometime not

3. it wont pass circleOptions="fillColor: '#FFFF00';fillOpacity: 1;strokeWeight: 5;"
fix by adding another regex to match and return an object.

**Comment by Fangmingdu** [comment]
take a look at all the changes. any comments?
https://github.com/Fangmingdu/angularjs-google-maps/compare/allenhwkim:master...master

thanks!

**Comment by Fangmingdu** [comment]
You are right.. I should have read more on how you used it.

reverted some changes. and I changed the way how attributes were parsed into drawing manager.

**Comment by allenhwkim** [comment]
This is great. Please send me a pull request, so that I can add you as s contributor.

**Comment by Fangmingdu** [comment]
Thanks Allen! I just make a few more changes to make it more complete and did the pull request.

**Comment by allenhwkim** [comment]
Closing, we will add remove button later when it is required.
