### ISSUE TITLE
Infobox - Advanced version of Infowindow

### ISSUE THREAD

**Issue by rasekar2000** [allenhwkim/angularjs-google-maps#141]
Hello Allen,

 Heard Infobox is advanced version of Infowindow. 
http://google-maps-utility-library-v3.googlecode.com/svn/trunk/infobox/examples/infobox-basic.html

 Can you please consider wrapping JS for this one as well when you get a chance ?

Some more details in the answer
   http://stackoverflow.com/questions/16716524/how-to-make-an-info-window-clickable

Thanks and Regards,
Raj

**Comment by allenhwkim** [comment]
this is community code
I do not have a plan, but wecolme contributions
