### ISSUE TITLE
ng-repeat does not work inside <info-widnow/>

### ISSUE THREAD

**Issue by yupitomets** [allenhwkim/angularjs-google-maps#142]
This is what I have in controller:

$scope.test = {};
$scope.test.parameters = [1, 2, 3,4];

This is what I have inside <map>:

marker position="46.143321, 53.35254" animation="Animation.DROP" icon="blue_marker.png" on-click="showInfoWindow(event, 'bar')"></marker>
 info-window id="bar" visible-on-marker="foo">                           
  p ng-repeat="parameter in test.parameters"> {{ parameter }}</p>
/info-window>

**Comment by allenhwkim** [comment]
Thanks for using this module, 
`info-window` should not be inside `ng-repeat`, There are several examples in testapp directory, and all `info-window` are not used with ng-repeat.
