### ISSUE TITLE
Basic Use On Mobile lead to App Crash

### ISSUE THREAD

**Issue by ayman88** [allenhwkim/angularjs-google-maps#143]
I am developing Phonegap app using ionic framework, and I used ngMap for Google Map and it works good, but the issue happend when I am testing device and tracing the Memory usage, I found out when open one Map Page, it consumes a lot of memory, OK No problem, The problem is the map doesn't destroyed from the memory after closing the Map, So After many times openning Map Page, it leads to App crash.

**Comment by allenhwkim** [comment]
Thanks for using this,

https://www.google.ca/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=google%20map%20delete%20map%20instance

From the information I learned, we should not create a new instance for SPA and use existing map, which is global. It's worth to look at it, and I will look into it.

**Comment by ayman88** [comment]
@allenhwkim  Did you find a work around?

**Comment by allenhwkim** [comment]
Haven't tested yet, but this I will try. Currently on other project and will be back to this later.

app/scripts/directives/map.

Before:

      var initializeMap = function(mapOptions, mapEvents) {
        var map = new google.maps.Map(el, {});    // This creates a new map and will stay in memory
        map.markers = {};
        map.shapes = {};

After:

      var initializeMap = function(mapOptions, mapEvents) {
        var map = window.myOnlyMap || new google.maps.map(el, {});  // will use only one map
        window.myOnlyMap = map;
        map.markers = {};
        map.shapes = {};

However, this approach does not allow multiple maps. Need to check map id.

**Comment by ayman88** [comment]
@allenhwkim  Actually, I found out that the bug in Google Map Api it self, and Google team that it won't be fixed because it is very difficult  https://code.google.com/p/gmaps-api-issues/issues/detail?id=3803 ,
But after reading, I find some people said that they made work around which is clearing events manually and remove any elements, but I actully , I don't how to implement that :( 

/////google.maps.event.removeListener(listener1);

**Comment by allenhwkim** [comment]
@ayman88 thanks for finding solution. I don't think it's about a listener(I may be wrong), but it's about map instance itself. They said not to create a map again and again. You may try my approach(nothing to lose, i guess) and let me know.

**Comment by ayman88** [comment]
@allenhwkim  I tried your approach, but NO Map At all, it gives me white page.
My approach was about reduce memory usage only.

**Comment by allenhwkim** [comment]
It seems working, http://plnkr.co/edit/mk5JJaV5euf9vBKzoz8k?p=preview
Haven't tested it reduces memory though.

**Comment by ayman88** [comment]
@allenhwkim  here's my email: aymanmostafa88@gmail.com , if u kindly send the new ng-Map.js file, and I will trace the memory.

Thanks Allen

**Comment by allenhwkim** [comment]
https://rawgit.com/allenhwkim/angularjs-google-maps/master/build/scripts/ng-map.js
https://rawgit.com/allenhwkim/angularjs-google-maps/master/build/scripts/ng-map.debug.js
https://rawgit.com/allenhwkim/angularjs-google-maps/master/build/scripts/ng-map.min.js

It's all downloadable.

**Comment by ayman88** [comment]
@allenhwkim  Bad NEWS :( , the map works only in the first time, but when trying reopen same page or any map page, Blank Page !!!

**Comment by allenhwkim** [comment]
@ayman88 plz send me your full html, so that I can take a look at it.

**Comment by ayman88** [comment]
CTRL:
function Controller($scope) {
    var CivilRegistry = [
         {
             "id": "1",
             "name": "Test1",
             "lat": "29.957565",
             "long": "31.212742",
             "city": "Cairo"
         },
         {
             "id": "2",
             "name": "Test2",
             "lat": "29.408060",
             "long": "31.252741"
         },
         {
             "id": "3",
             "name": "Test3",
             "lat": "30.052924",
             "long": "31.230419"
         }]



    for (var x = 0; x < CivilRegistry.length; x++) {
        if (CivilRegistry[x].id == $stateParams.id) {
            $scope.Map = CivilRegistry[x];
            break;
        }
    }


}


HTML:

<div ng-controller="apController" title="ى {{Map.name}}">
    <div >
      
        <div class="angular-google-map-container">

                <map draggable="true"  class="angular-google-map" zoom="17"
                    center="[{{Map.lat}}, {{Map.long}}]">

                    <marker position="{{Map.lat}}, {{Map.long}}" title="{{Map.name}}">
                        </marker>

                  
                </map>
            </div>
    </div>
</div>


ngMap.js:

I used this one ur link : http://plnkr.co/edit/mk5JJaV5euf9vBKzoz8k?p=preview

**Comment by ayman88** [comment]
@allenhwkim  Did you try it with Multible map pages?

**Comment by allenhwkim** [comment]
No I do not have your use case

Please provide me an example of your use case so that I can reproduce your problem on my end

**Comment by ayman88** [comment]
Thanks Allen, I'll do it :)

**Comment by allenhwkim** [comment]
Closing by Inactivity

**Comment by pcsantana** [comment]
@ayman88, did you find any solution for this? I'm facing the same problem =/

Thank you!
