### ISSUE TITLE
goolge-maps always ask to share location

### ISSUE THREAD

**Issue by yupitomets** [allenhwkim/angularjs-google-maps#145]
I don't know if it is a defect. Is there a way to configure anguar-google-maps not to ask user share his location?

**Comment by allenhwkim** [comment]
Please specify center="0,0" if you don't mind. If center is not given, ngmap does not know how to set center, and ngmap try to find your location and set the center.

**Comment by yupitomets** [comment]
I am using center variable to bind it from controller.
It shows me correct positioning but also ask for location in case center = "49,31"

map ng-if="filtered" style="height: 500px;" zoom="{{ zoom }}" center="{{ center }}">

**Comment by allenhwkim** [comment]
then the center is not set when the controller starts, using ajax i guess.
$scope.center="0,0"

**Comment by yupitomets** [comment]
center is set correctly, in other case map wall be not positioned.

Please take a look at my video.

https://drive.google.com/file/d/0B9p7S1WlVmbnaW1vdS1vd0hHYzA/view?usp=sharing

2015-02-12 10:54 GMT-06:00 Allen Kim <notifications@github.com>:

**Comment by allenhwkim** [comment]
console.log('$scope.center', $scope.center) at the end of your controller.

**Comment by yupitomets** [comment]
[image: Встроенное изображение 1]

2015-02-12 11:04 GMT-06:00 Allen Kim <notifications@github.com>:

**Comment by allenhwkim** [comment]
[image: Встроенное изображение 1] ? 
I can't go on like this. Please provide me a full working example by plnkr or jsfiddle

**Comment by yupitomets** [comment]
I will make it.

**Comment by allenhwkim** [comment]
Closing By Inactivity
