### ISSUE TITLE
Html map tags adds google-map 

### ISSUE THREAD

**Issue by yupitomets** [allenhwkim/angularjs-google-maps#146]
I using html map tag http://www.w3schools.com/tags/tag_map.asp, and this map is processes by angular and angular think that this is a directive. Is there a way to avoid for angular not to treat that as directive?

**Comment by allenhwkim** [comment]
Use google map as an attribute, i.e. `<div map></div>` instead of `<map></map>`.

**Comment by yupitomets** [comment]
Thanks for replay, but you probably got me wrong. <map> this is standard HTML tag. And when angular see this tag, he treat is a directive, but this is not a directive. Please follow link that I send to see more about <map>

**Comment by allenhwkim** [comment]
I agree with you. This tag has to be renamed to something else. i.e. `ng-map`. However many want a simple name, so I did it although I know map is already reserved tag name. That's why I also make it as available as attribute name. 

If you way using `map` is wrong, yes, it is wrong. However you don't have to use `map` tag.

**Comment by yupitomets** [comment]
Is there are any alternatives to <map> HTML tag? I think it's better to create attribute for map directive like <map skip../> and skip process tags that have this marker. All users who wish to have shorter name and who use HTML <map> tags at the same time will be satisfied.

**Comment by yupitomets** [comment]
Actually this is already exists - ng-non-bindable

**Comment by allenhwkim** [comment]
So you want to use `map` tag? I thought you don't want to use `map

**Comment by yupitomets** [comment]
Yes, I do want :) I have some interactive pictures. ng-non-bindable is what really helped me.

**Comment by allenhwkim** [comment]
Perfect! Different people, Different ways. Glad you find a way.
