### ISSUE TITLE
Publish as an NPM module

### ISSUE THREAD

**Issue by DaleJefferson** [allenhwkim/angularjs-google-maps#148]
AngularJS is now available as a NPM module it would be great if I could install ngmap in the same way.

**Comment by allenhwkim** [comment]
Good idea. Can you add instructions here? I.e, npm register

**Comment by DaleJefferson** [comment]
### Create an account with npm (if you have not already done so)
```
npm adduser
```

### Update your package.json
Add things like license, repository
https://docs.npmjs.com/files/package.json

### Publish
```
npm publish
```

That should be it.

**Comment by allenhwkim** [comment]
Thanks, it's done

https://www.npmjs.com/package/ngmap
