### ISSUE TITLE
Shape never removed

### ISSUE THREAD

**Issue by manland** [allenhwkim/angularjs-google-maps#149]
Hi! Thanks for this wrapper ;)

Markers are never removed from the map, even if i delete it from my scope. To fix this issue I made this little workaround : 

```javascript
map.shapes.forEach(function(shape) {
    shape.setMap(null);
});
map.shapes = {};
```

**Comment by allenhwkim** [comment]
Markers are removed when it is removed from DOM. 
I do not add expensive $scope.watch in default, and I want it to be handled by users.

If you want to work with dynamic markers, please use ng-repeat, which is sync. to DOM element. This will handle add/removal/update of markers very well.

**Comment by allenhwkim** [comment]
Closing, if stil  not working, please provide a plnkr example.
