### ISSUE TITLE
ng-map and ng-show not showing full map

### ISSUE THREAD

**Issue by finbar123** [allenhwkim/angularjs-google-maps#15]
Great directive very easy to get working, possible problem when using with an ng-show command only the first tile of the google map is displayed, if you use the chrome debugger to try and see what is happening the rest of the map is displayed

I have made a plnkr to show this 
http://plnkr.co/edit/i5Nme3VKeFao3Ievluip?p=preview

**Comment by silviotroia** [comment]
CDN is changed http://plnkr.co/edit/vLlulW7qtbG9q6Uup5d2?p=preview
