### ISSUE TITLE
mapInitialized event does not allow to get center information

### ISSUE THREAD

**Issue by jdesreumaux** [allenhwkim/angularjs-google-maps#150]
I have tried  Showing static coordinates of Chicago 
with  	$scope.$on('mapInitialized', function(event, map) {
but map.getCenter() returns undefined.

Is it normal?

**Comment by allenhwkim** [comment]
I believe that you are doing geolookup instead of giving lat/lng for centre. If you set the centre to 'Chicago', map is initialized without centre and  geolookup is done to find lat/lng asynchronously.

**Comment by allenhwkim** [comment]
Closing, if still not working, please provide an example with plnkr.
