### ISSUE TITLE
After browser asks to share location markers disapear 

### ISSUE THREAD

**Issue by MarkusPayne** [allenhwkim/angularjs-google-maps#151]
Works great until you answer the share location question. Then the markers disappear and don't come back.

<map  center="{{latlng}}">
  <marker
    position="{{latlng}}"
    title="Test"
    draggable="true"
    visible="true"
    icon="images/map-icon.png">
  </marker>
</map>

**Comment by allenhwkim** [comment]
Please create a plnkr for it, I will make the plnkr work for you

**Comment by allenhwkim** [comment]
closing by inactivity
