### ISSUE TITLE
load google maps api on initialization

### ISSUE THREAD

**Issue by kuntergunt** [allenhwkim/angularjs-google-maps#152]
Hi Allen, this is a feature that would add some benefit to angularjs-google-maps, at least to us:
We wanted to load the google api only on demand to speed up the loading of a page (our solution uses mainly offline resources on mobile devices). Therefore we tried to implement a lazy loading within angularjs-google-maps that supports a customer key. Maybe a generic implementation needs some more parameters to be added. 
This is the code that worked for us:

    ngMap.provider("googleApiLoader", function() {

      var apiKey = null; 
      var clientId = null;

      this.setApiKey = function(key) {
        apiKey = key;
      };

      this.setClientId = function(id) {
        clientIdt = id
      }, 

      this.$get = ["$q",
        function($q) {
          var deferred = $q.defer();
          function scriptError() {
            deferred.reject()
          }             
          if ("undefined" != typeof google) {
            deferred.resolve(),
            deferred.promise;
          }
          window.onGoogleScriptLoad = function() {
            "undefined" != typeof window.google ? deferred.resolve() : deferred.reject()
          };            
          var script = document.createElement("script");
          script.type = "text/javascript";          
          script.async = !0; 
          script.src = "http://maps.google.com/maps/api/js?callback=onGoogleScriptLoad"; 
          apiKey && (script.src += "&key=" + apiKey + "&");
          clientId && (script.src += "&client=" + clientId + "&v=3.18");
          script.onerror = scriptError;
          document.body.appendChild(script);
          return deferred.promise
        }       
      ] 
    });

**Comment by allenhwkim** [comment]
This is great
I would appreciate if you format the source code and provide some documentation usage example of this although it's clear between you and me.

For example, 
  1. how to set api key and client id it as a provider
  2. how to use it within controller as a service

Also it would be great if you explain how map directive initialization is delayed until this service loads the script.

**Comment by gabrielmancini** [comment]
Oh I need this too!

**Comment by allenhwkim** [comment]
I have tested your code with the following modification.
However, what I still don't understand is how to avoid racing condition between directives and this loader. 

directives are initialized with ngMap module, so does this loader. My question is how to make directives are loaded after loader is done. I did not see any module-level resolve method.
    ngMap.provider("mapsApiLoader", function() { 

      var apiKey = null, clientId = null;

      this.setApiKey = function(key) {
        apiKey = key;
      };

      this.setClientId = function(id) {
        clientIdt = id
      },

      this.$get = ["$q", function($q) {
        var deferred = $q.defer();
        var onError = function() {
          deferred.reject();
        }

        if (window.google && window.google.maps) {
          deferred.resolve();
        } else {
          window.onGoogleScriptLoad = function() {
            (window.google && window.google.maps) ? deferred.resolve() : deferred.reject()
          };

          var script = document.createElement("script");
          script.type = "text/javascript";
          script.async = !0;
          script.src = "http://maps.google.com/maps/api/js?callback=onGoogleScriptLoad";
          apiKey && (script.src += "&key=" + apiKey + "&");
          clientId && (script.src += "&client=" + clientId + "&v=3.18");
          script.onerror = onError;
          document.body.appendChild(script);
        }

        return deferred.promise;
      }];
    });

**Comment by kuntergunt** [comment]
first we initialize:

myApp = angular.module('app', applist);
myApp
    .config([
        '$locationProvider',
        '$routeProvider',
        '$provide',
        '$sceProvider',
        'googleApiLoaderProvider',
        function ($locationProvider, $routeProvider, $provide, $sceProvider, googleApiLoaderProvider) {
//…
googleApiLoaderProvider.setApiKey("myGoogleApiKey");
//…
}]);

To use the lazy loading, every directive must be extended with the googleApiLoader:
ngMap.directive("map", ["Attr2Options", "$timeout", "googleApiLoader“,function(…

What is missing is some additional configuration: http/https or the version of the API that should be changeable.

**Comment by allenhwkim** [comment]
Changing every directive is a lot of work. I wish there is a simpler way.

**Comment by allenhwkim** [comment]
Just adding the loader service as dependency without any action? I thought every single directive has to make use of that service within it. No?

**Comment by allenhwkim** [comment]
1.4.0 released with this feature.

Lazy Loading
------------
  Simply wrap the map tag with `ng-if="mapJsLoaded"`.

    <div ng-if="mapJsLoaded" ng-controller="MyCtrl">
      <map center="41,-87" zoom="3"></map>
    </div>
