### ISSUE TITLE
InfoWindow is not updated when binded with multiple markers 

### ISSUE THREAD

**Issue by ishaan2990** [allenhwkim/angularjs-google-maps#153]
When user clicks on the marker with showInfoWindow binded to it the template is replaced when infoWindow is compiled for one marker click. Therefore it is not updated when another marker is clicked

**Comment by allenhwkim** [comment]
Please checkout this example.

https://rawgit.com/allenhwkim/angularjs-google-maps/master/testapp/infowindow_compiled.html

**Comment by allenhwkim** [comment]
pull request accepted

**Comment by ishaan2990** [comment]
Fixed now !!

**Comment by ishaan2990** [comment]
Fixed now !!
