### ISSUE TITLE
ngMap giving injection error after last update 2 hours back

### ISSUE THREAD

**Issue by MagicalMaya** [allenhwkim/angularjs-google-maps#155]
Hi,

Am using ngMap in one of my applications, and have included from github.
<script src="http://maps.google.com/maps/api/js?libraries=places"></script>
<script src="http:/rawgithub.com/allenhwkim/angularjs-google-maps/master/build/scripts/ng-map.min.js"></script>
  

After the last update you made 2 hours back, ngMap is giving injection error. Error: [$injector:unpr] http://errors.angularjs.org/1.2.19/$injector/unpr?p0=eProvider%20%3C-%20e

If I remove ngMap, the app loads fine.

**Comment by mliu95** [comment]
+1, looks like the minified js file isn't loading correctly. We simply changed the source from ng-map.min.js to ng-map.js

**Comment by MagicalMaya** [comment]
Thank you Michael Liu. I reverted to previous version, will try with ng-map.js.

**Comment by mliu95** [comment]
Hi Maya, I just had a pull request merged in fixing the problems with ng-map.min.js, if you were previously linking to it from a CDN, it should be good now :)

Just tested and confirmed this one is working: //rawgit.com/allenhwkim/angularjs-google-maps/master/build/scripts/ng-map.min.js

**Comment by MagicalMaya** [comment]
Just checked, yeah 
//rawgit.com/allenhwkim/angularjs-google-maps/master/build/scripts/ng-map.min.js
 seems to work fine now.

Thanks Michael.
