### ISSUE TITLE
Change in ng-repeat model should delete existing shapes

### ISSUE THREAD

**Issue by mohammadjavadkho** [allenhwkim/angularjs-google-maps#157]
Change in ng-repeat model does not  delete existing shapes!!

**Comment by allenhwkim** [comment]
Thanks for using this module

Can you change app/scripts/directive/shape.js with destroy callback that are used by app/scripts/directives/marker.js

      /**
       * set event to clean up removed marker
       * useful with ng-repeat
       */
      element.bind('$destroy', function() {
        var markers = marker.map.markers;
        for (var name in markers) {
          if (markers[name] == marker) {
            delete markers[name];
          }
        }
        marker.setMap(null);          
      });

**Comment by allenhwkim** [comment]
fixed and published as 1.4.5
