### ISSUE TITLE
Do You Use ngMap In Production?

### ISSUE THREAD

**Issue by allenhwkim** [allenhwkim/angularjs-google-maps#158]
Please post your url here, so that developers visit your site and learn each other.

**Comment by simonh1000** [comment]
http://m.amsterdamfoodie.nl/

**Comment by pungme** [comment]
http://onestar.reviews

**Comment by jodibean** [comment]
We do, but our application is not public.

**Comment by azachar** [comment]
www.slacklinefestivals.com

**Comment by cameronbourke** [comment]
Yeah, using it for an Ionic app which will be released very shortly. Best angular wrapper for google maps out there!

**Comment by azachar** [comment]
+1
