### ISSUE TITLE
Safari dragging and styling problems

### ISSUE THREAD

**Issue by thenikso** [allenhwkim/angularjs-google-maps#159]
I'm reporting a couple of issues that I solved on a website (that I'll report to #158 when it's ready :)):

A style framework I was using (foundation) was setting:

```
img {
  max-width: 100%;
}
```

I had to counter that with:

```
map img {
  max-width: 100%;
}
```

To fix gmap widgets display.

Also (and I couldn't figure out how this happened) on Safary only, dragging the map resulted in a glitch that looked like I was dragging part of the page text. To fix it I added:

```
<map ... ondragstart="return false;">
```

This was using v1.4.2

**Comment by allenhwkim** [comment]
thanks for using reporting this. I will take a look into it and put into the default if possible

**Comment by thenikso** [comment]
those changes were on my side. What I cant think of is to add the drag-start fix directly on the directive. However I'm not sure why I had that effect on safari; it does not happen with your examples.

If I figure out something I'll let you know. Feel free to close this if you wish; it will still be available for future reference.

**Comment by allenhwkim** [comment]
closing. If you have reproducible case, please report again.
