### ISSUE TITLE
Mobile Device(Nexus 5 and Material Design): Click event on non-draggable marker not working properly

### ISSUE THREAD

**Issue by marcolanaro** [allenhwkim/angularjs-google-maps#162]
This issue is valid only if I open the web page from my nexus 5 or if I use the "device mode" in chrome debug tools.

If i define a draggable marker, the on-click event fires correctly:
\<marker on-click="click();" position="[45,11]" clickable="true" draggable="false"></marker>

If i define a not draggable marker, the on-click event does not fire:
\<marker on-click="click();" position="[45,11]" clickable="true" draggable="false"></marker>

**Comment by allenhwkim** [comment]
Thanks for using this module

I do not have Nexus, so I cannot test it 

It could be Google maps app issue because I do not modify those events

Could you test it without using this module and if it works I need to look into the issue. If not, Google has to solve the problem

**Comment by simonh1000** [comment]
I've something similar but only when using Angular Material Design, and other people have reported the same issue on the MD repository

**Comment by marcolanaro** [comment]
I am using angular JS implementation of materiale design!
Need ti investigate.
Il 15/mar/2015 16:02 "Simon Hampton" <notifications@github.com> ha scritto:

**Comment by simonh1000** [comment]
In the short run try attaching to 'mousedown' rather than 'click' events - that worked for me, but is clearly not completely satisfactory

**Comment by allenhwkim** [comment]
don't know how to fix this. any suggestions?

**Comment by allenhwkim** [comment]
I am not closing this issue although it seems a problem of Material Design. Comments are welcome and solutions are more appreciated.

**Comment by allenhwkim** [comment]
Closing it

**Comment by simonh1000** [comment]
The issue has been solved apparently on material design https://github.com/angular/material/issues/1441

**Comment by allenhwkim** [comment]
wonderful
