### ISSUE TITLE
How to trigger showInfoWindow outside of a marker

### ISSUE THREAD

**Issue by kirstilynn** [allenhwkim/angularjs-google-maps#164]
I was wondering if it is possible to trigger the same showInfoWindow function that a marker has on click, but on an href instead. 

I am building a store locator, so they can click on the marker and the info window shows OR they could click on the store text in the list below the map and it would trigger that same info window. So basically I want to use the same functionality that the on-click="showInfoWindow()" has on a marker, but just not on a marker. Thanks!

**Comment by allenhwkim** [comment]
Yes you can. I will get back to you tonight

**Comment by allenhwkim** [comment]
Here is the example.

http://plnkr.co/edit/VuSUswGryqZDwB6bEKQ4?p=preview

**Comment by kirstilynn** [comment]
Awesome, that works perfectly! Is there a way to send dynamic data to the info window for it to display?

**Comment by allenhwkim** [comment]
You can ignore that error that does not affect the functionality.
However, I need to make a fix for that. Thanks for reporting the bug

**Comment by allenhwkim** [comment]
bug fixed with release of v1.4.4 by wrapping $apply with $timeout
