### ISSUE TITLE
ngMap does not work with Angular 1.3.4 (only works with 1.2.10)

### ISSUE THREAD

**Issue by gayanpathirage** [allenhwkim/angularjs-google-maps#166]
I recently updated angular version and map stopped working. It doesn't display at all and no javascript level errors also. 

Can you please fix and release ngMap version compatible with 1.3.4.

**Comment by allenhwkim** [comment]
it seems working for me

http://plnkr.co/edit/iwyVobo7n4hFXZ6uNaSR?p=preview.

Please provide a plnkr that does not work. I will take a look at it. I believe AngularJS is always backward compatible in 1.X.X versions

**Comment by gayanpathirage** [comment]
Thanks a lot for the prompt response. I manage to isolate my issue and it's in this plnkr 
http://plnkr.co/edit/fWp5AQGw0AKpifysziOo?p=preview

    
    <script src="//ajax.googleapis.com/ajax/libs/angularjs/1.2.28/angular.js"></script>

    
    

Ideal, if you can get the same code working on 1.3.X versions as this is the current angular version.

**Comment by allenhwkim** [comment]
Thanks for using this module. however, your code is not ready for 1.3.15. 
Please readhttps://docs.angularjs.org/guide/migration

and search for "$parent" on that parent. You will see the difference between 1.2 and 1.3.

**Comment by gayanpathirage** [comment]
Thanks a lot Allen! I did fix the parent issue and now map is visible. But still click event does not work due to an error in ng-map. 

Please check and let me know how I can fix it as well.

Plnkr: http://plnkr.co/edit/fWp5AQGw0AKpifysziOo?p=preview

**Comment by allenhwkim** [comment]
controller: ‘ModalInstanceCtrl'

**Comment by gayanpathirage** [comment]
Sorry for the trouble Allen, I don't see an issue with the ModalInstanceCtrl code. Could you correct my plnkr and share if I have done something wrong.

**Comment by allenhwkim** [comment]
http://plnkr.co/edit/qxJ1otRJ2WqgCPKlDiOU

Controller must be a string

**Comment by gayanpathirage** [comment]
Finally landed with another issue! This could also be a bug in my code.

    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/angular-ui-bootstrap/0.11.0/ui-bootstrap-tpls.min.js"></script>
    
    

http://plnkr.co/edit/fWp5AQGw0AKpifysziOo?p=preview

**Comment by allenhwkim** [comment]
The bootstrap version change made the height of map not having solid number.
You can simply change your css or remove the css.
  
map, div[map] {display:block; width:100%; height:100%;}

**Comment by gayanpathirage** [comment]
Thank you loads Allen! Everything solved!
