### ISSUE TITLE
Heatmap-layer issue

### ISSUE THREAD

**Issue by pseudozach** [allenhwkim/angularjs-google-maps#167]
Hi,

Heatmap-layer doesn't seem to work as is. The demo plunk provided in http://ngmap.github.io/layers.html#/layer-heatmap#layer-heatmap also does not work.

Do you have a working example for the heatmap-layer with asynchronous data? Because whatever I provide to the layer it returns "invalid heatmap data". Even if I feed in google's own example "taxiData".

edit: sorry,it works just fine :)

**Comment by allenhwkim** [comment]
http://plnkr.co/edit/iwyVobo7n4hFXZ6uNaSR?p=preview
