### ISSUE TITLE
Event for when current-location is resolved

### ISSUE THREAD

**Issue by kirstilynn** [allenhwkim/angularjs-google-maps#170]
Is there an event for when center="current-location" is resolved? Even if is unsuccessful and uses the geo fallback location?

Thank you for the great directive!

**Comment by allenhwkim** [comment]
Sorry, 
currently no. I guess you are looking for an event when geoLookup is completed(success or failure).
Can u tell me some use cases for this, so that I can convince myself worth developing it.

FYI, the following is how geoLookup is used.
https://github.com/allenhwkim/angularjs-google-maps/search?utf8=%E2%9C%93&q=setDelayedGeoLocation

**Comment by kirstilynn** [comment]
Oh darn, well in my case I am using this as a store locator. So once the geolocation is resolved, it either sets the location to their geolocation or uses the fallback location. Then I just need to grab the maps current center and find the surrounding stores. 

I guess it would be helpful if you have dynamic data in the map that is dependent on the current location.

**Comment by allenhwkim** [comment]
I found myself correcting some geolookup code using promise $q to make it fully flexible by accepting any kind of callbacks. Basically refactoring!!!! It will be done in few days.

**Comment by kirstilynn** [comment]
Whoa you rule! That is great news!

**Comment by allenhwkim** [comment]
This feature is released with 1.5.0

documentation: https://rawgit.com/allenhwkim/angularjs-google-maps/master/build/docs/map.html
example: https://github.com/allenhwkim/angularjs-google-maps/blob/master/testapp/map_with_current_position.html

LMK if you have any issues

**Comment by kirstilynn** [comment]
This is great! Thank you so much. Exactly what I was needing.

**Comment by allenhwkim** [comment]
You're welcome. Thanks for reporting the issue and I am glad it helped.

**Comment by kirstilynn** [comment]
Is the callback function only supposed to fire for the geolocation? Or does it fire for the fall-back geolocation as well?

**Comment by allenhwkim** [comment]
not for fall-back. Do you need it for fallback location also?

        if (!center) {
          mapOptions.center = new google.maps.LatLng(0,0);
        } else if (!(center instanceof google.maps.LatLng)) {
          delete mapOptions.center;
          ctrl.getGeoLocation(center).then(function(latlng) {
            map.setCenter(latlng);
            var geoCallback = attrs.geoCallback;
            geoCallback && $parse(geoCallback)(scope);
          }, function(error) {
            map.setCenter(options.geoFallbackCenter);
          });
        }

**Comment by kirstilynn** [comment]
I would definitely use it if it were a feature but I don't think it will be a huge deal if we don't have that functionality. Thanks so much again!
