### ISSUE TITLE
Error "google is not defined" when library is loaded before google maps API JS

### ISSUE THREAD

**Issue by stranger82** [allenhwkim/angularjs-google-maps#172]
Hi,
 first of all thank you for all your efforts!

 I am trying to use your library in my Ionic project. The problem I have I want to load the library  before google maps JS API library. I get "google is not defined" error because of this line: 
var directionsService = new google.maps.DirectionsService();

Is it possible to remove this load-time dependency and allow to load library before google maps API JS?

 Thanks!

**Comment by kairoh** [comment]
+1. I have the same error using map-lazy-load.
I fixed it by removing this line (32) in "directions.js" : it's useless cause it's actually "deferly" instantiated a few line after (line 47)...

**Comment by allenhwkim** [comment]
yup. sorry about that. new feature caused a bug. I will make a fix ASAP.

**Comment by kairoh** [comment]
Thanks!

**Comment by stranger82** [comment]
Thank you, it works now
