### ISSUE TITLE
Small typo in bicycling-layers

### ISSUE THREAD

**Issue by kairoh** [allenhwkim/angularjs-google-maps#173]
Just noticed a small typo in bicycling-layers.js (never used it but found it in code)

```javascript
 mapController.addObject('bicyclingLayers', layer);
...
 mapController.deleteObject('biclclingLayers', layer);
```

One char make the difference ;-)

BTW this lib is really easy to use and nicely designed.
Well done!

**Comment by allenhwkim** [comment]
thanks
Why don't you fork and send me a PR?
