### ISSUE TITLE
Pass options to google.maps.places.Autocomplete

### ISSUE THREAD

**Issue by stranger82** [allenhwkim/angularjs-google-maps#174]
Hi,
 I want to pass options to original google.maps.places.Autocomplete. For example to limit  autocomplete options:  
 var options = {
         types: ['geocode']
  }

 It would be nice to support it in places-auto-complete directive.

 Thanks!

**Comment by allenhwkim** [comment]
updated it with 1.7.5. please check with this example
https://rawgit.com/allenhwkim/angularjs-google-maps/master/testapp/places-auto-complete.html
