### ISSUE TITLE
Detection if gmaps api sdk is already async loaded?

### ISSUE THREAD

**Issue by vlatkodrljin** [allenhwkim/angularjs-google-maps#175]
Can we detect if already is google maps api sdk already lazy loaded? I want to (lazy) load gmaps javascript file only first time (when my controller is initialized first time). Every time after that in console i have following error:

You have included the Google Maps API multiple times on this page. This may cause unexpected errors.

**Comment by allenhwkim** [comment]
Have seen this error with older versions. Can you send me a plnkr so that I can debug it?

**Comment by allenhwkim** [comment]
tested with this page. https://rawgit.com/allenhwkim/angularjs-google-maps/master/testapp/map-lazy-load.html. it works fine. Unless you provide a plnkr, I may close this later.

**Comment by vlatkodrljin** [comment]
Sorry, i used old version (1.4.2)
