### ISSUE TITLE
info-window is destroyed and cannot be re-opened after clicking the close (x) button 

### ISSUE THREAD

**Issue by swkruger** [allenhwkim/angularjs-google-maps#176]
Please help: the info-window is destroyed and cannot be re-opened after clicking the close (x) button. This also causes an error when navigating to another AngularJS view and/or back to the map view. 

"Error: obj.map is null" 
MapController/this.deleteObject@....
infoWindow/linkFunc/<@.....

I created this plunker: http://plnkr.co/edit/mCWXa2
Create the 3 markers, then view the info window by clicking on any of the markers, click the close button and attempt to view the info window again on any of the other markers.
You could also add 2 AngularJS views with one contianin the google map directive. With ng-href navigate back and forth between the views to reproduce the error.

From what I could determine the issue is related to this line when destroying info windows:
/* delete from map */
obj.map && obj.setMap && obj.setMap(null);

**Comment by allenhwkim** [comment]
fixed, please check

**Comment by swkruger** [comment]
Fixed. Thanks for the awsome support! Issue can be closed.
