### ISSUE TITLE
Setting new dynamic markers breaks infowindow

### ISSUE THREAD

**Issue by kirstilynn** [allenhwkim/angularjs-google-maps#177]
I have an ng-repeat for the markers and they can click on a form to search for new markers around that location. The infowindow works on page load but when the marker array changes, the infowindow for those new markers are broken.

Here is a hard coded plunkr of the issue. Click on the "Find Stores" button to load in new markers, thats when the infowindow breaks.

http://plnkr.co/edit/0Cy9UYEbxE8Ew3ndZQJB?p=preview

**Comment by allenhwkim** [comment]
This is broken since 1.4.7.. it works with 1.4.5. **sigh**
Need to find out what makes (x) button hides info window forerver.

**Comment by allenhwkim** [comment]
fixed, please check
