### ISSUE TITLE
Markers don't work with address

### ISSUE THREAD

**Issue by chadwtkns** [allenhwkim/angularjs-google-maps#178]
I dont know if markers are meant to handle addresses over coordinates but It would be nice if the markers directive did work with addresses. Unless I am just missing something here. I noticed that the map directive 'center' attribute seems to work with an address in there just not the markers 'position' attribute. Thanks. Hopefully this makes sense what I am talking about. So I have included a Plunker as well that shows what I am talking about.

http://plnkr.co/edit/ITwK4mnUt5YPsMnhQLst

**Comment by allenhwkim** [comment]
sorry, there was a bug in it. I made a fix with 1.7.6

**Comment by chadwtkns** [comment]
Awesome. thank you for such a quick reply
