### ISSUE TITLE
The current version throws an error

### ISSUE THREAD

**Issue by jeroenransijn** [allenhwkim/angularjs-google-maps#179]
I've tried a basic setup but something goes wrong and throws an `undefined is not a function` error in the console.log. It has something to do with: `ctrl.observeAttrSetObj`. I've tried an old version of ngMap which doesn't throw this error.

**Comment by allenhwkim** [comment]
Can u provide me a plnkr?

**Comment by saschaseewald** [comment]
A while back I ran into the same problem. In my case it turned out to be caused by a conflict with a customer controller "MapController". This is also used internally by the map directive. 
See console output of this example http://plnkr.co/edit/8VFOjOrdrI9PMEypSTlg?p=preview.

**Comment by allenhwkim** [comment]
ouch, I can change the internal controller name to something else.

**Comment by saschaseewald** [comment]
Yes, I guess that will do the trick. Thanks.

**Comment by jdhiro** [comment]
MapController seems like a pretty generic term for a library to be using :) I just hit this as well. Perhaps a more specific name is in order?
