### ISSUE TITLE
map without internet causes crash app

### ISSUE THREAD

**Issue by allenhwkim** [allenhwkim/angularjs-google-maps#180]
Hello, I'm using your module in my app. It's a great module, and it's helping our team to easily integrate gmap into our app. 
A few questions. 
1. In the case where I'm offline, your module raises an exception and causes my entire app to crash, is there a way to cause to fail silently, or to not startup at all when Google isn't available? 
2.any plans to make it work with other map services such as osm?
Thanks!

From Chaim Lando

**Comment by allenhwkim** [comment]
Hi Chaim

Thanks for using this module.

for no 1, try use lazy loading of google maps. `map-lazy-load`. and an example is here at testapp/map-lazy-load.html.

for no 2. no plan for building directive for openstreetmap yet.

**Comment by chiptus** [comment]
great! thank you!
