### ISSUE TITLE
Zoom out to show markers

### ISSUE THREAD

**Issue by chiptus** [allenhwkim/angularjs-google-maps#182]
Hi, 

My markers are loaded on page start and i'm interested to know if instead of putting zoom=n I can have the map zoom out to show all markers in the map?

Thanks

**Comment by allenhwkim** [comment]
Run the following code when map is initialized

    $scope.$on('mapInitialized, function(evt, map) {
        var markers = map.markers;
        var bounds = new google.maps.LatLngBounds();
        for(i=0;i<markers.length;i++) {
             bounds.extend(markers[i].getPosition());
        }
       map.fitBounds(bounds);
    };

**Comment by allenhwkim** [comment]
Closing this, since I do not have plan to add an map attribute like 'zoom-out-to-show-all-markers' because the behaviour must be on event based, for example, marker is added, center changed, shape is added, etc.

**Comment by chiptus** [comment]
You could add an api action for this. I'll look into this and make a pull
request.
Anyway thank you for this module and for your help.

**Comment by allenhwkim** [comment]
Thanks @chiptus a pull request would be very welcome.
