### ISSUE TITLE
custom info-window content for each marker

### ISSUE THREAD

**Issue by ggiacomo** [allenhwkim/angularjs-google-maps#186]
Hi,
first of all, great job with this project! 
I'd like to have a ng-repeat of markers, and each one with a custom content to be displayed clicking on the marker, is it possible? 
like this one: https://developers.google.com/maps/documentation/javascript/examples/infowindow-simple

Thank you very much.

**Comment by allenhwkim** [comment]
http://ngmap.github.io/drawings.html#/infowindow-simple#infowindow-simple

**Comment by ggiacomo** [comment]
My god, didn't see it. I'm ot that page since 2 hours. Thank you very much.

**Comment by allenhwkim** [comment]
There are more features than that page has. Please check out and testapp directory in github.

**Comment by williamsuane** [comment]
by the way, it's possible to use rotation on marker?

**Comment by allenhwkim** [comment]
Yes

**Comment by williamsuane** [comment]
Is there  any example in docs page? I really can't find

**Comment by ggiacomo** [comment]
Hi,
works fine with static names for ids, but when i assign dynamical ids with ng-repeat, i get 'Cannot read property 'apply' of undefined' by clicking on marker. Here's the code. Any suggestion?

        <map center="45.515424,9.088755" zoom="7">
            <marker
                    ng-repeat="image in images"
                    id="{{image._id}}marker"
                    position="{{image.lat}}, {{image.lon}}"
                    on-click="showInfoWindow(event, '{{image._id}}info')"
                    icon="modules/core/img/marker.png"
                    animation="DROP">
            </marker>
            <info-window
                    ng-repeat="image in images"
                    id="{{image._id}}info" visible-on-marker="{{image._id}}marker">
                <div ng-non-bindable="">
                    <div id="siteNotice"></div>
                    <h1 id="firstHeading" class="firstHeading">{{image.name}}</h1>
                    <div id="bodyContent">
                        <img src="{{image.url}}" width="100px" alt=""/>
                    </div>
                </div>
            </info-window>
        </map>

**Comment by allenhwkim** [comment]
info-window is not for ng-repeat. you should keep one info window and change it dynamically using your scope values. You can find examples in testapp directory.

**Comment by ggiacomo** [comment]
yeah, got it. Thank you!
