### ISSUE TITLE
Can't make the autocomplete work!

### ISSUE THREAD

**Issue by HoplaGeiss** [allenhwkim/angularjs-google-maps#189]
I am trying to use the auto complete example

```
      Auto Complete Type: 
      <select ng-model="types">
        <option value="['geocode']">Geodode</option>
        <option value="['establishment']">Establishment</option>
        <option value="['address']">Address</option>
      </select><br/>

      Enter an address: <br/>
      <input places-auto-complete size=80 
        ng-model="address" 
        component-restrictions="{country:'us'}"
        types="{{types}}"
        on-place-changed="placeChanged(place)" /> <br/>
      <div ng-show="place">
        Address = {{place.formatted_address}} <br/>
        Location: {{place.geometry.location}}<br/>
      </div>
      address : {{address}}
```

```
$scope.types = "['establishment']";
$scope.placeChanged = function() {
  $scope.place = this.getPlace();
 }
```

I get a type error cannot read property autocomplete of undefiened.
I must be missing something obvious.. The example is working pretty well

**Comment by allenhwkim** [comment]
Thanks for using this module and starring it.

could you make a plnkr for your problem, so that I can debug it?

**Comment by HoplaGeiss** [comment]
While making the plunker I found out the problem. It is angular's version

**Comment by HoplaGeiss** [comment]
http://plnkr.co/edit/2j37nnEfYPKAA1C5ENaD?p=preview

If I replace angular's version by the one you used in your example 
`<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.2.25/angular.min.js"></script>`
everything works fine

**Comment by allenhwkim** [comment]
I see this message on console.

GET https://code.angularjs.org/2.0.0-alpha.20/angular.js 404 (OK)

I did not tested mine with 2.0 yet, which is not released.

**Comment by HoplaGeiss** [comment]
Ok, so I guess I will need to find another way to use auto complete!
The rest of your directives seem to work fine with angular 2.0
I had only problems with auto complete!

**Comment by allenhwkim** [comment]
plnker is not ready for 2.0, yet. I think

I used 1.4.0-rc1 and it works fine.

http://plnkr.co/edit/IU1gRhkxB4oSomNYwGnj?p=preview

**Comment by HoplaGeiss** [comment]
Obviously I have a problem with my angular version. I will try to change this locally. Sorry I bothered you for nothing. Thanks for your amazing work!

**Comment by allenhwkim** [comment]
No worries as long as I could be a help.

**Comment by kumarStoryboard** [comment]
with angular 1.5.8 autocomplete of search box doesnt works over https connection
