### ISSUE TITLE
Place Markers with open info windows on a map using ng-repeat

### ISSUE THREAD

**Issue by angelobsks** [allenhwkim/angularjs-google-maps#191]
Is there a way to place some markers on a map using ng-repeat that having all the info windows open when they appear ???  At the code showing at the screen dump i can't do it works.!
![ngmap_is1](https://cloud.githubusercontent.com/assets/12217433/7444143/111db73e-f181-11e4-92cb-fe0fe13bbcd0.png)

**Comment by waswrongassembled** [comment]
Same issue here. I have the issue even when I use just one marker with an info-window (code from example page). I can place marker and info-windows but the click event is not working at all...

**Comment by allenhwkim** [comment]
Please do not use info-window within ng-repeat. It's been discussed several times. 

Here is an example

https://github.com/allenhwkim/angularjs-google-maps/blob/master/testapp/infowindow_compile.html
