### ISSUE TITLE
Options for KML Layer

### ISSUE THREAD

**Issue by cameronbourke** [allenhwkim/angularjs-google-maps#192]
Am I able to use preserveViewport & suppressInfoWindows KML options on the kml directive. And if so, is it something like this:

`<kml-layer url='someUrl' preserve-viewport=‘true' suppress-info-windows=‘true'></kml-layer>`

**Comment by allenhwkim** [comment]
As it says here, https://developers.google.com/maps/documentation/javascript/reference#KmlLayerOptions, yes you can.

**Comment by cameronbourke** [comment]
Sweet. Thanks! Awesome work with this module by the way.
