### ISSUE TITLE
Transit Layer not showing transit lines

### ISSUE THREAD

**Issue by lty83** [allenhwkim/angularjs-google-maps#193]
http://plnkr.co/edit/oXVsGMmqrwNbVDT8pA6x?p=preview

Does anyone know why a city like Cleveland, OH wouldn't show any transit lines? It appears to be supported by Google Transit.

**Comment by allenhwkim** [comment]
Thanks for using this module, but no idea about your issue,  it's outside of my ability. you can use pure google maps api without using this directive and see the transit layer, and you do not see this using this module, please reopen this issue.
