### ISSUE TITLE
Is possible to use map object instance to add markers and directions ? (instead of direction directive ? )

### ISSUE THREAD

**Issue by rahpuser** [allenhwkim/angularjs-google-maps#198]
I'm trying to create a directions map but I would like to do it from javascript code instead of directives cause pure javascript code fits better for my requirements.

Is this possible ?

**Comment by allenhwkim** [comment]
Yes

As you see it here, https://developers.google.com/maps/documentation/javascript/directions

Only you need to do is not to use directionsrenderer.

**Comment by rahpuser** [comment]
Now I get it, that object is the same of the api. thanks. great lib btw.
