### ISSUE TITLE
This plunker not working

### ISSUE THREAD

**Issue by adrivanrex** [allenhwkim/angularjs-google-maps#200]
https://ngmap.github.io/drawings.html#

Removing markers is not working.

**Comment by allenhwkim** [comment]
Some plunker is not working. I need to make some adjustment on plunker directive of my own.

Meanwhile, use this example,

https://rawgit.com/allenhwkim/angularjs-google-maps/master/testapp/marker-remove.html

Anytime it does not work, please visit this page , https://rawgit.com/allenhwkim/angularjs-google-maps/master/testapp/index.html, and you can find the exact working example.

**Comment by allenhwkim** [comment]
fixed
