### ISSUE TITLE
ngMap and Bootstrap grid cause difficulties

### ISSUE THREAD

**Issue by simonh1000** [allenhwkim/angularjs-google-maps#201]
I have been experiencing weirdness with my dragable maps and markers, and tried the examples on the website. The first time you drag it does not 'work' - hard to describe so please try e.g. http://ngmap.github.io/drawings.html

These are different and less dramatic artefacts than what I experience on my own site, but hopefully solving these will solve mine. Tested on chrome (linux/mac) and safari (osx)

**Comment by allenhwkim** [comment]
It works for me. http://plnkr.co/edit/ryUZ7IWAYxHlpYFihFhz?p=preview

This module does nothing related to draggable, so it should work as Google Maps API works.

Please provide a non-working plunker to reproduce the issue.

**Comment by simonh1000** [comment]
Have a look at this http://plnkr.co/edit/BQgMe5EQiFBmojgx45t5?p=preview and try dragging around a few times

**Comment by allenhwkim** [comment]
$scope.centerChanged = function(event) {
      $timeout(function() {
        map.panTo(marker.getPosition());
        console.log('foooooooooo');
      }, 3000);
    }

You are making timeout happens every time when center changed. I don't know your exact error. Please be descriptive to reproduce your error. I still believe that this is not related to this module, Google API , nor bootstrap related.  I think you should not run centerChanged event when an timer is still running on.

**Comment by simonh1000** [comment]
Here is a picture of what I am experiencing. Why I start to drag the map I see a picture of the map as part of a huge white layer moving in response ot my mouse. When I then let go of the muse button the layer disappears but then the map moves around (even though the button is not being held down).

This hadn't happened before and I was using numbered versions of angular, bootstrap etc. together with the rawgit version of ngMap, which is why I thought the problem needed to be reported here.

![img_20150511_181547](https://cloud.githubusercontent.com/assets/5256724/7569636/5da0df3e-f80a-11e4-9b7d-e89b9fc88c2a.jpg)

**Comment by simonh1000** [comment]
try this: http://plnkr.co/edit/BQgMe5EQiFBmojgx45t5?p=preview
note the spelling mistake of `draggable`
