### ISSUE TITLE
Parser fail to parse google.maps.LatLng objects in scope

### ISSUE THREAD

**Issue by fabn** [allenhwkim/angularjs-google-maps#204]
If i bind a position object to a `google.maps.LatLng` object the parser fails to recognize it as such. I found this issue in a complex application because I have a failing check at [this line](https://github.com/allenhwkim/angularjs-google-maps/blob/master/app/scripts/directives/marker.js#L90)

Here's a minimal fiddle to reproduce this: http://jsfiddle.net/fabn/L8cvwkub/

Maybe `position` attribute is not meant to be used in that way and I'm doing that wrong?

**Comment by allenhwkim** [comment]
sorry for the late response. could not make my time available during week days.

any `{{}}` in attributes are observed as a string, not as an object.
I wish I could watch it as an object.

    //  instead assign to attribute using {{ }} because position.toString() will be applied
    $scope.user = position;

    // you can directly set the posigoin of markers
    $scope.map.markers[0].setPosition(position);

Example: http://plnkr.co/edit/MZK832YwDM4T6w1MysvM?p=preview

**Comment by allenhwkim** [comment]
Closing

**Comment by fabn** [comment]
I'm commenting this issue because I encountered this issue in another context, when dealing with `direction` directive. Given the following directive

```html
<map>
  <!-- Directions renderer object -->
  <directions draggable="true"
              travel-mode="{{travelMode}}"
              origin="{{origin}}"
              destination="{{destination}}"
              waypoints="{{waypoints}}"
              panel="travel-route">
  </directions>

</map>
```

I'm having the same issue as above if I try to change waypoints array in my controller

```js
$scope.waypoints.push({location: new google.maps.LatLng(lat, lng), stopover: true})
```

I carefully read the above explanation on `$observe vs $watch` and I was wondering if it would be worth to change the library to use `$watch` since maps api deals a lot with native objects and since in this way I think it would be easier to use the library in a more angular way.

Let me know what do you think.
