### ISSUE TITLE
Marker cluster with <marker> and infowindow

### ISSUE THREAD

**Issue by ziobudda** [allenhwkim/angularjs-google-maps#206]
Hi, I have this working HTML code :

	    <map zoom="5" center="41.8919300, 12.5113300" on-center-changed="centerChanged()">
    	     <marker ng-repeat="pos in markers" position="{{pos.lat}},{{pos.lon}}" on-click="showStore(event, pos.k)" title="Click to zoom"></marker>
    	     <info-window id="foo2">
        	  <div ng-non-bindable="" style="width:120px;">
         	        {{item.title}}<br>
	        	  {{item.data}}<br>
         	      <a href="{{item.url}}"><img style="min-height: 100px;" ng-src="{{item.image}}"></a><br>
        	</div>
      </info-window>
    </map>

How can I use MarkerCluster in my situation? I have see your example, but in your example you use $scope.dynMarkers.push(new google.maps.Marker({position:latLng})); and you don't use any infowindow (opened at the marker click). I need to open an infowindow with "dynamic" value into. 

Thanks.

**Comment by allenhwkim** [comment]
Please check this example

https://rawgit.com/allenhwkim/angularjs-google-maps/master/testapp/infowindow_compile.html

**Comment by allenhwkim** [comment]
Closing
