### ISSUE TITLE
Spelling mistake in attributes causes weirdness

### ISSUE THREAD

**Issue by simonh1000** [allenhwkim/angularjs-google-maps#211]
I found this by accident, but a misseplling of `draggable` in the map attributes causes real issues. I would have expected it simply to be ignored.

Try this: http://plnkr.co/edit/BQgMe5EQiFBmojgx45t5?p=preview

**Comment by allenhwkim** [comment]
Cannot ignore, because It is html5 attribute. With that you should be able to drag an element 

Does it cause map to act weird?

**Comment by allenhwkim** [comment]
I will test

**Comment by allenhwkim** [comment]
I still could not reproduce your error
However, I think HTML5 `draggable` and map `draggable` is working at the same time

ngMap need to simply ignore HTML5 draggable by using `preventDefault`

Ref. https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Drag_and_drop
