### ISSUE TITLE
Markers not updating

### ISSUE THREAD

**Issue by markolbert** [allenhwkim/angularjs-google-maps#212]
Markers do not appear to update when their properties change. Please see the following plnkr: http://plnkr.co/edit/50idft4qaxqw1CduYkOd.

FYI, this is a simplified version of a plnkr I referenced earlier.

**Comment by allenhwkim** [comment]
`{{}}` within ng-repeat won't be observed by ng-map because it is out of control. I hope we can find a solution for that.
Until then, update your markers manually.
 http://plnkr.co/edit/zmf2pqYVN7j5Q6R6zcf6?p=preview

**Comment by markolbert** [comment]
Thanx, Allen. That did the trick!


-          Mark
