### ISSUE TITLE
Filter a list based on marker click

### ISSUE THREAD

**Issue by ideopia-curts** [allenhwkim/angularjs-google-maps#213]
Here's a Plunker.
http://plnkr.co/edit/GgcsVEY4KkZ5bCVHHGQA

This is my first Angular project, so there's probably some things that wouldn't be considered 'best practice.' 

I think I'm close. I put an ng-click handler on the International map markers. I have NOT put one on the US markers yet. 

What I'm trying to do is pass toller.countryTitle to the 'select' with ng-model="selectedItemIntl." That 'select' dropdown has a change handler on it to determine when to show the US select dropdown. 

There's a console.log on the click handler and it's passing something like '[object Object] France' if I click on the French location. But I can't figure out how to then pass 'France' to the select model. I get an error of 'Cannot set property 'countryTitle' of undefined'

Any help would be greatly appreciated. 

Thanks.

**Comment by allenhwkim** [comment]
Thanks for using this module. 
Based on your requirement, It's better for marker to have custom data.
I wonder why nobody complain about this. 
I will be back soon with new feature.

I will add a feature

**Comment by ideopia-curts** [comment]
Awesome. Thank you.

**Comment by nikeshbhagat** [comment]
I agree that this would be an excellent feature!

**Comment by ideopia-curts** [comment]
I'm so sorry to ask this. I know you're busy. But I’m getting a little heat from my boss. Is there a rough ETA on updating markers with custom data? Thanks. Again. Sorry to ask.

**Comment by allenhwkim** [comment]
Please  check out this example.

https://rawgit.com/allenhwkim/angularjs-google-maps/master/testapp/marker_data_with_ng_repeat.html

If this example does not satisfy your requirement, I will reopen this issue.

**Comment by ideopia-curts** [comment]
That looks like it will work great.

Thank you very much.
