### ISSUE TITLE
Marker Icon with origin and anchor

### ISSUE THREAD

**Issue by nikeshbhagat** [allenhwkim/angularjs-google-maps#215]
Hello,

Love the project. Good work!

My question is about custom marker icons.

I am able to get a custom marker icon by doing: <marker icon="{url: 'path-to-icon.png', scaledSize: [28, 28]}"... as you've shown in one of your examples...

My problem, however, is when I try to add origin and anchor parameters. When I add these two, it does not work.  

What I love about this project is how well it preserves the Google Maps Javascript API... 

It would be great if it could utilize the full icon specs.

For instance:

<marker icon=" { url: 'url.png', scaledSize: [10,10], origin: [0,0], anchor: [7,7] } " position="{{lat}}, {{long}}"

Any ideas? Your assistance is very much appreciated.

**Comment by allenhwkim** [comment]
Thanks for using it. I just tested it. and it works fine

```
  <map center="-25.363882,131.044922" zoom="4">
    <marker position="-25.363882,131.044922" title="Hello World!" 
      optimized="false"
      icon="{
        url:'images/spinner.gif', 
        scaledSize:[100,100],
        origin: [10,10],
        anchor: [50,50]
      }"></marker>
  </map>
```

For you, origin 0,0 does nothing.
anchor 7,7 won't make tiny difference.

**Comment by nikeshbhagat** [comment]
Hi, thanks. I'll try again... those weren't my real values, however, just examples.  

Real values are as follows:

icon="{
    url:'images/markerSprite.png',
    size: [14,14],
    scaledSize: [28, 294],
    origin: [0,0],
    anchor: [7, 7]
}"

As I typed that, I realized that I forgot to add the 'size' in my original inquiry.  Everything is working as expected now. Sorry to bother!

Thanks much.

**Comment by allenhwkim** [comment]
no worries. happy coding

**Comment by nikeshbhagat** [comment]
As a follow-up...

I'd like to be able to change the icon of a marker based on custom data. I see that you made the suggestion of allowing custom data for markers in another issue.. This would be great.  Will you be rolling custom data for markers out soon?
