### ISSUE TITLE
Using directions with origin and destinations in coordinates

### ISSUE THREAD

**Issue by sebrojas14** [allenhwkim/angularjs-google-maps#216]
Hi, I tried to use directiosn directive like in the example but using as origin the user locatiosn (coordenates) and doesn´t works :S

**Comment by sebrojas14** [comment]
I was missing call $scope.$apply() after get user locatios

**Comment by sebrojas14** [comment]
Now I'm using ngCordova so the call to $scope.$apply() is not required

**Comment by allenhwkim** [comment]
Please provide an example that are not working with plunker, so that I can take a look at it.

**Comment by allenhwkim** [comment]
Closing it. assuming this issue is resolved

**Comment by sebrojas14** [comment]
Yes, thank you
