### ISSUE TITLE
ng-repeat does not work inside custom-control

### ISSUE THREAD

**Issue by Fangmingdu** [allenhwkim/angularjs-google-maps#217]
Hi Allen,

@allenhwkim 

I have compiled a Plunker for this. You can take a look here.
http://plnkr.co/edit/cYdcW9vEsl6kcAvp8PEi?p=preview

I have a ng-repeat in custom-control, but it does not work.

Can you take a look and I will also look into it.

Thanks!

**Comment by allenhwkim** [comment]
Thanks for reporting this bug. 1.7.12 released with this fix.
Example is at testapp/custom-control.html
