### ISSUE TITLE
How to hide the initial map before directions map ?

### ISSUE THREAD

**Issue by flyflytn** [allenhwkim/angularjs-google-maps#218]
I am using the directions directive and its all working well, but since map directive precedes the directions directive, the user sees a map appear just a moment before the directions route shows.

How can I hide the initial show of the \<map\> and only see the \<directions\> result ?

**Comment by allenhwkim** [comment]
Map can be initialized by event. e.g., `init-event="init-map"`

Please check out this example.
https://rawgit.com/allenhwkim/angularjs-google-maps/master/testapp/map_lazy_init.html

**Comment by flyflytn** [comment]
thanks Allen.
Is there a msg from the directions directive that I could use as a trigger to then emit this map-init message to unhide the parent map directive ? What I need to do is only show the resulting directions map when its ready, I don't want any map to appear until then. So I would like to hide the map, and unhide once the directions have been rendered.

**Comment by allenhwkim** [comment]
no, directives do not emit any messages. your controller need to send out these messages. 
If you need more assistance, provide me a plunker, so that I can get into your code.

**Comment by flyflytn** [comment]
Sorry for my late response, I've been away for a few days.
Here's a plunker for what I'm trying to do. The user clicks a button to bring up a modal with a map of directions on it. I'd like to avoid seeing the initial map and only show the directions result.

http://embed.plnkr.co/Z8Ln6BpEE4bPX4kqITzJ/preview
