### ISSUE TITLE
Failed to execute 'write'

### ISSUE THREAD

**Issue by Sakpal** [allenhwkim/angularjs-google-maps#219]
Hello,

I used the library for a project. I followed the instructions, but  the map is not loaded.
In console the following warning is given:-

"Failed to execute 'write' on 'Document': It isn't possible to write into a document from an asynchronously-loaded external script unless it is explicitly opened."

Am I missing something ?

**Comment by allenhwkim** [comment]
Never seen that error. Please provide me a plunker example, so that I can investigate it.
