### ISSUE TITLE
Scope doesn't refresh

### ISSUE THREAD

**Issue by kucukkanat** [allenhwkim/angularjs-google-maps#220]
After an ajax request even though I $scope.$apply() the marker is still at [0,0] why can it happen?

**Comment by kucukkanat** [comment]
I have resolved the issue!
If you have allowed the website to use your geolocation before (for example you may have allowed localhost, earlier while working on another project),
ngMap automatically sets the center fetching the geolocation of the client which works before your ajax call responds.
Be carefull with that

**Comment by allenhwkim** [comment]
Thanks for using this module, but  I do not understand what you suggest.

If you want to get geolocation after it is resolved, use `geo-callback`.
Example is here, https://rawgit.com/allenhwkim/angularjs-google-maps/master/testapp/map_with_current_position.html
