### ISSUE TITLE
Performance Choppiness

### ISSUE THREAD

**Issue by AnjirHossain** [allenhwkim/angularjs-google-maps#221]
Here's my project [App](http://anjirdoes.com/TraversoFin/app/#/find), I'm loading my map with ui-router. When I zoom the map almost hops up and down and the zoom is choppy, if you compare my app with the maps used in ng-maps example apps you can see the difference, how do I make the zooming smooth. Looked through all of the possible variables the google maps api provides still zip.

**Comment by allenhwkim** [comment]
Might be related to this issue.https://github.com/allenhwkim/angularjs-google-maps/issues/211. Need to look into it.

**Comment by allenhwkim** [comment]
Not related to #211.

I have created the map with the exact same map options and markers that you used in your app. I don't see the choppiness
http://plnkr.co/edit/IHZAafvLl6ezG6zSigTw?p=preview

It might be related to your animation or some other Js you are using.
