### ISSUE TITLE
info-window open on event

### ISSUE THREAD

**Issue by rgolea** [allenhwkim/angularjs-google-maps#222]
Hi there! Is there any way to open the info window on clicking the marker? Thank you. Keep up the good job!

**Comment by allenhwkim** [comment]
checkout this example, https://rawgit.com/allenhwkim/angularjs-google-maps/master/testapp/infowindow_ng_click.html

**Comment by rgolea** [comment]
Is there a way to view the source code?

**Comment by allenhwkim** [comment]
right mouse click, 'View Page Source'?

**Comment by rgolea** [comment]
Yes but I don't know if the `showInfoWindow($event, 'bar', map.markers[0])` is available for the component or if I have to make it myself

**Comment by allenhwkim** [comment]
that function is made available by `info-window` directive as you see here, https://github.com/allenhwkim/angularjs-google-maps/blob/master/app/scripts/directives/info-window.js#L134. Thus you don't need to to any.

**Comment by rgolea** [comment]
Thanks!

**Comment by chiptus** [comment]
Hi,

the showInfoWindow is available on the info-window scope, but what if i'm in a different isolated scope?
I would think there should be a service that exposes this function, what do you think?

**Comment by allenhwkim** [comment]
info-window scope has the same scope as map.scope
and map is exposed by mapInitialized event

      $scope.$on('mapInitialized', function(map) {
         map.scope.showInfoWindow....
      })

It should works, but haven't tested the above code though
