### ISSUE TITLE
How to hide the initial map before directions map ? with plunker

### ISSUE THREAD

**Issue by flyflytn** [allenhwkim/angularjs-google-maps#224]
Sorry for my late response, I've been away for a few days so I've reopened this following on from #218 
Here's a plunker for what I'm trying to do. The user clicks a button to bring up a modal with a map of directions on it. I'd like to avoid seeing the initial map and only show the directions result.

http://embed.plnkr.co/Z8Ln6BpEE4bPX4kqITzJ/preview

**Comment by allenhwkim** [comment]
Unfortunately, I cannot do more than Google Maps API does.

Google maps directions renderrer automatically sets zoom and center for your origin and destination based on the existing map.

You can show the exact the same location if you have static origin and destination by giving the exact zoom and center like this,  http://embed.plnkr.co/6GNuGmXRAFDH6iR5krB1/preview
