### ISSUE TITLE
Marker clusterer Uncaught ReferenceError: MarkerClusterer is not defined

### ISSUE THREAD

**Issue by mastermind1981** [allenhwkim/angularjs-google-maps#225]
Hi,

Thank you for your great job on the module.

I'm testing the marker clusterer but i got the exception when instantiating the MarkerClusterer Object.

I have installed the module via bower. and included   ```
  <script src="http://maps.google.com/maps/api/js"></script>
``` in my html.

Is MarkerClusterer not shipped ?

Thanks in advance,

**Comment by allenhwkim** [comment]
No, MarkerClusterer is not officially supported by Google and not by this module either.

**Comment by mastermind1981** [comment]
Thanks for your prompt answer your module is :+1:
