### ISSUE TITLE
 $scope.$on('mapInitialized', ...) callback doesn't get fired after internet connection comes back

### ISSUE THREAD

**Issue by junerockwell** [allenhwkim/angularjs-google-maps#228]
I'm using this module in an ionic app that I'm working on. It works just fine. However, I tested it by loading the app without internet at first. As I've designed it, there won't be any data to list if there's no internet. So I would turn on wifi afterwards and the view will have a list of data. There's a button in each item in this list of data to view the map. But the map doesn't show at all. So I did some debugging. If there was internet when the app starts and the data loads, the callback function is called and `$scope.map` is set and map will load. Refer to the code below:

`$scope.$on('mapInitialized', function(event, map) {
    $scope.map = map;
});` 

But when there was no internet when trying to get the data and then turning on wifi, the callback function doesn't get fired. What am I doing wrong? Any workarounds? 

FYI: the data is a long list so I'm using `collection-repeat` directive which is just an "improvement" of `ng-repeat` from Ionic. So each data with have it's coordinates will be passed into a pop-up that contains the map that shows a pin.

**Comment by allenhwkim** [comment]
sorry for the late response. 

Could you provide me an example of your site using plnkr or any?
This is the second time I heard internet connection issue with ionic frame work.
My guess is that google map is loaded in <head> tag and ionic frame work never reload those head again although the internet connection is back.

However, it's just a guess.

If you provide an example page, I will look into it.

**Comment by allenhwkim** [comment]
* No internet -> no data -> no click -> thus no map.

* With internet -> data -> click -> map.

I do not think there would be an issue on the above logic unless the map section is generated before click. 
Please make it sure map section is created when button is clicked.

**Comment by allenhwkim** [comment]
closing it for inactivity.
