### ISSUE TITLE
Promise for google api initialization

### ISSUE THREAD

**Issue by robert-malai** [allenhwkim/angularjs-google-maps#229]
I need a promise object to chain on to it when the google api initialization is done. I want to geocode some addresses in order to populate some data in map markers.

The only solution that I have at the moment is to write a service which will pool for google and google.map objects; will it be possible to have a callback registered within lazy-load ?

Or is there another way to achieve this ?

Thank you !

**Comment by allenhwkim** [comment]
There is map-lazy-load directive. Please take a look into it.
https://github.com/allenhwkim/angularjs-google-maps/blob/master/app/scripts/directives/map-lazy-load.js

**Comment by allenhwkim** [comment]
Closing.
