### ISSUE TITLE
Max number of Markers?

### ISSUE THREAD

**Issue by wsimmerson** [allenhwkim/angularjs-google-maps#230]
Is there a max number of markers?

I'm drawing the markers using ng-repeat, in a set of 16 only 11 are being drawn.

**Comment by allenhwkim** [comment]
no i did not set max number of markers

**Comment by wsimmerson** [comment]
Problem was using addresses instead of geo coords.  There is a cap on how many address lookups can be performed.

**Comment by JacoboDB** [comment]
i am using geocoords and only shows 11 markers in a set of 20, why does it limit to 11?
