### ISSUE TITLE
Directions directive issue with lazy-load in 1.7.11

### ISSUE THREAD

**Issue by alextrs** [allenhwkim/angularjs-google-maps#232]
When try to use 1.7.11 with lazy load get the following error:

```javascript
ReferenceError: google is not defined
    at directions (ng-map.js:680)
    at Object.invoke (angular.js:3965)
    at angular.js:5716
    at forEach (angular.js:325)
    at Object.<anonymous> (angular.js:5714)
    at Object.invoke (angular.js:3965)
    at angular.js:3807
    at Object.getService [as get] (angular.js:3929)
    at addDirective (angular.js:6804)
    at collectDirectives (angular.js:6241)
```

**Comment by allenhwkim** [comment]
Thanks for using this module
Please provide me a plnkr fir this errir

**Comment by alextrs** [comment]
Well I see this error because on one of the pages I used 'directions' class. Here is codepen: http://codepen.io/alextrs/pen/MwVKNN

**Comment by allenhwkim** [comment]
As you see in the example, you need to include google maps javascript.
https://rawgit.com/allenhwkim/angularjs-google-maps/master/testapp/directions.html

Also there a lots of examples you can find in index page. https://rawgit.com/allenhwkim/angularjs-google-maps/master/testapp/

**Comment by alextrs** [comment]
That is the problem, I don't want to include google maps javascript to index.html and would like to use lazy-load feature. It shouldn't fail because somewhere in my application I used CSS class that matches ngMap directive (just to make it clear, my "directions" class on other page has nothing to do with google-maps).

**Comment by allenhwkim** [comment]
Is this about map-lazy-load directive does not work with directions directive? I also do not understand CSS class for directive because ngMap does not allow CSS directive.

**Comment by alextrs** [comment]
> Is this about map-lazy-load directive does not work with directions directive?

Not really
> I also do not understand CSS class for directive because ngMap does not allow CSS directive.

When you define 'directions' directive you immediately use google directions service:
````javascript
var directions = function(Attr2Options, $timeout) {
    var parser = Attr2Options;
    var directionsService = new google.maps.DirectionsService();
...
angular.module('ngMap').directive('directions', directions);
````

AngularJS parses DOM to find directives and sees 'directions' class. At this point it doesn't know whether it's allowed to use this directive as class or not because definition of it wasn't loaded yet. Then it tries to load definition and immediately fails because google maps library is not loaded
