### ISSUE TITLE
How to show markers in ng-repeat?

### ISSUE THREAD

**Issue by surendrakumar1992** [allenhwkim/angularjs-google-maps#234]
I have a query. I want to display dynamic markers in display and same for delete. How i can perform this?
Thanks in advance...

**Comment by quoidautre** [comment]
Hi,
Same question for me :).
I test, and it's not working...
Here : 

```
<map  center="{{center}}" zoom="{{mapzoom}}" pan-control="false"  zoom-control="true"  scale-control="true"  style="height:600px">

<marker  id="{{point.recordid}}"  
    on-click="showInfoWindow(event, 'infowindow-{{point.recordid}}')" 
    ng-repeat="point in allspots" position="{{point.fields.geo_coordinates[0]}},{{point.fields.geo_coordinates[1]}}" 
    title="{{point.fields.nom_site}}">
</marker>

   <info-window ng-repeat="point in allspots" id="infowindow-{{point.recordid}}"  visible-on-marker="{{point.recordid}}"> 
   
         <div>
            <div id="siteNotice"></div> 
            <h1 id="firstHeading" class="firstHeading">{{point.fields.nom_site}}</h1>
            <div id="bodyContent"> {{point.fields.adresse_complete}} </div>
        </div>
        
    </info-window>

</map>
```
Any idea ?

Thanks :)

F@brice

**Comment by allenhwkim** [comment]
info-window should not be ng-repeated. Please take a look the examples of infoWindow.

**Comment by surendrakumar1992** [comment]
Hey Man,  below code working for me..
$scope.allspots = [{ lat : 42.0004, lng : 97.676}, { lat : 42.4004, lng : 97.646}, { lat : 42.0404, lng : 97.6476}];
<map  center="41.0222, 93.6666" zoom="4" style="height:600px">
<marker  id="{{point.recordid}}"  
    ng-repeat="point in allspots" position="{{point.lat}} ,{{point.lng}}" 
    title="{{point.fields.nom_site}}">
</marker>
</map

**Comment by allenhwkim** [comment]
@surendrakumar1992 that works for marker, not for info-window. As I mentioned, infoWindow should not be used within ng-repeat. I am thinking of erroring out when infoWindow used in ng-repeat.

**Comment by quoidautre** [comment]
Ok. Thanks to answer, but it's a real problem for me if I can't using the InfoWindow.
Let me know if it's changing, please.

F@b

**Comment by allenhwkim** [comment]
This is the example infoWindow with multiple markers.

https://rawgit.com/allenhwkim/angularjs-google-maps/master/testapp/infowindow_compile.html
