### ISSUE TITLE
 $scope.$broadcast('init-map') troubleshooting help please

### ISSUE THREAD

**Issue by rasekar2000** [allenhwkim/angularjs-google-maps#235]
Hello Allen,

 I have slightly modified your Example 
  https://rawgit.com/allenhwkim/angularjs-google-maps/master/testapp/map_lazy_init.html
 to 
    http://59.160.116.52:9050/testapp/custom/map_lazy_init_mine.html

 Entire and much more details documented here 

 https://docs.google.com/document/d/1z4a7G_ZNqG2V5hPb_ZO3b3oTteKswQheKYQiiZBFwrk/

 Also raised in Stackoverflow.
 https://stackoverflow.com/questions/31215685/debug-scope-broadcastinit-map-in-ngmap-angularjs-google-map-troubleshoot

 Can you please help me on this troubleshoot.
Thanks and Regards,
Raj

**Comment by allenhwkim** [comment]
TL; DR;
Your example fires `init-map` event when document is loaded.

    angular.element(document).ready(function () {
        console.log('Hello World');
	 	$scope.clickMe(5);
        console.log('Hello World2 ');	 		       
    });

It seems all look fine to me. what's the problem is with your example.

**Comment by rasekar2000** [comment]
Hi Allen,
 
Thanks for the reply ..
 
 Inside that clickMe(5) , 
 All 4 options are <b>not firing</b> the close loop, so that the {{zoom}} get the value $scope.$broadcast('init-map') , $scope.$emit('init-map') , $rootScope.$broadcast('init-map') , $rootScope.$emit('init-map') 

 You can see that in 
    http://59.160.116.52:9050/seed/#/app/configure-svp
       And for the working example, 
          http://59.160.116.52:9050/testapp/custom/map_lazy_init_mine.html
              this  http://59.160.116.52:9050/testapp/app/scripts/services/attr2_options.js - Line 125 watches the {{zoom}} variable and gets updated.. But it is not the case with configure-svp. 

       Can you please review the difference in both console.log details.
 
Thanks and Regards,
Raj

https://docs.google.com/document/d/1z4a7G_ZNqG2V5hPb_ZO3b3oTteKswQheKYQiiZBFwrk/edit#heading=h.l0fofjpdmhc1

**Comment by allenhwkim** [comment]
Please make the problem short and simple.

 Honestly I do not read all your document and find out what problem  is . I only read your html  code without other library and find what is not working 

Thus send me the example code without 3rd party library and let me know what is expected and What is not working

**Comment by rasekar2000** [comment]
Hello allen,

 As per one of my friend's suggestion , In the clickMe, wrapped up with few ms delay (when making REST service call, there will be some realtime work will happen, so this $timeout hack is fine)  and $scope.$emit and it Worked.. So, updated the google doc as well closing this issue.
<code>
   $scope.clickMe = function(zoomValue){
                      console.log("Click Me");
                      $scope.zoom = zoomValue;
                     $timeout(function() {
                        $scope.$emit('init-map');
                    }, 100);						
    };
 </code>
Thanks and Regards,
rAj
