### ISSUE TITLE
Set the bounds to just the markers.

### ISSUE THREAD

**Issue by xavierjohn** [allenhwkim/angularjs-google-maps#237]
I would like the map to zoom in just to contains the shapes.
I can do it first time in mapInitialized but that won't get called again when the model changes later.

eg
        function setMapBounds(evt, evtMap) {
            var map = evtMap;
            //create empty LatLngBounds object
            var bounds = new google.maps.LatLngBounds();
            var locations= g_locations;
            for (var i = 0; i < locations.length; i++) {
                //extend the bounds to include each marker's position
                bounds.extend(new google.maps.LatLng(locations[i].coordinates[0], locations[i].coordinates[1]));
            }
            //now fit the map to the newly inclusive bounds
            map.fitBounds(bounds);
        }

It would be nice to have an AutoZoom option.

Thanks.

**Comment by xavierjohn** [comment]
I saw the pull request that talks about zoom-to-include-markers. How to use it?

**Comment by allenhwkim** [comment]
This has bee implemented with zoom-to-include-markers attribute for map tag. you can find example at testapp/map_zoom_to_include_markers.html

**Comment by xavierjohn** [comment]
Thanks, the only problem is it does not adjust when you add or remove markers.  I have fixed that in 
https://github.com/xavierjohn/angularjs-google-maps/commit/e135de22a67389dbdfeb4b2b1e6754befd91da95

Could you please point me to some material that shows how to setup your build environment? I am on Windows. I could then build and send you a pull request.  At this point the files in my build folder are not up to date.

**Comment by monove** [comment]
Please can someone help merge this mod. I really need it.

**Comment by allenhwkim** [comment]
it's already theere zoom-to-include-markers='true' or zoom-to-include-markers='auto'
