### ISSUE TITLE
Error while destroying directive with non-initialized map

### ISSUE THREAD

**Issue by fifonik** [allenhwkim/angularjs-google-maps#238]
Thanks for the great directives.

I have a map with @init-event in tab. The map is initialized when switching to tab. So in some cases the map is never initialized.

Unfortunately, in this case when the directive is destroyed, it tries to access obj.map, that is not initialized so an error is occured.

Demo:

	<div ng-if="!hide">
		<map zoom="11" center="[40.74, -74.18]" init-event="my-map-init">
			<marker position="[40.71, -74.21]" title="hello"></marker>
		</map>
	</div>
	<button ng-click="hide=!hide">Toggle</button>

Click Toggle button and you'll see an error in console.

**Comment by allenhwkim** [comment]
Could you add a plunker example to reproduce your error on my end?

**Comment by fifonik** [comment]
http://plnkr.co/edit/q4GAbPsnEmvZie2rAtNU

**Comment by allenhwkim** [comment]
The problem you have is 'ng-if' which destroy DOM element by condition.

`init-event` only works map tag is ready, but with `ng-if` map tag is not event ready, but you are broadcasting init event, which does not work at all.

I recommend to use `ng-show` instead of `ng-if` when you have `init-event`.

**Comment by fifonik** [comment]
Hm.
I understand why this error happened in the example. I used ng-if intentionally to demonstrate that if map was not initialized (there is not any broadcast that initialize the map in my example) it will cause the error.

In my real life application I do not have ng-if. I have a map on a tab in modal and the map is initialized only if the used switched to the tab after opening the modal. If user closes the modal without switching to the tab with the map -- I got the same error because of the same reason as in example.

I do not think that something wrong with a logic in my UI. A map might be not initialized before destroying. And I believe that the directive should delete variables after itself only if they were initialized.

**Comment by allenhwkim** [comment]
Init-event should not be used in your case then, or used it logically, eg, by calling it after the map section is visible and ready

**Comment by fifonik** [comment]
OK, I'll try to make another example to better explain my workflow.

**Comment by fifonik** [comment]
Here is another example (the way I'm trying to use ng-map atm):
http://plnkr.co/edit/eOzjGnY35OH6rb9zDTbQ

1. Click "Open modal" button.
2. Select tab with map.
3. Click OK/Cancel button => no error
4. Click "Open modal" button
5. Click OK/Cancel button without clicking tab with map first => error in console.

Could you recommend how to fix the logic?

Thanks.

**Comment by allenhwkim** [comment]
Thanks for adding another example, and thanks for your patience
I have added small routine to fix this issue.

**Comment by fifonik** [comment]
Thanks, It is fixed now.

P.S. I fixed it in local source in very similar way by adding if(!obj.map) return;
