### ISSUE TITLE
DirectionsRendererOptions not working?

### ISSUE THREAD

**Issue by nguyentrangdong** [allenhwkim/angularjs-google-maps#239]
hi, i have problem

https://developers.google.com/maps/documentation/javascript/reference#DirectionsRendererOptions
i tried add option "suppressMarkers" and "polylineOptions" for "directions" directive but it not working.

please help me :(

**Comment by allenhwkim** [comment]
Thanks for using this module.
Please add a plunker example for this, so that I can see your error on my end.

**Comment by nguyentrangdong** [comment]
Thanks for your reply, i just created example for this issues : http://plnkr.co/edit/iIsueZPGQLRJKUVQQ88n?p=preview

"suppressMarkers" => true : hide "A" and "B" marker icons
but it not working. please help me.

**Comment by nguyentrangdong** [comment]
So if it is Bug, can you fix for "markerOptions" and "polylineOptions" option same ? :)

**Comment by allenhwkim** [comment]
http://plnkr.co/edit/JgPjdTWkzatvCcjFZhJc?p=preview
