### ISSUE TITLE
Remove (move off) the fallback styling on the "map" directive

### ISSUE THREAD

**Issue by highfield** [allenhwkim/angularjs-google-maps#240]
I mean that you want to yield the user a ready-to-use component, but in my case the actual size (height) is dynamically calculated and it isn't ready at the moment of the "map" creation (i.e. directive linking).
The result is that there's no (easy) way to set the desired "height" style (100%) in my case, because the calculated result is always "0px", then set to "300px" by your patch.
My suggestion is to remove, as the original maps are, and/or add a small CSS document with the default styles.
At the moment I'm using a modified version of your source, but I don't like this solution!

**Comment by allenhwkim** [comment]
That's a good suggestion.

I do not usually style element in JS, however this directive was for a
beginner, it would be convenient for a user without .css.

How about this? Having an extra attribute not to write style for "map" tag.
e.g., `no-style`

Allen

**Comment by highfield** [comment]
Well, bear in mind I'm *not* an expert of the web dev.
The "no-style" could be a solution, but (question) would be feasible to inspect the "style" content attribute and look for the "height" prop? Just peeking at the presence: if present, the default styling should be skipped. I mean, whereas someone explicitly sets the style, probably do know what to do.

Anyway, again, feel free to choose what's better for your viewpoint.
In the meantime, I have other problems to solve (info-windows), but that's off this thread.
Mario

**Comment by allenhwkim** [comment]
added an attribute `default-style` to override it. you can find example at testapp/map_no_default_style.html
