### ISSUE TITLE
placeholder if no connection

### ISSUE THREAD

**Issue by happschinson** [allenhwkim/angularjs-google-maps#243]
Hi! Would it be possible to show a placeholder for the map, if there is no internet connection? Thanks!

**Comment by allenhwkim** [comment]
Google map requires internet connection AFAIK. 
Your use case might be different. Could you explain your use case for me please?

**Comment by fifonik** [comment]
My app should work without google maps available as well (with slightly limited functionality). Here is my current straightforward solution:

In controller:

	$scope.googleMapsLibs = {
		  ready: false
		, message: 'Initializing google maps...'
	};
	$timeout(function(){
		$scope.googleMapsLibs.message = 'Can\'t initialize google map libraries.';
	}, 10000);


In HTML:

	<style>
		.map-canvas {
			width: 450px;
			height: 300px;
			border: 1px solid black;
		}
		.map-canvas .map, .google-libs-not-initialized, .google-libs-initialized {
			width: 100%;
			height: 100%;
		}
	</style>
	<div map-lazy-load="https://maps.googleapis.com/maps/api/js">
		<div ng-init="googleMapsLibs.ready = true"></div>
	</div>
	...
	<div ng-if="googleMapsLibs.ready">
		<input
			id="location"
			places-auto-complete
			ng-model="location"
		/>
	</div>
	...
	<div class="map-canvas">
		<div
			class="google-libs-not-initialized"
			ng-if="!googleMapsLibs.ready"
			ng-bind="googleMapsLibs.message"
		></div>
		<div
			class="google-libs-initialized"
			ng-if="googleMapsLibs.ready"
		>
			<map
				...
			>
				...
			</map>
		</div>
	</div>

You can put <map/> into div/@map-lazy-load, but in my case it might be more than one map on the page so I decided to go this way :)

**Comment by allenhwkim** [comment]
thanks @fifonik
