### ISSUE TITLE
Show/Hide Map

### ISSUE THREAD

**Issue by MadaManu** [allenhwkim/angularjs-google-maps#244]
I am using the map directive to show a map on a page after the loading of data has been done. So I'm trying to display a loading message (and not the map) and once the load has happened and returns the promise (api call) then I want to show the map. 

However once the loading is done and the map should be displayed I get back this

http://i.gyazo.com/80f1cf0592eac0a6fdf4d06c2ea24ca0.png

How can I fix this?

**Comment by allenhwkim** [comment]
I need to see your code. Please provide me a plunker.

**Comment by MadaManu** [comment]
I can't provide with the actual code as it is part of a bigger project, but I have tried to simulate it in a plunker and here is what it happens.

http://plnkr.co/edit/oQE2ugZS8Li7V8DibCGS

**Comment by MadaManu** [comment]
I have fixed the issue by using a little workaround by triggering the resize on the map after a short delay.
Here's the updated plunker.
http://plnkr.co/edit/yIzwZuHF21GmYxGmBmqp

Also, if anyone will require once the map is shown that it will focus on bounds do the fit bounds just after the resize as shown in the comments on the plunker above.
