### ISSUE TITLE
Can i get all polygons?

### ISSUE THREAD

**Issue by minmur** [allenhwkim/angularjs-google-maps#245]
Hi.

I have a list of polygon descriptions and am painting them with `shape` directive. Something like this:

```javascript
// in controller
vm.polys = [{
            "id": 40571,
            "name": "Via Garibaldi, Genoa, Italy",
            "path": [
              [44.412482, 8.930734], [44.410795, 8.929901], [44.409432, 8.935265],
              [44.410795, 8.935989], [44.412482, 8.930734]
            ],
            "area": 0.0000092841999999853514
          }, ...];
```
```html
// in template
<shape
  ng-repeat="poly in ctrlGeo.polys track by poly.id"
  name="polygon"
  paths="{{poly.path}}"
  stroke-color="#FF0000"
  stroke-opacity="0.8"
  stroke-weight="2"
  fill-color="#FF0000"
  editable="{{poly.editable || false}}"
  on-click="ctrlGeo.onPolyClick(poly)"
  fill-opacity="0.35"></shape>
```

Thing is that some of polygons are overlapping and it's impossible to select some of them. For example, one big polygon overlaps some smaller ones and i can't select them.
I'm thinking to bind click event on map (instead of shape's on-click) and check how many polygons were hit (`google.maps.geometry.poly.containsLocation` will help). But thing is that i need to iterate over all polygons in the map (no more them 200) to check if each of them was hit. And i can't find the way to get this list of polygons.

Any ideas?

**Comment by allenhwkim** [comment]
To click a polygon possible, I think zIndex options is for that.

https://developers.google.com/maps/documentation/javascript/3.exp/reference#RectangleOptions.

**Comment by minmur** [comment]
That helped. Thanks.
