### ISSUE TITLE
Marker not clear form map?

### ISSUE THREAD

**Issue by surendrakumar1992** [allenhwkim/angularjs-google-maps#246]
@allenhwkim 
Hey dude... I move a maker between two date data on map. I create a marker and set it to map. But when i again move to maker then new marker instance create but old marker remain on map.
I try $scope.marker = [] but not working
Please help

**Comment by allenhwkim** [comment]
`ng-repeat` is for that case. There are some examples you can find

On Fri, Jul 24, 2015 at 1:47 AM, surendrakumar1992 <notifications@github.com
