### ISSUE TITLE
setMap(null) Directive Attribute

### ISSUE THREAD

**Issue by nikeshbhagat** [allenhwkim/angularjs-google-maps#248]
Hello,

I think it would be very useful if, along with the 'visible' attribute of shapes and markers, you could include an attribute that would set shapes/markers to null by default (e.g., setMap(null) ).  For maps that are heavier in terms of polygons and polylines, this would be very useful.

What do you think?

Best,

NB

**Comment by allenhwkim** [comment]
There are visible options for marker and shapes

https://developers.google.com/maps/documentation/javascript/reference#MarkerOptions
https://developers.google.com/maps/documentation/javascript/reference#RectangleOptions

You can easily make it show and hide by setting this attribute. e.g., `visible="true"`, `visible="false"`, ., `visible="{{myVal}}"`,

**Comment by nikeshbhagat** [comment]
Hello,

Thank you for your replay.

I am aware of that functionality. What I'm proposing is that there is also a way to set shapes and markers to null. Using the Google Maps V3 Javascript API, that would look like this, marker.setMap(null) or polygon.setMap(null), etcetera. Perhaps, as an attribute to Marker or Shape, you could add 'setMap' or something with values that could be something like true | false or maybe map | null (false and null values would trigger setMap(null) or remove the map from the marker/shape.

There is a big difference between setting a marker or polygon's visibility attribute and it's map attribute.

Hope I am explaining myself well enough.

Best.

**Comment by allenhwkim** [comment]
With ng-repeat, markers and shapes are dynamically created and destroyed along with DOM element.

You can have a pool of properties of markers and shapes, and collect the ones you want to show(by using filter) , then assign the collection to ng-repeat.

IMO this approach is a lot simpler than setting map to null or not

**Comment by achwak** [comment]
HEllo, 
I have a question
I wonder how we can access shapes created by ng-repeat in order to update them
