### ISSUE TITLE
Marker Labels

### ISSUE THREAD

**Issue by extravagangsta** [allenhwkim/angularjs-google-maps#249]
Hi!

I didn't find the Marker Label feature available in the library. Not an issue really but would be very helpful to have it out of the box.

Will this be added any time soon?

More info here:
https://developers.google.com/maps/documentation/javascript/3.exp/reference#MarkerLabel
https://developers.google.com/maps/documentation/javascript/examples/marker-labels

**Comment by allenhwkim** [comment]
You can just add label="X"

http://plnkr.co/edit/ClzY0NvA5TeoTGvya1Sm?p=preview

**Comment by extravagangsta** [comment]
So easy! Thanks a lot!
