### ISSUE TITLE
Is there an example for marker clustering?

### ISSUE THREAD

**Issue by suuuunto** [allenhwkim/angularjs-google-maps#251]
Hi there,

I work with that rep and it works perfect! But I got too many markers, therefore I am looking for an example for clustering the markers with ngmap (https://developers.google.com/maps/articles/toomanymarkers). Is there something around?

Thanks,
suuuunto

**Comment by allenhwkim** [comment]
https://rawgit.com/allenhwkim/angularjs-google-maps/master/testapp/marker-clusterer.html

For this case, you need to control all markers through marker-clusterer though. Lots of raw programming required.
