### ISSUE TITLE
Zoom does not work the first time.

### ISSUE THREAD

**Issue by xavierjohn** [allenhwkim/angularjs-google-maps#252]
When zoomToIncludeMarkers = 'auto', it does not zoom the first time. You need to call ctrl.zoomToIncludeMarkers() the first time. Here is the fix.

            google.maps.event.addListenerOnce(map, "idle", function () {
                scope.$emit('mapInitialized', map);
                if (attrs.zoomToIncludeMarkers) {
                   ctrl.zoomToIncludeMarkers();
                   if (attrs.zoomToIncludeMarkers == 'auto') {
                     scope.$on('objectChanged', function(evt, msg) {
                       msg[0]== 'markers' && ctrl.zoomToIncludeMarkers();
                     });
                  }
               }
           });

**Comment by allenhwkim** [comment]
can u send me a pull request, including the document changes in map.js?

**Comment by xavierjohn** [comment]
Sure, I will send it tomorrow. The build env is on the office machine which took me a few hours to figure out. Luckily angualr js has a good doc on it https://docs.angularjs.org/misc/contribute and I just needed to use gulp instead of grunt.

**Comment by allenhwkim** [comment]
@xavierjohn fixed this issue and the changes are merged.
