### ISSUE TITLE
Causing some issues

### ISSUE THREAD

**Issue by fclaussen** [allenhwkim/angularjs-google-maps#253]
Hey guys. I'm working on a project and I'm using this map module to display the map on the contact page.

However, ever since I included it I'm having some issues. My extension that inspect angular (ng-inspect) stops working and chrome crashes. If I open batarang I can see some of the map information like the info-window floating inside my console and it also crash.

Also, on the console it says that it could not find a image. But the image is being loaded fine. It also says that ng-map is trying to load that image and failing but I know for a fact that the image is coming from somewhere else.

![ngmap2](https://cloud.githubusercontent.com/assets/1021860/8942362/93dd1712-353a-11e5-9ac0-9feb0bd76bc1.jpg)

![ngmap1](https://cloud.githubusercontent.com/assets/1021860/8942363/93dda7ea-353a-11e5-99e8-73fe667556a9.jpg)

My code for the map:
`angular.module('app', ['ui.router', 'ngSanitize', 'ui.utils', 'ngAnimate', 'ngMap']);`

```html
<map center="{{general.map.lat}}, {{general.map.lng}}" zoom="16" scrollwheel="false">
	<marker id="map-marker" position="{{general.map.lat}},{{general.map.lng}}" title="Lorem Ipsum"></marker>
	<info-window id="address" visible-on-marker="map-marker">
		<div id="bodyContent" ng-bind-html="trustAsHtml(general.address)"></div>
	</info-window>
</map>
```

Any ideas? If I remove the map module and code everything works fine.

**Comment by allenhwkim** [comment]
tested with batarang and ng-inspect. Could not find any issue.

![image](https://cloud.githubusercontent.com/assets/1437734/8943019/83ec4920-3546-11e5-9b9c-c27030de4015.png)

I have tested this page. https://rawgit.com/allenhwkim/angularjs-google-maps/master/testapp/infowindow_compile.html

One thing I found is that infoWindow should be ng-non-bindable, but doubt it causes issues.

        <info-window id="bar">
          <div ng-non-bindable="">
            Lat: {{this.getPosition().lat()}}<br/>
            Lng: {{this.getPosition().lng()}}<br/>
          </div>
        </info-window>

It looks like Batarang version different.

**Comment by fclaussen** [comment]
;(
I'm using an old version of batarang. The new one is not working for me anymore. But I really just have it installed for no reason. I'm using ng-inspect extension to work. I found it better.

But anyway. Even with no extensions. There is the image not found problem. So weird.

**Comment by allenhwkim** [comment]
You have image name wrapped with `{` `}`

**Comment by fclaussen** [comment]
This is how I'm doing it.
`<div style="background:url({{contact.featured_image.source}}) center center no-repeat; background-size: cover;" class="single-hero">`

If I remove the module all problems disappear.

**Comment by allenhwkim** [comment]
Can I see your example in plnkr?

**Comment by fclaussen** [comment]
Cannot replicate. If I create a plunker with the map only it works fine.
It could be some problem with some other module, maybe?

I'm using ui.router NgSanitize ui.utils and ngAnimate.

For the routing I'm using resolve like this:
```javascript
.state('contact', {
		url: '/contact/',
		templateUrl: TK.theme_folder + '/partials/contact.html',
		controller: 'ContactController',
		resolve: {
			Contact: function($http){
				return $http.get(TK.home_url + 'wp-json/posts?filter[name]=contact&type[]=page');
			},
			General: function($http){
				return $http.get(TK.home_url + 'wp-json/option');
			},
			SEO: function($http){
				return $http.get(TK.home_url + 'wp-json');
			}
		}
	});
```

and on my controller I assign it like this

```javascript
$scope.contact = Contact.data[0];
$scope.general = General.data;
```

It would take me a while to replicate it exactly on plunker.

**Comment by allenhwkim** [comment]
If it is ngMap problem, I can make a fix. To know it is a ngMap problem, I need to see the problem.

**Comment by fclaussen** [comment]
I understand. Do you have a public email I can send a dev environment link?
I can't make it public

**Comment by allenhwkim** [comment]
Sorry, I do not get into your dev env. I want you to replicate your issue in simpler way.

**Comment by fclaussen** [comment]
I understand.
Well I realized now that the problem is being caused by something else.
I just tested a different gmaps module and I got the same problem as soon as I load it.
Not sure what it is, but it is not related to this module exactly.

Thanks for your help

**Comment by azachar** [comment]
Try to remove ngAnimate what would happen.

**Comment by fclaussen** [comment]
Nothing changes. I removed all except ui.router
