### ISSUE TITLE
Draggable not working with Windows Phone Nokia N9

### ISSUE THREAD

**Issue by nguyentrangdong** [allenhwkim/angularjs-google-maps#257]
Hi, i found out that your map can't Draggable in Windows Phone.

Example: Access any demo
like :
- https://rawgit.com/allenhwkim/angularjs-google-maps/master/testapp/street-view_road_trip.html
Click right mouse on Chrome browser, choose Inspect Element -> Click Mobile Icon in Left angle -> At Device, you choose Nokia N9 and Reload Browser. Try to drag on map, it not working :)

Thanks.

**Comment by allenhwkim** [comment]
Actually all example are not working with Nokia N9. 
All examples in testapp are not coded for all mobile phones.

All maps in ngmap.github.io are working with Nokia N9. 

There must be some difference between two, but I did not debug for those.
When I have some time to debug all testapp files for Windows phone, I will get into it. Not high priority though.

**Comment by nguyentrangdong** [comment]
Anyway, your product is awesome. But i still hope you can fix that, at least for newest Windows Phone version.

Thanks. :)

**Comment by allenhwkim** [comment]
Thanks @nguyentrangdong 

This will not be a fix of ngMap module though. Based on two different sites(one working, one not), it must be some adjustment in html(css, head, javascript). That's why I do not give high priority to it.

**Comment by nguyentrangdong** [comment]
i understand, thank for your response :)
