### ISSUE TITLE
Controller As over $scope ?

### ISSUE THREAD

**Issue by JeffBaucom** [allenhwkim/angularjs-google-maps#258]
Is it possible to use Controller As instead of $scope for this? I've tried to access the map variable with the Controller As method instead of $scope but it comes up as undefined.

I know you can mix $scope and Controller As but I was just wondering if there was a way to access the map with Controller As only.

**Comment by allenhwkim** [comment]
Please add a plunker for your usage. 
FYI, you can have any controller the way you want, and you can get map instance with `mapInitialized` event.

**Comment by JeffBaucom** [comment]
http://plnkr.co/edit/4rnQWdJNTn2mbZPBCPDs?p=preview

**Comment by allenhwkim** [comment]
Here we go,

http://plnkr.co/edit/n9M0RqIhrKRyEGgF0dfk?p=preview

**Comment by JeffBaucom** [comment]
Works great, thank you!

**Comment by allenhwkim** [comment]
A star to this module can be helpful for other users.
