### ISSUE TITLE
Using variable in map-lazy-load

### ISSUE THREAD

**Issue by stschaefer** [allenhwkim/angularjs-google-maps#259]
Hi Allen,

first: thanks for sharing your work. :) I really appreciate it.

I'm using the map-lazy-load mechanism. We have the requirement to use different Google API keys on different websites. So I want to store them in config variables and use them in map-lazy-load. Is something like the code below possible?

<div map-lazy-load="{{ myConfigVariable }}">
    <map center="Brampton" zoom="10">
      <marker position="Brampton"></marker>
    </map>
  </div>

Thanks for your time. Greetings,
Stefan

**Comment by allenhwkim** [comment]
Setting the source .js in config state would be great. 

However, you still have an option to specify your .js using `src` attribute. Please take a look at this example

https://github.com/allenhwkim/angularjs-google-maps/blob/82b5c10b6b00763f940430d95e8cb084105e3fce/testapp/map-lazy-load.html

If this example does not satisfy, I need to build a provider that will be used in config, which I thought was a overkill.


    `<div map-lazy-load="https://maps.google.com/maps/api/js" ng-controller="MyCtrl">`

**Comment by stschaefer** [comment]
Hi,

thanks for your quick reply. I've already implemented the lazy-loading exactly as described in the documentation. I was just searching for a way to use variables in it.

Do you have an idea how I can achieve this? Or do you plan to implement that feature in the near future?

Stefan

**Comment by allenhwkim** [comment]
This will work?

`<div map-lazy-load="{{myVariable}}" ng-controller="MyCtrl">`

**Comment by allenhwkim** [comment]
any update? if not I will close it

**Comment by stschaefer** [comment]
Sorry for my late response. I was off for vacation for five days... :)

Passing a variable in map-lazy-load works, but the map is not initialized. The container stays empty and the "mapInitialized" event is not thrown.

In my coding the container looks like this:
<div map-lazy-load="{{myVariable}}">
    <map id="map" zoom="15" class="map">
    </map>
</div>

In the html's source code the container then looks like this:
<div map-lazy-load="https://maps.googleapis.com/maps/api/js?key=XXX&amp;v=3.exp&amp;libraries=places" class="ng-scope"></div>

Somehow I need to force the initialization by myself because the directive does not "notice" the variable has a value??? Any ideas?

**Comment by pmcochrane** [comment]
I seem to have the same issue and getting the same effect in that the map is not created on the page. The html source just shows an empty  map-lazy-load div.

**Comment by allenhwkim** [comment]
@stschaefer could you create a plnkr for this without api key?

**Comment by pmcochrane** [comment]
Hi Allen. Not really ever created a plunkr or a pull-request and have enough problems getting my app to work. I have worked around this with a very slight modification to map-lazy-load.js which would be great if you could include it.


```
(function() {
  'use strict';
  var $timeout, $compile, src, savedHtml;

  var preLinkFunc = function(scope, element, attrs) {
    window.lazyLoadCallback = function() {
      void 0;
      $timeout(function() { /* give some time to load */
        element.html(savedHtml);
        $compile(element.contents())(scope);
      }, 100);
    };

    if(window.google === undefined || window.google.maps === undefined) {
      var scriptEl = document.createElement('script');
      var mapsUrl = attrs.mapLazyLoadParams || attrs.mapLazyLoad;    
      scriptEl.src = mapsUrl + (mapsUrl.indexOf('?') > -1 ? '&' : '?') + 'callback=lazyLoadCallback';
      document.body.appendChild(scriptEl);
    } else {
      element.html(savedHtml);
      $compile(element.contents())(scope);
    }
  };

  var compileFunc = function(tElement, tAttrs) {

    (!tAttrs.mapLazyLoad) && void 0;
    savedHtml = tElement.html(); 
    src = tAttrs.mapLazyLoad;

    /**
     * if already loaded, stop processing it
     */
    if (document.querySelector('script[src="'+src+(src.indexOf('?') > -1 ? '&' : '?')+'callback=lazyLoadCallback"]')) {
      return false;
    }

    tElement.html('');  // will compile again after script is loaded
    return {
      pre: preLinkFunc
    };
  };
```

This is pretty much the same apart from the scriptEl.src line in the preLink function. I also copied your code to detect if the URL already has a ? in it to the compileFunc.


The html to pass in the path to google plus the API parameters is:
```
<div map-lazy-load="http://maps.google.com/maps/api/js" map-lazy-load-params="{{googleMapsUrl}}">
	<map class="col-xs-12 noGutter bordered roundedBottom mapVanRun" name="mapVanRun"
		center="Perth,Scotland"
		zoom="8">
	</map>
</div>

```
Set the googleMapsUrl in your controller (e.g. from an app constant) and this is passed as an additional attribute to the map-lazy-load directive. Using a combination of your lazy-load technique (the fixed URL to google) and detecting if the other attribute (the one with the API key) has been set in the prelink function basically leads to google being loaded with the correct API key.

Hopefully this will fix Stefan's problem as well.

**Comment by stschaefer** [comment]
@pmcochrane Thanks for your coding. :)

@allenhwkim Do you still need a plnkr?

**Comment by allenhwkim** [comment]
@stefan, i m just busy and lazy to copy/paste code into plunker.
If you can do, that will make the process faster.
Actually pull request is a lot better than plunker if you can, so that I
can add you as a contributor here.

**Comment by pmcochrane** [comment]
Hi. I've tried to make a pull request for this but can't seem to get it to upload to github. I'm using Github Desktop and it's failing at upload with an "authentication failed" error. Do I need to be added as a contributor or something by yourself Allen?

**Comment by allenhwkim** [comment]
Thanks Paul,
You do not do `git push`, but creating a pull request.

https://help.github.com/articles/using-pull-requests/

**Comment by pmcochrane** [comment]
Allen. I think I've created the pull request it properly but unsure. It updates the javascript, adds a new testapp page map-lazy-load-params.html and I've also had a go at adding information to the docs. Unfortunately, I haven't a clue how to add test cases at present so can't really add anything there.

Have a look and see what you think.

**Comment by pmcochrane** [comment]
I think I've forgot to do something for the pull request but not entirely sure what. Maybe I missed something for bower.

Came into work today, ran bower update but never got an updated copy of the repository downloaded. The github repository has the changes but bower doesn't seem to pick them up.
