### ISSUE TITLE
Marker Right Click event handler (marker context menu)

### ISSUE THREAD

**Issue by extravagangsta** [allenhwkim/angularjs-google-maps#260]
Hi,

This is not a real issue and probably out of scope of this project but I just wondering if I can have right click handler on the marker in some way using ngmap.
I need to create Context menu on the marker. Something similar to what google maps has: right click on the displayed marker shows context menu with "Directions from here", "Direction to here" items in it.

Thanks!

**Comment by allenhwkim** [comment]
There are rightclick event on marker, use `on-rightclick=yourFunc()`.

https://developers.google.com/maps/documentation/javascript/3.exp/reference#Marker

**Comment by extravagangsta** [comment]
Thanks for the reference and such a quick response!

I got the handler working in this way:
```
    $scope.$on('mapInitialized', function (evt, map) {
      vm.map = map;

      var marker = new google.maps.Marker({
        position: vm.map.getCenter(),
        map: vm.map,
        title: 'Marker right click'
      });

      google.maps.event.addListener(marker, 'rightclick', function () {
        $log.info('Marker right clicked');
      });

    });
```
As I understand I will need to control event listeners and markers creations on my own (can't use marker directive for this)?

Is there something like "on-right-click" directive within "marker" directive which will automatically create, attach and destroy listeners on marker creation/removal (with the use of marker directive)?


Thanks!

**Comment by allenhwkim** [comment]
I was talking this way.

    $scope.myFunc = function(evt) {
       console.log('this marker', this);
    }

    <map ... >
      <marker on-rightclick="myFunc" position="xxxxxxx" ... ></marker>
    </map>

Sllrn

**Comment by extravagangsta** [comment]
Great! Exactly what I need. Didn't know I can do this.
Thanks a lot!

**Comment by mkgn** [comment]
on-rightclick doesn't work if you add it to a custom marker. I have
<custom-marker ng-repeat="(key, value) in positions" position="" on-click="markerAction(value)" on-rightclick="markerRightClick()"> ....

on-click works but not the right click. am I doing something wrong here ?

**Comment by fasalir** [comment]
@allenhwkim hi, how to have on-rightclick working on direction? so i want to remove waypoints from the map. i want the selected marker removed from the map on rightclick

this is my code 
`<ng-map id="map" 
	class="ui-map" 
	center="{{_setPointRuteCtrl.center}}" 
	zoom="12" 
	on-click="mapClicked()" 
	on-rightclick="markerRightClick()"
	disable-double-click-zoom="true" 
	on-dragend="_setPointRuteCtrl.onDragend($event)">
	<directions draggable="false"
		on-dragend="_setPointRuteCtrl.onDragend($event)"
		panel="directions-panel"
		waypoints="{{_setPointRuteCtrl.listMarkers}}"
		origin="{{_setPointRuteCtrl.origin}}"
		destination="{{_setPointRuteCtrl.destination}}">
	</directions>
</ng-map>`

if i place is inside ng-map tag, it doesn't work.
