### ISSUE TITLE
Change overlay image url

### ISSUE THREAD

**Issue by main-kun** [allenhwkim/angularjs-google-maps#261]
If i show an image over a map, is there any way to change it's url, for example, with a press of a button? I thought if I set the url of an image to a scope variable and change it inside the function, the image would update, but it doesn't. [I put together a plunkr to show the problem](http://plnkr.co/edit/YCzlqh04prZnJ5Gty3yY)

**Comment by main-kun** [comment]
I found a solution. If you get the map object on mapInitialized, you can access the url of the url with it.

    var map;
    $scope.$on('mapInitialized',function(evt, evtMap){
        map=evtMap;
        console.log(map.shapes.foo.url);
    }) 

And then you need to redraw the overlay 

    map.shapes.foo.setMap(null);
    map.shapes.foo.setMap(map);

Anyway, it would be nice if the directive could handle this.

**Comment by allenhwkim** [comment]
use `ng-if` or `ng-repeat` to handle that

**Comment by main-kun** [comment]
ng-if wasn't working for me for some reason, and now it worked when i tried out in plunkr. Anyway, thank you, great lib.

**Comment by allenhwkim** [comment]
http://plnkr.co/edit/853fw4dFRh5wIt7tYQoK?p=preview

 Overlay does not have setUrl function, thus, you cannot change it by observing it.

You need to manually set url, and redraw it.

      $timeout(function(){
        $scope.map.shapes[0].url = $scope.url;
        $scope.map.shapes[0].setMap(null);
        $scope.map.shapes[0].setMap($scope.map);       
      })
