### ISSUE TITLE
When using directions, how can I set the current location as the origin?

### ISSUE THREAD

**Issue by kdawg1406** [allenhwkim/angularjs-google-maps#264]
I can't figure out how to use directions correctly.  

How can I set the origin to my current location?  The below code does not work.  Thank you so very much, fantastic API.

<directions 
    destination="..."
    origin="current-location">
</directions>

**Comment by allenhwkim** [comment]
Sorry, `current-location` is not currently supported for directions directive. 
Will be added in later release.

**Comment by kdawg1406** [comment]
Allen, thank you.

Can you help me with finding my current location using your API?  Couldn't figure this out.

Thank you,

Karl

**Comment by allenhwkim** [comment]
https://github.com/allenhwkim/angularjs-google-maps/blob/master/services/navigator_geolocation.js

```
NavigatorGeolocation.getCurrentPosition().then(function(pos) {
   ...
});
```

**Comment by kdawg1406** [comment]
Thank you!!

**Comment by allenhwkim** [comment]
Can u give this module a star, so that other people can use it?

**Comment by allenhwkim** [comment]
Reopening to add `current-location` for origin/destination

**Comment by kdawg1406** [comment]
Star added.  Thank you, fantastic API.

**Comment by allenhwkim** [comment]
Please leave this issue open. I will use this ticket to add feature of adding `current-location` for origin/destination

**Comment by kdawg1406** [comment]
oops, my bad.
