### ISSUE TITLE
zoom-to-include-markers = auto with slow AJAX requests

### ISSUE THREAD

**Issue by Charkhan** [allenhwkim/angularjs-google-maps#265]
Hi,

I faced this problem today, when you need to display a gmaps depending on dynamic results.

Locally it works perfectly fine, because dynamic results are fetching quick enough ( ~ < 1sec)

But when results takes too much time (ie: in dev servers...), it displays something like this : 

![bug](https://cloud.githubusercontent.com/assets/2292699/9175766/b61fa734-3f87-11e5-99a3-61e01d2f0205.png)

Markers are in, but it's clearly zoom out.

Here's a sample of the syntax I'm using
```
<map zoom-to-include-markers="auto" center="[@{{ map.lat }}, @{{ map.lng }}]" scrollwheel="false" class="search-map" draggable="{{ isMobile() ? 'false' : '' }}">
        <marker position="[@{{ map.lat }}, @{{  map.lng }}]" icon="{{ url('/assets/images/icon-my-search-red.png') }}"></marker>
        <marker ng-repeat="result in results track by $index" position="[@{{ result.locations[0].practice.gps_lat }}, @{{ result.locations[0].practice.gps_lng }}]" icon="{{ url('/assets/images/pin-others-map.png') }}"></marker>
</map>
```
I tried to use the "objectChanged" event, but console reports me errors about "maps.fitBounds is undefined"

Thanks for the great work anyway !

**Comment by allenhwkim** [comment]
Can u make a plunker for this using `$timeout` to fake the slow Ajax responses, so that I can see your problem?

**Comment by Charkhan** [comment]
http://plnkr.co/edit/Mfege9lhpBCKmhxkCMQz?p=preview

For some reason, I can't make the map working properly... I got "Error: s.getGeoLocation is not a function" for the first marker.

**Comment by allenhwkim** [comment]
http://plnkr.co/edit/qRuR8PtNSluYjCENQh7c?p=preview

These are reserved by ngMap.
$scope.maps
$sc0pe.mpa
MapController

**Comment by Charkhan** [comment]
http://plnkr.co/edit/Mfege9lhpBCKmhxkCMQz?p=preview

Ok I figured out. If the center is changed (if not defined, it will center to coords 0,0), then its like remembering the old center and deal with the new one to fit both in the map ( which would explain the big zoom out).

You can see it on the plunkr.

**Comment by allenhwkim** [comment]
so, closing?

**Comment by Charkhan** [comment]
Well, Not really don't know how to resolve it, because timeout to wait for AJAX data to fetch is not very reliable...

I Dunno if it comes from de directive or GMaps itself ?

**Comment by allenhwkim** [comment]
You set center of map close to the new one, it will be good.
Or you can delay of the map initialization by using init-event. Example is here

https://github.com/allenhwkim/angularjs-google-maps/blob/master/testapp/map_lazy_init.html

**Comment by meditsimple** [comment]
Added the start !

Ok the init-event thing made it work ! Thanks for the help.

Just one more thing : what if you move the map's center ? zoom-to-include-markers = auto must re-evaluate not only when markers are changed, but also when the map's center change.

I'm trying it right now and it doesn't work :/

**Comment by Charkhan** [comment]
Added the start !

Ok the init-event thing made it work ! Thanks for the help.

Just one more thing : what if you move the map's center ? zoom-to-include-markers = auto must re-evaluate not only when markers are changed, but also when the map's center change.

I'm trying it right now and it doesn't work :/

**Comment by Charkhan** [comment]
http://plnkr.co/edit/zmOVPFJB6Z9MPc8EGKIS?p=preview

You can see the concrete example here.
