### ISSUE TITLE
Updating ng-model with autocomplete content in AngularJS app using keyboard to select from dropdown

### ISSUE THREAD

**Issue by Trevomatic** [allenhwkim/angularjs-google-maps#268]
Hi - I am designing an Angular app using ngMap. I got the autocomplete working fine, and when I select an address with the mouse it updates the ng-model, but when I select with the keyboard the ng-model doesn't update and the only content I can console.log is what I typed.

**Comment by allenhwkim** [comment]
Please check this example,

https://rawgit.com/allenhwkim/angularjs-google-maps/d5ab042cbe6fbb5145a5174c2bc7e16d5305c30d/testapp/places-auto-complete.html

You need to add `on-place-changed` callback to customize your result.

**Comment by cur3n4** [comment]
You can see that behaviour in your test app for places autocomplete: type in an address, move down with the arrows and click enter. The underlying ng-model doesn't get updated (bottom address row). It does if you select it with the mouse.

**Comment by allenhwkim** [comment]
updated with 1.10.1

**Comment by cur3n4** [comment]
Thanks a lot for the fix. I believe an improvement would be to add the updateModel to the place_changed event before all the other events are added. That way when the on-place-changed callback is invoked, the model has already been updated.

**Comment by allenhwkim** [comment]
I could not exactly get it. This is the way implemented; update model when place is changed.
```
      var updateModel = function() {
        $timeout(function(){
          ngModelCtrl && ngModelCtrl.$setViewValue(element.val());
        },100);
      }
      google.maps.event.addListener(autocomplete, 'place_changed', updateModel);
      element[0].addEventListener('change', updateModel);
```
Any improvement in pull request is always welcomed.

**Comment by Trevomatic** [comment]
Works great, thanks for the fix!

**Comment by allenhwkim** [comment]
@Trevomatic Adding a start to this would be appreciated, so that other developers can be aware of this module.

**Comment by cur3n4** [comment]
@allenhwkim I meant something like:

           var updateModel = function () {
                ngModelCtrl && ngModelCtrl.$setViewValue(element.val());
                scope.$evalAsync();
            }
            google.maps.event.addListener(autocomplete, 'place_changed', updateModel);
            element[0].addEventListener('change', updateModel);
            for (var eventName in events) {
                google.maps.event.addListener(autocomplete, eventName, events[eventName]);
            }

This way the model is always updated before calling the on-place-changed callback.
