### ISSUE TITLE
Map Not Showing on Reload

### ISSUE THREAD

**Issue by realph** [allenhwkim/angularjs-google-maps#270]
I'm trying to use [Angularjs-Google-Maps](http://ngmap.github.io/) in comibination with ui-router. I'm getting a weird issue where the map is only partially appearing.

I've managed to resolve it by creating a directive that triggers a 'resize' event to repaint the map:

    function autoRefresh() {
      return {
        restrict: 'A',
        link: function(scope, element, attrs) {
          scope.$on('$stateChangeSuccess', function(){
              google.maps.event.trigger(scope.map, 'resize');
          });
        }
      }
    }

    <map center="-34.397, 150.644" zoom="8" auto-refresh></map>
    
And this works great, once the initial page has loaded and I change the state, the map appears. But if I simply do a hard reload of the page in the browser, the map doesn't appear. I have to change the state before the map is visible.

Is there an alternative to '$stateChangeSuccess' that works on initial page load?

Any help is appreciated. Thanks in advance!

**Comment by allenhwkim** [comment]
Add this to map tag, `init-event="init-map"`
and add this to your controller or any place desired; `$scope.$broadcast('init-map')` like in this example, https://github.com/allenhwkim/angularjs-google-maps/blob/82b5c10b6b00763f940430d95e8cb084105e3fce/testapp/map_lazy_init.html

The purpose of this is not to render map until an event is fired.
