### ISSUE TITLE
Get latitude and longitude of any restaurant that a user clicks 

### ISSUE THREAD

**Issue by Xainu31** [allenhwkim/angularjs-google-maps#271]
When i click any restaurant then the on-click function do not fire. Is there a way i could get latitude and longitude of the clicked restaurant?

**Comment by allenhwkim** [comment]
You can customize this behaviour for your own marker.

I think the restaurant you see is provided by Google, and you cannot have your own custom click or InfoWindow on Google's provided places.

To have your own, disable the default behaviour,

http://stackoverflow.com/questions/7337266/how-to-disable-places-on-google-map-v3

Then add your own by using places api
