### ISSUE TITLE
on-tap not working with Ionic Framework

### ISSUE THREAD

**Issue by sepandb** [allenhwkim/angularjs-google-maps#272]
I have a map, that has the following code:

            <map center="current-location" zoom="10" on-click="addMarker()" on-tap="addMarker()">
              <shape ng-repeat="pos in positions" ng-model="pos" id="circle" name="circle" stroke-color='#FF0000' stroke-opacity="0.8"stroke-weight="2" center="[{{pos.lat}}, {{pos.lng}}]" on-radius-changed="updatePosition(pos)" on-center-changed="updatePosition(pos)" radius="{{pos.radius}}" editable="true" ></shape>
            </map>

The on-click works and passes the ngMap event object to my controller, but the object doesn't get passed to the on-tap event.

I believe this is because Ionic has it's own on-tap, specified here: http://ionicframework.com/docs/api/directive/onTap/

How can I pass the ngMap object to the Ionic on-tap function so that it works on mobile devices?

Thanks!

**Comment by allenhwkim** [comment]
touch event is not supported for map by google yet.
https://developers.google.com/maps/documentation/javascript/events

**Comment by allenhwkim** [comment]
Does `on-click` work on mobile with Ionic framework?

**Comment by aaronbroad** [comment]
```on-click``` works on mobile Ionic for me.

**Comment by allenhwkim** [comment]
Closing

**Comment by tuvistavie** [comment]
I bumped into the same issue.
After some research, this was not related to this library but to Ionic.
Ionic intercepts the tap event, so the element containing the map needs to have `data-tap-disabled="true"` for `on-click` to work properly.
