### ISSUE TITLE
Dynamically create info windows and markers

### ISSUE THREAD

**Issue by Xainu31** [allenhwkim/angularjs-google-maps#273]
I want to create markers and info windows dynamically i am able to do that with the markers but when i click the market no info window is shows.
Here is the fiddle that explains my problem

http://jsfiddle.net/9gk0552x/3/

**Comment by extravagangsta** [comment]
You usually better to avoid creating multiple info windows since in most of the cases you open just one `infoWindow` at a time. So there is no need for `ng-repeat` in you case.

`showInfoWindow` method's scope is `window` object by default as i remember so you need to bind your site (marker) to that function to display dynamic `infoWindow` content.

Here is how I would do it:

html:
```
<body ng-app="HelloApp">
    <div ng-controller="MyController">
        <map center="51.511344, -0.122234" zoom="10">
            <marker ng-repeat="sites in siteList" id="{{$index}}" position="{{sites.latitude}},{{sites.longitude}}" 
              on-click="showSites(event, $index)">
            </marker>
            <info-window id="bar-info-window" max-width="200" visible-on-marker="                       {{$index}}">
                <div ng-non-bindable="">
                    <div id="siteNotice"></div>
                    <div id="bodyContent">
                        <p>
                            {{selectedSite}}
                        </p>
                    </div>
                </div>
            </info-window>
        </map>
    </div>
</body>
```

js:
```
var app = angular.module('HelloApp', ['ngMap']);
app.controller('MyController', function ($scope) {
    
    $scope.siteList = [{"siteName":"Zain DB Test 4","siteScore":100,"latitude":51.504976,"longitude":-0.018872},{"siteName":"Zain DB test 1","siteScore":54,"latitude":51.521085,"longitude":-0.075924},{"siteName":"Zain DB Test 6","siteScore":50,"latitude":51.607866,"longitude":-0.173722},{"siteName":"Zain DB Test 3","siteScore":38,"latitude":51.518437,"longitude":-0.15191},{"siteName":"Zain DB Test 8","siteScore":33,"latitude":51.760996,"longitude":-0.338482},{"siteName":"Zain DB Test 7","siteScore":15,"latitude":51.656717,"longitude":-0.393984}] ;
    
    $scope.showSites = function (evt, id) {
      $scope.selectedSite = $scope.siteList[id];
      $scope.showInfoWindow.apply(this, [evt, 'bar-info-window']);
    };
    
});
```

**Comment by allenhwkim** [comment]
thansk @extravagangsta

**Comment by allenhwkim** [comment]
Will error out  when `info-window` is used with `ng-repeat`.

**Comment by Xainu31** [comment]
With i little bit changes i got it working thanks @extravagangsta

**Comment by tangervu** [comment]
How are you supposed to have multiple info-windows open when the map has been initialized?

http://plnkr.co/edit/5ZkKrN9TCHFdNjQyR8P3?p=preview contains some tests I had with the infow-window, check it out also.

**Comment by mozaikid** [comment]
i've tried using @extravagangsta  solution but i got an error,
Uncaught TypeError: Cannot read property 'apply' of undefined

**Comment by mozaikid** [comment]
please help.. @allenhwkim

**Comment by extravagangsta** [comment]
Here is jsfiddle with exactly the same code I posted before:
http://jsfiddle.net/uan2ju64/1/

Works for me. Doesn't it work for you?
