### ISSUE TITLE
google map Marker update on clicking on Div

### ISSUE THREAD

**Issue by Gardezi1** [allenhwkim/angularjs-google-maps#274]
I am finding it dificult to put animations on the makers(like bounce) when I click on a div. Can anybody tell me how can I do that.

**Comment by allenhwkim** [comment]
There is an example or two in http://ngmap.github.io

http://plnkr.co/edit/cAy6t4QGnAA0rM8DEF3Q?p=preview

**Comment by Gardezi1** [comment]
I know about this example but on clicking on a p tag this animation should happen. I can't understand how to do that

**Comment by allenhwkim** [comment]
There is a easy way to do it, but it's better to be done in the example.
Please provide me a plunker with your issue, so that people can improve it.

**Comment by Gardezi1** [comment]
I don't know how to make an example of this. Since I personally don't know how to do this. That's why I was asking you :)

**Comment by allenhwkim** [comment]
http://plnkr.co/edit/Dp5C1h1kJk0XaW1FLc1P?p=preview

You want this way?

**Comment by Gardezi1** [comment]
I want something like this

https://www.airbnb.com/s/Belgrade--Serbia

When I hover over the images (on the left side) its marker on the map highlights or starts animating

**Comment by Gardezi1** [comment]
@allenhwkim sorry I wasn't able to give you an example before but I just found it

**Comment by allenhwkim** [comment]
I believe that's not a marker, but a custom overlay.
This is an example of OverlayView, http://plnkr.co/edit/OeRATG?p=preview. 
This module cannot support custom overlays because it must be hand-made for each business case.

**Comment by Gardezi1** [comment]
can you direct me something else that could do this. I would be very thankful

**Comment by allenhwkim** [comment]
Sorry, that not I know of except CustomOverlay which should be tailor-made. You can start from the example that I provided, http://plnkr.co/edit/OeRATG?p=preview

**Comment by dbelieves** [comment]
any update on this. is this doable now?
