### ISSUE TITLE
Occasional execptions "TypeError: google.maps.Map is not a function" & "TypeError: google.maps.DirectionsService is not a function""

### ISSUE THREAD

**Issue by komushi** [allenhwkim/angularjs-google-maps#275]
Appreciate a lot for making this module. It makes my angular work much easier.

I copy/pasted the map object from the following example:
https://github.com/allenhwkim/angularjs-google-maps/blob/master/testapp/directions2.html
Thanks for the response. I posted it by mistake before finishing the description.

I am not sure if it is a network issue.
By implementing the example from your testapp using the normal angular way everything is fine.

But I am using an angular theme which utilize oclazyload (https://github.com/ocombe/ocLazyLoad). All the 3rd party modules are loaded in this way so I do not want to break the conventions.

I loaded the dependencies like this
```javascript
angular.module('app')
    .config(['$ocLazyLoadProvider', function($ocLazyLoadProvider) {
        $ocLazyLoadProvider.config({
            debug: true,
            events: true,
            modules: [{
                    name: 'ng-map',
                    files: [
                      {type: 'js', path: 'http://maps.googleapis.com/maps/api/js?v=3&sensor=false&callback=initialize' },
                      'assets/plugins/ng-map/ng-map.min.js'
                    ]
                }
            ]
        });
    }]);
```
If I refresh the browser for several times I might see the exceptions.

Below is the link.

http://ngmap.cfapps.io/#/app/ngmap_test

I will try map-lazy-load later.

Thanks.

**Comment by allenhwkim** [comment]
I assume your network is slow or not consistent. To make it sure google map is loaded, there is a way to do it. `map-lazy-load`.

**Comment by allenhwkim** [comment]
The problem that you have is ngMap requires full load of google map. 
I do not know ocLazyLoad has a method of step by step loading or not, but before ngMap is executed, it expects google map is there.

That's why all examples has google map in `<head>` tag.

I think you need to figure out ocLazyLoad to load google map in advance.

**Comment by komushi** [comment]
As I use a hosted nginx server the problem disappeared.
Thanks. I will close this issue.
