### ISSUE TITLE
The parameter 'travel-mode' of the directive directions does not work with 'TRANSIT'.

### ISSUE THREAD

**Issue by komushi** [allenhwkim/angularjs-google-maps#276]
I am using test/directions2.html. But the WALKING and DRIVING work while TRANSIT does not.
Is this the spec of ngmap?

Thanks,
Lei Xu

**Comment by allenhwkim** [comment]
that means Google 
Maps does not support it

**Comment by komushi** [comment]
Thanks for the response.
I was reading the google maps doc and it seems to support TRANSIT.
https://developers.google.com/maps/documentation/javascript/examples/directions-travel-modes

**Comment by allenhwkim** [comment]
Will look into it again

You may simply add as an option

**Comment by allenhwkim** [comment]
Of course, there is no TRANSIT in mountain area in New Zeland, Google does not support.

If you want to see TRANSIT, you need to pick up a city like in the testapp/directions.html
https://rawgit.com/allenhwkim/angularjs-google-maps/master/testapp/directions.html

Closing again.

**Comment by komushi** [comment]
Thanks. I figured out the area I use does not support TRANSIT by google yet.
