### ISSUE TITLE
Use ngMap with tab - only the first tab will be initiated

### ISSUE THREAD

**Issue by komushi** [allenhwkim/angularjs-google-maps#279]
The map in the first active tab works fine but all the other maps do not work.
I tried tab features of bootstrap and angular-bootstrap but both have the same issue.

Code sample which uses angular-bootstrap.
```
  <tabset>
	<tab heading="Static title 1"><map center="[40.74, -74.18]" /></tab>
	<tab heading="Static title"><map center="[42.74, 34.18]" /></tab>
  </tabset>
```

**Comment by allenhwkim** [comment]
Please close the map tag with `</map>`

**Comment by komushi** [comment]
Thank you for the response.
This is not the solution. I also tried the following code but got the same result.

```
  <tabset>
    <tab heading="Static title 1"><map center="36.74, 139.11"></map></tab>
    <tab heading="Static title"><map center="36.74, 139.11"></map></tab>
  </tabset>
```

**Comment by allenhwkim** [comment]
Please provide me a plnkr that is not working

**Comment by komushi** [comment]
http://plnkr.co/edit/DZj5RkDUHk9C8oTvsjcf

**Comment by allenhwkim** [comment]
If you remove bootstrap css or js, it works again. 
Thus, it's not a problem of ngMap, but a problem of bootstrap. 
<link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">

Please add your full example in plunker, next time, so that we can quickly see what's the issue without guessing around.

**Comment by komushi** [comment]
Thanks for checking. The reason to use bootstrap is to use the tab feature.
If removed there is no way to initialize the map.

**Comment by allenhwkim** [comment]
bootstrap is out of scope on this discussion. I can't and won't answer
outside of ngMap.

**Comment by komushi** [comment]
Understood. Thanks.

**Comment by mnovak20** [comment]
I had a very similar issue. The only difference I guess is that I had tabs inside a ui-bootstrap modal. 

Add an ng-if on the map element in the 2nd tab and run a function that sets the boolean for the ng-if to true on select of the 2nd tab.  Something like this.

<tab heading="Location" select="mapTabSelected()">
        <map ng-if="showMap" class="google-map" center="39.8282, -98.5795" zoom="2" style="width:100%; height:400px">

**Comment by silviotroia** [comment]
same error.... someone know how solve it?

**Comment by allenhwkim** [comment]
Please add plunder example

**Comment by silviotroia** [comment]
it's the same http://plnkr.co/edit/DZj5RkDUHk9C8oTvsjcf?p=preview

**Comment by mnovak20** [comment]
The solution I listed above works in your plunker.

```
$scope.showMap = false;
    
    $scope.reRednerMap = function() {
        $scope.showMap = true;
        google.maps.event.trigger($scope.maps[1], 'resize');  
        google.maps.event.trigger($scope.maps[2], 'resize');  
    }
```

```
<tab heading="One"><map center="London"></map></tab>
    <tab heading="Two" select="reRednerMap()">
      <map ng-if="showMap" id="liverpool" center="Liverpool"></map>
    </tab>
```

**Comment by allenhwkim** [comment]
thanks @mnovak20

**Comment by allenhwkim** [comment]
@mnovak20 's solution in plunker, http://plnkr.co/edit/fUECI0?p=preview.

This is another solution with delayed init with init-event.

http://plnkr.co/edit/K1kFDh?p=preview

```
  <tabset>
    <tab heading="One" ng-click="$emit('a')">
      <map center="London"></map>
    </tab>
    <tab heading="Two" ng-click="$emit('b')">
      <map init-event="b" center="Liverpool"></map>
    </tab>
    <tab heading="Three" ng-click="$emit('c')">
      <map init-event="c" center="Andria"></map>
    </tab>
  </tabset>
```
