### ISSUE TITLE
Possible to use ngmap with multiple maps with direction panels? 

### ISSUE THREAD

**Issue by komushi** [allenhwkim/angularjs-google-maps#281]
Need to generate dynamic panel names during runtime.
But it seems the current direction directive does not support it.
Any work-around? Thanks.

http://plnkr.co/edit/pBz9lk

**Comment by maiconpazin** [comment]
I need the same thing. 
**komushi** did you find a solution for it?

**Comment by allenhwkim** [comment]
This issue has been resolved with 1.13.3, please check it out.

**Comment by komushi** [comment]
Thanks!
