### ISSUE TITLE
disable mose zoom

### ISSUE THREAD

**Issue by Gardezi1** [allenhwkim/angularjs-google-maps#283]
Is there any way to diable the mouse/touchpad zoom ??

**Comment by allenhwkim** [comment]
https://developers.google.com/maps/documentation/javascript/reference?hl=en#MapOptions

You can use maxzoom and minzoom option.

**Comment by Gardezi1** [comment]
thanks but I changed the value of scroll wheel to false and put it in as an attribute of the map tag and it worked for me

**Comment by allenhwkim** [comment]
Nice, I guess you still want to enable zoom by buttons(+/-). If you don't mind a star to this would be appreciated so that other developers can notice this module.

**Comment by Gardezi1** [comment]
nope I didn't want that too so I put this attribute too in the scroll wheel options zoom-control="false"

**Comment by Gardezi1** [comment]
and how can I do that ??

**Comment by Gardezi1** [comment]
done

**Comment by Gardezi1** [comment]
for all the people who can't figure out how to use option of gmaps in ngmap. Just put them as attributes in the map element and then you can use that option
