### ISSUE TITLE
Cannot get place with places-auto-complete on-place-changed

### ISSUE THREAD

**Issue by fabn** [allenhwkim/angularjs-google-maps#286]
The example in the documentation is wrong

```html
<input places-auto-complete types="['geocode']" on-place-changed="myCallback(place)" />
```

in my callback `place` is undefined, place can be obtained with `this.getPlace()` in that function, this however is very ugly if you use CoffeeScript classes as callback because you lose a references to your class.

Can this library in some way fix that?

**Comment by allenhwkim** [comment]
Having zero knowledge in coffeescript, I would appreciate anyone's suggestion or pull request.

**Comment by fabn** [comment]
In coffeescript you can use classes for angular controller, here's a small example>

```coffeescript
class MyController
  constructor: ($scope, $log)-> # $whatever
    # Do something fancy when object is initialized
    
  placeChanged: (place)=>
    @utilityFunction(place)
    
  utilityFunction: (place)=>
    # Do something useful with place
 ```

The key issue is that coffeescript has a fat arrow operator (`=>`) which retain current value of this, no matter how the function is actually called. In this way you don't need to worry about `this` value when you want to call other functions in the same class. If you don't use that notation you can safely use `this.getPlace()` but you lose access to other functions in the same controller with no way to call them.

To better understand what is happening the above example is compiled to the following javascript:

```js
var MyController,
  bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

MyController = (function() {
  function MyController($scope, $log) {
    this.utilityFunction = bind(this.utilityFunction, this);
    this.placeChanged = bind(this.placeChanged, this);
  }

  MyController.prototype.placeChanged = function(place) {
    return this.utilityFunction(place);
  };

  MyController.prototype.utilityFunction = function(place) {};

  return MyController;

})();
```

To return to the original issue when you configure event listener you can change [this code](https://github.com/allenhwkim/angularjs-google-maps/blob/master/directives/places-auto-complete.js#L30) to ensure that callback has access to the place object instead of relying on `this` value. 

I think this is a breaking api change, however the current api does not work as stated in the documentation thus it should not be an issue for existing user.

A simple fix to pass place as first argument would be this

```js
for (var eventName in events) {
    google.maps.event.addListener(autocomplete, eventName, function () {
        // maybe also autocomplete itself can be passed if one need to access any of the methods listed 
        // here https://developers.google.com/maps/documentation/javascript/3.exp/reference#Autocomplete
        events[eventName](this.getPlace());
    });
}
```

**Comment by allenhwkim** [comment]
Honestly, I hesitate to change the code just for coffeescript. As you see in this line, https://github.com/allenhwkim/angularjs-google-maps/blob/master/services/attr2_options.js#L219

All maps events are designed to run within the scope of map object that event happend, e.g. marker, shapes, etc. This design also makes the code as the same as native google maps v3 event code.

What if function takes more than one parameter? What if function does not take any parameter like this example, https://github.com/allenhwkim/angularjs-google-maps/blob/master/testapp/places-auto-complete.html?

I suggest you do make coffeescript to result the following;

MyController = (function() {
  function MyController($scope, $log) {
    this.utilityFunction = bind(this.utilityFunction, this);
    this.placeChanged = bind(this.placeChanged, this);
  }

  MyController.prototype.placeChanged = function() {
    return utilityFunction(this.getPlace());
  };

  MyController.prototype.utilityFunction = function(place) {};

  return MyController;

})();

**Comment by fabn** [comment]
> Honestly, I hesitate to change the code just for coffeescript. As you see in this line, https://github.com/allenhwkim/angularjs-google-maps/blob/master/services/attr2_options.js#L219
> 
> All maps events are designed to run within the scope of map object that event happend, e.g. marker, shapes, etc. This design also makes the code as the same as native google maps v3 event code.

That's a good point. Personally I don't like events that change `this` binding however if you want to keep current behavior it's perfectly understandable. In that case you can safely close this issue but please update the [related documentation](https://rawgit.com/allenhwkim/angularjs-google-maps/master/build/docs/places-auto-complete.html)

> What if function takes more than one parameter? What if function does not take any parameter like this example, https://github.com/allenhwkim/angularjs-google-maps/blob/master/testapp/places-auto-complete.html?

> I suggest you do make coffeescript to result the following;

I've already fixed my code in that way, thanks.
