### ISSUE TITLE
'google is not defined' error came back 

### ISSUE THREAD

**Issue by piotrd** [allenhwkim/angularjs-google-maps#287]
@allenhwkim,

With the last commit (`2fd17de`, I presume), the `google is not defined` error came back. This time js console points to this line: https://github.com/allenhwkim/angularjs-google-maps/blob/master/build/scripts/ng-map.js#L708

Also, your example doesn't work, probably for the same reason: https://rawgit.com/allenhwkim/angularjs-google-maps/master/testapp/map-lazy-load.html

**Comment by piotrd** [comment]
As a quick workaround, I commented out the `customMarker` directive and that helped.

**Comment by allenhwkim** [comment]
Do you use map-lazy-load?

**Comment by piotrd** [comment]
Yes, I do.

**Comment by allenhwkim** [comment]
Thanks I will make a fix for that. It wouldn't be that hard. 
I really appreciate your feedback on the new release.

**Comment by piotrd** [comment]
It just happened that I started implementing your plugin today in my app ;)

**Comment by allenhwkim** [comment]
updated with 1.13.2. please check.

**Comment by piotrd** [comment]
Tested and all seems to be fine. Thank you!

**Comment by raphitz** [comment]
In version 1.13.13 
the google is not defined error came back.

**Comment by allenhwkim** [comment]
@raphitz could you create an issue for this with example plunker?

**Comment by raphitz** [comment]
Sorry I forgot to call the js google-maps in my index.html. I solved
