### ISSUE TITLE
Erro when using current-location and user had disabled location

### ISSUE THREAD

**Issue by sebrojas14** [allenhwkim/angularjs-google-maps#290]
When I use <map center="current-location" ...> and the location is disabled on device, ngmap doen't load

**Comment by allenhwkim** [comment]
How do you disable location?

**Comment by allenhwkim** [comment]
Oh, not to share location. There is fallback location for that

**Comment by sebrojas14** [comment]
No. Is in the configuration (at least in andorid):

![screenshot_2015-08-27-21-06-24](https://cloud.githubusercontent.com/assets/1771574/9537569/8fa0b564-4cff-11e5-88f7-15615c8b8649.png)

**Comment by allenhwkim** [comment]
You can use like this,   `<map id="map" zoom="16" center="current-location" geo-fallback-center="4.672585, -74.059525"></map>`

Check this example, https://rawgit.com/allenhwkim/angularjs-google-maps/master/testapp/map_geo_fallback_center.html

![image](https://cloud.githubusercontent.com/assets/1437734/9560126/e300de0e-4dd2-11e5-9231-9f28c4bb358d.png)

This happens from this line, https://github.com/allenhwkim/angularjs-google-maps/blob/5e385b07a0e67e7bb14f02be5bba385995bfdf40/directives/map.js#L127

**Comment by sebrojas14** [comment]
Thank you, gonna test it in soon

**Comment by sebrojas14** [comment]
Not workin...only works on browser when location request is not accepted (blocked). I think add a timeout opction on the navigator.geolocation.getCurrentPosition call https://github.com/allenhwkim/angularjs-google-maps/blob/5e385b07a0e67e7bb14f02be5bba385995bfdf40/services/navigator_geolocation.js#L30 could resolve the issue

**Comment by allenhwkim** [comment]
Could you send me a pull request for it?

**Comment by sebrojas14** [comment]
Sure, I'm gonna try. Because a think timeout should be parameterized, I'm gonna give it a try (I'm new ai this)

**Comment by sebrojas14** [comment]
Can you help me? I already made the modification, but I'm no be able to run all test, and git shows some modified files I not touched. Maybe I could commit only the 3 files I modified?

**Comment by allenhwkim** [comment]
https://github.com/allenhwkim/angularjs-google-maps/blob/master/README.md#contributing

I assume you followed the contributing section of README.md. If anything not work as described, please let me know

gulp test-e2e is not always passing, but 'gulp test' should pass.

You still can send a pull request with modified files, and I can take a look into it if tests are not passing.

**Comment by sebrojas14** [comment]
Yes, gulp-test passed, but gulp test-e2e gives me errors. Already sent the pull request, but still with one problem (I decided to create a geo-location-options, but I dont know -in your code- how to receive a an object parameter in the map directive, the parameter I created receive an object but in string representation)

**Comment by allenhwkim** [comment]
No worries, Attr2Options automatically converts all strings to proper object, for your case, string to an object. As you see here, options are passed as object to map, not as string. 

![image](https://cloud.githubusercontent.com/assets/1437734/9572042/9875ecee-4f76-11e5-91f2-aa246bb6d9b8.png)

**Comment by sebrojas14** [comment]
Yes, but I wnat to pass the geoLocation object as a variable setted in the controller, I couldn't do this

**Comment by allenhwkim** [comment]
How about `{{myObj | json}}`?

**Comment by sebrojas14** [comment]
`{{myObj}}` did the job I'm gonna update the docummentation of the new geo-location-optiosnn parameter

**Comment by sebrojas14** [comment]
Can close it

**Comment by sebrojas14** [comment]
Estimated release?

**Comment by tedc** [comment]
using variable with curly brackets in  geo-fallback-center (ie: geo-fallback-center="{{start}}") gives this error: "InvalidValueError: setCenter: not a LatLng or LatLngLiteral: not an Object".

**Comment by tedc** [comment]
Here a plunker with various ways, everyone fails 
https://plnkr.co/edit/YIleQHVXsbZxbz86vhH2
