### ISSUE TITLE
Changing existing marker from fixed to draggable(ng-repeat does not respect dynamic attribute values)

### ISSUE THREAD

**Issue by ReinierKorth** [allenhwkim/angularjs-google-maps#291]
Is it possible to change an existing marker from draggable false to draggable true when clicking a button inside the infowindow? Setting pin.draggable = true on the scope doesn't seem to work.

    <marker ng-repeat="pin in pins"
                draggable="{{pin.draggable}}"
                id="pin{{pin.id}}"
                position="{{pin.latitude}}, {{pin.longitude}}"
                on-click="showInfoWindow(event, 'win{{pin.id}}')">

**Comment by allenhwkim** [comment]
currently attribute observers are not working with `ng-repeat`. There was two reason for that.

1. Technical difficulty. with `ng-repeat` markers are not set immediately, but in delayed way.
2. IMPORTANT: Not to se too may observers with `ng-repeat`. It may abuse the use of watchers(observers).

To solve your problem, you can set draggable Google API way

      $scope.map.markers.pin1.setDraggable(true);

**Comment by chromano** [comment]
Hi @allenhwkim, do you mind to share more information about these two issues?  I'm willing to help here.
