### ISSUE TITLE
Custom Marker doens't apper in the right place

### ISSUE THREAD

**Issue by sebrojas14** [allenhwkim/angularjs-google-maps#293]
What I could have missing? I added a custom marker to my map vut nothing shows up

```
<map center="current-location" geo-fallback-center="4.672585, -74.059525" zoom="11" on-dragend="dragend()" data-tap-disabled="true">
              <custom-control id="centermap" position="LEFT_BOTTOM" index="1" on-click="center()">
                <i class="icon ion-pinpoint" style="font-size: 2.5em; color: #fff; font-weight: bold; text-shadow: 1px 1px 0 #000; margin-left:10px"></i>
              </custom-control>
              <custom-marker position="4.672585, -74.059525">
                <div>
                  <b>Home</b>
                </div>
              </custom-marker>
              <marker id="currnet" position="current-location" icon="{ url: 'img/location-me.png', scaledSize: [60, 60] }"></marker>
              <marker ng-repeat="marker in markers" id="marker_{{marker.id}}" position="{{marker.location.latitude}}, {{marker.location.longitude}}" animation="DROP" icon="{ url: 'img/marker1.png', scaledSize: [40, 40] }" on-click="showDetails(event, marker.id)"></marker>
              <info-window id="details">
                <div ng-non-bindable="">
                  <h4>{{ecopoint.name}}</h1>
                  <p>{{ecopoint.address}}</p>
                  <p translate>Hours: {{ecopoint.hoursStart}}hrs to {{ecopoint.hoursEnd}}hrs</p>
                  <a ng-click="next(ecopoint)" translate>Select</a>
                </div>
              </info-window>
            </map>
```

I also tried to leave only the custom marker inside the but but nothing shows up

**Comment by allenhwkim** [comment]
zoom out to see the whole world. You will see the custom marker.

**Comment by sebrojas14** [comment]
Oh yes. But why? what abput the position attribute?

**Comment by sebrojas14** [comment]
The point in google maps:
![capture](https://cloud.githubusercontent.com/assets/1771574/9572747/ed6977fa-4f78-11e5-8c34-11ace6f231c8.PNG)

The custom marker:
![capture1](https://cloud.githubusercontent.com/assets/1771574/9572753/f48ffd56-4f78-11e5-9e3e-7724664976df.PNG)

The same happens wit my app:

**Comment by allenhwkim** [comment]
```
      <map center="4.672585, -74.059525" zoom="11">
        <custom-marker position="4.672585, -74.059525">
          <div>
            <b>Home</b>
          </div>
        </custom-marker>
      </map>
      <map center="4.672585, -74.059525" zoom="11">
        <marker id="currnet" position="4.672585, -74.059525"></marker>
      </map>
```
It's pointing to the same place on both `marker` and `custom-marker`.
![image](https://cloud.githubusercontent.com/assets/1437734/9591556/1bc3aae4-500a-11e5-87ef-e5754b927d24.png)

Not sure why yours are different. Please remember that the geo-located marker is not the exactly the same place that you expect. It depends on how google send you data.

**Comment by sebrojas14** [comment]
What css are you using?

**Comment by allenhwkim** [comment]
The same one in the example custom-marker-2.html

**Comment by allenhwkim** [comment]
can i close this?

**Comment by sebrojas14** [comment]
I'm sorry, but I have not had time to test properly, as decided by timepo tmabién in the application and use markers infowindows

**Comment by allenhwkim** [comment]
Closing it. if this is not fixed, you can always open a new issue
