### ISSUE TITLE
Maps don't appear when printing

### ISSUE THREAD

**Issue by mattlewis92** [allenhwkim/angularjs-google-maps#296]
This is a really odd bug, but when trying to print a page in chrome with this directive on, the map doesn't display. For example try and print the demo page and you'll see what I mean:
http://ngmap.github.io/basics.html#/map-simple#map-simple

However if you try with other GM directives it prints OK:
http://angular-ui.github.io/angular-google-maps/#!/

I had a look to see if I could work out what was causing it but I couldn't find anything that might be causing it. If you could work out a fix that would be great, thank you!

**Comment by allenhwkim** [comment]
This is related to css of ngmap.github.io, especially media tag of css. 
However, this is not related to this module. This module does not prevent browser from printing the map.

I have copy/pasted this issue to https://github.com/ngmap/ngmap.github.io/issues/1, and will make a fix in that repo.

Thanks for the reporting.

**Comment by mattlewis92** [comment]
Odd, it's happening in our app as well and we don't have any `media="screen"` tags on our stylesheets - any ideas?

**Comment by allenhwkim** [comment]
I believe that It is related to css.
If you can print out this page, https://rawgit.com/allenhwkim/angularjs-google-maps/master/testapp/map-simple.html., that means this module does not prevent printing.

**Comment by mattlewis92** [comment]
OK thanks for the help!

**Comment by mattlewis92** [comment]
I realised the issue was being caused by bootstrap, this was the fix for anyone else having the same problem:
```
@media print {
  img {
    max-width: none !important;
  }
}

```

**Comment by ajmueller** [comment]
If anyone happens to find their way here because they're missing tiles when printing (but not the whole map), [I found another CSS solution that works](https://bugs.chromium.org/p/chromium/issues/detail?id=426294):

```css
ng-map div > img {
	position: absolute;
}
```
