### ISSUE TITLE
Dynamic Marker Labels (using angular expression in the label)

### ISSUE THREAD

**Issue by extravagangsta** [allenhwkim/angularjs-google-maps#297]
The label attribute works just fine with static string value like this:

But I couldn't make it working on `marker` with `ng-repeat`. My labels are counters (integers up to 9 so I don't really need custom markers) assigned to each marker object.

Here is an example:
http://plnkr.co/edit/PMuoyAcQrc6D6ZUbjWeF?p=preview

Is it possible to use angular expression with the `label` directive?

Thanks!

**Comment by allenhwkim** [comment]
http://plnkr.co/edit/b5WErtbRl7RmvA25CaLh?p=preview

All you need to do is pass string to label.

**Comment by extravagangsta** [comment]
Works perfect! Thanks a lot!
Closing this.
