### ISSUE TITLE
Unable to use wayponits of LatLng in directions

### ISSUE THREAD

**Issue by jiangxiaoli** [allenhwkim/angularjs-google-maps#300]
when i using the directions directive with value "waypoints", i got this error

![screen shot 2015-09-10 at 7 41 48 pm](https://cloud.githubusercontent.com/assets/7184578/9806009/770e1910-57f4-11e5-9b22-aa2dbeef60f9.png)

The waypoint is Array<DirectionsWaypoint>, with property location of LatLng, the structure of the array of waypoints is printed in the console in last image, which looks ok.
![screen shot 2015-09-10 at 7 42 11 pm](https://cloud.githubusercontent.com/assets/7184578/9806019/8d91a666-57f4-11e5-93f7-f22ba24dbf48.png)

![screen shot 2015-09-10 at 7 51 08 pm](https://cloud.githubusercontent.com/assets/7184578/9806101/5c922882-57f5-11e5-9c6f-cdc1e5ba71ae.png)

and html is
![screen shot 2015-09-10 at 7 44 29 pm](https://cloud.githubusercontent.com/assets/7184578/9806015/835e19ae-57f4-11e5-8bf7-e4fe8e00fb3a.png)

I also tried to use LatLngLiteral for location, there is no error, but also no show of any directions.

**Comment by allenhwkim** [comment]
Thanks for using this module. The reason why it is not understoood by Google map is that value of  waypoints are passed as string, then parsed by ngMap module.

So, if you pass the actual object, it can't be parsed. 

However, if you pass a JSON, that can be parsed, and Google Maps works in that way too.
 
        $scope.wayPoints = [
          {location: {lat:44.32384807250689, lng: -78.079833984375}, stopover: true},
          {location: {lat:44.55916341529184, lng: -76.17919921875}, stopover: true},
        ];

**Comment by jiangxiaoli** [comment]
Thanks so much for your fast response! 

the second solution, LatLngLiteral works fine and i also need to pay attention to the max limit of waypoint (which is 8), otherwise there is no route on map.

Thanks!

**Comment by allenhwkim** [comment]
Nice, a star would be appreciated to this module, so that other developers get aware of it.

**Comment by jiangxiaoli** [comment]
sure, thanks a lot for your module. it's the best google map module i used so far!
