### ISSUE TITLE
marker's showInfoWindow & hideInfoWindow

### ISSUE THREAD

**Issue by komushi** [allenhwkim/angularjs-google-maps#301]
When there are multiple markers with infowindows the user expectation is to automatically close an existing infowindow when a new marker is clicked.

I was wondering how to achieve this. Is it possible to implement a scope.hideAllInfoWindows function?

Thanks in advance!!

**Comment by allenhwkim** [comment]
You only use only one info window. It will automatically close others. If you use multiple infowindows wth multiple instances, you have to manually close infowindow, using close method. https://developers.google.com/maps/documentation/javascript/3.exp/reference#InfoWindow

**Comment by komushi** [comment]
Thanks. Problem solved.
