### ISSUE TITLE
Marker icon property not passing instanceof Object

### ISSUE THREAD

**Issue by miclaus** [allenhwkim/angularjs-google-maps#302]
The marker directive doesn't pass the condition 
```if (options.icon instanceof Object)``` for the icon property, given as such:
```
<marker
    position="{{ myPosition.coords.latitude }}, {{ myPosition.coords.longitude }}"
    icon="
    {
        url  : 'assets/img/my_position.png',
	    size : [ 22, 22 ]
    }"
    z-index="{{ myPositionZIndex }}">
</marker>
```

**Unless** the icon ```Object``` is passed to the ```$scope```:
```
<marker
	position="{{ myPosition.coords.latitude }}, {{ myPosition.coords.longitude }}"
	icon="{{ myPositionIcon }}"
	z-index="{{ myPositionZIndex }}">
</marker>
```
And in the controller:
```
$scope.myPositionIcon =
{
	url  : 'assets/img/my_position.png',
	size : [ 22, 22 ]
}
```

**Comment by allenhwkim** [comment]
When Hash object is passed from attribute, it tries to parse using JSON.parse as much as it can. Howerver, it does  not always parse free format as your example

Try this way.

      icon="{
        url: 'assets/img/my_position.png',
        size: [ 22, 22 ]
      }"

Or 
      icon="{url: 'assets/img/my_position.png', size: [22, 22] }"

**Comment by allenhwkim** [comment]
Closing, LMK if the last response did not solve your issue.

**Comment by miclaus** [comment]
thank you for the tipps. 
i haven't written yet, since my proposed solution seems more promising for my project.

however neither of the proposed solutions, don't work for me.

**Comment by allenhwkim** [comment]
Hmm, This examle always works for me. Your case might be different.

https://rawgit.com/allenhwkim/angularjs-google-maps/master/testapp/marker_icon.html  

Source Code: https://github.com/allenhwkim/angularjs-google-maps/blob/master/testapp/marker_icon.html

**Comment by miclaus** [comment]
Hmm, well blank spaces, tabulators or new lines might make the difference.

However, I believe that my syntax in the first comment is valid JSON, and should be recognized as valid and therefore be "parseable". And since there is no explicit error or warning that comes with this problem, it leaves the developer not knowing what the actual problem is.

**Comment by allenhwkim** [comment]
AFAIK, those are not a valid JSON but a valid Javascript Object. If do not want to go through this module's parser(which is provided for convenience and you don't seem to like it), you can simply provide a valid json like the following.

    icon='
    {
        "url"  : "assets/img/my_position.png",
        "size" : [ 22, 22 ]
    }'

The working example, http://plnkr.co/edit/J0uXkJ?p=preview

**Comment by miclaus** [comment]
Ah, true; sorry my fault. This solves my issue.

My first problem is the "clogged" syntax within my HTML templates. Secondly I don't like using single quotes for HTML attributes. 

The JSON-thingy is however convenient for quick prototyping. And I would use the JS Object notation as well, if it worked with the specified syntax from the first post.

However, thank you ! 
You helped. :smile:
