### ISSUE TITLE
Multiple custom markers of the same position are not showing in the same location

### ISSUE THREAD

**Issue by Moqadi** [allenhwkim/angularjs-google-maps#303]
I tried to add more than one custom markers on the map (by using ng-repeat), all these custom markers have the same position. I have found that custom markers are shifted according to the size of the custom marker. I think they should be placed in the same location.

**Comment by Moqadi** [comment]
```
![multiple_custom_markers](https://cloud.githubusercontent.com/assets/9657047/9875591/d5fa4202-5bb7-11e5-912b-f166c01d14d4.png)

"<map zoom="8" center="1600 pennsylvania ave, washington DC" style="height:600px">
    <custom-marker ng-repeat="n in ['A', 'B']" position="4.672585, -74.059525" on-click="click()">
        <div>
          {{n}}
        </div>
    </custom-marker>
  </map>"
```

**Comment by allenhwkim** [comment]
icon="{
        url: 'assets/img/my_position.png',
        size: [ 22, 22 ]
      }"

**Comment by allenhwkim** [comment]
It's a CSS styling issue. Change custom-marker position from relative to absolute

http://plnkr.co/edit/PXnNGp?p=preview

**Comment by Moqadi** [comment]
It works! Thanks much :)

**Comment by allenhwkim** [comment]
Glad it works, closing;
