### ISSUE TITLE
Error showing various maps with info window

### ISSUE THREAD

**Issue by jcampalo** [allenhwkim/angularjs-google-maps#304]
Having two or more maps instances with an info window in each one only shows info windows in the last one.

Example in the following link:

http://plnkr.co/edit/V1HzywahHeHM0FcAplXz?p=preview

**Comment by allenhwkim** [comment]
Thanks for reporting this error. I will take a look into it.

**Comment by allenhwkim** [comment]
Currently infoWindow is only for one scope. If you want to have two different infoWindow on two different map, please use different scope.

Example: http://plnkr.co/edit/5petC7?p=preview

**Comment by allenhwkim** [comment]
It's a CSS styling issue. Change custom-marker position from relative to absolute

http://plnkr.co/edit/PXnNGp?p=preview

**Comment by allenhwkim** [comment]
Implemented with 1.14. closing

![image](https://cloud.githubusercontent.com/assets/1437734/11066312/b2a505a8-8795-11e5-9eca-6696860d0216.png)
