### ISSUE TITLE
1.13.0 version is not published to npm

### ISSUE THREAD

**Issue by Moqadi** [allenhwkim/angularjs-google-maps#305]
I tried to install the latest version of the ngmap (1.13.x), but it looks like it's not in the npm (https://www.npmjs.com/package/ngmap). The latest version there is 1.10.0, could you please try to publish it there.

Thanks

**Comment by allenhwkim** [comment]
Thanks for reporting this. Just have done.
```
$ npm publish
+ ngmap@1.13.5
```

**Comment by Moqadi** [comment]
Thanks much :)

**Comment by allenhwkim** [comment]
A star to this repo. would be appreciated if you recommend it to other developers in the world.
