### ISSUE TITLE
How to bind model's latitude and longitude data to markers to display on a map?

### ISSUE THREAD

**Issue by tinker20** [allenhwkim/angularjs-google-maps#306]
I have a model object defined such that 

<p> {{shop.latitude}} , {{shop.longitude}} </p> renders the model's latitude and longitude data on the html page. How to bind the data to the google map marker so that the marker is located at the model's coordinates?

Thanks in advance.

**Comment by allenhwkim** [comment]
`<marker position="{{shop.latitude}} , {{shop.longitude}}"></marker>`

**Comment by tinker20** [comment]
I can see the data changing in the inspector but the marker is not displayed on the map. No change in the map behavior. Any tip regarding how to display the marker?

**Comment by allenhwkim** [comment]
Please check the source code of this


https://rawgit.com/allenhwkim/angularjs-google-maps/master/testapp/marker_with_dynamic_position.html

**Comment by allenhwkim** [comment]
Closing it. If the given example does not explain enough, please your case in plunker.

**Comment by tinker20** [comment]
Yes problem solved. :) Thanks.

**Comment by tinker20** [comment]
How should I iterate over a set of latitude and longitude float values using ng-repeat? Considering that the model I defined has latitude and longitude as property which can be accessed by 

    {{shop.latitude}} {{shop.longitude}}

**Comment by allenhwkim** [comment]
You can Angular number filter
