### ISSUE TITLE
Map click event object frequently changed by Google

### ISSUE THREAD

**Issue by phuyem** [allenhwkim/angularjs-google-maps#307]
Hi,

Thanks for your great and simple-to-use. But we are facing a problem with event object: 

	<map zoom="14" center="{{address}}"
					on-click="pickLocation(event)"> 

       $scope.pickLocation = function (event) {
                map.setCenter(event.latLng);
               new google.maps.LatLng(event.latLng.G, event.latLng.K);

You can see cleary what I mean in testapp/places-auto-complete.html
         
         $scope.placeChanged = function() {
           $scope.place = this.getPlace();
         }

The problem is Google (intentionally?? ) keep changing the alias for lat and long. They used to use E , F for lat/long (if I remember correctly), then G/K for lat/long. Now they have changed it to H/L .

We cannot reliably extract the lat/long from the map. Is there any helper utility to do that. Thanks!

**Comment by allenhwkim** [comment]
Please take a look at this example, https://rawgit.com/allenhwkim/angularjs-google-maps/master/testapp/events.html

**Comment by phuyem** [comment]
Sorry for not being very clear : 

What i was referring to is : 

https://rawgit.com/allenhwkim/angularjs-google-maps/master/testapp/places-auto-complete.html

Upon the auto-completed done, it fires back to controller :

    $scope.placeChanged = function(event) {
         $scope.place = this.getPlace();
       console.log(event);  //-> undefined      

     }


And there is no reliable way to get Lat/Long from $scope.placeChanged

**Comment by allenhwkim** [comment]
placeChanged is not related to any map event and thus, it does not have an event as parameter.
If you want to know the lat/lng, use place.geometry.location. It has it's own function to return latitutue and longitude. e.g., lat(), lng().
        
         $scope.placeChanged = function() {
           $scope.place = this.getPlace();
           map.setCenter($scope.place.geometry.location);
         }

**Comment by phuyem** [comment]
Yes, I have been using the source code from your places-auto-complete.html for months. The problem is that $scope.place.geometry.location or even the whole $scope.place is pure object which has no getter for lat/lng , and google name lat/lng as A, B, then changed to C, D...so on.. . As the result I have to update my application every few months or so.

P/S: I know this issue not not totally related to your nice angular module. I just post here more as a discussion thread

**Comment by allenhwkim** [comment]
Yes, it is pure object, but It is not a pure JSON object. It has getter setter on each property as the document says, https://developers.google.com/maps/documentation/javascript/3.exp/reference#Autocomplete

It returns an object, not a hash. Thus, you will have full access to LatLng object when it comest to place.geometry.location.

    <script>
      angular.module('myApp', ['ngMap'])
       .controller('MyCtrl', function($scope) {
         $scope.types = "['establishment']";
         $scope.placeChanged = function(place) {
           $scope.place = this.getPlace();
           console.log($scope.place.geometry.location.lat(), $scope.place.geometry.location.lng());
           $scope.map.setCenter($scope.place.geometry.location);
         }
       });
    </script>

**Comment by phuyem** [comment]
it does work !! I feel kinda silly right now. Thank you for your time, and again your awesome-easy-to-use module!

**Comment by allenhwkim** [comment]
Nice!, I also thought as you thought at the beginning. If you recommend this repo. to other developer, please add a star.

**Comment by phuyem** [comment]
stared it! I will surely recommend the module to any non-heavily-gmap-based web app !

Have a good day sir! 

P/S: BTW, nice avatar!
