### ISSUE TITLE
InfoBox support

### ISSUE THREAD

**Issue by sebastian-zarzycki** [allenhwkim/angularjs-google-maps#308]
One of the crucial features that are somewhat lacking is the angular-way Google Maps InfoBox support, to be able to style the marker popup better. I would see this as the same as InfoWindow, so by using directive. I know there were 3rd party attempt to do so, that were basing on http://google-maps-utility-library-v3.googlecode.com/svn/trunk/infobox/src/infobox.js, but they no longer seem to work, and the code was badly written and ineffective / leaking memory. Any chance to do so?

**Comment by allenhwkim** [comment]
There are `info-window` and `custom-marker` to satisfy that kind of needs

**Comment by sebastian-zarzycki** [comment]
How exactly? Is there an example? From what I could gather, info-window is just a regular InfoWindow from Google Maps that cannot be styles, while custom-marker is html placed on the map instead of the marker icon. How can I combine these two to achieve InfoBox effect?

**Comment by allenhwkim** [comment]
InfoWindow can be styled.

**Comment by sebastian-zarzycki** [comment]
The content of it, inside, yes. Not the outside. If I want to make the popup with completely black background, how do I go about it?

**Comment by allenhwkim** [comment]
Check out this, http://plnkr.co/edit/TUHnBu?p=preview
`custom-marker` can also work like a InfoWindow, and you can style everything.

**Comment by sebastian-zarzycki** [comment]
I'm sorry, this is in no way a solution that is acceptable in a real-world project. The starting marker is displayed "opened", and if it requires an additional marker definition for each normal marker, that would further increase the number of watchers. This is overly complicated and ineffective. I find it puzzling, that you don't support one of the standard and commonly used scenarios, and yet you have things like "custom markers".

**Comment by allenhwkim** [comment]
Thanks for comment. This module only supports Googles' official objects, which excludes 3rd party objects; InfoBox, MarkerWithLabel, and MarkerClusterers. I tried to support your requests with the existing objects, but it seems not satisfactory for you.

You still can build your own using Google's native object with this module.
