### ISSUE TITLE
On-click Marker doesn't work

### ISSUE THREAD

**Issue by pikkolojoe** [allenhwkim/angularjs-google-maps#309]
Hi,
1-the event on-click on markers doesn't work! Works only if I set proprety draggable=true. This in mobile device. I use ng-repeat to put markers on map.

2- I've tried to avoid the first problem, adding a function on marker (on-drag) but when I tried to set the position of marker by JS logcat return me an error:"cannot call method setPosition of undefined". 
I use alert($scope.map.marker) and show me undefined. How can I resolve the problem?

My html is:
```
<map>
<marker position="current position"></marker>
<marker ng-repeat="marker in markers"  draggable="true" on-drag="dragMe()" id="OtherMarker" on-click="showInfoWindow(event, 'bar')" icon="{{image}}" position="{{marker.lat}}, {{marker.lng}}">
<info-window id="bar" visible="false" visible-on-marker="markerAltri">
         <div ng-non-bindable="">   
        {{marker.lat}}         
         </div> 
         </info-window>
</marker>
</map>
```

**Comment by allenhwkim** [comment]
Please take a  look at this example, https://rawgit.com/allenhwkim/angularjs-google-maps/master/testapp/infowindow_compile.html

**Comment by pikkolojoe** [comment]
I don't understand what I have to do. Sorry but I'm new on angular.

**Comment by allenhwkim** [comment]
It all works fine for me
http://plnkr.co/edit/sW6SXX?p=preview

**Comment by pikkolojoe** [comment]
It work only in a browser. On a mobile device works only if I set proprety draggable==true, but I don't want that markers are draggable
