### ISSUE TITLE
watch suppress-markers value

### ISSUE THREAD

**Issue by extravagangsta** [allenhwkim/angularjs-google-maps#310]
Hi!

Is it possible to have two-way binding for suppress-markers directive?

Here is my plunker:

http://plnkr.co/edit/mPdo2euvMygXAU4FGAep?p=preview

Thanks!

**Comment by allenhwkim** [comment]
Unfortunately, there is no get/set method for suppress-markers, which means it does not respond to two-way bindings. However you can do this in native coding

http://plnkr.co/edit/0IJYPT?p=preview

**Comment by extravagangsta** [comment]
This should work for me just fine.
Thanks a lot for your help!
