### ISSUE TITLE
Assertion failed: InvalidValueError: setIcon: in property scaledSize: not a Size: in property height: not a number

### ISSUE THREAD

**Issue by benjamincharity** [allenhwkim/angularjs-google-maps#313]
I am seeing this error for one batch of ng-repeat markers. The marker's still work perfectly; just am getting tons of errors in the console. 

![screen shot 2015-09-22 at 9 13 20 am](https://cloud.githubusercontent.com/assets/270193/10019234/37535834-610a-11e5-9b09-c89fedb5365a.png)

My other markers don't seem to be throwing this error, but I'm not sure what is different about them..

Marker HTML:

```
<marker
  data-ng-repeat="merchant in vm.merchants track by merchant._id"
  position="{{ ::merchant.location.geo.coordinates[1] }}, {{ ::merchant.location.geo.coordinates[0] }}"
  icon="{{ ::vm.merchantIcon }}"
  z-index="{{ $index }}"
  id="{{ ::merchant._id }}"
  on-click="vm.showInfo(event, merchant._id, 'merchantInfoWindow')"
></marker>

```

Icon object:

```
vm.merchantIcon = {
    url: '/assets/icons/merchant.svg',
    size: [512, 512],
    scaledSize: [20, 20],
    anchor: [10, 10]
};
```

My editor sure seems to think that I'm passing in integers:

<img width="358" alt="screen shot 2015-09-22 at 8 24 15 am" src="https://cloud.githubusercontent.com/assets/270193/10018988/a728c998-6108-11e5-92f9-cd8372c01722.png">

But it seems Google doesn't agree.

And the same icon object works without throwing errors elsewhere:

```
vm.movingIcon = {
    url: '/assets/icons/location_moving.svg',
    size: [100, 100],
    scaledSize: [50, 50],
    anchor: [25, 25]
};
```

- I've tried using `ng-repeat` without the `data-`prefix.
- I've tried copy/pasting different (working) icon object.
- Tried just changing the icon asset.
- Tried removing just `size` or just `scaledSize`.

Any insight on what I might be missing here?

**Comment by allenhwkim** [comment]
Please add a plunker example so that debugging can be done eaaily

**Comment by benjamincharity** [comment]
Here is a plunker: http://plnkr.co/edit/hGaU6O2mQxsKvVLjkpLN?p=preview

You can see the errors in the console.

(While not part of this exact issue, you can see another issue I am having in the plunker... my info windows are all offset to the right.)

**Comment by allenhwkim** [comment]
Those are caused by attribute observers.
When marker is initialized, it reads icon attributes and converts into appropriate Point or Size. However, when it is set as `{{ .. }}`, it is also observed and whenever it is changed it tries to set the properity by calling setIcon method.

It works fine with other attributes because they are very common, but not with icon right now.

In summary,
It's safe to ignore the errors. If you want to fix this error, please look into directives/marker.js

Can't promise to fix this sooner though

**Comment by benjamincharity** [comment]
Thanks for the quick response! It's good to know at least I haven't set things up incorrectly. Definitely have been enjoying this plugin over others that I've tried.

Any thoughts on the mis-aligned info windows? (or should I open a separate ticket?)

**Comment by allenhwkim** [comment]
Separate ticket please
