### ISSUE TITLE
Info-windows placed too far to the right.

### ISSUE THREAD

**Issue by benjamincharity** [allenhwkim/angularjs-google-maps#314]
I see this doesn't happen with the default Google icons. But I'm not sure what it is about my custom icons that are causing the misalignment. 

The icons themselves seem to be placed perfectly.. it's only the `info-window` that is out to the right:

![screen shot 2015-09-21 at 3 49 39 pm](https://cloud.githubusercontent.com/assets/270193/10028084/792c2ece-6138-11e5-884f-d0a3c1207210.png)

<img width="631" alt="screen shot 2015-09-22 at 8 22 25 am" src="https://cloud.githubusercontent.com/assets/270193/10028081/74cb469e-6138-11e5-93e3-36fce37c6680.png">

Plunker reproduction: http://plnkr.co/edit/hGaU6O2mQxsKvVLjkpLN?p=preview

**Comment by allenhwkim** [comment]
Could not debug your code. too much for me. 
However, I tested with my own code, and it works fine.

http://plnkr.co/edit/w1PCzs?p=preview

I would recommend to debug your marker icon like the following.
![image](https://cloud.githubusercontent.com/assets/1437734/10092339/39dbb60e-6313-11e5-88cf-48f406a2ec0b.png)

There is no additional logic to positoining infowindow on this module. It is as it is.
