### ISSUE TITLE
asynchronous loading

### ISSUE THREAD

**Issue by HoplaGeiss** [allenhwkim/angularjs-google-maps#315]
right now I am loading angularjs-google-maps this way:

I have a script in my `head` to load google map:
`<script src="https://maps.googleapis.com/maps/api/js?libraries=places"></script>`

In some other place of my code I require `ngmap`
`//= require ngmap/build/scripts/ng-map.min`

However thanks to google pageSpeed insight, I saw that google map is a render blocking script.
so I tried to load it asynchronously like this:
`<script src="https://maps.googleapis.com/maps/api/js?libraries=places" async></script>`
It fails because afterwards I require ngmap which require google map to be loaded.

Is what I attempt to do possible ?

**Comment by allenhwkim** [comment]
Please take a look at "map-lazy-load" directive

**Comment by HoplaGeiss** [comment]
Thanks, it is awesome.
