### ISSUE TITLE
Can not apply different CSS classes for custom-markers

### ISSUE THREAD

**Issue by Moqadi** [allenhwkim/angularjs-google-maps#319]
I am trying to apply different CSS classes for different custom markers, but looks like that custom markers only understand "custom-marker" class name and you can not assign a class name with different name for a custom marker.

**Comment by allenhwkim** [comment]
I am pretty sure that you can add your own class according to the code


    CustomMarker.prototype.addClass = function(className) {
      var classNames = this.el.className.split(' ');
      (classNames.indexOf(className) == -1) && classNames.push(className);
      this.el.className = classNames.join(' ');
    };

**Comment by Moqadi** [comment]
What should I do to pass my own class?

**Comment by allenhwkim** [comment]
http://plnkr.co/edit/6cMEyk?p=preview

You need to add your own class inside of container. This can be improved though.

**Comment by allenhwkim** [comment]
This is fixed with 1.13.6 release, Example: https://rawgit.com/allenhwkim/angularjs-google-maps/master/testapp/custom-marker-custom-style.html

**Comment by Moqadi** [comment]
I see. Thanks much for the examples.
