### ISSUE TITLE
places-auto-complete 

### ISSUE THREAD

**Issue by iamnizzam** [allenhwkim/angularjs-google-maps#321]
Input-html: places-auto-complete types="['geocode']" on-place-changed="myCallback(place)" 
Angular: $scope.myCallback = function(place){
      console.log(place);
    };
Output: undefined

**Comment by allenhwkim** [comment]
Please add a plunker example.

**Comment by iamnizzam** [comment]
or just give me the source of this 
https://rawgit.com/allenhwkim/angularjs-google-maps/master/testapp/places-auto-complete.html

**Comment by allenhwkim** [comment]
```
         $scope.placeChanged = function() {
           $scope.place = this.getPlace();
           console.log($scope.place.geometry.location.lat(), $scope.place.geometry.location.lng());
           $scope.map.setCenter($scope.place.geometry.location);
         }
```

**Comment by anggadaus** [comment]
places auto compete not respon list places in web admin...

<input places-auto-complete on-place-changed="placeChanged(place)">
not list place

**Comment by allenhwkim** [comment]
Please add a plunger that reproduces your problem

**Comment by iamnizzam** [comment]
well i found ans tanks @allenhwkim 
ans is:  $scope.place = this.getPlace();
