### ISSUE TITLE
how to get 'Directions path length' inside controller

### ISSUE THREAD

**Issue by iamnizzam** [allenhwkim/angularjs-google-maps#322]
hint:
https://github.com/allenhwkim/angularjs-google-maps/blob/master/testapp/directions.html

**Comment by allenhwkim** [comment]
There is no length in distance, but you can measure distance between two points.
Please take a look at this issue, https://github.com/allenhwkim/angularjs-google-maps/issues/298

      Distance:
      {{map.directionsRenderers[0].directions.routes[0].legs[0].distance}}

**Comment by iamnizzam** [comment]
but this not updated when i edit route...
like places-auto-complete ... this.getPlace give the place object...
somthing like this i want

**Comment by allenhwkim** [comment]
https://github.com/allenhwkim/angularjs-google-maps/blob/master/testapp/directions.html

As you see, when you change origin/destination, distance also changes on this example.
![image](https://cloud.githubusercontent.com/assets/1437734/10240237/66fe0d28-68a7-11e5-97f5-0ccf7b31e58a.png)
Directions path length: 226

![image](https://cloud.githubusercontent.com/assets/1437734/10240248/7ee3d058-68a7-11e5-9140-8dbe2a27df0d.png)
![image](https://cloud.githubusercontent.com/assets/1437734/10240250/859ba6aa-68a7-11e5-8f20-32386701cb44.png)

**Comment by iamnizzam** [comment]
thanks your example's "$rootScope.map.directionsRenderers[0]" that i want
