### ISSUE TITLE
Conflict with tabset (angular-ui /bootstrap)

### ISSUE THREAD

**Issue by Ofer-Gal** [allenhwkim/angularjs-google-maps#323]
This is great but I can't use it in a tab made with angular-ui /bootstrap (https://github.com/angular-ui/bootstrap/tree/master/src/tabs)

If the map tag is in a tab, it does not show.
outside a tab, it shows great.
Any advice?

**Comment by allenhwkim** [comment]
Please checkout this https://github.com/allenhwkim/angularjs-google-maps/issues/279. 

```
  <tabset>
    <tab heading="One" ng-click="$emit('a')">
      <map center="London"></map>
    </tab>
    <tab heading="Two" ng-click="$emit('b')">
      <map init-event="b" center="Liverpool"></map>
    </tab>
    <tab heading="Three" ng-click="$emit('c')">
      <map init-event="c" center="Andria"></map>
    </tab>
  </tabset>
```

**Comment by Ofer-Gal** [comment]
Cool! thanks
After moving the map to the first empty tab, it stated showing on "Good" browsers :-)

Nothing showing in IE 11 and Edge shows just the background. 
Is there a shim or something you know of?

**Comment by allenhwkim** [comment]
This does not work in IE 11, http://plnkr.co/edit/K1kFDh?p=preview?

**Comment by allenhwkim** [comment]
Can someone who has IE11 test this url?  http://plnkr.co/edit/K1kFDh?p=preview

**Comment by Ofer-Gal** [comment]
I did test it. Use the code and it works for me fine
Thank you for a great help

**Comment by allenhwkim** [comment]
Nice, if u don't mind, could you add a star to this repo if you want to recommend to other developers?

**Comment by Ofer-Gal** [comment]
Done. But you deserve more than one star :-)

**Comment by allenhwkim** [comment]
Thanks.

**Comment by przemoli** [comment]
How would that work with ui-gmap-google-map? Also for me Angular translates tabs as li + a with a having its own ng-click so it ignore tab ng-click aparently.
