### ISSUE TITLE
Any possibility to bind event on marker hover?

### ISSUE THREAD

**Issue by zsitro** [allenhwkim/angularjs-google-maps#325]
For example to show a infoWindow on hover..

thanks

**Comment by allenhwkim** [comment]
I do not think Google maps API has that event.

**Comment by zsitro** [comment]
Ye, probably..

**Comment by extravagangsta** [comment]
@zsitro How about this?:
http://plnkr.co/edit/DoD28n45mwYiNSTINGcC?p=preview

**Comment by allenhwkim** [comment]
https://developers.google.com/maps/documentation/javascript/events. Never tried on infoWindow

**Comment by zsitro** [comment]
looks good, thanks!
