### ISSUE TITLE
stroke does not change

### ISSUE THREAD

**Issue by CrazyD81** [allenhwkim/angularjs-google-maps#326]
When I bind stroke properties of a shape to model values, the stroke does not change when I change the values in the controller.

```html
<shape name="polyline" data-ng-repeat="feature in layer.features"
					 path="{{::feature.pathString}}"
					 geodesic="true"
					 stroke-color="{{feature.stroke.color}}" stroke-opacity="{{feature.stroke.opacity}}" stroke-weight="{{feature.stroke.weight}}"					 
					 on-mouseover="vm.onLineEnter(this, feature)"
					 on-mouseout="vm.onLineLeave(this, feature)"								 
					 on-click = "vm.onFeatureClick(this, feature)"
					 editable="false"
					 draggable="false"
					 clickable="true"
					 >					 
  				</shape>
```
and then in the controller

```javascript
vm.onLineEnter = function (event, marker, feature) {
			if (feature.stroke)
			{			
				feature.stroke.color = feature.layer.defaultHoveredStroke.color;
				feature.stroke.weight = feature.layer.defaultHoveredStroke.weight;
				feature.stroke.opacity = feature.layer.defaultHoveredStroke.opacity;
			}
		};
```

Anybody experienced the same issue?

**Comment by allenhwkim** [comment]
Please add a plunker example

**Comment by allenhwkim** [comment]
How about this?

vm.onLineEnter = function (event, feature) {
            if (feature.stroke)
            {           
                feature.stroke.color = feature.layer.defaultHoveredStroke.color;
                feature.stroke.weight = feature.layer.defaultHoveredStroke.weight;
                feature.stroke.opacity = feature.layer.defaultHoveredStroke.opacity;
            }
        };

**Comment by CrazyD81** [comment]
Here is a plunker example

http://plnkr.co/edit/JhoRIySLlAHFGUGD2KF7?p=preview

**Comment by allenhwkim** [comment]
Dynamically setting options are only working if there is set function for that object. e.g., `setCenter` for `center` attribute. For some cases, you need to read Google maps api document, and find the right function and apply it into your javaacript.

http://plnkr.co/edit/5qaWRi?p=preview

**Comment by allenhwkim** [comment]
You also can use options as an attribute to set dynamically set the properties
http://plnkr.co/edit/2qAJGrYfm6O0PmvETvzW?p=preview

     <shape name="polyline" path="{{path}}" 
       geodesic="true" 
       options="{{options}}" 
       on-mouseover="onLineEnter()"
       on-mouseout="onLineOut()">
     </shape>

**Comment by CrazyD81** [comment]
Thank you!

This is just what I needed. I really like your directive. It is otherwise very straight forward. Been using other directive before and had many problems.

Cheers!

**Comment by allenhwkim** [comment]
Thanks, that's the reason why I developed this directive. If you recommend this directive to other developers, please add a star to this repo.
