### ISSUE TITLE
Mouse listeners on custom marker are not functioning

### ISSUE THREAD

**Issue by Moqadi** [allenhwkim/angularjs-google-maps#327]
I am trying to add mouse over/out listeners over some divs on the custom markers.
It seems that the events are not propagating and not triggering my handlers.

**Comment by allenhwkim** [comment]
AFAIK, Google maps API does not respond to mouse events. I might be wrong.
However, it is a custom marker, we can add the event on our own.
You may try this before I actually started working on it.

Please add your example here as plunker, so that we can share what your issue is.

**Comment by Moqadi** [comment]
Please see the following example: I added the 'on-click' on a div inside the 'custom marker'
http://plnkr.co/edit/WUNGu5z3RKGPSYMih6CX?p=preview

**Comment by Moqadi** [comment]
The example above is using a click listener.

**Comment by allenhwkim** [comment]
You may try this way.
http://plnkr.co/edit/OR1pvk?p=preview

**Comment by Moqadi** [comment]
But looks like we can't add these mouse events on the DIV inside the Custom Marker and this is actually my problem. In fact, I am using chart component inside the Custom Marker and this chart has some mouse events that are not functioning.

**Comment by allenhwkim** [comment]
http://plnkr.co/edit/OR1pvk?p=preview

For that case, you need to add normal javascript event, not google map event.

**Comment by Moqadi** [comment]
Thanks. JS listeners are working.
