### ISSUE TITLE
Controls not working

### ISSUE THREAD

**Issue by SergioEnrique** [allenhwkim/angularjs-google-maps#328]
Controls are not working on my code, not even in the plunker example you have here: http://ngmap.github.io/controls.html#

This plunker example is exactly the same of one of the code samples:
http://plnkr.co/edit/nqRw7dtfjDhylyYcWlin?p=preview

**Comment by allenhwkim** [comment]
Which control is not working from the following?

```
  pan-control="true" 
  map-type-control="true" 
  map-type-control-options="{style:'DROPDOWN_MENU'}" 
  zoom-control="true" 
  zoom-control-options="{style:'SMALL'}"
```

**Comment by SergioEnrique** [comment]
I think any of them... this should work like your example: 
![image](https://cloud.githubusercontent.com/assets/2131376/10240576/443df2d4-68a3-11e5-983c-2af9fb6f2d8d.png)

but instead of your example I get the same map as your image:
![image](https://cloud.githubusercontent.com/assets/2131376/10240586/6272d5bc-68a3-11e5-8427-af5e8328c2f1.png)

**Comment by allenhwkim** [comment]
https://developers.google.com/maps/documentation/javascript/controls
please read this document

**Comment by SergioEnrique** [comment]
I know how controls work, is just that I'm not able to replicate my controls in Google API pure code to an Ng-Map, the problem I think is not in my code but in ngmap because your examples don't work either.

This is my map working without angular:
http://plnkr.co/edit/FOMTTxLndy4YD23lqRmw?p=preview

And this is what I get with the Ng-Map:
http://plnkr.co/edit/nqRw7dtfjDhylyYcWlin?p=preview

**Comment by allenhwkim** [comment]
http://plnkr.co/edit/3B9HkMYX89xSEJ9WYjsU?p=preview

**Comment by SergioEnrique** [comment]
Thank you very much!
