### ISSUE TITLE
Activate or not places-auto-complete depending on condition

### ISSUE THREAD

**Issue by vladlep** [allenhwkim/angularjs-google-maps#329]
Hi,

The places-auto-complete feature is very nice and works great. But I would need to activate it or not based on a condition. Basically premium users can use it while the rest not. 
I can not find in the docs more about this and tried to set  by luck places-auto-complete=false  or true but that does not change anything. 

Is this possible? 

Thanks,
Vlad

**Comment by allenhwkim** [comment]
https://github.com/allenhwkim/angularjs-google-maps/blob/master/directives/places-auto-complete.js#L24

It is possible, by simply adding 
```
if (attrs.placesAutoComplete ==='false') {
   return false;
}
```

**Comment by allenhwkim** [comment]
This issue has been resolved, please checkout the recent version.

**Comment by vladlep** [comment]
thanks!
