### ISSUE TITLE
How to add a marker event?

### ISSUE THREAD

**Issue by SergioEnrique** [allenhwkim/angularjs-google-maps#330]
Hi again,

I'm trying to add a "dragend" google map listener for a marker, but I can't find any example about it.

I just read that I can add an event as an attribute:
```
<MapEvent>	String	Any Marker events
```
So I tried this:
```
<marker position="current-position" draggable="true" dragend="dragendFunction(event)"></marker>
```
But it doesn't work.

How can I add an event?

**Comment by allenhwkim** [comment]
`on-dragend`
