### ISSUE TITLE
ReferenceError: marker is not defined

### ISSUE THREAD

**Issue by ayoubjs** [allenhwkim/angularjs-google-maps#331]
Hello,

I'm currentrly modifying my code to use the new custom-marker directive (great idea btw) but i'm getting a "ReferenceError: marker is not defined" after map actions since I switched to custom markers.

The error happens in custom-marker.js on line 165.

I'm pretty new to Angular so I can't figure out if i'm doing something wrong or if it's a bug.

Thanks!

Keep up the good work!

**Comment by allenhwkim** [comment]
It seems like a bug. It should be a `customMarker`, not a `marker`. copy/paste went wrong, I guess :)

**Comment by allenhwkim** [comment]
Please check out the recent release 1.13.10, and check.

**Comment by ayoubjs** [comment]
Hi, I just checked out the new release and everything is working ! 
Thank you :)
