### ISSUE TITLE
Object with strings in html attributes are not parsed correctly

### ISSUE THREAD

**Issue by thallgren** [allenhwkim/angularjs-google-maps#334]
I have a html `<marker>` element where I add the following `place` attribute:

    place="{
      location: {
        lat: {{info.latitude}},
        lng: {{info.longitude}}
      },
      placeId: &quot;{{info.id}}&quot;
    }"

this works OK as long as `info.id` contains some characters that are not numeric. When all characters are numeric I get an assertion error:

    Assertion failed: InvalidValueError: setPlace: in property placeId: not a string

I've tried different ways of quoting the ID to no avail. The parser seems to "quess" that since it's entirely numeric it must be a number, regardless of if it's quoted or not.

**Comment by allenhwkim** [comment]
How about this?

    place='{
      location: {
        lat: {{info.latitude}},
        lng: {{info.longitude}}
      },
      placeId: "{{info.id}}";
    }'

**Comment by thallgren** [comment]
That makes no difference (well, you have an extra semicolon in there causing an error but with that removed it yields exactly the same object as in my example).

Adding a character however, like this:

    place="{
      location: {
        lat: {{info.latitude}},
        lng: {{info.longitude}}
      },
      placeId: &quot;X{{info.id}}&quot;
    }"

(note the extra X), makes it parse OK. This leads me to believe that the quotes are disregarded. If it's possible to convert the value to a number, then that conversion takes place even if the value is quoted.

**Comment by allenhwkim** [comment]
Could add an plunker example?

**Comment by thallgren** [comment]
Here's [a plunker that demonstrates the problem](http://plnkr.co/edit/ami59e4hKosDTG1NMwf3?p=preview) (errors are printed in the console view). Add a non-numeric character to the 'id' in script.js and the error goes away.

I found that ng-map.js line 2161 is a good place to set a breakpoint. Look at `options.place.placeId` in the local scope.

**Comment by allenhwkim** [comment]
Tried to debug it, but not found solution yet. Any help would be appreciated.

**Comment by larsdecker** [comment]
The problem came directly from the google api. The placeId must be a string value
with characters.

https://developers.google.com/maps/documentation/javascript/examples/places-placeid-finder

**Comment by allenhwkim** [comment]
I can change like the following, 
```
diff --git a/services/attr2_options.js b/services/attr2_options.js
index eed848d..0e91e18 100644
--- a/services/attr2_options.js
+++ b/services/attr2_options.js
@@ -217,7 +217,11 @@
             if (typeof attrs[key] !== 'string') {
               options[key] = attrs[key];
             } else {
-              options[key] = toOptionValue(attrs[key], {scope:scope, key: key});
+              if (attrs[key].match(/^[0-9.]+$/)) {
+                options[key] = attrs[key];
+              } else {
+                options[key] = toOptionValue(attrs[key], {scope:scope, key: key});
+              }
             }
           }
         } // if (attrs[key])
```

However, it's never the case. Google placeID is never a number, but a string.  https://developers.google.com/maps/documentation/javascript/examples/places-placeid-finder

**Comment by thallgren** [comment]
Not sure I understand. Are you saying that this behavior (auto converting numeric values to numbers even when they are quoted) are specific for the placeId attribute? I used that attribute just as an example and the place where I observed the incorrect parsed result (numeric rather than String) seemed to be _before_ anything was sent to the Google API.

**Comment by thallgren** [comment]
I updated the plunker to not use placeId as an example. Instead it now uses a label, like this:

    label='{
      text: "3"
    }'

The error is:

    Assertion failed: InvalidValueError: setLabel: in property text: not a string

so please reopen this ticket.

**Comment by allenhwkim** [comment]
This feature has been released. 
Thanks @thallgren for the patience
