### ISSUE TITLE
lazy load

### ISSUE THREAD

**Issue by HoplaGeiss** [allenhwkim/angularjs-google-maps#335]
Hello, I am using the lazy load. In some cases ( I didn't figure out really the rules, maybe the browser ) the maps doesn't appear (I have a grey background). If I re-size the window than it appears.

```
<div map-lazy-load="http://maps.google.com/maps/api/js?libraries=places">
  <map ..></map>
  <input places-auto-complete size=80/>
</div>
```

**Comment by allenhwkim** [comment]
It works fine with me. My guess is you are recreating DOM with javascript. e.g.. tabs, etc. 
Please add a plunker example.

**Comment by HoplaGeiss** [comment]
Hello,

Thanks for your answer. I looked into the issues about tabs. It helped me solve my issue.
I have all my configuration in my directive. 

```
<div map-lazy-load="http://maps.google.com/maps/api/js?libraries=places">
    <map
      center="[48.46, 7.48]"
      disable-default-ui="true"
      zoom="6"
      map-type-id="ROADMAP"
      >
    </map>
</div>
```

To fix my problem I just added this lines in the javacript.

```
      scope.$on('mapInitialized', function(evt, evtMap) {
        google.maps.event.trigger(evtMap, 'resize');
      });
```

I didn't quite understand why I need to "reload the map". But it does the trick.

**Comment by allenhwkim** [comment]
Tabs are recreating DOM, and it makes to re-render map. However, map renders before tab width/height is set.

e.g., map is rendered for width/height 1px/1px, but tab increase its width/height after map is rendered to   100px/100px.
