### ISSUE TITLE
Documentation probably needs update

### ISSUE THREAD

**Issue by mmswi** [allenhwkim/angularjs-google-maps#336]
Hello, so I've tried inserting in the index the <script src="assets/bower_components/ngmap/build/scripts/ng-map.min.js"></script> and <script src="//maps.google.com/maps/api/js"></script> but it doesn't work. 

If, however, I'm inserting <script src="//rawgit.com/allenhwkim/angularjs-google-maps/master/build/scripts/ng-map.min.js"></script> and <script src="https://maps.google.com/maps/api/js?sensor=false"></script>, it works.

Another weird thing is that if I copy paste the code from the "//rawgit.com/" link to my min.js file, it doesn't work. If I, however, beautify the code and un-minify it, it works...

Thanks,

**Comment by allenhwkim** [comment]
Please add you example as a plunker, so that i can see what problem you have.

**Comment by mmswi** [comment]
hm...I had some "script tags" which seem to have been deleted when I've posted. in short, the min.js from the bower components and the "http://maps.google.com/maps/api/js" script, don't work. what works is: "https://maps.google.com/maps/api/js?sensor=false" and "http://rawgit.com/allenhwkim/angularjs-google-maps/master/build/scripts/ng-map.min.js".
