### ISSUE TITLE
Map doesn't show in tabs

### ISSUE THREAD

**Issue by benji87** [allenhwkim/angularjs-google-maps#337]
When trying to render the map with bootstrap tabs the map tiles won't load until you resize the window.

For example:

`<div id="map" class="tab-pane in">
						<div class="wrapper">
							<map center="{{map.center.latitude + ',' + map.center.longitude}}" street-view-control="true" zoom="{{map.zoom}}" width="100%" height="640">
								<marker position="{{map.center.latitude + ',' + map.center.longitude}}" title="Click to zoom"></marker>
							</map>
						</div>
					</div>`

**Comment by larsdecker** [comment]
Can you create a short plunker example for this problem?

**Comment by allenhwkim** [comment]
Please search for 'tab' in issues. https://github.com/allenhwkim/angularjs-google-maps/issues?utf8=%E2%9C%93&q=tab

**Comment by allenhwkim** [comment]
Example: http://plnkr.co/edit/K1kFDh?p=preview
