### ISSUE TITLE
Set custom infoWindow to direction's origin and destination

### ISSUE THREAD

**Issue by personstays** [allenhwkim/angularjs-google-maps#338]
First, thanks for a good plugin.
Direction directive is working fine. However, I'd like to have custom infoWindow for origin and destination. Suppose origin's infoWindow is "You're here!" and destination's infoWindow is "Your destination!".

**Comment by allenhwkim** [comment]
InfoWindow has this option, 'visible-on-marker'. Please use that one.
https://rawgit.com/allenhwkim/angularjs-google-maps/master/build/docs/info-window.html

**Comment by personstays** [comment]
However, the origin's and destination's markers are created automatically via direction directive. What value do I have to put in visible-on-marker of info-window for origin and destination?

**Comment by allenhwkim** [comment]
The markers on directions service is handled by Google. 
I don't think you can get the instance of marker for origin and destination.

However, you can add your own custom-marker since you already know the origin and destination, for this case, you don't need to use InfoWindow.

**Comment by allenhwkim** [comment]
Example: https://rawgit.com/allenhwkim/angularjs-google-maps/master/testapp/directions-with-custom-marker.html

Closing issue.
