### ISSUE TITLE
Consider changing the name of "map" directive to "ng-map"

### ISSUE THREAD

**Issue by brgrz** [allenhwkim/angularjs-google-maps#339]
`<map>` tag is used for image maps in HTML, as such we encounter a few issues when using it for directive name/tag. Change it to ngMap (ng-map) or something similar.

**Comment by allenhwkim** [comment]
I agree, but it's a big task to do in once. mean while you can use `<map ng-non-bindable>` for a image map.

**Comment by jkornata** [comment]
I think that the backwards compatibility might be the biggest issue here. With the directive name change everyone would need to update their projects.

**Comment by brgrz** [comment]
It's not like this is a project that's used by millions worldwide..The directive name choice was unfortunate in the first place.

**Comment by jkornata** [comment]
It might be not used by millions worldwide but I still believe that it should be done the smart way. 

I am rather a backend developer and have a really short experience with Angular but maybe there is a way to deprecate directive and create something like suggested ng-map.

**Comment by allenhwkim** [comment]
Backward compatibility is the issue to change map to ng-map. We should either support both names or make no change. 

Users also can use map as attribute to avoid namespace collision with the current version.

**Comment by allenhwkim** [comment]
Implemented with 1.14. closing

**Comment by kharmonycentral** [comment]
As of version 1.18.5, there is still an issue with ng-map conflicting with the html map directive. I have resolved it by commenting out line 1725 in build/scripts/ng-map.js.

`angular.module('ngMap').directive('map', [mapDirective]);`

Should I submit a PR to resolve this?
