### ISSUE TITLE
Markers not working properly.

### ISSUE THREAD

**Issue by zunairzubair** [allenhwkim/angularjs-google-maps#340]
Hey, 
I am creating markers on the map using geolocation. But I keep getting to run into an issue. The issue is, the Google Maps API keeps changing the variable names in which it stores Longitude and Latitude. First it was G , K. Then it became H and L. And now it has been shifted to a new object named 'viewport'.
How can I keep track of these changes. Can I include a stable version of the google maps API in my code?

**Comment by allenhwkim** [comment]
You should use function, e.g., latitude(), instead of name.

**Comment by zunairzubair** [comment]
Thanks. Fixed it.
