### ISSUE TITLE
Google Geocoded response statuses 

### ISSUE THREAD

**Issue by jkornata** [allenhwkim/angularjs-google-maps#341]
Hey, I've noticed that currently GeoCoder Service in case of failure returns message: 
*'Geocoder failed due to: '+ status*

I'd like to suggest changing it either to an object with complete message or just the status returned from Google API. They do return a few errors, and it would be easier to react to the error codes. 

In case you do agree, I am willing to change it with a PR (even though it's not a huge change :smile: )

**Comment by allenhwkim** [comment]
Yes, PR please. Thank you.

**Comment by jkornata** [comment]
Can we get a version update with this change? like 1.13.14?

**Comment by allenhwkim** [comment]
1.13.14 is published to bower and npm
