### ISSUE TITLE
places autocomplete get response

### ISSUE THREAD

**Issue by lluiscanals** [allenhwkim/angularjs-google-maps#342]
Hi, first of all thank you form this great repo!

I'm trying to use your places-auto-complete directive. It's working as expected but I don't know if I can get the entire response from google and store in a scope variable in my controller in order to e.g fill a form automatically, or render a map with the input.

Is it posible?

Thanks in advance!

**Comment by allenhwkim** [comment]
As you see in this example, https://github.com/allenhwkim/angularjs-google-maps/blob/master/testapp/places-auto-complete.html, `this.getPlace()` will give you the entire response.

```
    <script src="../directives/map.js"></script>
    <script>
      angular.module('myApp', ['ngMap'])
       .controller('MyCtrl', function($scope) {
         $scope.types = "['establishment']";
         $scope.placeChanged = function() {
           $scope.place = this.getPlace();
           console.log($scope.place.geometry.location.lat(), $scope.place.geometry.location.lng());
           $scope.map.setCenter($scope.place.geometry.location);
         }
       });
    </script>
```

**Comment by lluiscanals** [comment]
Oh, thank you very much! I was looking in the api docs but I didn't see this testapp examples.

Regards!

**Comment by allenhwkim** [comment]
@lluiscanals thanks for letting me know. 
 If you want to update the documentation in places-auto-complete.js and send me a pull request, that would be very appreciated.
