### ISSUE TITLE
Lat and Lng changed after resize event

### ISSUE THREAD

**Issue by mckenzielong** [allenhwkim/angularjs-google-maps#346]
This one could be a bit tricky to reproduce...

Perhaps this is due to flexbox, but the call to resize is messing up the values I have provided for the map's center.  The first time the map loads this is does not happen, but subsequent calls (for example a route change reusing a view with different center) will cause the center latitude to decrease.  

For example, I have this element flexing in the column direction beneath a title bar.

```html
<map ng-if="vmMap.timeout" center="[lat,lng]" zoom="10" default-style="false" 
disable-default-u-i="true" class="layout-fill ng-scope layout-column flex"></map>
```
With the following css:

```css
-webkit-font-smoothing: antialiased;
box-sizing: border-box;
color: rgba(0, 0, 0, 0.870588);
display: flex;
flex-basis: 0%;
flex-direction: column;
flex-grow: 1;
flex-shrink: 1;
font-family: Roboto, 'Helvetica Neue', sans-serif;
margin-bottom: 0px;
margin-left: 0px;
margin-right: 0px;
margin-top: 0px;
```

While this seems like a pretty small corner case, or even an issue with the resize event, here is a work around:

As stated in the comments for the map directive, the resize has to be triggered to get the map to display.  Caching the center and resetting the center does seem tor resolve it.
```javascript
$timeout(function () {
   var center = map.getCenter();
   google.maps.event.trigger(map, "resize");
   map.setCenter(center);
});
```

**Comment by allenhwkim** [comment]
This has been discussed several times. This happens all google maps AFAIK. When dom is resized, the center of  map is not reset by the width/height of DOM. You can use $timeout or function  to call setCenter and resize event.

We can add a systematic approach for this. For that case, we need to consider all possibilites. DOM recreation, window resize, DOM resize .. etc. 

Not a solid solution found yet, but any suggestions  or PRs are welcomed.
