### ISSUE TITLE
maps inside hidden elements (tabs)

### ISSUE THREAD

**Issue by geostima** [allenhwkim/angularjs-google-maps#347]
I have had very unsuccessfull attempts at getting the maps to work in an angular page where the map is not seen on the initial load. When switching to a certain tab where the map is, it does not show due to its element being hidden initially. As soon as we resize the browser window the map starts up and then works normally.

My question is, how would I trigger the map to only turn on when the tab is shown, is there a refresh function we can call?

Here is a fiddle to illustrate my problem. http://plnkr.co/edit/dOMKgE?p=preview

**Comment by lluiscanals** [comment]
You have to trigger this,
google.maps.event.trigger(map, 'resize'); 
when the tab is selected 

see this:
http://stackoverflow.com/questions/32371691/use-ngmap-with-tabset-only-the-first-tab-will-be-initiated

**Comment by geostima** [comment]
@lluiscanals thank you so much, i got it to work. For the life of me I could not find that specific stack page. I found countless others however which had similar solutions which did not help at all. This one however resolved my issue. I simply called the reRedner method on my ng-click instead of doing it using their tabbed way but all works as it should now. Gratitude.
