### ISSUE TITLE
Can I add Marker name with the custom-html marker?

### ISSUE THREAD

**Issue by Moqadi** [allenhwkim/angularjs-google-maps#348]
I am looking a way to add a marker name with the custom html marker, please see the following, but this with default marker

![marker-name](https://cloud.githubusercontent.com/assets/9657047/10663360/0a3cf22e-78bb-11e5-8080-7718963f60c8.PNG)

**Comment by allenhwkim** [comment]
Could you add clarification for this.

**Comment by allenhwkim** [comment]
Please add clarification for this request. If not, this issue will be closed soon.

**Comment by allenhwkim** [comment]
Closing because there is no response from user.
