### ISSUE TITLE
How to disable Scroll Wheel

### ISSUE THREAD

**Issue by existence17** [allenhwkim/angularjs-google-maps#349]
I just stated using your directive, but I cant seem to find any information in how to disable the scroll wheel. It is pretty annoying when the user wants to scroll on the page and suddenly it stops scrolling and it zooms in the map.

Do you know how can I prevent it?

**Comment by lluiscanals** [comment]
https://developers.google.com/maps/documentation/javascript/reference?csw=1#MapOptions

Look at MapOptions ->scrollWheel
and set it to false.

**Comment by allenhwkim** [comment]
As @lluiscanals  said, `<map scrollwheel="false"></map>` will do the job.

**Comment by puneet94** [comment]
How can you enable scrollwheel when the map is clicked?
