### ISSUE TITLE
Problems with markers on the north and south poles

### ISSUE THREAD

**Issue by chiptus** [allenhwkim/angularjs-google-maps#350]
Google maps are not supporting locations with lat > +85 or < -85 (by this thread: http://stackoverflow.com/questions/11849636/maximum-lat-and-long-bounds-for-the-world-google-maps-api-latlngbounds)
Try looking for places with the mentioned latitude on google maps and you'll get a grey screen. The problem is when adding a marker with that latitude it appears on the map with coordinates (0,0). 
What should happen in my opinion is that the marker would be removed and an error will be logged to the console. Other option would be to let us know what are the coordinates and let us decide this.

What do you think? I'm willing to help with this, just need to know where to put the logic? Geocoder? marker directive?

**Comment by allenhwkim** [comment]
Thanks for the suggestion.

However, as you see it here, http://plnkr.co/edit/1rRcT4?p=preview, it points to a certain position. It may be a right position or it may be a wrong position. 

The point is that I do not want to manipulate Google Maps API V3 behaviour for this directive. It must be a users' choice, not from this directive.

**Comment by allenhwkim** [comment]
Unless I have a different opinion from users, this issue will be closed later.

**Comment by chiptus** [comment]
So how can the user make that choice? When I put a marker on the map, how
do I know what its location?

Thanks

**Comment by allenhwkim** [comment]
when you click on map, it has its location. As long as marker is from map, it has its own location with lat/lng.

**Comment by chiptus** [comment]
sorry, i didn't mean the end user. How can I as a developer know that a
marker has been added and see its coordinates? When the location is a
string I would like to know what are the resulting coordinates of the
geolocation inorder to decide whether it's valid or not.

Thanks

**Comment by allenhwkim** [comment]
if location is string. It's translated to LatLng via GeoCoding it. There is also a call back as you see in this document , `geo-callback`. https://rawgit.com/allenhwkim/angularjs-google-maps/master/build/docs/source/marker.html#line1
