### ISSUE TITLE
Enable controls after click

### ISSUE THREAD

**Issue by celsomtrindade** [allenhwkim/angularjs-google-maps#351]
Is it possible to enable the map control only after clicking on the map? Like the examples.
Didn't found anything about this in the docs.

**Comment by allenhwkim** [comment]
Please take a look at the testapp directory, and I think this file is you need to look at it, https://github.com/allenhwkim/angularjs-google-maps/blob/master/testapp/map_lazy_init.html

**Comment by allenhwkim** [comment]
The issue will be closed later unless the follow up questions are appended.

**Comment by celsomtrindade** [comment]
I didn't returned before because I was trying to fix other related thing, without success until now. Since it's generating an img as a placeholder before init the map, is there a way to make this img responsive? Or does it only work with a fixed img?

Another solution I'm using right now is to create an div on top of the map, so the user can't control the map until the div is clicked. Then i use an ng-hide to remove the div and "enable" the map control.

Don't know if is the best solution, but is working nice for me.
Also, my map is always showing 2 address points, origin and destination, so i also need the directions on the map.

If there isn't a solution for this specific problem, you close the topic.

But thanks for the response @allenhwkim , it's going to fit in other areas on the app!

**Comment by allenhwkim** [comment]
solution1: make image witdh 100% to make responsive.
solution2: broadcast an event, and the event will hide div and enable map as you seen on the example.

I recommend that you create a plunker example with your solution, and ask more question based on the example.

**Comment by celsomtrindade** [comment]
Ok. like i said, with your orientation I've created another solution.

With ng-hide I'm removing a div that overlays the map when clicked on the overlay div, and thus enable the map controll.

Thanks.
