### ISSUE TITLE
Marker with user profile photo inside pin

### ISSUE THREAD

**Issue by AdamPietrasiak** [allenhwkim/angularjs-google-maps#353]
I want to create markers with user profile photo inside styled pin.

I've seen example of "Marker Symbol Custom" that allows me to create custom path and it's very cool, but am I able to add some image to be part of it?

Also, my pins could have additional informations like notifactions number that would be in circle attached to each pin. I think it would require pin with custom html code. This one is optional however. 

Main thing is pin with photo inside.

Is it possible?

**Comment by allenhwkim** [comment]
Please use a `custom-marker` for that purpose. Marker has its own limitation.
