### ISSUE TITLE
Street View Panorama bug in "pov" property

### ISSUE THREAD

**Issue by harm-less** [allenhwkim/angularjs-google-maps#354]
Hello,

I just found a bug during development and it seems it's also on the latest release of the library.

When you go to the [Street View](https://rawgit.com/allenhwkim/angularjs-google-maps/master/testapp/street-view-panorama.html) demo and open the console you'll see the problem right away: `Assertion failed: InvalidValueError: setPov: in property pitch: not a number`

This happens because the parsing of the attributes from the HTML doesn't quite go right. The demo pov data is `pov="{heading:90, pitch: 0}"` and Google complains about the pitch not being a number. It seems from the source the Attr2Options parser does make it an object but leaves out `pitch` because it has a value of `0`. So it looks like this then, pitch is missing: `{heading: 90}`. Making this anything resembling a truthy value (1 or higher in this case) solve the error. 

So I guess the parser needs to consider `0` as a valid value too.

Harm

**Comment by allenhwkim** [comment]
Thanks for reporting this bug. I am impressed by the detail of the issue. It will be fixed sooner than later. also PR would be appreciated.

**Comment by harm-less** [comment]
Well, I tried to fix it myself, but came to the realization it was a problem in ng-maps. So why not share what discoveries I made  to make the work here easier, right? ;)
But that's good to hear, so thank you and good luck!

**Comment by allenhwkim** [comment]
Thanks, you will be notified by email when it is fixed.

**Comment by allenhwkim** [comment]
Leah, can u try fixing this?

**Comment by allenhwkim** [comment]
Fixed by 1.14.7
