### ISSUE TITLE
How can get the underlying Marker object from <marker> directive on click event?

### ISSUE THREAD

**Issue by jlstr** [allenhwkim/angularjs-google-maps#355]
Hello, in order to avoid repeating myself, I will just post a link to the StackOverflow Question that I created regarding this topic.

http://stackoverflow.com/questions/33445886/ng-map-how-can-get-the-marker-object-when-i-click-it

I was hoping to get the attention of someone directly related to the project here.

Thank you very much!

**Comment by allenhwkim** [comment]
Please follow this example
https://rawgit.com/allenhwkim/angularjs-google-maps/master/testapp/events.html

**Comment by jlstr** [comment]
Perfect. This is it! Thank you very much @allenhwkim.
