### ISSUE TITLE
Clustering of custom-markers

### ISSUE THREAD

**Issue by cogidoo** [allenhwkim/angularjs-google-maps#356]
Custom-Markers should support the MarkerClusterer-library like simple markers. I've tried it briefly and came across the following errors:
- custom-markers does not have the function getDraggable()
- custom-markers does not have the function getPosition()
- custom-markers emit no events so that I could not find a way to bypass the shortcomings of them

**Comment by stshmms** [comment]
+1

**Comment by allenhwkim** [comment]
Please add your example in plunker

**Comment by cogidoo** [comment]
http://plnkr.co/edit/GstHEnVSpPz5zmhgH7Fa?p=preview

As you can see, I temporarly add the functions `getDraggable()` and `getPosition()` to the custom-markers. But as soon as you start to zoom in, you get errors at the console and the drawing of the map is shattered.

**Comment by allenhwkim** [comment]
ng-map does not officially support MarkerClusterer, but only support official Google Maps APIs. MarkerClusterer is community driven feature. So, it's out of scope.
However, there is not much to lose trying this, but less priority.
We will mark it as enhancement and tackle it later

**Comment by allenhwkim** [comment]
fixed with 1.14.9 release
