### ISSUE TITLE
Custom-markers does not support zoom-to-include-markers

### ISSUE THREAD

**Issue by cogidoo** [allenhwkim/angularjs-google-maps#357]
With common markers you can use `zoom-to-include-markers` to fit the bounds of the map. Actually, this does not work with custom-markers. As a workaround I have to set the center and bounds programmatically.

**Comment by stshmms** [comment]
+1

**Comment by solidevolution** [comment]
@cogidoo Do you have an example of your solution? I've got problems with the process order, my function, triggert on the event "mapInitialized" after filtering the markers on the map looks like

        function fitMap() {
            var bounds = new google.maps.LatLngBounds();
            angular.forEach(vm.map.markers, function(marker) {
                if (marker.getVisible()) {
                    bounds.extend(marker.getPosition());
                }
            });
            vm.map.setCenter(bounds.getCenter());
            vm.map.fitBounds(bounds);
        }

**Comment by cogidoo** [comment]
@solidevolution I create the custom-markers with ng-repeat over a list. So when I change that list, I also call `setCenter` and `fitBounds` - like you do. But I iterate over my list-items and take the position from there. 
Do you really work with custom-markers? Because custom-markers a stored at `vm.map.customMarkers`.

**Comment by solidevolution** [comment]
@cogidoo I use markers, no custom-markers but with ng-repeat.

How do you listen for ng-repeat changes on markers?

**Comment by cogidoo** [comment]
@solidevolution You may wanna take a look at this: http://plnkr.co/edit/7b8ngAD85BjBniAFNEWU?p=preview

At the end of the function `switchList` I would do something like this:
```javascript
var bounds = new google.maps.LatLngBounds();
_.forEach($scope.devices, function(d) {
    var latlng = new google.maps.LatLng(d.attributes.lat, d.attributes.lng);
    bounds.extend(latlng);
});

$scope.map.setCenter(bounds.getCenter());
$scope.map.fitBounds(bounds);
```

**Comment by realph** [comment]
+1

**Comment by allenhwkim** [comment]
ng-map does not officially support MarkerClusterer, but only support official Google Maps APIs. MarkerClusterer is community driven feature. So, it's out of scope.
However, there is not much to lose trying this, but less priority.
We will mark it as enhancement and tackle it later

**Comment by allenhwkim** [comment]
added this feature with release 1.14.3.
