### ISSUE TITLE
custom-marker-relics when changing the list of ng-repeat

### ISSUE THREAD

**Issue by cogidoo** [allenhwkim/angularjs-google-maps#358]
I have a list of devices with which I create custom markers on the map.
```html
<div ng-controller="MapController as mapCtrl">
...
<map>
  <custom-marker position="[{{device.lat}}, {{device.lng}}]" ng-repeat="device in mapCtrl.devices">
    ...
  </custom-marker>
</map>
...
</div>
```
The user can select some devices whereupon the map only shows the selected devices (aka custom-markers). In order to achieve this, I replace the `devices`-array at the controller with a new array containing only the selected ones. The map updates with the new custom-markers. But there are also some duplicated markers.

Resulting HTML looks like this:
```html
<map ....>
  ...
    <div class="custom-marker" ...>
      ...
    </div>
  ...
  <custom-marker postition="..." ng-repeat="....">
    ... <!-- I think thats wrong! -->
  </custom-marker>
  ...
</map>
```
As you can see, there are custom-marker-tags with the template of the markers that should actually be removed by the directive.
I don't know whether I use the custom-markers in the wrong way, the directive has a bug or ng-repeat tricked me once again.

**Comment by allenhwkim** [comment]
Please add your example in plunker

**Comment by cogidoo** [comment]
Ok, I've created a plunker with two ways to reproduce the bug: http://plnkr.co/edit/7b8ngAD85BjBniAFNEWU?p=preview

Short description about whats happening:
There are two lists (`devices1`, `devices2`) of elements with positions and a list for the map (`devices`) that contains all elements of `devices1` and the two first elements of `devices2`.
With `switchList` you just change `devices1`with `devices2` and re-create the list `devices`.
With `toggleElement` you remove one element from the list and add it again.

**Comment by allenhwkim** [comment]
The main point is not to change ng-repeat variable, but to reset it entirely.

Please follow this example. 

https://rawgit.com/allenhwkim/angularjs-google-maps/master/testapp/custom-marker-ng-repeat.html
