### ISSUE TITLE
StreetView Panorama: consider use of StreetViewSource option

### ISSUE THREAD

**Issue by pietromarrone** [allenhwkim/angularjs-google-maps#359]
When switch to StreetView and ask for Panorama The Service ask for a default Image,  it can be either Outdoor or indoor, the latter can be very unopportune.

Google api provide a option to choose only outdoor image. Refer the link

https://developers.google.com/maps/documentation/javascript/reference#StreetViewSource

Here the relative ticket for nmap https://code.google.com/p/gmaps-api-issues/issues/detail?id=4831

**Comment by allenhwkim** [comment]
Still not fully understanding this issue. The following is a note for future development.

StreetViewPanorama options
https://developers.google.com/maps/documentation/javascript/reference?hl=en#StreetViewPanoramaOptions

StreetViewSource
https://developers.google.com/maps/documentation/javascript/reference#StreetViewSource

SreetViewSource is used by StreetViewLocationRequest

**Comment by pietromarrone** [comment]
From inside my office I cant use JsFiddle nor none of similar service (proxy settings), I'll wait when will work at home to send it.

**Comment by allenhwkim** [comment]
Closing soon if not active

**Comment by allenhwkim** [comment]
AFAIK StreetViewPanorama does not use StreetViewService , StreetViewSource, nor StreetViewLocationRequest. 

Closing this until Google provides options of StreetViewSource for StreetViewPanorama
