### ISSUE TITLE
Streetview not hitting the correct location?

### ISSUE THREAD

**Issue by ericyliu** [allenhwkim/angularjs-google-maps#361]
trying to use the street-view-panorama directive gives me a 404 request not found error

http://cbk0.googleapis.com/cbk?output=json&oe=utf-8&it=all&dmz=1&pmz=1&panoid=my-pano&cb_client=apiv3&v=4&hl=en-US&gl=US&callback=_xdc_._xj1lr0&token=110036

**Comment by allenhwkim** [comment]
Please add your example in plunker

**Comment by ericyliu** [comment]
I just copy and pasted the default sample code from here:
https://rawgit.com/allenhwkim/angularjs-google-maps/master/build/docs/streetview-panorama.html

http://plnkr.co/edit/JhDtmejkkdLG9MVC8FUR?p=catalogue

**Comment by allenhwkim** [comment]
duplicate to #354
