### ISSUE TITLE
Hi, I got grey map. Google map is displayed but the map itself is a grey box. what should I do?

### ISSUE THREAD

**Issue by kalitas** [allenhwkim/angularjs-google-maps#362]
HTML:
  `<div class="distribution">
    <div class="container-fluid">
       <map ng-transclude class='google-map'> </map>
    </div>  
  </div>`

CSS:
.google-map {  height: 500px }

I have no error on console...
update:when i set width as well to 500PX, map is displayed however i would like to have it all over the screen...
<img width="1439" alt="screen shot 2015-11-05 at 1 00 37 pm" src="https://cloud.githubusercontent.com/assets/149232/10966607/52132bec-83bd-11e5-9ad3-4960800d37b7.png">

**Comment by allenhwkim** [comment]
Please provide a plunker example

**Comment by smaier** [comment]
i think you need to trigger the redraw event from gmaps after document is ready

**Comment by allenhwkim** [comment]
please check this example

http://plnkr.co/edit/gWgyZ2J6WRUbVd6DF7yE?p=preview

Will be closed soon without user-provided plunker example
