### ISSUE TITLE
Invalid map-type object

### ISSUE THREAD

**Issue by andershagebakken** [allenhwkim/angularjs-google-maps#364]
Hi. I am trying to use this directive, but I am encountering an issue. I get the following error in console:
invalid map-type object – "<overlay-map-type object=\"imageMapType\" init-method=\"push\">"

I am trying the out-of-the-box example you provided on here: http://ngmap.github.io/maptypes.html#/maptype-image-overlay#maptype-image-overlay

Other examples, such as the basic example works fine.
The map is showing with the overlay-map-type tag, but the tiles are not loading, and the for mentioned error occurs in console. How can I fix this? Any help is very much appreciated. Thanks in advance.

**Comment by allenhwkim** [comment]
Thanks for reporting this bug

**Comment by allenhwkim** [comment]
This is fixed with 1.14 release, http://ngmap.github.io/#/maptype-image-overlay.html
