### ISSUE TITLE
Styling Not Working

### ISSUE THREAD

**Issue by realph** [allenhwkim/angularjs-google-maps#365]
Any reason why this Google Map Style Array doesn't work with the map?

https://snazzymaps.com/style/42/apple-maps-esque

**Comment by allenhwkim** [comment]
Please provide a plunker example

**Comment by realph** [comment]
@allenhwkim Added a [plunker here](http://plnkr.co/edit/LAQBgBu79Gy4cgDY9UXI?p=preview). The styles aren't being applied to it. It just defaults to the default Google Map style.

**Comment by allenhwkim** [comment]
Fixed
http://plnkr.co/edit/33hxaB?p=preview
Please close this issue if satisfied

**Comment by realph** [comment]
Awesome. Sorry, slight oversight by myself there.
