### ISSUE TITLE
Get marker info on drag end.

### ISSUE THREAD

**Issue by shotoreaper** [allenhwkim/angularjs-google-maps#366]
Hi!

Is possible get the marker´s information when I finish drag?

My code:

Html
```
<map center="{{center.lat}},{{center.lon}}"
      zoom="15"
      disable-double-click-zoom="true">
        <marker ng-repeat="info in information" 
        position="{{info.lat}}, {{info.lon}}"
        on-click="showInfoWindow(event, info)"
        animation="DROP" draggable="true"
        on-dragend="onDragEnd($event,info)"
        icon="./assets/svg/mark.svg"></marker>
</map>
```
Javascript
 ```
$scope.onDragEnd = function($event,info) {
        console.log($event); // Here I get the latLng
        console.log(info); // undefined
    };
```

**Comment by allenhwkim** [comment]
Yes, try this with plunker, and provide me the plunker example if it does not work

<map center="{{center.lat}},{{center.lon}}" zoom="15" disable-double-click-zoom="true">
        <marker ng-repeat="info in information" 
            info="{{info}}"
            position="{{info.lat}}, {{info.lon}}"
            on-click="showInfoWindow(event, info)"
            animation="DROP" draggable="true"
            on-dragend="onDragEnd()"
            icon="./assets/svg/mark.svg"></marker>
</map>

$scope.onDragEnd = function($event) {
        console.log($event); // event
        console.log(this.info); // marker
 };

**Comment by rodzod** [comment]
this was helpful for me, thaks

**Comment by niyando** [comment]
This might be totally off to this issue but how do I access $scope variables inside callback functions. In this case `onDragEnd`. Is this because callbacks run outside the scope of angular?
