### ISSUE TITLE
Cannot read property 'x' of undefined - on load and onscroll

### ISSUE THREAD

**Issue by smaier** [allenhwkim/angularjs-google-maps#367]
I Have a Angular Setup with ngMaterial.
On Pageload and each time i change the zoom-level of the map i get the console error:
Cannot read property 'x' of undefined
I even get this error after removing all other Angular-Modules and using the <map> from your example with the australian map... i dont get it

**Comment by allenhwkim** [comment]
Please provide me an example.

**Comment by allenhwkim** [comment]
Closing. if you can reproduce this issue with a plunker example, please let me know, so that I can reopen it.
