### ISSUE TITLE
Angular JS Error: 10 $digest() iterations reached. Aborting

### ISSUE THREAD

**Issue by realph** [allenhwkim/angularjs-google-maps#369]
I'm using [angularjs-google-maps](https://github.com/allenhwkim/angularjs-google-maps) and am getting an error when trying to loop over my customers as markers on a map.

    <map>
      <custom-marker ng-repeat="cust in customers" position="[ {{ cust.lat }}, {{ cust.lon }} ]">
        <div class="{{ cust.category }}">{{ cust.name }}</div>
      </custom-marker>
    </map>

The error seems to have something to do with `cust.category` and `cust.name`, as when I remove these they work fine.

This is the first couple lines of the error message I'm getting:

    Watchers fired in the last 5 iterations: [["[ cust.category , cust.name ]; newVal:
    [\"pro\",\"Fred\"]; oldVal: [\"pro\",\"Fred\"]","fn: function (context) {\n          
    try {\n for(var i = 0, ii = length, part; i<ii; i++) {\n

Full error message [here](http://pastebin.com/raw.php?i=gTaKHTJ6).

Any help with this is appreciated. Thanks in advance!

**Comment by allenhwkim** [comment]
Please provide a plunker example

**Comment by allenhwkim** [comment]
Closing, I do not know what happend, but please follow this example http://ngmap.github.io/#/custom-marker-ng-repeat.html.

**Comment by realph** [comment]
@allenhwkim I'm unable to provide a plunker example, the app is quite big and it's hard to pin down why it's happening.

My API is returning an array of objects, which is saved on `$scope.customers`, every object in `$scope.customers` looks like this:

    {
      "name": "Raphael",
      "category": "standard",
      "lat": 51.5318181,
      "lon": 0.0056104
    }
    ...

I'm able to successfully repeat over these customers using `ng-repeat` on the page:

    <li ng-repeat="cust in customers">{{ cust.name }}</li>

And I'm able to repeat over the custom markers, each with their correct position:

    <custom-marker
      ng-repeat="cust in customers"
      position="[ {{ cust.lat }}, {{ cust.lon }} ]">
      <div>name to go here</div>
    </custom-marker>

This doesn't produce any errors.

But once I add an Angular expression (`{{ cust.name }}`) to the `<div>` inside my `<custom-marker>`, then [this error](http://pastebin.com/raw.php?i=gTaKHTJ6) appears.

    <custom-marker
      ng-repeat="cust in customers"
      position="[ {{ cust.lat }}, {{ cust.lon }} ]">
      <div>{{ cust.name }}</div>
    </custom-marker>

**Comment by realph** [comment]
@allenhwkim Updating to a more recent version of Angular seemed to solve the issue. Was using 1.2, now I'm on 1.4.7.

**Comment by allenhwkim** [comment]
Thanks for letting me know. FYI, all examples are based on 1.3.15.
