### ISSUE TITLE
showInfoWindow is not available in $scope when used with ionic

### ISSUE THREAD

**Issue by rakesh1988** [allenhwkim/angularjs-google-maps#370]
Firstly this is not an issue :) and thank you so much for enabling google maps via angular. I am currently using ionic and ng-map. I would like to display multiple markers and based on the marker clicks, display a infoWindow.

There is clearly no problem to achieve the above when used with plain AngularJS. But when I use ng-map with ionic's Angular bundle, showInfoWindow ($scope.showInfoWindow.apply) function is not available with $scope. (ERROR: Cannot read property 'apply' of undefined)

Could you please help me with some pointers in resolving this issue.

**Comment by allenhwkim** [comment]
Please provide me a plunker example

**Comment by rakesh1988** [comment]
http://jsfiddle.net/rakesh1988/1yw756zg/
I was not able to get this fiddle to work.. may be because it needs ionic included..

**Comment by rakesh1988** [comment]
http://plnkr.co/edit/wuRwR7FJcMwrp21wqQnP?p=preview

this works.. didnt know plunkr was so good :+1:

**Comment by allenhwkim** [comment]
There is a slight change in 1.14. This is fix with 1.14.
http://plnkr.co/edit/5JuQlZAqRQPydVkQNKK0?p=preview

Please close this ticket if all good

**Comment by rakesh1988** [comment]
Thank you so much for your help.

**Comment by allenhwkim** [comment]
Please add a star if you recommend to others.
