### ISSUE TITLE
JavaScript runtime error: 'google' is undefined

### ISSUE THREAD

**Issue by vangraan** [allenhwkim/angularjs-google-maps#371]
I'm trying to use this in my Cordova project.

I add the following in my index file.

    <script src="http://maps.google.com/maps/api/js?sensor=false"></script>
    <script src="scripts/ng-map.min.js"></script>

I get Unhandled exception at line 1, column 5813 in ms-appx-web://io.cordova.myapp02769b/www/scripts/ng-map.min.js
0x800a1391 - JavaScript runtime error: 'google' is undefined

**Comment by allenhwkim** [comment]
It's working fine.

You may load http from https. 
http://rawgit.com/allenhwkim/angularjs-google-maps/master/testapp/map-simple.html

If that does not solve, please provide me a plunker example
