### ISSUE TITLE
Map height always 300px??

### ISSUE THREAD

**Issue by mathisjay** [allenhwkim/angularjs-google-maps#372]
This is new.  I had a map set to 100% height, now it is 300px.  Even the map on the demo page is 300px.

What's up?

**Comment by allenhwkim** [comment]
This happened with 1.14 release. I  made it as `default-style` as `true` in default. 
You can override it with `default-style="false"` until I make a fix.

**Comment by mathisjay** [comment]
Awesome. Thanks!  That fixed it.

**Comment by Tallyb** [comment]
Seems that the default-style="false" does not work - still getting 300px
