### ISSUE TITLE
Your recent changes have broken Angular 1.x

### ISSUE THREAD

**Issue by jorgeabarrera** [allenhwkim/angularjs-google-maps#374]
Your recent changes have broken Angular 1.x. Info windows are broken, default-style now used where it wasn't before. I am sure there are many others I haven't discovered yet.

I believe the last good version for  Angular 1.x is angularjs-google-maps-1.13.15

**Comment by allenhwkim** [comment]
Sorry. I had to make some changes for Angular 2, and missed some backward compatibility. The following is the changes that I made. The main change was to remove the usage of `scope`

![image](https://cloud.githubusercontent.com/assets/1437734/11085409/019f4b04-8814-11e5-939c-6d39ff7d40a1.png)

**Comment by jorgeabarrera** [comment]
Thanks for the update. And thanks for your work on ng-map. 

We change our code to use angularjs-google-maps-1.13.15, which is good for Angular 1.x
