### ISSUE TITLE
Shouldn't 1.14 really be 2.0?

### ISSUE THREAD

**Issue by simonh1000** [allenhwkim/angularjs-google-maps#380]
There seems to be a complete change in the API (promises are great, don't get me wrong), and the 'mapInitialized' event I relied upon seems have gone?

**Comment by allenhwkim** [comment]
Hi @simonh1000 
'mapInitialized' is still working as well as $scope.map, but those are deprecated.

1.14 is the prepration of angular 2 migration, but not 2 yet.

All the features you are using should be available, unless I miss something.

* $scope.map is deprecated, but still available
* $scope.$on('mapInitialized', function(event, map) {..} is deprecated, but stiill available
* $scope.showInfoWindow(id) is deprecated, but still available
* map tag is deprecated, but still available
