### ISSUE TITLE
Set Styles in Controller

### ISSUE THREAD

**Issue by realph** [allenhwkim/angularjs-google-maps#381]
Is it possible to set the styles in the controller instead of setting them on the styles attribute in the HTML, as to not bloat the views?

**Comment by allenhwkim** [comment]
Yes, not in the controller but use your own css. set `default-style="false"`, and apply your own style.

**Comment by realph** [comment]
@allenhwkim The styling I've got is a JS array and won't work in a CSS file. Is there something I'm missing...

**Comment by allenhwkim** [comment]
Well, you can style any DOM in your javascript.
![image](https://cloud.githubusercontent.com/assets/1437734/11120597/ed1bc098-891e-11e5-99fc-c39989f6e4c3.png)

However, I do not recommend to update DOM in your controller. It's not a good practice

If you insist, you can get map div by;

1. document.querySelector('ng-map div')
2. or, map.getDiv()
