### ISSUE TITLE
ngMap issue when used inside ng-view

### ISSUE THREAD

**Issue by kgignatyev** [allenhwkim/angularjs-google-maps#382]
When ng-map is used inside ng-view then first time map is initialized properly with NgMap.get.then but when we come back to the same view we see empty map.

Here is plunk to illustrate problem, please click on About and see USA map, then click on Contact, and then on About again to see the problem

http://embed.plnkr.co/ABwxa4/preview

Any solutions? Workarounds?

**Comment by allenhwkim** [comment]
Thanks for reporting this.  TL;DR; this is the working version. http://plnkr.co/edit/6Y6LIIdoXmg5DOTrfXfv?p=preview

I see your code do like this. 
```
  NgMap.getMap().then(function(map) {
    var latlng = new google.maps.LatLng(40, -110);
    map.setCenter(latlng);
    map.setZoom(4);
  });
```
Also you provided html like this
```
<ng-map>
</ng-map>
```
Here is the sequence.
1. ng-map is initialized with no center, then launch asynchronous geocode to search center.
2. Then, your Javascript is executed and set center
3. geocode failed, and set the center again to 0,0

You don't have to do this with ng-map. You just put all required fields into ng-map as attributes. That's it. No Javascripting is required for static map.

```
<ng-map center="40,-110" zoom="4">
</ng-map>

```

**Comment by kgignatyev** [comment]
The code is simplified, I actually do more with map directly, and when I
try to interact with map I got second time it seems to be a different
instance than displayed. You can see for yourself if assign map within then
block to s window variable.

**Comment by kgignatyev** [comment]
I have added the code to plunk
http://run.plnkr.co/plunks/ABwxa4/#/about 
click on Contact, then About and then in console you can interact with window.map to try to set center or zoom, and you will see that it will have no effect on the displayed map.

**Comment by allenhwkim** [comment]
If you want to set center dynamically, use it with lat/lng instead of no center given.
Without center given, it try to use geocode, becasue it has no idea you are setting center by your javascript.

**Comment by kgignatyev** [comment]
I think issue has different root. Please look at the updated plunk. I have added 'set center' button that works with window.map that is set by then() function. First time it works, when you view is rendered second time (click Contact, then click About) it does not work. It seems like directive is keep creating maps and new map but get() always returns map with id=0, which is no longer attached to the div that visualizes it.

**Comment by allenhwkim** [comment]
You are right.   window.map.getDiv() does not link to the actual DOM.

**Comment by allenhwkim** [comment]
Fixed this bug by removing a map when element is removed.

Here is the working example. http://plnkr.co/edit/VvGzuNBtSVBe0ItoMNG2?p=preview

However, you need to add id to the map, and getMap with id as given by example

**Comment by kgignatyev** [comment]
Thank you! That seems to work. Is there a way to make it work simpler? Maybe by providing a callback function as an attribute  to ng-map that will get called when map for this particular tag is ready. IMO that would be more inline with the spirit of directives in angular. What do you think?

**Comment by allenhwkim** [comment]
It's a good idea. I am thinking of `map-initialized="CALLBACK"`.

e.g.
   `map-initialized="callback(map)"`.

**Comment by kgignatyev** [comment]
That would be just perfect!

**Comment by allenhwkim** [comment]
1.14.14 release included `map-initialized`. Example http://ngmap.github.io/#/map-initialized-callback.html

**Comment by kgignatyev** [comment]
Works perfectly, thank you!

**Comment by dmackerman** [comment]
This still only fires one time. Subsequent calls to `mapInitialized` don't return a map. Very confused.

**Comment by allenhwkim** [comment]
@dmackerman , please open a new issue for this. closing it.
