### ISSUE TITLE
Reference to directives fail after minification using uglify

### ISSUE THREAD

**Issue by roybekhuis** [allenhwkim/angularjs-google-maps#383]
First of all thanks for the nice directive which works awesome on my dev environment.
I am using https://github.com/DaftMonk/generator-angular-fullstack for my project and included the latest version [1.14.10] of angularjs-google-maps.

After building my dist [grunt build:dist] all the references to the ngmap directives seem to by corrupt, probably by uglifying the code.

![image](https://cloud.githubusercontent.com/assets/13818041/11143087/bdd12b6e-89f2-11e5-98d5-bb60422ccc67.png)

In my view i have:
<ng-map style="height:100%" zoom="7" center="[{{vm.map.location.latitude}},{{vm.map.location.longitude}}]" disable-default-u-i="true"></ng-map>

In my controller:
'use strict';
angular.module('app').controller('MainCtrl', function (NgMap) {
NgMap.getMap().then(function(map) {
			bounds = map.getBounds();
			map.setZoom(7);
});

in my none uglified enviroment everything works, also using version 1.13.0 works. All versions after break on minification. Hopefully someone can give me some directions to proper inject ngmap and it's directives.

**Comment by roybekhuis** [comment]
It seems all local variables e.a. _$windows_ are broken after building dist. Am i Doing something wrong?

**Comment by allenhwkim** [comment]
It seems working fine with minified version.
http://plnkr.co/edit/GErhxRRm1gWsGsHCT6WY?p=preview.

Are you using the recent 1.4.* version?

**Comment by roybekhuis** [comment]
@allenhwkim thanks for your reply. I think understand what happens, by grunt build:dist the non minified version gets minified and breaks. If I exclude ngmap from bower.json and refer to your minified version in the index it all works fine. 
Any clue how to prevent this to happen? 
Thanks again!

**Comment by allenhwkim** [comment]
No idea, I only use `gulp`. so someone using `grunt`, please help here.

**Comment by roybekhuis** [comment]
I've tried to debug it with no luck so far and decided to bypass the grunt build.
For those reading this with the same problem and need a solution. Exclude ngmap in bower.json so the grunt process of angular fullstack is not minifiying. Refer in index.html like this           
<script src="bower_components/ngmap/build/scripts/ng-map.min.js"></script>
[make sure it's after the 

I know it's not the best solution, but it's working now. If someone knows a proper solution please let me know.

@allenhwkim thanks again. You can close this iddue if you like.

**Comment by allenhwkim** [comment]
Tested with gulp-usemin, and all seems working fine.
```
<!-- build:js myapp.min.js-->
<script src="lib/angular.js"></script>
<script src="build/scripts/ng-map.min.js"></script>
<!-- endbuild -->
```
output
```
<script src="myapp.min.js"></script>
```
