### ISSUE TITLE
NgMap.getMap() always returns the first map

### ISSUE THREAD

**Issue by cogidoo** [allenhwkim/angularjs-google-maps#385]
In many directives, like `info-window` you have something like this:
```javascript
NgMap.getMap().then(function(map) {
  ....
  map.showInfoWindow = ....function(p1, p2, p3) { ....
```
It works like expected as far as you don't have multiple maps. We have one map at the page and another one within a modal. Both maps use the infowindow-directive with ngClick, but when you want to open an info-window at the modal you get an error:
```
this.map.showInfoWindow is not a function
```
Reason is, that for the second map the lines at the top were never executed, because `NgMap.getMap()` always returns the first map.
I think for the info-window-directive calling `NgMap.getMap(options)` would do the trick.

**Comment by stshmms** [comment]
+1

**Comment by allenhwkim** [comment]
Please use options to get a specific map.
`NgMap.getMap()` always works as  `NgMap.getMap(0)`. 

```
    NgMap.getMap({id:'foomap'}).then(function(map) {
      map.setZoom(4);
    });
```
http://ngmap.github.io/#/ui-router.html

**Comment by allenhwkim** [comment]
Please close this ticket if you are ok with using options

**Comment by shvelo** [comment]
There is a problem with setting the map id with a variable, like `<ng-map id="{{mapId}}>`

**Comment by allenhwkim** [comment]
mapId shouldn't be dynamic

**Comment by flc** [comment]
Hi @allenhwkim 
What if I have to show map instances in an ng-repeat loop? How do you set the map id not dynamically in that case?
In my use case I have to show undefinit number of map instances in a view and eventually call their fitBounds functions. Do you have any idea how to achieve that?

**Comment by rishab-yumist** [comment]
@allenhwkim I'm using ng-loop to show maps within a panel. On click, I want to retrieve the map. My ids are dynamic in nature.

**Comment by chalcrow** [comment]
You _can_ now use dynamic map id's to identify different maps. So, you can assign the unique scope id to the map, for each instance of your map directive, and then reference the map in your controller using that id. You'll need to do something like this to dynamically set the id on the map directive itself:

<ng-map id="{{'map-' + mapsCtrl.$scope.$id}}" 

> Note: you _can't_ do the following when outputting the id (i.e. append something dynamically to the id name) - this will break the dynamic id assignment and the id won't be recognised in your angular code:
> 
> <ng-map id="map-{{mapsCtrl.$scope.$id}}}}"
> 

To reference the map in your controller code, you can then reference like this (I'm using the ES2015 class syntax to define my controller):

class mapsCtrl {
  constructor(...) {
            this.mapId = {};
            this.mapId.id = "map-" + this.$scope.$id;

.... and then when you need to reference the map:

NgMap.getMap(this.mapId).then(.....
