### ISSUE TITLE
Google Maps reload not propagated to the CustomMarker class

### ISSUE THREAD

**Issue by stshmms** [allenhwkim/angularjs-google-maps#386]
If I reload the Google Maps API with another language while I placed CustomMarkers on the map, I get instanceof errors:
```
js?v=3.exp&language=EN:34 Assertion failed: InvalidValueError: setMap: not an instance of Map; and not an instance of StreetViewPanorama
```
The ```js?v=3.exp&language=EN``` is the old loaded API.
I reload the API like the example does: http://jsfiddle.net/2AKqM/

A fix is to call the ```setCustomMarker();``` function in the compile function of the directive. After that all errors are gone. And the CutsomMarker class inherits from the right API class.

**Comment by ajh123** [comment]
+1

**Comment by allenhwkim** [comment]
I will do this time, but please send me a pull request next  time for this simple change.
btw, thanks for reporting this.

**Comment by stshmms** [comment]
Thanks. I will send a pull request it next time.
