### ISSUE TITLE
init-event not waiting

### ISSUE THREAD

**Issue by Vandersteen** [allenhwkim/angularjs-google-maps#387]
Hello everyone,

I am trying to make use of the init-event directive but the map loads anyway on startup.

my html:

```
  <ng-map init-event="MapDataReady" default-style="false" zoom-to-include-markers="true">
      <div ui-view="map"></div>
  </ng-map>
```

Removing or adding the init-event does not change the behaviour of the map (loading of it I mean).

Do I use it in a wrong way ? What am I missing ?

**Comment by allenhwkim** [comment]
Thanks for reporting this. Release 1.14.0 removed all usage of $scope including $scope.$emit and $scope.$broadcast. 

There is a new way. and please follow this example. http://plnkr.co/edit/mcZ2Ov4OLvA4jAuPaoZT?p=preview / http://ngmap.github.io/#/map_lazy_init.html

Sorry for the confusion again.

**Comment by Vandersteen** [comment]
Thanks a lot for the fast response ! And great job on this plugin !

**Comment by Vandersteen** [comment]
I have one last issue with this, in my controller I inject NgMap:

```
function Controller(NgMap, $http) {

 //Fetch the data
$http.get('url')
.then(function(data) {

    //Data fetched successfully
    NgMap.initMap('mapId');

});

}
```

gives me the following error:

```
TypeError: Cannot read property 'initializeMap' of undefined
    at Object.initMap (ng-map.js:2692)
    at map.controller.js:21
    at processQueue (angular.js:14745)
    at angular.js:14761
    at Scope.$eval (angular.js:15989)
    at Scope.$digest (angular.js:15800)
    at Scope.$apply (angular.js:16097)
    at done (angular.js:10546)
    at completeRequest (angular.js:10744)
    at XMLHttpRequest.requestLoaded (angular.js:10685)
```

In your example I noticed that you bind NgMap to the $rootScope, I doubt that could / would be the issue but wanna be sure before I start debugging.

**Comment by Vandersteen** [comment]
I am using map-lazy-load aswel, could that have something to do with it ?

**Comment by allenhwkim** [comment]
1. Use the most recent release, i.e.,  1.14.13
2. `$http.get` is asynchronous, and `map-lazy-load` is also asynchronous. You might have a racing condition.

To avoid racing conditoin, you ou can wrap $http.get within `NgMap.getMap().then(..`, to avoid racing condition.

Please provide me a plunker example if you need further questions.

**Comment by Vandersteen** [comment]
When using `lazy-init` makes `NgMap.getMap.then()...` to never resolve (which is to expected).

Updating NgMap made it work with:

```
$http.get()
        .then(function() {
         NgMap.initMap();
        });
```

Thanks for your time ! (I believe this issue can get closed)

**Comment by solidevolution** [comment]
Trying to load the google api (it could be down, so I want it async) and the async my maps with "lazy-init="true"

If I do initMap('myMap') in my controller - the directive cannot find the lazy-init map:

Cannot read property 'map' of undefined

If I do getMap('myMap') in my controller - the directive doesn't wait for google:

could not find map

Is there a possibility to load the map only if the callback from google appears? We use the map only as additional filter to an list, so we want an running application if the map is down.

**Comment by TimoPerplex** [comment]
@solidevolution, I had the same problem (also with map-lazy-load).
My solution for this problem was:

            NgMap.getMap("map").then(function(){
                // Initialize the Google map
                vm.map = NgMap.initMap("map");
            });

getMap gets the required variable, after that is defined you can call the initMap function.
