### ISSUE TITLE
refresh map not working

### ISSUE THREAD

**Issue by knodeit** [allenhwkim/angularjs-google-maps#388]
I'm displaying a map with some markers fetch via AjaxService and that renders all ok

HTML

 <ui-gmap-google-map center='map.center' zoom='map.zoom' control="map.control" >
        <ui-gmap-marker  ng-repeat="marker in markers" coords="marker.coords" options="marker.options" idkey="marker.idkey" >
    </ui-gmap-google-map>

JS Controller

 $scope.OndemandAclService = OndemandAclService;
        $scope.map = { center: { latitude: 35.046772, longitude: -85.308863 }, zoom: 12 };
        $scope.markers = markers;
        refresh();
        $scope.control = {};

        uiGmapIsReady.promise().then((function (maps) {
            $scope.map.control.getGMap();

        }))

        function refresh() {
            var timer = null;
            startTimer();
            function startTimer() {
                setInterval(refreshData, 5000);
            }

            function refreshData() {
                $scope.markers = OndemandKNMapService.getMarkers();
                $scope.map.control.refresh({ latitude: 35.046772, longitude: -85.308863 });
                clearTimeout(timer);

            }

        }

On initial load the markers are shown correctly (after resolve with initialising router) but on refresh() they are gone

**Comment by allenhwkim** [comment]
Wrong repository.
FYI, this is the working example. http://ngmap.github.io/#/marker_dynamic_ng_repeat.html
