### ISSUE TITLE
Have no idea how to provide center coordinates dynamically

### ISSUE THREAD

**Issue by aki-russia** [allenhwkim/angularjs-google-maps#391]
```
<ng-map center="[{{ a }}, {{ b }}]"><ng-map>
```
— Just not works.

Do I have to provide them always as string without ng expression?

**Comment by allenhwkim** [comment]
try this `<ng-map center="{{ a }}, {{ b }}"><ng-map>`

**Comment by aki-russia** [comment]
Not works also.
I read sources and it is because there is no evaluation of expressions from `center` attr in map controller

**Comment by allenhwkim** [comment]
Please provide me a plunker example. 
This example works fine, http://ngmap.github.io/#/map_with_dynamic_center.html

**Comment by aki-russia** [comment]
I have no idea, it works in your plunker. And today get working in my project, but from time to time. I'll provide plunker after I understand the reason why it happening. 
Only have screenshot from project page:
<img width="1256" alt="screenshot 2015-11-17 10 48 09" src="https://cloud.githubusercontent.com/assets/449604/11202451/f1055642-8d1a-11e5-9c1a-f6df6639c47e.png">

**Comment by larissaleite** [comment]
I am having the same problem :( any ideas on how to fix this?

**Comment by cristianounix** [comment]
@larissaleite you can fix this ?

**Comment by Steven-Chang** [comment]
if (navigator.geolocation) {
    	navigator.geolocation.getCurrentPosition(function(position){
      	$scope.$apply(function(){
        	$scope.position = position;
      	});
    	});
  	}

**Comment by tedpennington** [comment]
Ran into a similar problem.  For me it was that I was using `center=` on my marker tag instead of ng-map.  
This code is working, and provides a drag-able marker w/ function to run on that event:
`<ng-map center="[{{latitude}}, {{longitude}}]">
    <marker position="{{latitude}},{{longitude}}" draggable="true" on-dragend="getCurrentLocation()"></marker>
</ng-map>`

**Comment by isaacSolano** [comment]
how can I get the coords when moving the marker?

**Comment by phuwin** [comment]
@isaacSolano 
```
<marker position="[40.74, -74.18]" centered="true" draggable="true" on-dragend="vm.getMarkerLocation()"></marker>
```

````
    vm.getMarkerLocation = function(){
        var lat = this.position.lat()
        var lng = this.position.lng()
        console.log(lat,lng)
    }
````
