### ISSUE TITLE
iOS 9 searchbox

### ISSUE THREAD

**Issue by HarunOr** [allenhwkim/angularjs-google-maps#392]
Hi, since I am using iOS 9 for my emulator, 

the places autocomplete function doesn't work. Thought it might be because of https, but the weird thing is that the map is showing properly, its just the search box.

The searchbox is working on Android and Desktop, it's just iOS 9..

-I am using Ionic, Angular

Any suggestions ?

**Comment by allenhwkim** [comment]
Can you reproduce your issue with plunker?

**Comment by HarunOr** [comment]
Here you go: http://plnkr.co/edit/0Y8Mn66rvGDMbnCsncAB?p=preview

**Comment by allenhwkim** [comment]
I think this issue is out of scope. 

* http://vedanova.com/tech/2014/11/24/google-maps-places-autocomplete-bug-on-ios.html
* https://github.com/driftyco/ionic/issues/1798

**Comment by HarunOr** [comment]
Thanks for your response, 

but the problem is still there, I don't think it is related to scope, since it is working on other platforms. 
Maybe it is related to iOS9 blocking non-HTTPS connections, which prevents the searchbox to run google predictions, because it won't show any ?
