### ISSUE TITLE
bootstrap tabs problem

### ISSUE THREAD

**Issue by cemkaya** [allenhwkim/angularjs-google-maps#395]
Google maps doesn't initialize on tabs. Any solution ?

**Comment by lluiscanals** [comment]
see #347

**Comment by cemkaya** [comment]
Thanks that's solved the problem.

**Comment by lluiscanals** [comment]
Perfect! :+1:  close this if its ok.

**Comment by allenhwkim** [comment]
Thanks @lluiscanals 

There is also an example on ngMap.github.io. Please search with "router"
