### ISSUE TITLE
lazy-init and ng-show not loading markers

### ISSUE THREAD

**Issue by poppahorse** [allenhwkim/angularjs-google-maps#396]
Having some issues getting a map with markers working properly. Its not loaded initially, as its a viewmode for a list of results, so to prevent the grey map issue I am using `lazy-init`.

The markers are `ng-repeat` however it seems to have to the same issue when they are static. When the map is initiated they wont load.

Also getting this in the console `InvalidValueError: setMap: not an instance of Map; and not an instance of StreetViewPanorama`

http://plnkr.co/edit/krjy7BSP2qJ4IBuXu1dT?p=preview

The issue seems to be lazy-init rather than the ng-show. Any ideas?

**Comment by allenhwkim** [comment]
it seems like a bug. I will take a look at it.

**Comment by poppahorse** [comment]
thanks for the speedy response :) and loving ngmap so far!

**Comment by allenhwkim** [comment]
@poppahorse thanks. worth adding to your starred repo.?

**Comment by poppahorse** [comment]
have starred :+1: any news on that bug fix? I was hoping to go live on this project in about a week

**Comment by allenhwkim** [comment]
busy, busy, I haven't looked at it yet. Sorry about that.

**Comment by poppahorse** [comment]
Cool, I have a go live of the 7th, so if it can be done before then that would be legendary, if you don't think you will get to it in time, if you can let me know and I will try and make other arrangements / see if the client doesn't mind going live without the maps

Thanks again!

**Comment by allenhwkim** [comment]
released with 1.14.16. Thanks for your patience

**Comment by poppahorse** [comment]
thanks @allenhwkim works like a charm :)
