### ISSUE TITLE
Binding user-editable shape parameters to DOM elements

### ISSUE THREAD

**Issue by joshkopecek** [allenhwkim/angularjs-google-maps#397]
Hey I'm having problems binding user-editable shape coordinates (any parameters) to user elements within the DOM. Please take a look at this Plunker:

http://plnkr.co/edit/Nte0YmcTH6pdh1oXYtqo?p=preview

I've managed to get the shapes to 'refresh' by removing them and readding them to an array when using `ng-repeat`, but I haven't managed to get the coordinates of a shape to bind to DOM/`$scope` elements.

**Comment by allenhwkim** [comment]
There is no automatic binding from map to $scope.

i.e., $scope -> map binding does exist, but there is no map -> $scope binding.

To make it possible, you need to use map event to do data binding manually. 

Example here, http://ngmap.github.io/#/rectangle-event.html

**Comment by joshkopecek** [comment]
Thanks for the example, that's fantastic! Ok, I managed to pull data from events for circle radius and centre, but I was struggling with the correct event for polylines and polygons - do you have an example for this?

**Comment by allenhwkim** [comment]
check this and use one of the event. e.g. `on-dragend=myFunc()`

https://developers.google.com/maps/documentation/javascript/reference#Polyline
https://developers.google.com/maps/documentation/javascript/reference#Polygon

**Comment by joshkopecek** [comment]
Nice, ok I'll dig a bit further and let you know how I get on. Thanks for all your help :-)
