### ISSUE TITLE
Map not loading when in a route without window resize

### ISSUE THREAD

**Issue by edinchez** [allenhwkim/angularjs-google-maps#399]
I know this isn't an issue with the directive itself, but with the way Angular loads it, or how I'm implementing it? I should also note that I'm a beginner at Angular.

Basically the map is in a route, and when I go to the route, the map is completely gray, and stays like that until I resize the window. That's when it appears/loads.

Also I can't seem to load the styles through "NgMapProvider.setDefaultOptions".

Help please?

**Comment by allenhwkim** [comment]
Please check out the following examples,

http://ngmap.github.io/#/ui-bootstrap.html
http://ngmap.github.io/#/ui-router.html

Basically, if your google map is within a hidden element, the map is initialized with 0px width and 0px height. Then when it is fully sized, map does not follow DOM size. 

If your map is not in hidden element, it's all good. 

If the above case is not your case, and the given example does not solve your case, please create a plunker example and provide here.

**Comment by edinchez** [comment]
Hmm. RawGit seems to be down and clicking on "Run In Plunker" doesn't do anything.

**Comment by edinchez** [comment]
That's weird. When I do it in the same way in a Plunker it works fine, but not on my project. Here's the Plunker:

http://plnkr.co/edit/07DVa1tvlCWFfgmAkSHl?p=preview

I'm guessing there's something else breaking it. Is there any way I can "reload" the map on the route's onEnter function?

**Comment by allenhwkim** [comment]
This may helps you.

http://stackoverflow.com/questions/30443918/ng-map-shows-partial-map-in-html

```
  google.maps.event.trigger(map,'resize');
  map.setCenter(new google.maps.LatLng($scope.location.latitude, $scope.location.longitude));
```

**Comment by edinchez** [comment]
Where exactly do I include that code? I tried in both the state's controller and its onEnter function, it keeps giving me the `ReferenceError: google is not defined` error on both.

Thanks a lot for helping out by the way!

**Comment by allenhwkim** [comment]
Your html should have google maps script tag. Include those line within the block of NgMap.getMap
