### ISSUE TITLE
Demo website broken

### ISSUE THREAD

**Issue by Jonfor** [allenhwkim/angularjs-google-maps#401]
The demo website, https://ngmap.github.io/, is broken on the latest Firefox and Chrome due to retrieving http content on an https website. See my picture for the error messages. The fix is to simply load the content over https instead of http.

![ngmap_error](https://cloud.githubusercontent.com/assets/3246528/11376963/917f78d2-92b1-11e5-8829-54cabd814cbd.PNG)

**Comment by allenhwkim** [comment]
Will change to https. Meanwhile please use http site.

**Comment by allenhwkim** [comment]
Thanks for reporting this. Fixed and closing
