### ISSUE TITLE
script-tags-for-development.js is empty.

### ISSUE THREAD

**Issue by Jonfor** [allenhwkim/angularjs-google-maps#402]
Why is there nothing in the script-tags-for-development.js file? I see there is another file with the same exact name in the testapp folder that adds all the scripts but it is completely blank at the top level. Should it be deleted?

**Comment by allenhwkim** [comment]
I do not understand. That.js does document.write all files. If you see the source, you should see document.write block

**Comment by Jonfor** [comment]
Here is the empty script-tags-for-development.js at the root level. In the testapp folder, however, it has the document.write block as you said.
![ngmap_empty](https://cloud.githubusercontent.com/assets/3246528/11405796/2bd6c37e-9378-11e5-9d0a-01bd9748c6fa.PNG)

**Comment by allenhwkim** [comment]
That might have mistakenly committed to root level. It should be removed.

**Comment by allenhwkim** [comment]
Deleted the file. Will be tagged with later release.
