### ISSUE TITLE
Issue on reload map on url param change 

### ISSUE THREAD

**Issue by majitimir** [allenhwkim/angularjs-google-maps#404]
Hi , I am getting an issue on map loading 

First lime when i am loading 
http://59.162.181.92/dtswork/bluejaypt/ptnew/referralpages/index.html#/referralmapsearch/4800/0.000000/0.000000/ptLanguageId:all;ptPracticeAreaId:2/distance/0

its loading properly

but now if i change one parameter (;ptPracticeAreaId:1) and hit enter , then page is blank 

http://59.162.181.92/dtswork/bluejaypt/ptnew/referralpages/index.html#/referralmapsearch/4800/0.000000/0.000000/ptLanguageId:all;ptPracticeAreaId:1/distance/3.11.2

Here i attaching html and controller file 

Please help me out is very urgent

**Comment by allenhwkim** [comment]
I do not usually debug someone's application, but you said it's urgent. So this may help.

When you first init. your page. your ng-view div section has a height
![image](https://cloud.githubusercontent.com/assets/1437734/11454593/5b7c2d06-95ff-11e5-89be-fd6ba1e446f9.png)


When you change your url and hit.  it does not reload from the server, and some reason your page. your ng-view div section does NOT have height
![image](https://cloud.githubusercontent.com/assets/1437734/11454594/695393f6-95ff-11e5-9744-7cbeb8ba33bd.png)


So setting the height correctly will make a fix

![image](https://cloud.githubusercontent.com/assets/1437734/11454598/7651f0ca-95ff-11e5-80d6-f2139e336fbd.png)

**Comment by majitimir** [comment]
Thanks a lot
