### ISSUE TITLE
Problem with Drawing

### ISSUE THREAD

**Issue by charleston10** [allenhwkim/angularjs-google-maps#407]
I've a problem with library. 
My Map is worked when I not use a drawing, but when use the layout break.
I put coordinates to create the drawing [2 points of location] and refresh the map to work.. but.. 
I attached the image. 
Someone help me?

Image of problem
https://a.disquscdn.com/uploads/mediaembed/images/2851/2709/original.jpg

**Comment by charleston10** [comment]
My code
```javascript
<div map-lazy-load="http://maps.google.com/maps/api/js?v=3.20&client={{vm.googleApiKey}}">
			<map center="[{{vm.myPosition}}]" zoom="11">   			
				<shape data-ng-repeat="data in vm.data"
					name="circle" 
					stroke-color="#2a88bd" 
					stroke-opacity="0.7" 
					stroke-weight="2" 
					fill-color="#2a88bd" 
					fill-opacity="0.35" 
					center="{{data.location.latitude}},{{data.location.longitude}}" 
					radius="{{data.location.radius}}">
				</shape> 
			</map>
		</div>

```

**Comment by allenhwkim** [comment]
please add a plunker example for it

**Comment by charleston10** [comment]
I tested in plucker and worked.. I believe that can be problem in my scopes of angular.
Thanks by help you and attention.

This library It helped me a lot
