### ISSUE TITLE
zoom controls went missing

### ISSUE THREAD

**Issue by belfz** [allenhwkim/angularjs-google-maps#408]
Hello,

I'm using ngMap and up until now, the zoom controls used to display fine using the attribute below:
```zoom-control-options="{position:'LEFT_TOP', style:'DEFAULT'}"```

for some reason, the zoom controls are no longer displayed (since past few days).

Could it be caused by the size of the map (its 542px * 156px)? Did something change on the Google?

**UPDATE:** looks like the zoom controls are displayed correctly when the map is at least 205px high. Is there any way to force it to display the controls on smaller map?

**Comment by allenhwkim** [comment]
According to this https://developers.google.com/maps/documentation/javascript/controls#DefaultControls, I don't think I can control that. You can make at least 200px height.
ngMap does not make its own behaviour, it just makes Google maps conveniently enabled using AngularJS.

**Comment by allenhwkim** [comment]
No, it's by Google. I don't think we can avoid min. height set by Google.

**Comment by belfz** [comment]
Thanks!
