### ISSUE TITLE
ng-map dies if no google property is present on window

### ISSUE THREAD

**Issue by stshmms** [allenhwkim/angularjs-google-maps#409]
Please, add a check for availability of google maps in the current window and log a warning if it isn't and do not cause a error.

Possible error sources (1.14.12): 
line 134:
```
vm.initializeMap = function() {
      var mapOptions = vm.mapOptions,
          mapEvents = vm.mapEvents,
          ngMapDiv = vm.ngMapDiv;

      vm.map = new google.maps.Map(ngMapDiv, {});
```
line 188:
```
$scope.google = google; //used by $scope.eval to avoid eval()
```
line 395:
```
 var setCustomMarker = function() {

    CustomMarker.prototype = new google.maps.OverlayView();
```

if I have enough time in the next days for a pull request, I will provide a fix for that.

**Comment by allenhwkim** [comment]
Please use map-lazy-load for that if your app does not require consistent Internet connection. 
Here is the example. https://ngmap.github.io/#/map-lazy-load-params.html

Checking `google` variable is also an idea, and please send me a pull request.

**Comment by allenhwkim** [comment]
Can I close this?

**Comment by stshmms** [comment]
Yes! When I get time for a pull request, I send one. Meanwhile the issue can be closed.
