### ISSUE TITLE
customising map

### ISSUE THREAD

**Issue by rakesh1988** [allenhwkim/angularjs-google-maps#411]
I would like to know if it is possible to remove street view, satellite view and map view selection buttons on the map.
Using google maps api this can be done when initializing the map
{
  zoomControl: boolean,
  mapTypeControl: boolean,
  scaleControl: boolean,
  streetViewControl: boolean,
  rotateControl: boolean
}

**Comment by allenhwkim** [comment]
Take a look at this
http://ngmap.github.io/#/map_control.html
Just set it to `false` that anything you don't want it.
