### ISSUE TITLE
<info-window> directive hides the map

### ISSUE THREAD

**Issue by Spittal** [allenhwkim/angularjs-google-maps#414]
```
<ng-map center="kelowna" zoom="6">
    <marker ng-repeat="office in officeMapVM.offices" position="{{office}}" label="A"></marker>
  </ng-map>
```

This works fine, the map is totally visible and functional. However

```
<ng-map center="kelowna" zoom="6">
    <info-window visible="true" id="1" position="vancouver">
      <h1>Hello</h1>
    </info-window>
  </ng-map>
```

This fails to show the map, I can see that all the DOM elements are there but the height of the actual map element is set to 100% which resolves to zero pixels (if the parent is not set to a fixed height). Forcing a height on the parent removes the responsive-ness of the map and is not a good solution.

**Comment by allenhwkim** [comment]
It happens becasue the height of ng-map is bigger than 0 because of info-window. You can set 
`default-style="true"`, or  apply your own custom style.

**Comment by sfandrew** [comment]
@allenhwkim Been scratching my head on this one for hours. No luck. Map canvas dissapears whenever my div with ng non bindable has content. Here is my setup.
`angular.module('buildingInspections').controller('homeCtrl', ['$scope', 'buildings','NgMap',
	function($scope, buildings, NgMap){

		NgMap.getMap().then(function(map) {
            $scope.map = map;
            console.log("Map mapped to scope.");
        });
		
		$scope.retriveBuildings = function(){
			$scope.buildings = buildings.index();
		};
		$scope.buildingAddress = function(event,building){
			console.log($scope.map);

			$scope.name = building.name;
			$scope.map.showInfoWindow('foo-bar', this);

			
		};



	$scope.retriveBuildings();
	
}]);`

`<div class="row" ng-controller="homeCtrl">
	<div class="col-sm-10">
		<ng-map zoom="4" center="[37.5591399,-95.6927916]">
			
			<marker ng-if="building.latitude"  id="{{building.id}}" ng-repeat="building in buildings" 
				position="{{ building.latitude }}, {{ building.longitude }}" on-click="buildingAddress(event, building)">
			</marker>
			<info-window id="foo-bar" visible="true" default-style="true">
        		<div ng-non-bindable="">
            		Building name: {{building.name}}
        		</div>
    		</info-window>
			
		</ng-map>
		
	</div>
</div>
`

**Comment by aman-gautam** [comment]
`default-style="true"` did the trick for me... 

You, SIR @allenhwkim, are AWESOME...
