### ISSUE TITLE
NgMap Directions - Disable Drag Route

### ISSUE THREAD

**Issue by Matthewloughton** [allenhwkim/angularjs-google-maps#415]
Hi Allen,

First of all, I'm loving the NgMap directive. Thank you for creating it.

I'm using the directions side of the map and my question is, is there anyway of preventing the user from being able to drag and reroute the directions? Basically, I want google maps to calculate the route and the user not be able to manipulate the route.

**Comment by allenhwkim** [comment]
Please just set `draggable="false"`. 

Example: 
http://ngmap.github.io/#/directions.html

Documentation:
https://developers.google.com/maps/documentation/javascript/3.exp/reference#DirectionsRendererOptions

**Comment by pujabhatt1** [comment]
Ng-Map is really nice and already loving it. We are using directions in ng-map.  I did not see any option in directions to add traffic. I guess it is showing the travel time with no traffic. Is there any way to show total travel time depending on traffic?
