### ISSUE TITLE
info-window with lazy-init

### ISSUE THREAD

**Issue by poppahorse** [allenhwkim/angularjs-google-maps#417]
So I am trying to get info-window working with `lazy-init`, the problem being that I cannot load the instance of `getMap` into the scope.

Not exactly sure how to use `getMap` and `initMap` in conjunction with each other, and suspect this would not be possible due to their nature.

http://plnkr.co/edit/zDuNZYaXbmFc7WgrPpSp?p=preview

As `initMap` doesn't return anything, or have a callback, unsure how to get the instance of `map` so I can use it with `showInfoWindow`

Have tried a few things, but usually end up with `Uncaught TypeError: $scope.map.showInfoWindow is not a function`

Any assistance would be much appreciated!

**Comment by allenhwkim** [comment]
This is a bug.

I made a fix, but not coded yet.
http://plnkr.co/edit/8vHO4Jn6q6rKvfeJoWXZ?p=preview

I will let you know when this code is done to the repository.

**Comment by poppahorse** [comment]
thanks @allenhwkim, I will use the debug version from the plunkr for now! much appreciated

**Comment by allenhwkim** [comment]
This has been resolved AFAIK.
