### ISSUE TITLE
Load heatmap data asynchronously?

### ISSUE THREAD

**Issue by simonh1000** [allenhwkim/angularjs-google-maps#418]
I am getting `invalid heatmap data <heatmap-layer id="hmap" data="vm.restos">` while loading my page, and thus no heatmapLayers property on my map, which then leads a to second error as the NgMap promise resolves.

How should I configure this as the website example is for synchronously loaded data

```
		Promise.all([NgMap.getMap(), $http.get('/api/restos/heatmap')])
		.then( results => {
			this.map = results[0];
			this.heatmap = this.map.heatmapLayers.hmap;

			this.restos =
				results[1].data
				.map( r => ({
					location: new google.maps.LatLng(r.lat, r.lng),
					weight: r.rating
				}) );
				
			var heatmap = new google.maps.visualization.HeatmapLayer({
				data: this.restos
			});
			heatmap.setMap(this.map);
		});
```

**Comment by allenhwkim** [comment]
hmm. you are doing ES6? 
Have you tried `ng-if`?
If not work, please provide me a plunker example with google heat map example data, which is used here or any public heatmap data.

**Comment by allenhwkim** [comment]
Closing, if not works, please reopen it with an example
