### ISSUE TITLE
autocomplete save lat and lng

### ISSUE THREAD

**Issue by vialou** [allenhwkim/angularjs-google-maps#421]
How can I save latitude and longitude into a $scope.entity[attribute] ?
attribute is parameter of the on-place-changed function ?

http://ngmap.github.io/#/places-auto-complete.html
Also the example isn't working on updating the map.

Thank you.

**Comment by tharrington** [comment]
I can't get the sample to work either... In fact, I am getting:

Cannot read property 'Autocomplete' of undefined

Although, I am using NgMaps in other parts of my app, suggesting I have included it properly.

**Comment by allenhwkim** [comment]
My example was wrong. Fixed it with 1.15.4. Thanks for reporting it.
