### ISSUE TITLE
zoom-to-include-markers and Max Zoom

### ISSUE THREAD

**Issue by realph** [allenhwkim/angularjs-google-maps#422]
Is there a way to use the `zoom-to-include-markers` attribute whilst setting a max zoom level? It seems when `zoom-to-include-markers` is set to true, it overrides the `zoom` attribute. And when there is only one marker it zooms in real close, almost like a zoom level of 20.

**Comment by allenhwkim** [comment]
It is possible, but not with current code base.
We can read maxZoom option of a map, then use it when the zoom is reset.
Marking it as enhancement.

**Comment by Rodonies** [comment]
:+1: Would like a minimum zoom so one marker doesn't result in a zoom of 20+.

**Comment by Rodonies** [comment]
@realph @allenhwkim I made this functionality, please check the pull request (It has a plunker example)

I did not use the existing maxZoom option though, I don't think the user should be prevented from zooming in if he wants to.

**Comment by allenhwkim** [comment]
pull request accepted. thatnks for it @Rodonies
