### ISSUE TITLE
DirectionsRendererOptions preserveViewport and suppressMarkers don't work

### ISSUE THREAD

**Issue by Haverra** [allenhwkim/angularjs-google-maps#425]
![screen shot 12-06-15 at 10 43 pm](https://cloud.githubusercontent.com/assets/10177260/11615812/c55c1c10-9c6a-11e5-8bd9-e1eb790059a9.PNG)
preserveViewport="true" and suppressMarkers="true" don't do anything.

**Comment by allenhwkim** [comment]
Please try it with `perserve-viewport` and `suppress-markers`.
