### ISSUE TITLE
Wrong size of the map, and show location

### ISSUE THREAD

**Issue by niklas73** [allenhwkim/angularjs-google-maps#435]
Nice tutorials...
I can only see the map on half on the window.

I use this code:

.controller('MapCtrl', function ($scope, NgMap) {
$scope.googleMapsUrl="https://maps.googleapis.com/ma...";
var vm = this;
NgMap.getMap().then(function (map) {
vm.showCustomMarker = function (evt) {
map.customMarkers.foo.setVisible(true);
map.customMarkers.foo.setPosition(this.getPosition());
};
vm.closeCustomMarker = function (evt) {
this.style.display = 'none';
};
});
})

I whant to show my location...

**Comment by allenhwkim** [comment]
Please add your plunker example to show your problem.

**Comment by niklas73** [comment]
Sorry

I dont understand " plunker ", Do you whant to see code from app, controller, map

**Comment by allenhwkim** [comment]
Yes, I want to see your up and running code. You can create your plunker from here http://ngmap.github.io/#/custom-marker-2.html by clicking "Run In Plunker"

**Comment by niklas73** [comment]
I dont now how to make the plunker....sorry

**Comment by allenhwkim** [comment]
Closing. Without example, no progress will be made.

**Comment by neoatmatrix** [comment]
map size is set as 300 px;
