### ISSUE TITLE
Documentation for map event callbacks is outdated

### ISSUE THREAD

**Issue by emersonthis** [allenhwkim/angularjs-google-maps#436]
Trying to learn how to use events with ng-map...

[This documentation](https://rawgit.com/allenhwkim/angularjs-google-maps/master/build/docs/ngMap.ng-map.html) says that the attribute name should be "<MapEvent>" but something like `bounds_changed` will not work. Rather, it needs to be `on-bounds-changed`. Perhaps this was explained in the link in the description, but that link is now broken.

Not sure how those docs are edited but I'd be happy to submit a PR if there's a way for me to do it myself.

**Comment by allenhwkim** [comment]
All documentation are written within the code. e.g. https://github.com/allenhwkim/angularjs-google-maps/blob/master/directives/map.js

1. modify source code comments for documentation
2. gulp docs
3. done

**Comment by emersonthis** [comment]
Cool! Do you want a PR with that change?
(Great library btw!)

**Comment by allenhwkim** [comment]
Yes PR please

**Comment by allenhwkim** [comment]
Closing, will be done by PR
