### ISSUE TITLE
How to set the initial size of the ng-Map element?  

### ISSUE THREAD

**Issue by chaiyitsheng** [allenhwkim/angularjs-google-maps#437]
How can I set the initial size of the ng-Map? ie height and width in pixels? CSS doesn't seem to work.

Also the map doesn't show up in Firefox or Safari but works well on Chrome.....what have I missed? 

Thanks

**Comment by allenhwkim** [comment]
Please create a plunker example for this issue

**Comment by Eralph** [comment]
you can add an attribute `default-style="false"` to `ng-map`. Play around with it and if you want to make it fill the container you can add this CSS `ng-map {width:100%; height:100%;position: absolute;}`.

Experiment on it.

**Comment by allenhwkim** [comment]
Clonsing for inactivity.

**Comment by jdmagic21** [comment]
If you are not able to get the map to display the correct height using `default-style="false"` then try adding a inline style to the map `style="height: 500px; display:block; "`

**Comment by boltex** [comment]
problem is it's 'getstyle' function gets the calculated actual height, instead of the specified height style,   which for instance, for height:100%; will be 0 pixels while the page is being built by angular... and so it gets replaced by 300px ! (and will not fill the page!)

**Comment by DonHege** [comment]
Interesting, but is there a work around or solution to this? I want it to fill the entire height of the page.
