### ISSUE TITLE
[Lazy init] wrong position for center

### ISSUE THREAD

**Issue by aitboudad** [allenhwkim/angularjs-google-maps#438]
Example: http://plnkr.co/edit/wJgTUyDrQWFSiBGRYw73?p=preview

----
https://github.com/allenhwkim/angularjs-google-maps/blob/43a77dbc7dc5216ebf34259d1c44c84c900c5a50/controllers/map-controller.js#L156

**Comment by allenhwkim** [comment]
Thanks for reporting this. This has been fixed with new release

**Comment by aitboudad** [comment]
Thanks!
