### ISSUE TITLE
[$injector:unpr] Unknown provider: _$window_Provider <- _$window_ <- NgMap <- NgMap

### ISSUE THREAD

**Issue by AlexandruCiobanu** [allenhwkim/angularjs-google-maps#439]
Hi,
I included your library in my project and using grunt-ng-annotate and grunt usemin I get this error in the webapp. The error does not appear on the dev version which is not minified. Why do you need to reference _ $window _ in your directives? Won't $window work just fine?

**Comment by AlexandruCiobanu** [comment]
You should rewrite a bit the references:
for example, you had: 
GeoCoder.$inject = ['$q'];
angular.module('ngMap').service('GeoCoder', GeoCoder);

It should be rewritten to :+1: 
 GeoCoder.$inject = ['$q'];
angular.module('ngMap').service('GeoCoder', ['$q', GeoCoder]);

NG annotate seems to think that the reference is _$q and not $q. 
Same applies to the error I received:
this.$get = [
      '$window', '$document', '$q',
      'NavigatorGeolocation', 'Attr2MapOptions',
      'GeoCoder', 'camelCaseFilter', NgMap];

**Comment by AlexandruCiobanu** [comment]
I honestly can't get why would you want to write the dependencies like this, using $inject. I get it that Angular allows this way and it may work for websites referencing the js but you need to consider the fact that most likely people will use ng-annotate to do the dependency writing and will use a concat minifier to slim down the load. 
Please consider changing the way you reference dependencies to solve this ng-annotate/minify situation.

**Comment by allenhwkim** [comment]
Thanks for looking into ng-map code.

First I don't know why you run ng-annotate although the minified code is already provided.

The reason why I wrote like this is simple,  Better coding style.  

By exposing singleton services to IIFE scope,  all functions does not have to be in the nested function block,

Let's take an example of GeoCoder.

Without exposing singleton services to IIFE, the service will look like this. This may work for a small number of functions, but if the number of functions gets grow, it ends up with a big big function. 
```
  var GeoCoder = function($q) {
    var geocodeFunc = function(options) {
      var deferred = $q.defer();
      ...
      return deferred.promise;
    };
    return {
      geocode : geocodeFunc
    };
 }; 
```

To avoid a gigantic function, I exposed all singleton services to IIFE using underscore.

```
  var $q;
  var geocodeFunc = function(options) {
    var deferred = $q.defer();
    ....
    return deferred.promise;
  };

  var GeoCoder = function(_$q_) {
    $q = _$q_;
    return {
      geocode : geocodeFunc
    };
  };
```
Now all functions that I created in IIFE are not nested, and I can organize the functions whatever I want without considering the service scope.

This is matter of how the code is organized, and it is working with Angular code.

There might be a different approach to achieve better organization of code. If you have one, please let us know.

FYI, I approached the author of ng-annotate to allow to use underscore for inject, but the request was declined.

**Comment by AlexandruCiobanu** [comment]
I am not saying modify your structure nor am I criticizing your code structure. The only revision I propose is in the way you reference the dependencies when you register the service for example.
Instead of having: 
GeoCoder.$inject = ['$q'];
 angular.module('ngMap').service('GeoCoder', GeoCoder);

I propose
 angular.module('ngMap').service('GeoCoder', ['$q', GeoCoder]);

BTW, I like the way you structured your code.

**Comment by allenhwkim** [comment]
Thanks for your suggest. We appreciate your proposal, but will be implemented later only when we found out that your proposal provides significant benefits

Closing

**Comment by elvizcacho** [comment]
Having same issue :+1:

**Comment by pkerspe** [comment]
+1 same issue here
