### ISSUE TITLE
map-data not loading geo.json from model

### ISSUE THREAD

**Issue by ArtworkAD** [allenhwkim/angularjs-google-maps#442]
<map-data load-geo-json="someData"></map-data>

This will only work if someData is an url pointing to a geo.json file. Is there any reason why it does not accept variables containing geo.json?

**Comment by allenhwkim** [comment]
As you see here, map-data is not actually an object.
it's just wrapper of map.data.

https://github.com/allenhwkim/angularjs-google-maps/blob/master/directives/map-data.js

There is no specific reason not to watch the variables. It was just not used in that way by other users.
If we need to watch it, we need to add watchers into the directive. 

I would recommend to use `map.data.loadGeoJson()` method manually in your controller. If you don't find a feature in this directive, you can always go around by implementing google maps api directly.

**Comment by ArtworkAD** [comment]
@allenhwkim thank you!
