### ISSUE TITLE
Issues with custom-control - Plunkers Included

### ISSUE THREAD

**Issue by trainerbill** [allenhwkim/angularjs-google-maps#443]
Seems like it dupicates when you have multiple maps and routes:

http://plnkr.co/edit/1dBDgqiwJTfcJ87EJ8zZ?p=preview

Switch between the routes.  If I assign the map an id then custom-control does not render.

http://plnkr.co/edit/cJjIcGcizTcVo5RcURba?p=preview

**Comment by trainerbill** [comment]
Update:
I made some modifications that make it work for my use case.  I don't know enough about the module yet to submit a PR.  Still deciding whether or not to use this in my project

On the custom control directive I added a get map id and cleared the array before pushing the new control
```js
mapController.addObject('customControls', customControlEl);
    NgMap.getMap({ id: mapController.mapOptions.id }).then(function(map) {
      var position = options.position;
      map.controls[google.maps.ControlPosition[position]].clear();
      map.controls[google.maps.ControlPosition[position]].push(customControlEl);

    });
```

**Comment by allenhwkim** [comment]
It looks like a bug. I assume it happens because map instance is being reused to prevent memory leak. When a new page is rendered, it uses the existing map instance, it does not clear all the controls of the existing map instance. 

I need to dig into it.

**Comment by allenhwkim** [comment]
This has been fixed with new release

**Comment by kirandas82** [comment]
customMarkers is also repeating in the same way.. is there any solution for it?
