### ISSUE TITLE
New Drawing Manager instantiated every time

### ISSUE THREAD

**Issue by trainerbill** [allenhwkim/angularjs-google-maps#444]
http://plnkr.co/edit/5X6rwdfommrJ8SWE0zuS?p=preview

Switch between routes.

My workaround for drawingManager directive was to just return if it already exists.  Not sure if you should remove and reinstantiate or just return.  Looking forward to an official patch.

```js
mapController = mapController[0]||mapController[1];

        if (mapController.map.mapDrawingManager) {
          return false;
        }
        
        var filtered = parser.filter(attrs);
```

**Comment by allenhwkim** [comment]
The same. This happens because the map instance is being re-used to prevent memory leak. I will look into it.

**Comment by allenhwkim** [comment]
This has been fixed with new release
