### ISSUE TITLE
Major Pooling issue

### ISSUE THREAD

**Issue by trainerbill** [allenhwkim/angularjs-google-maps#448]
If you have more than one map not in use your find logic overwrites the first index in the pool since you are doing !map.inUse.  

https://github.com/allenhwkim/angularjs-google-maps/blob/master/services/ng-map-pool.js#L30

I am not sure what you are doing with the in use property but switching to 

```js
if (el.id === map.id) {
```

On that line fixed my problem.  I think its better technique anyway, but am not sure of any other issues it may cause.

**Comment by allenhwkim** [comment]
It's a good idea. However, this won't prevent memory leak if map ids are dynamically changing.
it's tedious to delete all object when map is removed, but it's only the proper way I found so far.

Please let me know any pooling issues are still there.

**Comment by trainerbill** [comment]
Why would map ID's dynamically change?  I can't think of a good use case for an ID changing.  Or do a 2 way bind on a ngmap-id?

**Comment by allenhwkim** [comment]
NgMapPool service is providing map instances which is not in use regardless of map id assigned. This is how it works 
1. ng-map directive get map instance from the pool
2. assign all options and events to the map instance including id
3. when ng-directive is destroyed, return the map instance to the pool

If we get the map instance from pool by  id, we will get the number of map instances by unique ids for all pages. If page one uses id `one', and page two uses id `two`, and so on. In that case, we need only one map instance, but we will keep two map instances.

The worst case is that if user wants to change their map id dynamically. You may say it's crazy, but I have seen these requests, and it's totally users' choice. Although we do not allow two-way bindings of map Id, `ng-map` within `ng-repeat` will create too many map instances if map pool is managed by id, and unused map instance will cause memory leak. 

For example first ids by `ng-repeat`, 1,2,3, second ids, 4,5,6, third ids 7,8,9. We only need three map instances for max usage, but we 9 map instances will be in memory if we manage by id.

**Comment by trainerbill** [comment]
@allenhwkim I think this is a pretty bad idea.  For instance one of my maps has the bounds_changed event listener and it was being reused in another portion of my site, causing many issues since I did not want that event on that specific map.  What would be your recommendation?  I don't want to run with a modified fork of the repository, but think that map by ID is the best case scenario.

**Comment by allenhwkim** [comment]
@trainerbil when map is deleted, all events bounds to the map should also be removed. This behaviour, removing all events, is already applied to removal of each object. 

I will check with map removal logic and will apply this behaviour if not applied. 

About map instance by id, if you can solve the memory leaks by dynamic IDs, I will be happily implement your idea.

**Comment by allenhwkim** [comment]
Found out that map is not removing all events when an instance is removed. This has been fixed with https://github.com/allenhwkim/angularjs-google-maps/commit/bfe02f4e3294ba6bc7400956e0218e0e84ed1378, and released with 1.15.10
