### ISSUE TITLE
Can not inject ngMap: Error: $injector:unpr Unknown Provider

### ISSUE THREAD

**Issue by langhoangal** [allenhwkim/angularjs-google-maps#452]
Hello,

I'm following the get started but get the error when inject.

// index.html
script src="assets/js/ng-map.min.js"
script src="http://maps.google.com/maps/api/js"

// app.js
app = angular.module('app', ['ngRoute', 'ngResource', 'ngMessages', 'ngMaterial', 'ngMap']);

// controller
angular.module('app').controller('myController', myController);
myController.$inject = ['$scope', '$mdToast', 'ngApp'];
function ContactEditController($scope, $mdToast, NgApp) {...}

The map was show as normal, but whenever i inject ngMap to use in controller it fire an error like this:
Error: [$injector:unpr] http://errors.angularjs.org/1.4.8/$injector/unpr?p0=ngMapProvider%20%3C-%20ngMap.
Error: $injector:unpr
Unknown Provider
Unknown provider: ngMapProvider <- ngMap

Could you help to give a hint?

**Comment by allenhwkim** [comment]
Try `NgMap` instead of `ngMap`.

**Comment by langhoangal** [comment]
Hello,

The same error when trying with NgMap. But now, due rush, i switched to use another map at this time. So, we might close this issue for now (it seem not lot of people got in to this problem like me).

Thanks for your help!

**Comment by allenhwkim** [comment]
Sorry for not being helpful. I have never seen your error. Hope other map works well with you,

**Comment by Digi-reaper** [comment]
try to use these scripts 
<script src="https://maps.google.com/maps/api/js?libraries=placeses,visualization,drawing,geometry,places"></script>
<script src="https://rawgit.com/allenhwkim/angularjs-google-maps/master/build/scripts/ng-map.js"></script>

**Comment by campsjos** [comment]
I've got the same error and solved it updating the library to the last version.

Also, in my case, I needed to run `bower remove ngmap` and `bower install ngmap` to get the very last version.

**Comment by browniebroke** [comment]
Here is a

https://plnkr.co/edit/TlpqI3k4haGCPEFz4mQR?p=preview

**Comment by allenhwkim** [comment]
@browniebroke This works, https://plnkr.co/edit/iYYRyr?p=preview

**Comment by browniebroke** [comment]
Great, thanks for the fast response ! :+1:

**Comment by AnirudhaGohokar** [comment]
+1 I also faced the same issue. Changing it to NgMap when injecting in controller fixed it.  
Don't know why there's this inconsistency when injecting in module vs controller.

Thanks,
Anirudha
