### ISSUE TITLE
Displayed map content not fitting bounds of map

### ISSUE THREAD

**Issue by blbigelow** [allenhwkim/angularjs-google-maps#454]
I have an angular ui router project and I have different states with different size maps and when I switch between the states the maps seem connected somehow and the content doesn't fit correctly.

Here's a plunker showing the problem: http://plnkr.co/edit/3opaATfKoGO5kPvyF13n?p=preview
Running the demo in full screen mode shows the problem better.

**Comment by allenhwkim** [comment]
fixed with v 1.16.3, please try again.
