### ISSUE TITLE
Error: [$interpolate:interr] Can't interpolate: {{map}} TypeError: Converting circular structure to JSON

### ISSUE THREAD

**Issue by Alvarz** [allenhwkim/angularjs-google-maps#456]
Hi great job! 

this error appear when I copy paste the example of quick start here, however it works, i mean all i was test like markers, events and more, are working but this error on my console dont let me sleep

this look like generate the error
```
  NgMap.getMap().then(function(map) {
    //   console.log(map);
    //  console.log(map.getCenter());
    //  console.log('markers', map.markers);
    //  console.log('shapes', map.shapes);
   });
```

sorry my terrible english

**Comment by Alvarz** [comment]
Fixed! it was ginving that error cause a polymer map components.

**Comment by allenhwkim** [comment]
I tested with your code, and it works fine. Can I close this?
