### ISSUE TITLE
does support custom infowindow?

### ISSUE THREAD

**Issue by handleror** [allenhwkim/angularjs-google-maps#457]
I have tried to hook my own code to style infowindow, but could not. Does it support custom info-window like this http://google-maps-utility-library-v3.googlecode.com/svn/trunk/infobubble/examples/example.html

**Comment by allenhwkim** [comment]
It does not support a custom infowindow, but a custom marker

**Comment by handleror** [comment]
oh, thank you for replying me. I guess the feature must be helpful. I did try the feature here http://angular-ui.github.io/angular-google-maps/#!/api/window. It will be supported in future hopefully?

**Comment by allenhwkim** [comment]
I would not reinvent info-window just for css. I have injected ng-map-info-window class name to the parent of info-window so that you can style it. Example, http://ngmap.github.io/#/!infowindow-simple.html

**Comment by handleror** [comment]
Nice, it seems to be hard to customize IW's border and width for this way. http://www.trulia.com/for_rent/Saratoga,CA/
Anyhow, i will try it. Thank you @allenhwkim
