### ISSUE TITLE
1.16.0 globally configures the log and compile provider

### ISSUE THREAD

**Issue by mattlewis92** [allenhwkim/angularjs-google-maps#459]
A 3rd party module shouldn't configure these 2 settings, as it broke all my tests when upgrading this library (e.g. elm.isolateScope() is no longer a function). Please can you revert this please, thanks!

https://github.com/allenhwkim/angularjs-google-maps/blob/9d6eae9d5128c399ff20ec3733d0b12ad95cec41/app.js

**Comment by allenhwkim** [comment]
reverted and pushed as 1.16.5. Thanks for letting us know this.

**Comment by mattlewis92** [comment]
Great thanks! Can you publish 1.16.5 to npm as well please?

**Comment by allenhwkim** [comment]
published

**Comment by mattlewis92** [comment]
Great, thank you!
