### ISSUE TITLE
Switch maps on a change on `zoom-to-include-markers`

### ISSUE THREAD

**Issue by execat** [allenhwkim/angularjs-google-maps#462]
Hi,

I am trying to switch between zooms of a map depending on the value that I am using to set `zoom-to-include-markers` in the directive (`true` or `false`). However, this does not auto update the map.

Is this the expected behavior of the directive? Can the map not auto update on a change on `zoom-to-include-markers` attribute?

Thanks!

**Comment by allenhwkim** [comment]
There is undocumented feature `zoom-to-include-makers="auto"`.
