### ISSUE TITLE
$log is used in deleteMap but not injected

### ISSUE THREAD

**Issue by derkoe** [allenhwkim/angularjs-google-maps#463]
On [this code location](https://github.com/allenhwkim/angularjs-google-maps/blob/master/services/ng-map.js#L93) $log is used without injecting it. That means every time a map with event listener is destroyed the error occurs.

See this Plunk: http://plnkr.co/edit/kLGvrBQQG6GQVJ3xU8JQ?p=preview
* click on "Map"
* then click on "Start"

**Comment by allenhwkim** [comment]
ok. I will fix it soon.

**Comment by luncht1me** [comment]
+1 annoying. I had to just comment out the line ` $log.debug('clearing map events', eventName);`

**Comment by allenhwkim** [comment]
fixed. 1.16.6 released
