### ISSUE TITLE
(discussion) Version 2.0

### ISSUE THREAD

**Issue by trainerbill** [allenhwkim/angularjs-google-maps#468]
I wanted to start a discussion about a version 2 of this module.  It is great as is but could really use some new features that won't be possible without a core rewrite.  Some things that I can think of

1.  Persistent maps and data.  If I switch states and return I should not have to add back all my data and render the map.  It should be in the same state I left it.  Maps should have ids so that they can be reloaded.  Data layers and Heatmaps have Ids so they can be reloaded.  All stored in the NgMap service and can be accessed outside of the module

2.  Bindable attributes.  Separate attributes so that the ones core to ngmap are bindable.  Will allow us to bind a heatmap to a data source and have it automatically update.  I would like to prefix these with ngmap- and then we can parse the rest of the attributes as "google maps" attributes and pass them directly to google maps.

3.  Conform to John Papa Angular styleguide
https://github.com/johnpapa/angular-styleguide

4.  Use NgLodash to make the code more readable

5.  Use Promises as much as possible.

I have started some preliminary work on what I would like to see.  I currently have a new map pool, map service, controller, heatmap and custom tools directives.

You can see the heatmap here:

http://plnkr.co/edit/xaTb75PVBFG2mEdnNpQy?p=preview

You will see the heatmap dynamically change after 3 seconds.  @allenhwkim This is quite different from the current release of this module so if you are uncomfortable with these changes I will just run with a fork in my project.

Current files updated:
https://github.com/trainerbill/angularjs-google-maps/blob/2.0/services/google.map.api.js
https://github.com/trainerbill/angularjs-google-maps/blob/2.0/services/map.service.js
https://github.com/trainerbill/angularjs-google-maps/blob/2.0/services/pool.maps.factory.js
https://github.com/trainerbill/angularjs-google-maps/blob/2.0/controllers/initialize.controller.js
https://github.com/trainerbill/angularjs-google-maps/blob/2.0/directives/heatmap-layer.js
https://github.com/trainerbill/angularjs-google-maps/blob/2.0/directives/custom-control.js

Up for discussion!

**Comment by trainerbill** [comment]
Refactored main directive.  Added zoom and center attrs.

http://plnkr.co/edit/m15IbvWmPIWUUPaAoLsh?p=preview

**Comment by trainerbill** [comment]
Updated the Map pooling.  Maps can now be reused in the same state they were left.  Example using UI router:

http://plnkr.co/edit/Sb92u0S3s1thpMMLgNHV?p=preview

If you scroll on the maps and then change states and come back the map is the same.

The directives are now promise based.  The main directive has a promise for ready and rendered.  Ready resolves when the created map is idle and the rendered resolves on the tiles_loaded event.  The child directives wait for them to resolve before doing their thing.  The custom controls waits for rendered and heatmap waits for ready.

NgMap is now an instance and NgMapPool saves the created instances.  NgMapPool can be used in controllers to get a map.

**Comment by hany-andriyanto** [comment]
Hi Bill, what is this compatible with angular version below 1.3?

**Comment by trainerbill** [comment]
@hany-andriyanto awesome.

Added Default setup and options.  You no longer are required to have a map id or class if you don't want to pool multiple maps.  You can render a map with just the <ng-map> directive only:

http://plnkr.co/edit/6hdF61yDgzHJp5DCG34W?p=preview

**Comment by trainerbill** [comment]
Bindable ngmap-options done:

http://plnkr.co/edit/F7wB3qfj8VXatEKozBzx?p=preview

You can pass anything from:

https://developers.google.com/maps/documentation/javascript/3.exp/reference#MapOptions

**Comment by trainerbill** [comment]
Drawing manager version 1 with bindable controls:

http://plnkr.co/edit/SbgTKrinl55SxdJrqBg2?p=preview

**Comment by allenhwkim** [comment]
@trainerbill thanks for writing these up. I am sorry not been able to look these into. I have been sick for last weekend.

**Comment by trainerbill** [comment]
@allenhwkim No problem.  Take a look when you can.  Its quite a bit different than the current module so you may not want to go down this route....  I think its a better implementation, but I have not gotten through all the directives yet so I may be missing something.  Drawing manager now has mode watching and event setting.

http://plnkr.co/edit/SbgTKrinl55SxdJrqBg2?p=preview

**Comment by allenhwkim** [comment]
@trainerbill I took a brief look at your code, and I appreciate your effort to 2.0 for this module. Few things I did not see in the new approach are;

  1. 2.0 has better to be rewritten in Angular 2.0, not with 1.x.

  2. Everything in tag and attributes as in README.md. 
![image](https://cloud.githubusercontent.com/assets/1437734/12254215/43be379a-b8b4-11e5-92a1-e44f0159311b.png). Accepting map object options as a json object e.g., `markerOptions`, `mapOptions`, or any, are done with many other modules.  We should be able to pass any option as an attribute, and a  directive should accept as it is. This module is not created if xxxOptions= are acceptable as an attribute. 

  It's also HTML-first approach. This module really tried to  avoid Javascript usage. If users want to change a map, change the html, then it should work, not Javascript. especially options. All are designed to focus on HTML-first approach and try not to use Javascript.

  3. We should avoid number of watchers as possible as we can, which affects the performance. With 1000 markers, the application still should work without performance issue without any watchers. The current implementation of `{{` and `}}` is how user specify what to watch and what not to. This module tried to avoid everything `$watch`able.

**Comment by SoaringTiger** [comment]
2.0 has better to be rewritten in Angular 2.0, not with 1.x.

**Comment by uiktiomasfeliz** [comment]
Angular 2. +1

**Comment by david-lee** [comment]
Angular 2. +1

**Comment by prusswan** [comment]
It would be nice to have options though (to trigger reload of objects), in some cases it is very difficult or impossible to get the desired behavior (like dynamic update of markers as certain markerOption values are modified, some attributes like position values are updated but others like animation are not)

**Comment by chiptus** [comment]
what the status on this?

**Comment by allenhwkim** [comment]
@chiptus going slow, I don't make time at night for this progress. Maybe some day later.

**Comment by chiptus** [comment]
how can i help?

**Comment by allenhwkim** [comment]
@chiptus, if you know Angular2 and Typescript, you can make a start at https://github.com/jsvalley/ng2-map. The current challenge that I have is to make a package that works in plunker. Angular2 is great, but not so stable like Angular1.

**Comment by chiptus** [comment]
I checked this project. Other then the readme there is nothing there.

**Comment by ericjames** [comment]
I would like a clarification between marker and custom-marker implementation.  It appears that other libraries require the standard marker (ie: spiderfy) and it seems like custom-marker is inserting DOM content manually.    There may be a native way for custom-marker to insert special dom content that Google will then recognize as a gmno "marker" object and therefore work with other libraries.

Otherwise, a simple label attribute or style attribute would be great, if we could append a class to marker and the gmno div inherits that.

**Comment by allenhwkim** [comment]
ng2-map is released

**Comment by ruisilva450** [comment]
@allenhwkim some of us can't simply switch to Angular2 right now and we appreciate if this efforts are coming for Angular1
