### ISSUE TITLE
Map Height always 300px and default-style="false" not working as expected

### ISSUE THREAD

**Issue by cammanderson** [allenhwkim/angularjs-google-maps#470]
You would expect that by specifying default-style="false"; that the default styles of "display:bock; height: 300px" would not be added.

Currently, unless you specify a height manually it is added for you at 300px. I have tried setting height:auto etc still to no avail, it overwrites the value.

We use flex to manage the height of this map, so the height can't be set.

**Comment by allenhwkim** [comment]
Could you add an plunker example for this issue?

**Comment by allenhwkim** [comment]
Can you try outer container height as certain pixel, and map as 100% height?

**Comment by cal2dev** [comment]
http://plnkr.co/edit/og1eVPmMeJPHWkpNlcsY?p=preview

**Comment by cal2dev** [comment]
http://plnkr.co/edit/Ib3H32M4wooIQGm9JxMk?p=preview

**Comment by mkarganov** [comment]
Hi @allenhwkim, thanks for great lib. I have the same issue with fixed height of outer container.

As a workaround it is possible to set class for <ng-map> element and set its height to 100%. It will fit the height of outer div height. But it would be great to disable the default 300px at all.

**Comment by Eralph** [comment]
what I did with this one was using the CSS

`ng-map {width:100%; height:100%;position: absolute;}`

**Comment by joshkopecek** [comment]
For me this issue is linked to #489 . The issue is Google Maps requiring dimensions before loading, or requiring a refresh to be called when the dimensions change. I think the issue is deeper than this one - has anyone looked into how the styling is set and how the refreshes are managed?

**Comment by ActionCommunity** [comment]
From my side, Im interested in using your nice library too and struggling here too. So @mkarganov I can't get a workaround rid. What i tried:
```

<style>
    .gmap {
        height: 100%;
    }
</style>

<div id="map_canvas" flex>
    <ng-map zoom="5" default-style="false" class="gmap" style="height:100%;"></ng-map>
</div>
```

**Comment by allenhwkim** [comment]
For the given example, map must be `ng-map`, not `map` since `ng-map` is used in html
```
<style>
  ng-map#custom {display:block; width:200px; height:800px}
</style>
```

**Comment by raagve** [comment]
Hi
i used above code and it fixed the height issue. but when i try to show pop up from marker then it shows error like "Cannot read property 'showInfoWindow' of undefined" .
