### ISSUE TITLE
lazy loading: had to trigger 'resize' to display map

### ISSUE THREAD

**Issue by YayConnolly** [allenhwkim/angularjs-google-maps#471]
Just found this library and excited to get started using it. Tried lazy loading to google script with
```
  <div map-lazy-load='https://maps.google.com/maps/api/js'>
    <ng-map center="[40.74, -74.18]" zoom="3"></ng-map>
  </div>
```
And got this grey screen
![lh_concierge](https://cloud.githubusercontent.com/assets/1444054/12219432/dbf96a52-b6f7-11e5-863c-fcb88e0761b8.png)

I had to set a timeout like
```
 NgMap.getMap().then((map) => {
   $timeout(() => {google.maps.event.trigger(map, 'resize')}, 1000)
 });
```
before the map would render.

My angular version is 1.5.0-rc.0, bower ngmap version 1.16.6

**Comment by allenhwkim** [comment]
As in this example, http://ngmap.github.io/#/!map-lazy-load-params.html, you don't have to trigger resize the map. Do you use ui-router or any other frame work to show/hide a map? If so, please add your plunker example, so that I can debug quickly.

**Comment by YayConnolly** [comment]
Thanks for your reply and the link! I ended up loading the google maps script synchronously, because I am also using your `places-auto-complete` directive. 

I am using ui-router, and also UI Bootstrap-- the map was inside a `uib-tab` directive-- so the issue may have been related to that. The only other difference I could see from your example is that I had not set a timeout like `NgMap.getMap({timeout:5000}) ...`. Anyway closing this for now, can try to put together a plunker if others run into this.

**Comment by J-McElroy** [comment]
Hi,

I have the same problem, please see an example in plunker below:
http://plnkr.co/edit/GFaBdLAiUAfF4RI021V9?p=preview
Could you please describe what I should do to avoid manually resize it?

Thanks in advance

**Comment by lucaslandry** [comment]
Hi,
I've got the same problem with Materialize. How did you proceed to load the map synchronously please? I'm not an expert in that.
Thanks

**Comment by dotlouis** [comment]
I got the same problem and went my way around it with [this](https://github.com/allenhwkim/angularjs-google-maps/issues/387#issuecomment-216898248) solution I copied below:

```JS
NgMap.getMap("map").then(function(){
    // Initialize the Google map
    vm.map = NgMap.initMap("map");
});
```

**Comment by solidevolution** [comment]
For me it worked since I use

```
NgMap.getMap({id:'mainMap'}).then(function(response) {
    vm.mapService.mainMap = response;

    [...] some map manipulation code [...]

    google.maps.event.trigger(vm.mapService.mainMap, 'resize');
});
```

**Comment by avinashbhujan** [comment]
This one worked for me (Typescript Version):

**HTML:**
`<ng-map zoom="14" center="[0,0]" trigger-resize="true" map-initialized="modalController.onMapLoaded()" >
                    <shape  id="circle" name="circle" centered="true"
                            center="{{modalController.address}}"
                            stroke-color='#FF0000' stroke-opacity="0.8" stroke-weight="2"
                            radius="800" editable="false"></shape>
                </ng-map>`

**Controller Method:**
`public onMapLoaded() {
        var self = this;
        self.ngMap.getMap().then(function (map) {
            self.gMap = map;
            google.maps.event.trigger(self.gMap, 'resize');
        });
    }`

If using Typescript, make sure you have the file google.maps.d.ts and if some types are not available just set them to `any`.

**Comment by AntonisFK** [comment]
```
        //Init maps
          NgMap.getMap().then(function(map) {
              vm.map = map;
              marker = map.markers[0]; 
              google.maps.event.trigger(map,'resize');
              
          }); 
```


Fixed my issue as well but now my marker doesn't show up once the map is loaded.

**Comment by U-like** [comment]
I was having this issue and my solution was to add `$scope.$apply()` after `google.maps.event.trigger(map,'resize');`. Without that, the map was not rendering until scroll.

**Comment by anderson631** [comment]
This work for me:

$timeout(function() {
	NgMap.getMap({id:'my_map'}).then(function(response) {
		google.maps.event.trigger(response, 'resize');
	});
}, 500);
