### ISSUE TITLE
Map with Bootstrap collapse

### ISSUE THREAD

**Issue by ottz0** [allenhwkim/angularjs-google-maps#473]
I'm using this inside a bootstrap collapse. My map is gray (blank but with controls) and I need to action a resize (had this issue before with BS). Can anyone help with using this inside a bootstrap collapse or tab with Angular or this directive?

**Comment by luncht1me** [comment]
@ottz0 

you need to do ``` $scope.$on('mapInitialized', function (evt, map) {
				console.log("map initialized.");
				google.maps.event.trigger(map, 'resize');
                               }); ```

in your controller, or within your collapse callback if there is one, or where ever. This isn't really an issue with ngmap but just javascript google maps in general.

**Comment by Abhith** [comment]
Thank you so much @luncht1me , i have the same problem while using map inside modal. And now it solved.
