### ISSUE TITLE
Directions and placing a marker after [x] miles

### ISSUE THREAD

**Issue by mrpharderwijk** [allenhwkim/angularjs-google-maps#474]
Hi Allen,

First of all thanks for this nice plugin!

I've got everything to work as I want. As an addition I have an input field where people can type in a mile amount. After submit I want to add that between the origin and destination direction path. Is that possible?

**Comment by mrpharderwijk** [comment]
Allen? Do you have no answer for me? Nobody? I cannot imagine that this is a first time feature question...

**Comment by allenhwkim** [comment]
Sorry about that, I recently moved to a new company and could not focus on this project.
I have calculated miles between two destinations, but not origin + X miles => destination

**Comment by mrpharderwijk** [comment]
So it is not possible (yet)

**Comment by allenhwkim** [comment]
This question is about Google Maps API. google maps API might have a way to calculate miles from an origin, but I have not found the way yet. However, I did not find a way to do yet mean it is not possible yet.
The certain thing is that, it's not about ng-map, it's about Google Maps API. ng-map is just a angular wrapper of Google Maps API.

**Comment by allenhwkim** [comment]
closing this as `out of scope`
