### ISSUE TITLE
Change custom map style after map load

### ISSUE THREAD

**Issue by josangel555** [allenhwkim/angularjs-google-maps#478]
Hi,

Is there is any option to change the custom style of a map after it's initial load.

 I have tried changing the `styles` attribute of `ng-map` using angular binding, eg,

    <ng-map ... styles="{{vm.markers.zoomType === 'Site' ? vm.mapSiteStyle : vm.mapGlobalStyle}}"

This expression is evaluated when the map is initializing and shows corresponding style, but further updates to this expression won't change the style. Also tried modifying the styles attribute of map object in controller (`vm.map.styles`). 

    vm.map.styles = _getMapGlobalStyle();

But not able to change the style that is loaded to the map initially. I understand that there isn't a method in `map` for setting the the style (eg: `setStyles()`). I'm raising this as an issue since I saw in the changelog that from 1.15.0, 'All attributes can have {{}} expression evaluated'.

I was wondering if there is a way to achieve this. Ultimately I'm try to disable few map features in certain zoom level and enable them in other (like lables, roads etc..). If this is not possible at present, could you please consider adding this feature. That will be of great help to me.

Kindly refer the below plnkr.
http://plnkr.co/edit/zmUe9LYkcyxSorxsirJf?p=preview

Thank you,
Jos

**Comment by edinchez** [comment]
I need this as well. I have the map in a hidden div and I'm resizing it with `google.maps.event.trigger(map, 'resize');` after the div resizes, but it loses its custom style on resize.

**Comment by josangel555** [comment]
I have observed something. If we update `vm.map.styles` and then change the mapType to say `SATTELITE` and then turn back to say `TERRAIN`, the newly assigned style is being picked. At least as a workaround I tried doing this programatically. But no luck.

http://plnkr.co/edit/4pdaKZscp7wGaqpGbloF?p=preview

**Comment by josephclawrence** [comment]
Also having problems with this - has anyone found a passable workaround, or are there any plans to fix this, if it is indeed a bug? If not a bug, is there any way to trigger a style change after a map is loaded? Thank you! Joe

**Comment by allenhwkim** [comment]
As you see here, https://developers.google.com/maps/documentation/javascript/reference#MapOptions

MapOptions has `styles`. That's why initial `styles` is working.
However,  as you see here, https://developers.google.com/maps/documentation/javascript/reference#Map

Map does not have method `setStyles`. That's why it does not apply new style.

If you want to make new style work, you need to cod set `setOptions` with styles in it.

Here is the working plunker, http://plnkr.co/edit/nWAGkJ?p=preview

**Comment by tewfik-ghariani** [comment]
Thanks a lot! I have been struggling with the same issue for a while
You're amazing :)
