### ISSUE TITLE
Multiple istance of ng-map in the same container using ng-repeat

### ISSUE THREAD

**Issue by simonepri** [allenhwkim/angularjs-google-maps#479]
Hello, I'm having some problems setting up multiple maps on the same page.
Basically I load infos from an object and I create new istance of the <ng-map> element into the ng-repeat directive.
For a single map it works, but when more object are added into the array only the last map is correctly loaded.

This is the example on plunker:
https://plnkr.co/edit/XT3OvPZ7uyp5eIXSSaGe?p=preview

If i remove the "map-lazy-load" attribute and include the google map js manually in the head, both the maps loads, but only the last one display the route between waypoints.

Why this happen?

**Comment by allenhwkim** [comment]
map-lazy-load should only happen once in a page.
Please take a look at this example.
https://plnkr.co/edit/B1IJSPbGH29MtKjj2c4x?p=preview

**Comment by pmannle** [comment]
Hello - awesome directive..... Question: I'm having trouble getting multiple maps to work inside an ng-repeat as well.... the above plunker is not working. The first map just shows the default 'middle of the ocean' view.... is it possible to get the plunker working so I can refer to it??

**Comment by pmannle** [comment]
Ok, got this figured out. The key for me was using the center attribute within the map directive:

http://plnkr.co/edit/62mzZLQ3NxHORkU683PP?p=preview
