### ISSUE TITLE
Map didn't display in Modal for iOS - Ionic

### ISSUE THREAD

**Issue by aishahismail** [allenhwkim/angularjs-google-maps#482]
I'm created ionic project. Then follow the instruction to create a google maps. After already finish I tried to run my project in browser (ionic serve --lab). I'm made 2 maps, first is at main page and second is in modal view. In main page, both outputs android and iOS was fine but when I opened my modal for iOS , the map didn't display. Thanks

**Comment by allenhwkim** [comment]
please add your plunker example. You might have to trigger `reload` event for a map, or it could be a height issue. I am not sure until I see your example in plunker.

**Comment by aishahismail** [comment]
yeah you're right. Problem solved. Thanks.
