### ISSUE TITLE
Custom marker performance

### ISSUE THREAD

**Issue by mkarganov** [allenhwkim/angularjs-google-maps#487]
Hi, not sure if it is a right place to ask.

Custom markers feature is great. However we are facing some performance issue putting ~500 custom markers on the map with two way binding and ng-repeat. Unfortunately it takes around 5 seconds to iterate.

Is there any way to avoid using ng-repeat? Or maybe optimize it somehow?

I also found an answer here http://stackoverflow.com/questions/22372161/using-ng-repeat-with-markers-in-ngmap, but I am not sure if it is possible with custom markers.

Thanks!

**Comment by allenhwkim** [comment]
Are there watchers in custom marker, then use `no-watcher="true"` not to listen to watchers.
500 custom markers are pretty big.

**Comment by mkarganov** [comment]
Thanks! I will try!

**Comment by chalcrow** [comment]
Custom markers will kill your performance for anything above about 200 markers. See my answer on the Stackoverflow question for how to use a custom icon when using the standard marker directive https://stackoverflow.com/questions/36053355/how-can-i-use-custom-icon-in-ng-map-markerangular/46066574#46066574
