### ISSUE TITLE
NgMap not working with flex

### ISSUE THREAD

**Issue by joshkopecek** [allenhwkim/angularjs-google-maps#489]
Hey, firstly the NgMap library is incredible… It does 100% of what I've wanted it to do so far.

I am struggling with styling + flex and maps. After specifying flex and 100% height it still defaults to 300px. I would ideally like to be able to have NgMap within a flex layout.
http://plnkr.co/edit/bFh7nFasa8PxVAopfOHI?p=catalogue

**Comment by allenhwkim** [comment]
I am out of idea. Can someone help me?

**Comment by allenhwkim** [comment]
AFAIK the rendering is correct. Please take a look at this plunker
http://plnkr.co/edit/CFFVOg?p=preview
The problem is the container height is incorrect. Please change to this.
```

  .container {
    height: 100%;
    border: 1px solid black;
    display: flex;
    flex-direction: row;
  }
```
