### ISSUE TITLE
weird NgMapPool behavior if ngAnimate and ui-router are app dependencies

### ISSUE THREAD

**Issue by flc** [allenhwkim/angularjs-google-maps#490]
http://plnkr.co/edit/eWE8lM0UteXZZhYrCk7Z?p=preview
Click the Map X links and as you can see there are multiple instances for the same map in NgMapPool's mapInstances. While in this example it doesn't really cause any harm, in my complex application it causes really weird things which I'm not able to demonstrate here.

Now the weird thing is that if you remove ngAnimate from the app dependencies the problem is gone.
```
var myapp = angular.module('myapp', ['ngAnimate', 'ngMap','ui.router']);
```
->
```
var myapp = angular.module('myapp', ['ngMap','ui.router']);
```
It took me hours to debug this and figure out that the ngAnimate dependency is the root of the problem. I've tried to use the 1.0.0alpha0 version of ui-router but I get the same result with it.
What I found is that if I remove this particular if statement from ui-router's viewDirective then the problem is gone:
https://github.com/angular-ui/ui-router/blob/db79d76e5abdb71bbf4baf8d9c3c08ba5ea08d20/src/viewDirective.js#L143
I guess it's because with ngAnimate active the 'enter' and 'leave' are promises.

**Comment by allenhwkim** [comment]
hmm, very interesting. I personally never use ngAnimate, so I am not a good candidate to answer your question. Anyone can help @flc

**Comment by allenhwkim** [comment]
Closing this inactivity and out of scope. Please reopen a new issue if problem is consistent.
