### ISSUE TITLE
Removing draggalbe makes no effect to map

### ISSUE THREAD

**Issue by lluiscanals** [allenhwkim/angularjs-google-maps#493]
Hi @allenhwkim!
    I've remove draggable="true" from your directions.html example with no effect to the map. You can see in this plunkr example.

http://plnkr.co/edit/OQ96CRVp0z2rxiELaNI0?p=preview

Thanks in advance!

**Comment by allenhwkim** [comment]
draggable="true" means you can change directions by dragging markers. 
draggable="true  means you can NOT change directions by dragging markers.

**Comment by lluiscanals** [comment]
Oh sorry I misunderstood the draggable keyword. I was thinking that this avoids the interaction with the mouse when scrolling because is annoying the zoom in/out when going up/down through the page.

**Comment by allenhwkim** [comment]
closing this
