### ISSUE TITLE
turning drawing manager on and off on click

### ISSUE THREAD

**Issue by samriddhi** [allenhwkim/angularjs-google-maps#494]
Hi @allenhwkim!
I have been trying to turn drawing manager on by changing drawingControl dynamically using multiple scope variables, even the provided ones. 
 $scope.vm.map.mapDrawingManager[0].drawingControl = false;
 $scope.vm.map.drawingControl = true;

That doesnt seem to turn on drawing manager. I did manage to do it with native google code by initializing the manager but then I couldn't get any data back. Is there a way I can turn this feature on and off without having to duplicate the map?

**Comment by allenhwkim** [comment]
Documentation here.

Try this `map.mapDrawingManager[0].setOptions({drawingControl:false})`

**Comment by beaver71** [comment]
why not observe also drawingControl attribute changes?

**Comment by samriddhi** [comment]
I have tried that before it changes the object but doesn't affect the map itself.
Also looking into the code it seems you have a TODO listed on the drawing manager area to implement it
