### ISSUE TITLE
NgMap location name error handling

### ISSUE THREAD

**Issue by 4tee** [allenhwkim/angularjs-google-maps#495]
Hi I am new to Angularjs and NgMap. I find it very interesting and thanks for this cool NgMap library. I have a question for direction. I have a start point, startP and an end point, endP. They are usually location name, eg. 1135 Karamea-Kohaihai Rd, Kahurangi National Park, Tasman.

My question is if startP or endP location name is not a valid location name or any error during ng-map loading/processing, how should i handle the error? is there any callback for geo coding error? Appreciate if you can show some code. Thanks a lot. Cheers.

```javascript
<ng-map zoom="14"
  center="{{ StartPoint }}"
  style="height:90%" >

  <directions
  draggable="true"
  panel="directions-panel"
  travel-mode="DRIVING"
  origin="{{ startP }}"
  destination="{{ endP }}">
   </directions>
</ng-map>
```

**Comment by allenhwkim** [comment]
You can use GeoCoding API, https://developers.google.com/maps/documentation/geocoding/intro
or Directions API, https://developers.google.com/maps/documentation/directions/
before you set origin and destination.

I don't think there is a callback to let you know that it's a wrong point or not, AFAIK.

**Comment by allenhwkim** [comment]
Closing this as "out of scope"
