### ISSUE TITLE
NgMap and ui-router $reload

### ISSUE THREAD

**Issue by Vandersteen** [allenhwkim/angularjs-google-maps#497]
Using the NgMap and $state.reload from ui-router I encountered the following issue:

HTML looks like:

```
<div map-lazy-load="...">
  <ng-map class="GMap" id="Map" lazy-init="true" default-style="false" zoom-to-include-markers="true">
      ... //Markers and so on
  </ng-map>
</div>
```

In the Contoller:

```
$http
    .get()
    .then(function() {
        ...

        NgMap.initMap('Map');
    });
```

This works on the first load. But on `$state.reload()`

I get the following error:

> angular.js:12520 TypeError: Cannot read property 'map' of undefined
    at Object.initMap (ng-map.js:2709)
    at map.controller.js:39
    at processQueue (angular.js:14792)
    at angular.js:14808
    at Scope.$eval (angular.js:16052)
    at Scope.$digest (angular.js:15870)
    at Scope.$apply (angular.js:16160)
    at done (angular.js:10589)
    at completeRequest (angular.js:10787)
    at XMLHttpRequest.requestLoaded (angular.js:10728)

Code at those lines:

```
  /**
   * @memberof NgMap
   * @function initMap
   * @param id optional, id of the map. default 0
   */
  var initMap = function(id) {
    var ctrl = mapControllers[id || 0];
    if (!(ctrl.map instanceof google.maps.Map)) {
      ctrl.initializeMap();
    } else {
      void 0;
    }
  };
```

Also using:

```
NgMap.getMap().then(function() {
    console.log('initing map');
});
```

Inside the $http.get().then( `here` ) does not seem to fire on first load or reloads.

**Comment by allenhwkim** [comment]
I only have this example to debug your issue, http://ngmap.github.io/#/!map-lazy-inint.html.
Could you create an another example using ui-router to reproduce this issue?

**Comment by Vandersteen** [comment]
I will get back to you as soon as I get the opportunity.

For now I went a round the problem and sent the users to the dashboard without a map on `reload`.

Thank you for the example.

**Comment by rustywebguy** [comment]
I encountered same problem. But for me the maps should be triggered as soon as page reload. So what
I did is I watch google scope. I don't know if this is the solution but it works for me.

`$scope.$watch('google', function(google){
        $scope.map = NgMap.initMap('map');
 });`

**Comment by allenhwkim** [comment]
Still waiting for example ..

**Comment by idrenski** [comment]
@rustywebguy Can you give more completed example how it works for you?

**Comment by allenhwkim** [comment]
Closing it for inactivity, please create another issue if you want to reopen it.

**Comment by rolintoucour** [comment]
I cannot provide a full example. However I noticed the following behavior:

I have a state 'mystate' with a param 'id'. There might be links from various 'mystate' to various 'id'. On each 'mystate' a ng-map is displayed.

Opening the first 'mystate' => ng-map is OK
From it I open another 'mystate' => it crashes (because in initMap the ctrl is undefined)
I go to any other state (=! 'mystate'), then back to any 'mystate' => ng-map is OK

It seems that, staying on the same state with various parameters throws the error (it seems that changing the parameter clears the controller but doesn't initiate it again).

**Comment by ElPsyCongro** [comment]
+1

**Comment by ElPsyCongro** [comment]
I have an issue that is something like that ... I open state_1 where i have a button that takes me to other state (state_2) where it is my ngmap and it loads well... then I go back to state_1 y click the button that takes me to state_2 again and my ngmap it looks weird and it doesn't charge well.

**Comment by ElPsyCongro** [comment]
I use... 
NgMap.getMap().then(function(map){
    $scope.map=map;
});
...on my controller... Am I using it wrong?
