### ISSUE TITLE
info Window shows/stuck in top left corner

### ISSUE THREAD

**Issue by MortezaAghili** [allenhwkim/angularjs-google-maps#498]
When i click on a marker, the info window shows/stuck in top left corner but it should display at top of the marker.

<img width="356" alt="screen shot 2016-01-29 at 1 38 24 pm" src="https://cloud.githubusercontent.com/assets/6826680/12677978/9a883ae8-c6b1-11e5-973b-6824c94d54a6.png">

this element style should be set left and top css property dynamic for every marker's infoWindow. but if you look at generated element, you see there is no left or top css property...
and one more thing, when i drag the map, and try clicking a marker again, its display at the previous place.
```
<div class="ng-map-info-window" 
     style="cursor: default; 
            position:absolute; 
            width: 110px; 
            height: 84px;>
```
this is my angularjs controller for show and hide the info window

```
vm.showDetail = function (e, p) {
    vm.p = p;
    vm.map.showInfoWindow('foo-iw', p.locationId);
};

vm.hideDetail = function () {
    vm.map.hideInfoWindow('foo-iw');
};
```
and this is my ui

```

<marker id='{{p.locationId}}' 
                   ng-repeat="p in locations track by $index" 
                   position="[{{p.locationX}},{{p.locationY}}]" 
                   on-click="vm.showDetail(p)">
                <marker>     
<info-window id="foo-iw">
           <div ng-non-bindable="">
                id: {{vm.p.locationId}}<br/>
                name: {{vm.p.locationName}}<br/> 
                <a href="#" ng-click="vm.clicked()">Click Here</a>
           </div>
     </info-window>

```

* i use ng-map in Ionic/Angular project. 
thanks

**Comment by allenhwkim** [comment]
This normally happens when the anchor is not clearly defined for the infoWindow.  For your case `p.locationId` must be a maker id. 

I am pretty sure you follow this example, http://ngmap.github.io/#/!infowindow_ng_click.html, but you may take a look at it again and find out the difference. I do not see that much difference between the example and your requirement.

**Comment by MortezaAghili** [comment]
You're right @allenhwkim . In my code the anchor is not clearly defined for the infoWindow  if i use **this** instead p.location the error will be gone...

thanks

**Comment by rodrigosaling** [comment]
Sorry to post this on a closed issue, but for anyone out there, struggling to make your code work, being it the same as the `infowindow_ng_click.html` example, here is the thing: the `id="{{p.id}}"` can't be just numbers.

I was not aware of that HTML requirement and spent hours trying to figure out what was wrong with my code. So now I use like this `id="m{{p.id}}"` with a single char and everything works.

**Comment by jasekz** [comment]
Thank you @rodrigosaling , great fix.  Strangely, this works as expected on my local machine with only a numeric id, but not on the production server.

**Comment by liamlaverty** [comment]
@rodrigosaling thanks for this update - if anyone else appears here in the future, you also need to update your showInfoWindow() function

`<marker id="m{{foo.Id}}" 
                         position="[{{foo.GpsLat}}, {{foo.GpsLong}}]"
                            ng-repeat="foo in fooCollecion"
                            title="{{foo.name}}"
                            on-click="showFooDetail(event, foo)">
                        </marker>`

  `<info-window id="fooIw">
                            <div ng-non-bindable="">
                               <h4>{{selectedFoo.name}}</h4>
                            </div>
                        </info-window>`

and then in your controller

`
$scope.fooCollecion = [...foos go here...];
$scope.selectedFoo = $scope.fooCollecion[0];
$scope.showFooDetail = function(evt, myFoo){
            console.log("showing detail for " + JSON.stringify(myFoo));
            $scope.selectedFoo = myFoo;
            $scope.map.hideInfoWindow('fooIw');
            $scope.map.showInfoWindow('fooIw', 'm' + myFoo.Id); 

        }`

This works for multiple info windows, as well as without an ng-click event on any marker

**Comment by AllanD1** [comment]
vm.showDetail = function (e, p) {
    vm.p = p;
    vm.map.showInfoWindow('foo-iw', this);
};

use 'this'

**Comment by superburrito** [comment]
Highlighting a detail from the demo that fixed things for me:
Instead of writing `on-click="showDetail(ev, coord)"` in your template HTML, try passing coord as a single arg: `on-click="showDetail(coord)"`. However, in your JS controller, continue to define showDetail with two args: `$scope.showDetail = (ev, coord) => { ... } `.
