### ISSUE TITLE
NOTICE: Please help me by answering issues.

### ISSUE THREAD

**Issue by allenhwkim** [allenhwkim/angularjs-google-maps#499]
Hi, ng-map users.

This project is not officially maintained by a sponsor or a company. I personally spend my extra time at night or weekend to answer/improve the quality of ng-map.

Recently, I have been sick, moved to a new company,  and started renovation of my basement. My family also has been sick recently.

Bottom line: I can't find my time for this ng-map for few months, min. two months. I still can answer simple questions, but debugging and improving is a different story.

Please help me if you are interested in answering questions. So that not only I answer the questions, you guys can answer each other's question so that we can close issues.

Allen Kim

**Comment by jasongb** [comment]
I've just started with Angular, Ionic and so on - but ng-map has been a great tool so far.  Thanks for working so hard on it!

I hope you and your family get better, and that your life settles down to a regular rhythm.  Take care of yourself and your family first!

**Comment by allenhwkim** [comment]
thanks @jasongb. Renovation is done, and my house is sold. Things got better. I will do more than the last month for this project.
