### ISSUE TITLE
Markers on page 1 still present in page 2

### ISSUE THREAD

**Issue by Eralph** [allenhwkim/angularjs-google-maps#501]
I have a page that serves map with custom markers, but when I visit page 2, the markers are still there which supposedly should not since I am not making any markers in page 2. This is a single page application.

Anybody experienced this issue? How did you go around with it?

**Comment by allenhwkim** [comment]
Can you create a plunker example for this issue?

**Comment by Eralph** [comment]
here is the plunker example

https://plnkr.co/edit/7XlEwsQ9RqNqDhagG3jk?p=preview

as you can see, in the page2Controller, i have not added any markers yet but the markers from page 1 still shows.

**Comment by Eralph** [comment]
checked out the closed issues and found #475

viola!

it solved my problem! sometimes its good to dig a little deeper into the closed ones.

thanks
