### ISSUE TITLE
Set polygon as default in drawing mode

### ISSUE THREAD

**Issue by faidoc** [allenhwkim/angularjs-google-maps#502]
Hi

I am trying to activate by default the polygon on drawing mode but it doesn't seem to work.

I have drawingMode to "polygon" and still:

```
<div map-lazy-load="https://maps.google.com/maps/api/js" map-lazy-load-params="https://maps.google.com/maps/api/js?libraries=drawing,geometry,visualization">
    <ng-map center="[-12.097828, -77.030406]" scrollwheel="true" zoom="14" style="height:500px" street-view-control="false" map-type-control="false">
      <drawing-manager
        on-overlaycomplete="geofences.onMapOverlayCompleted()"
        drawing-control-options="{position: 'TOP_CENTER',drawingModes:['polygon']}"
        drawingControl="true"
        drawingMode="polygon"
        polygonOptions="{fillColor:'#01539f', strokeColor: '#01539f', editable: true}">
      </drawing-manager>
    </ng-map>
</div>
```

What am I missing?

**Comment by faidoc** [comment]
Sorry, I just saw the answer on another issue here

https://github.com/allenhwkim/angularjs-google-maps/issues/494

**Comment by neelshah23** [comment]
Getting same issue, Can any one help me this

I want polygon as my default marker, Here is my code:

` <drawing-manager
                on-overlaycomplete="onMapOverlayCompleted()"
                drawing-control-options="{position: 'RIGHT_TOP',drawingModes:['polygon']}"
                drawingControl="true"
                drawingMode="polygon"
                rectangleOptions="{fillColor:'red'}"
                polygonOptions="{fillColor: 'rgba(255,0,0,0.4)',fillOpacity: 1,strokeWeight: 3,clickable: true,zIndex: 1,editable: true}" >
              </drawing-manager>`

**Comment by luiscastillos** [comment]
drawingMode: google.maps.drawing.OverlayType.POLYGON
