### ISSUE TITLE
Event on polygon change

### ISSUE THREAD

**Issue by faidoc** [allenhwkim/angularjs-google-maps#503]
Hi

How can I listen to an event when a polygon with the editable set to true, is changed?

**Comment by allenhwkim** [comment]
Please take a look at the events section of this document
https://developers.google.com/maps/documentation/javascript/reference#Polygon

You can use `on-EVENTNAME="myFunc()"`

**Comment by faidoc** [comment]
Hi, thanks

I finally made it with:

```
google.maps.event.addListener(polygon, 'insert_at', function() {
    vm.finalForm.paths = e;
});
google.maps.event.addListener(polygon, 'set_at', function() {
    vm.finalForm.paths = e;
});
```
