### ISSUE TITLE
Use provideRouteAlternatives?

### ISSUE THREAD

**Issue by alaeMellon** [allenhwkim/angularjs-google-maps#504]
Hello,

is it possible to show route alternatives?
https://developers.google.com/maps/documentation/javascript/3.exp/reference#DirectionsRendererOptions
When I use provideRouteAlternatives="true" nothing happens...

Thanks,
alaeMellon

**Comment by allenhwkim** [comment]
That's a DirectionsRequest option, not a part of DirectionsRenderer options.

**Comment by alaeMellon** [comment]
thanks, i got it!
