### ISSUE TITLE
Info window stuck in top left corner for custom marker

### ISSUE THREAD

**Issue by k-ljung** [allenhwkim/angularjs-google-maps#505]
I'm using custom marker and try to show an info window but it gets stuck in the top left corner, I have seen your examples and also found the case #498 but the difference is the custom marker. I have tried to add id attribute on the custom marker markup but then my custom markers get placed on wrong locations on the map.

This example does not work for me, I cannot use the r id="'{{eventLocation.id}}'"
<custom-marker id="'{{eventLocation.id}}'"
						   ng-repeat="eventLocation in vm.eventLocations"
						   position="{{eventLocation.location.latitude}}, {{eventLocation.location.longitude}}">

//Kalle

**Comment by MortezaAghili** [comment]
@k-ljung take a look at my issuse, its solved 
https://github.com/allenhwkim/angularjs-google-maps/issues/498#issuecomment-177223826

**Comment by k-ljung** [comment]
Thank you @MortezaAghili but the problem is that a custom marker does not support to use an Id.

**Comment by allenhwkim** [comment]
Updated the example for this, testapp/custom-marker-ng-repeat.html 

```
  <ng-map zoom="8" center="[40.74, -74.18]" default-style="true">

    <custom-marker ng-repeat="p in vm.positions track by $index"
      id="custom-marker-{{$index}}"
      on-click="vm.map.showInfoWindow('foo', 'custom-marker-'+$index)"
      position="{{p.pos}}">
      <div>
        position {{p.name}}: {{p.pos[0]}}, {{p.pos[1]}}
      </div>
    </custom-marker>

    <info-window id="foo" on-mouseover="vm.mouseover()">
      <div ng-non-bindable="">
        Lat: {{anchor.getPosition().lat()}}<br/>
        Lng: {{anchor.getPosition().lng()}}<br/>
      </div>
    </info-window>

  </ng-map>
```

**Comment by allenhwkim** [comment]
Closing this, please open another issue if you have more questions.

**Comment by celsomtrindade** [comment]
Just to comment on this issue.
I had the same problem when using id as int number. The way I solved this was to convert the ID to string:

    vm.map.showInfoWindow('infoId', data.id.toString());

**Comment by cecchisandrone** [comment]
You saved my day!
