### ISSUE TITLE
Using streetview with the address detail rather than lat/lang values

### ISSUE THREAD

**Issue by rcadhikari** [allenhwkim/angularjs-google-maps#507]
Hi Guys,

could you please confirm whether we could be able to display the street view from the address out of the box. If not what would be the wayout for that.

Any help would be really appreciated.

Cheers!

**Comment by allenhwkim** [comment]
Yes, Please look at this example, http://plnkr.co/edit/0mkiBHcYXWbdIuOEDv1J?p=preview

**Comment by rcadhikari** [comment]
Thanks for that.

Just noticed that there is some issu on the on the [example ](http://plnkr.co/edit/0mkiBHcYXWbdIuOEDv1J?p=preview) provided, where we need to remove the commented code below to make the correct location for street view.

  ```
<ng-map zoom="20" center="150 London Wall, London EC2Y 5HN" >    
    /* <marker position="40.740, -74.18"></marker> */
    <street-view-panorama
      click-to-go="false"
      disable-default-u-i="false"
      disable-double-click-zoom="false"
      /* position="40.740, -74.18" */
      pov="{heading: heading, pitch: pitch}"
      scrollwheel="false"
      enable-close-button="true"
      visible="true">
    </street-view-panorama>
  </ng-map>
  <div id="streetview" style="width: 100px; height: 100px"></div>
```

**Comment by allenhwkim** [comment]
Closing this
