### ISSUE TITLE
DrawingManager markerOptions icon object.

### ISSUE THREAD

**Issue by luncht1me** [allenhwkim/angularjs-google-maps#508]
Can we not use custom icons in the Drawing Manager for drawing Markers???

With the following code, I get the default marker icon...

```
<drawing-manager
    drawing-control-options="{position: 'TOP_CENTER',drawingModes:['marker']}"
    drawingControl="true"
    drawingMode="MARKER"
    markerOptions="{
        draggable:true,
	    icon: {url:'./img/transparent-circle-marker.png', 
            origin: [0,0], 
            anchor: [12,12]}
	    }"
     on-overlaycomplete="onMapOverlayCompleted()"
> 
```

But, if I change `icon:` to `icon: {url: './img/transparent-circle-marker.png'}` without the anchor property I get my custom marker image.... but it of course isn't anchored properly! >:(

Am I missing something? Or is this just not implemented?

**Comment by allenhwkim** [comment]
It seems like `anchorPoint`, not `anchor` according to https://developers.google.com/maps/documentation/javascript/reference#MarkerOptions

**Comment by luncht1me** [comment]
I've yet to test it, but thanks for the reply. I didn't find this on my own lol. :+1:

**Comment by allenhwkim** [comment]
Closing it.
