### ISSUE TITLE
Can't apply style to map

### ISSUE THREAD

**Issue by Moqadi** [allenhwkim/angularjs-google-maps#509]
Hi,

I have tried applying style to ngmap, but it does not take the effect with no errors on the console.

I am using the following array to apply the style using  map.data.setStyle(styles);

var styles = [
  {
    "elementType": "geometry",
    "stylers": [
      {
        "hue": "#ff4400"
      },
      {
        "saturation": -68
      },
      {
        "lightness": -4
      },
      {
        "gamma": 0.72
      }
    ]
  },
  {
    "featureType": "road",
    "elementType": "labels.icon"
  },
  {
    "featureType": "landscape.man_made",
    "elementType": "geometry",
    "stylers": [
      {
        "hue": "#0077ff"
      },
      {
        "gamma": 3.1
      }
    ]
  },
  {
    "featureType": "water",
    "stylers": [
      {
        "hue": "#00ccff"
      },
      {
        "gamma": 0.44
      },
      {
        "saturation": -33
      }
    ]
  },
  {
    "featureType": "poi.park",
    "stylers": [
      {
        "hue": "#44ff00"
      },
      {
        "saturation": -23
      }
    ]
  },
  {
    "featureType": "water",
    "elementType": "labels.text.fill",
    "stylers": [
      {
        "hue": "#007fff"
      },
      {
        "gamma": 0.77
      },
      {
        "saturation": 65
      },
      {
        "lightness": 99
      }
    ]
  },
  {
    "featureType": "water",
    "elementType": "labels.text.stroke",
    "stylers": [
      {
        "gamma": 0.11
      },
      {
        "weight": 5.6
      },
      {
        "saturation": 99
      },
      {
        "hue": "#0091ff"
      },
      {
        "lightness": -86
      }
    ]
  },
  {
    "featureType": "transit.line",
    "elementType": "geometry",
    "stylers": [
      {
        "lightness": -48
      },
      {
        "hue": "#ff5e00"
      },
      {
        "gamma": 1.2
      },
      {
        "saturation": -23
      }
    ]
  },
  {
    "featureType": "transit",
    "elementType": "labels.text.stroke",
    "stylers": [
      {
        "saturation": -64
      },
      {
        "hue": "#ff9100"
      },
      {
        "lightness": 16
      },
      {
        "gamma": 0.47
      },
      {
        "weight": 2.7
      }
    ]
  }
]

**Comment by Moqadi** [comment]
Please note that I am using ngmap version 1.13.14, if it's a valid bug, can we do a fix on the same version ?

**Comment by Moqadi** [comment]
Any updates about this ??

**Comment by Moqadi** [comment]
@allenhwkim

**Comment by allenhwkim** [comment]
Sorry I have no updates for this since I m not working on older version. I may look into your issue with the recent version and let you know what happens

**Comment by Moqadi** [comment]
Actually I have tried on the recent version and got the same result.

**Comment by Moqadi** [comment]
Any updates on this @allenhwkim ?

**Comment by allenhwkim** [comment]
Please provide me a plunker example for this.

**Comment by w0ns88** [comment]
I have found the answer from this question: [741](https://github.com/allenhwkim/angularjs-google-maps/issues/741)

JS:
```
vm.mapStyle = [
            //your style here
        ];
```
HTML:
` <ng-map center="[56.028122, 10.122942]" zoom="7" styles="{{vm.mapStyle}}">`
