### ISSUE TITLE
New Release with UMD-Support

### ISSUE THREAD

**Issue by brunnurs** [allenhwkim/angularjs-google-maps#510]
Hi @allenhwkim 
Would it be possible to release a new _npm_-version with the new UMD-Support? It would help me & everyone who uses Browserify or similar tools to include your nice library in his project, directly from the `node_modules `.
I tested the UMD-Support with Browserify, it fixes also my issue #434. Many thanks @nkovacic for your PR!

**Comment by brunnurs** [comment]
For everyone using Browserify: You can now include the ngMap-library this way into your angular-app:

```javascript
var app = angular.module('myProject', [
    require('ngmap'),
    require('angular-ui-router'),
    require('angular-animate'),
    require('angular-resource'),
    require('angular-ui-bootstrap'),
    require('ng-file-upload'),
    require('angular-smart-table'),
    require('angular-cookies'),
    require('angular-translate'),
    require('angular-dynamic-locale')
```

**Comment by claywhipkey** [comment]
@brunnurs I keep getting `[$injector:modulerr]` errors when trying to add ngMap as a dependency the way you showed above. Can you share what you did in your package.json? Also, did you install via Bower or NPM?

**Comment by claywhipkey** [comment]
Nevermind. I discovered that the default bower install goes to the last tagged version, which didn't include the latest commit with UMD support. I was able to install it via NPM with this in my package.json:

```"dependencies": {
      "ngmap": "git+ssh://git@github.com:allenhwkim/angularjs-google-maps.git"
  }```

Combining this with the injection example above and now I am able to use the directives and the `NgMap` provider.

**Comment by nkovacic** [comment]
+1 for a new NPM release. Would be helpful for us browserify/webpack users.

**Comment by brunnurs** [comment]
@claywhipkey :thumbsup: I also use the direct-github dependency as you do, it's the only option AFAIK until the new version is released. From my point of view it's a great thing to inject the dependencies with browserify/webpack. Cleaner, less code, lot easier in maintanace and ready for the future (ecmascript 6 modules - http://www.2ality.com/2014/09/es6-modules-final.html).

Btw. I don't use bower, just npm. Don't see any reason to use bower as a second package-manager, as all my dependencies are on npm as well.

**Comment by allenhwkim** [comment]
sorry guys, just published npm.

**Comment by brunnurs** [comment]
Thx @allenhwkim
