### ISSUE TITLE
Minimum circle radius 

### ISSUE THREAD

**Issue by hanselsen** [allenhwkim/angularjs-google-maps#512]
Is it possible to prevent a user from creating a circle smaller then X meters?

**Comment by joshkopecek** [comment]
You could try putting a custom filter on the radius field 
``
<ng-map center="37.09024, -95.712891" zoom="4" mayTypeId="TERRAIN">
    <shape name="circle" ng-repeat="circle in vm.circles" no-watcher="true"
      stroke-color="#FF0000"
      stroke-opacity="0.8"
      stroke-weight="2"
      fill-color="#FF0000"
      fill-opacity="0.35"
      center="{{circle.position}}"
      radius="{{circle.radius | minRadius : 20)}}">
    </shape>
  </ng-map>
``
and something like:
``
app.filter('minRadius', function(){
    return function(input, min) {
      return input < min ? min : input;
    };
  });
``
Caveat: I haven't tested this at all, and I'm not sure if NgMaps will update the radius if you do it like this.

**Comment by hanselsen** [comment]
That's a great suggestion, but sadly this does not work.
The value in circle.radius is fine, but the UI still lets me re-size it to
smaller than the minRadius.

Op za 13 feb. 2016 om 18:45 schreef Josh <notifications@github.com>:

**Comment by joshkopecek** [comment]
You have to do some trickery with the radius change events then. Can you
create a plunkr with some example code?

On Sun, 14 Feb 2016, 09:26 Hans van den Elsen <notifications@github.com>
wrote:

> That's a great suggestion, but sadly this does not work.
> The value in circle.radius is fine, but the UI still lets me re-size it to
> smaller than the minRadius.
>
> Op za 13 feb. 2016 om 18:45 schreef Josh <notifications@github.com>:
>
> > You could try putting a custom filter on the radius field
> >
> > <ng-map center="37.09024, -95.712891" zoom="4" mayTypeId="TERRAIN">
> > <shape name="circle" ng-repeat="circle in vm.circles" no-watcher="true"
> > stroke-color="#FF0000"
> > stroke-opacity="0.8"
> > stroke-weight="2"
> > fill-color="#FF0000"
> > fill-opacity="0.35"
> > center="{{circle.position}}"
> > radius="{{circle.radius | minRadius : 20)}}">
> > </shape>
> > </ng-map>
> >
> > and something like:
> >
> > app.filter('minRadius', function(){
> > return function(input, min) {
> > return input < min ? min : input;
> > };
> > });
> >
> > Caveat: I haven't tested this at all, and I'm not sure if NgMaps will
> > update the radius if you do it like this.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/allenhwkim/angularjs-google-maps/issues/512#issuecomment-183712532
> >
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/allenhwkim/angularjs-google-maps/issues/512#issuecomment-183860350>
> .
>
-- 
https://echoes.xyz

**Comment by hanselsen** [comment]
You can probably use the plunkr on this page.

https://ngmap.github.io/#/!shape.html

Op zo 14 feb. 2016 12:04 schreef Josh <notifications@github.com>:

**Comment by allenhwkim** [comment]
There is `radius_changed` event. You can make use of it.

https://developers.google.com/maps/documentation/javascript/3.exp/reference#Circle

Example;
http://plnkr.co/edit/FBJrp3RKLGZuzr1YCY8F?p=preview

**Comment by hanselsen** [comment]
In your plunkr, I can still change the radius to smaller than 4000. So not closed.

**Comment by allenhwkim** [comment]
```
angular.module('ngMap').controller("MyCtrl", function($scope){
  this.radiusChanged = function(event) {
    if (this.radius < 4000) {
      this.setRadius(4000);
    }
  }
})
```
