### ISSUE TITLE
dynamically change drawing manager's drawing mode

### ISSUE THREAD

**Issue by Tallyb** [allenhwkim/angularjs-google-maps#513]
I have tried to build my own drawing manager tool selection, by setting a variable on the drawing-mode property of the drawing manager. 
Unfortunately, this does not work. Any suggestions? 
See plunker here: http://plnkr.co/edit/JI1WyUlzKAYnRnYobUhm?p=preview

**Comment by allenhwkim** [comment]
I think you want to build your own custom drawing control, by setting `drawingControl="true"`, which is never tried by other before IMO. I think DrawingManager and drawing control is tightly related, and I am not even sure that you can build your own drawing control.

**Comment by Tallyb** [comment]
Dear @allenhwkim 
Thanks for the quick response and a great library. 
I did manage to get it to work: http://plnkr.co/edit/MaUzotgjfWnojdhWiqsf?p=preview
[I know the buttons look really lame, but as they are on normal HTML I can do whatever I want with them... ]
I do not think it takes a lot to combine them into the directive, but I am currently under very tight schedule. Once I will have a bit more spare time I will try to include it.

**Comment by allenhwkim** [comment]
Thanks @Tallyb Loving it. Simple solutiojn and  It looks good.
