### ISSUE TITLE
map options are not dynamically evaludated

### ISSUE THREAD

**Issue by Tallyb** [allenhwkim/angularjs-google-maps#514]
See this plunker for dynamically changing draggable on and off. 
http://plnkr.co/edit/ng5ff4VUiouvKaH21OYq?p=preview

Is this a bug or a feature? ;)

**Comment by allenhwkim** [comment]
Dynamic evaluation only happens if it has set options. e.g. `setDraggable`
According to the documentaion, https://developers.google.com/maps/documentation/javascript/reference, it does not have that method, which users need to implement it manually.

**Comment by Tallyb** [comment]
mmm... then I would expect something like this to work: http://plnkr.co/edit/ctm8vuq7IhgGYAy3iZGp?p=preview
Or is this a problem with observing / watching object attributes?

**Comment by allenhwkim** [comment]
You need to use map.setOptions({draggable: false})
Please take a look at this example ; http://plnkr.co/edit/6tuVdz?p=preview
