### ISSUE TITLE
Circle shaped with dashed lines

### ISSUE THREAD

**Issue by ccasallas** [allenhwkim/angularjs-google-maps#515]
Hi,

I am trying to draw a circle with dashed lines following "http://ngmap.github.io/#/!overlay-symbol-dashed.html" example, but it does not works:

`<shape name="circle"
           stroke-color="#FF0000"
           stroke-opacity="0.3"
           stroke-weight="2"
           fill-opacity="0"
           center="[0,0]"
           icons="[{
        icon: {
          path: 'M 0,-1 0,1',
          strokeOpacity: 1,
          scale: 4
        },
        offset: '0',
        repeat: '20px'
      }]"
           radius="1000">
    </shape>`

Do I missing something? or it is a bug?

thanks,

Carlos

**Comment by allenhwkim** [comment]
AFAIK, this is not possible. The closest solution I found is using polyline, which is complex, http://stackoverflow.com/questions/19181762/how-to-stylize-a-circle

**Comment by ccasallas** [comment]
Ok, thanks for your help and thanks for this great google maps directive.
