### ISSUE TITLE
Missing one closing tag

### ISSUE THREAD

**Issue by Warlord08** [allenhwkim/angularjs-google-maps#516]
Hello,

not an actual issue, but a small fix - on the layer-fusionables-heatmap HTML file, there's one element that was not closed properly. This might not cause the application to crash (as far as I know) but still, might let you know about it.

Current code: 

> `<fusion-tables-layer
>         query= "{ select: 'location',
>           from: '1xWyeuAhIFK_aED1ikkQEGmR8mINSCJO9Vq-BPQ'}",
>         heatmap = "{enabled: true}"
>       </fusion-tables-layer>`

Fix:

> `<fusion-tables-layer
>         query= "{ select: 'location',
>           from: '1xWyeuAhIFK_aED1ikkQEGmR8mINSCJO9Vq-BPQ'}",
>         heatmap = "{enabled: true}">
>       </fusion-tables-layer>`

**Comment by allenhwkim** [comment]
thanks
