### ISSUE TITLE
Custom Control index does not do anything

### ISSUE THREAD

**Issue by manish2535** [allenhwkim/angularjs-google-maps#519]
In this example - http://ngmap.github.io/#/!control-custom-state.html

If you go to plunker and change the index of the 2 custom controls, it does not do anything.

**Comment by allenhwkim** [comment]
This is the strict implementaton of this example. https://developers.google.com/maps/documentation/javascript/examples/control-custom

I doubt that index does any on to custom control. You can ignore it.
