### ISSUE TITLE
Would like to wait for id attribute to load before addMap() in lazy init

### ISSUE THREAD

**Issue by galenmarchetti** [allenhwkim/angularjs-google-maps#520]
Currently, the attribute "id" on the map object is established when the template is compiled. This means that if you are trying to lazy load a map in order to wait for an id to be loaded from the server (for example, having a map labeled for each object stored in a database), you seem to be out of luck.

Happens here:
https://github.com/allenhwkim/angularjs-google-maps/blob/master/controllers/map-controller.js#L234

This is important because I am trying to maintain a mapping between id's stored in a database and maps created in the front end. It seems that the "map" object returned by ngMap.getMap() always points to the most recently returned map, and not a specific map. Therefore when ngMap.getMap() is called for different id's, all objects references that were created on previous calls point to the most recently retrieved map and not the map they were pointing to when they were originally created. Thus if I try to create my own datastructure to keep track of maps using my custom id's, I will only ever be able to point to the most recently retrieved map. This is only a problem if these id's are generated asynchronously from a database rather than hardcoded in a plunker.

If my understanding as described above is incorrect, please correct me. 

I resolved my specific use case by wrapping ng-map in my own directive and using the scopeID (scope.$id) as my map identifier to keep maps separate and then using other attributes of the scope to maintain the mapping between maps and custom ids.

Is there an interest in incorporating dynamically loaded ID's with lazy initialization, or is this not the purpose of map ID's?

**Comment by galenmarchetti** [comment]
This is somewhat mitigated by https://github.com/allenhwkim/angularjs-google-maps/pull/522

**Comment by allenhwkim** [comment]
Closing this issue assuming it's resolved by #522. If not please reopen it
