### ISSUE TITLE
Remove a particluar polygon after it has been drawn

### ISSUE THREAD

**Issue by osmaanahmed** [allenhwkim/angularjs-google-maps#521]
How to remove a polygon after a user has drawn it?

**Comment by allenhwkim** [comment]
This would be useful, http://stackoverflow.com/questions/12004550/how-to-delete-all-the-shape-after-draw

**Comment by osmaanahmed** [comment]
Thanks @allenhwkim, I got the idea. This can be used inside onMapOverlayCompleted function to remove the selection just added:
event.overlay.setMap(null);

I added a button on top of map and called a function on it's click to  call above function inside onMapOverlayCompleted function.
