### ISSUE TITLE
Help With Integrating angularjs google maps into an ionic app

### ISSUE THREAD

**Issue by bonzysalesman** [allenhwkim/angularjs-google-maps#523]
Hi,
I'm looking for a developer who can assist me with integrating angularjs-google-maps into an ionic app.

I have some code. I just need someone to help me finish it. And I'm going to pay for this.

I apologise if this is the wrong place for this kind of request.

Kind Regards,
Bonzy
bonzys@gmail.com

**Comment by allenhwkim** [comment]
Sorry, I am interested in making more money, but not having enough time for this. Closing it.
Closing this issue. I wish other ng-map users can help you.
