### ISSUE TITLE
Add Custom Marker from angular controller

### ISSUE THREAD

**Issue by ccasallas** [allenhwkim/angularjs-google-maps#524]
Hi,

We are having problems using ng-repeat to draw custom markers in Android WebView, seems there is a bug with android WebView. Does Ng-map have  any alternative to add custom markers programmatically from angular controller (using CustomMarker and map objects), some like:

http://plnkr.co/edit/OeRATG?p=preview

thanks,

Carlos

PS: sorry for my english.

**Comment by allenhwkim** [comment]
Short Answer:NO
Long Answer: Possibliy Yes in the future

As you see [here](https://github.com/allenhwkim/angularjs-google-maps/blob/master/directives/custom-marker.js), CustomMarker is not exposed as a service, but a part of a directive.

You can copy/paste that code, and make your own class until we  make CustomMarker as a separate class.

**Comment by allenhwkim** [comment]
Closing this as answered. I will make this feature as an enhancement in the future release.

**Comment by ccasallas** [comment]
ok, thanks!

**Comment by HuaHub** [comment]
Is this possible now (adding more markers from the controller)?
