### ISSUE TITLE
angularjs-google-maps and ng-inspector

### ISSUE THREAD

**Issue by bponder** [allenhwkim/angularjs-google-maps#525]
1st of all love the ng maps package.  However there is some issue with ng-maps and ng-inspector.  When ng-maps directive is used on a page then ng-inspector loads with a gray screen.  Is there anyway to get this fixed?  I know the owner is likely investing his own time into this project and I know how valuable time is, that being said I could donate to get this issue resolved if that would help :)

**Comment by allenhwkim** [comment]
I don't know what's wrong with ng-inspector. Personally, I would not open an inspector to DOM, which seems ng-inspector does, unless it's a shadow DOM. I recommend to use console command or Batarang instead.

![image](https://cloud.githubusercontent.com/assets/1437734/13375373/6706c51a-dd6b-11e5-9789-9d28fb6694ee.png)

**Comment by bponder** [comment]
Understand...

Well it's just that ng-inspect is very simple to use and batarang seems to be full of issues.  Console well yeah I should probably learn how to debug with.  

I've read before that applications that have issues with ng-inspect likely have something modified in the bootstrap process.  I'm honestly not that savy when it come to client side languages so I haven't dove any deeper.

Thanks

**Comment by allenhwkim** [comment]
Hope this article is useful for you. http://blog.ionic.io/angularjs-console/
Closing this unless someone dig into ng-inspector for this issue.
