### ISSUE TITLE
new google.maps.Marker on Ionic makes the app crashes

### ISSUE THREAD

**Issue by xavierxc14** [allenhwkim/angularjs-google-maps#527]
Hi, when I use ngMap within the Ionic Framework all is going well until I need to create some markers from the controller.
I follow the approach on this issue: https://github.com/allenhwkim/angularjs-google-maps/issues/17. But when I try to move the map the app crashes. Someone has solved this problem or have any idea on how to solve it?

**Comment by allenhwkim** [comment]
I would not recommend creating marker from controller. HTML can do it for you. There are several downside for creating marker in your controller

1. Javascript gets bigger and not maintainable
2. If marker is not created by directive, it won't get destroyed. It's your responsibility to maintain markers, which HTML directive does automatically
3. All events, options of a marker also has to be maintained manually.

If all are ok with you, and you still want to create a marker manually and still crashes, please create a plunker to reproduce error.

**Comment by xavierxc14** [comment]
Hi, thanks for your response. I only need to query the position of the markers based on a user action, but I cant know how many markers will generate this action. This is why I create the markers using the controller. Is there any way to do this natively using your directives?

**Comment by allenhwkim** [comment]
there are several examples in ngmap.github.io. please look for event

**Comment by xavierxc14** [comment]
Something like this??
http://ngmap.github.io/#/!event-arguments.html

**Comment by xavierxc14** [comment]
Just found this example: http://ngmap.github.io/#/!event-arguments.html
