### ISSUE TITLE
Markers re-appearing on the wrong map

### ISSUE THREAD

**Issue by schnauss** [allenhwkim/angularjs-google-maps#528]
I've got an issue when using NgMap with ui-router: When I use `NgMap.getMap().then(function(){})` to add markers (instead of `<marker>`), it works fine- until I go to a different state, with a different controller that also uses NgMap, when those markers will appear, unwanted in the new map. This happens even when I address the map by ID in `getMap()`.

[I've created a Plunker here that displays the issue.](http://plnkr.co/edit/3sPxGt0mX5gmLLpiyaN1?p=preview)

Any thoughts?

**Comment by allenhwkim** [comment]
When you create markers without using directive, it won't be collected by ngMap, and it won't be removed when the instance is re-used.

**Comment by BatteryAcid** [comment]
I have the same issue, @allenhwkim please elaborate on 

> it won't be removed when the instance is re-used

I have two separate maps created with directives.  I add a single marker to one using the NgMap service.  When switching views, that marker shows up on the other map, is this expected?
[My plunkr](https://plnkr.co/edit/nO3BZf7qS49LFcjCQNWh?p=preview)

thanks

**Comment by allenhwkim** [comment]
these markers must be added by `<marker>` tag, not by code unless if you want to remove markers manually.
```
      var marker = new google.maps.Marker({
        position: new google.maps.LatLng("28.29", "-80.70")
      });
      marker.setMap(mapResponse);
```

**Comment by allenhwkim** [comment]
I will consider to use map id, so that if map id is different, it may not reuse map instance in a pool. I wish Google can properly distroy map, so that I don't have to use map pool.
