### ISSUE TITLE
Absolute icon url not working

### ISSUE THREAD

**Issue by Sephen** [allenhwkim/angularjs-google-maps#529]
For some reason my markers are not showing when i use an absolute url instead of a relative one.

In my view i use:
`<marker ... icon="{url: '{{markerSrc}}'}"></marker>`

When i do this (in my controller):
`$scope.markerSrc = "/images/marker.png";`
everything works and the icon is shown.

but when i do:
`$scope.markerSrc = "http://complete/path/to/marker/images/marker.png";`
i get an error:

`GET http://localhost:9000/%7Burl:%20'http://complete/path/to/marker/images/marker.png'%7D 404 (Not Found)`
i tried different methods like:
```
<marker ... icon="{url: "'{{markerSrc}}'" }"></marker>
<marker ... icon="{url: "{{markerSrc}}" }"></marker>
<marker ... icon="{url: {{markerSrc}} }"></marker>
```
but none seem to work...

**Comment by allenhwkim** [comment]
Please provide me a plunker example for this issue.

**Comment by Sephen** [comment]
The correct way apparently is:
<marker ... icon="{{markerSrc}}"></marker>

http://stackoverflow.com/questions/35813188/angularjs-google-map-ng-map-icon-url-not-working
