### ISSUE TITLE
ng-map in ng-dialog

### ISSUE THREAD

**Issue by Sofianio** [allenhwkim/angularjs-google-maps#530]
Hi,
I like this module a lot but i have a pb:
I noticed a strange behavior when i put a map inside  `ngDialog`, 
- The 1st time i open the dialog the map shows properly
- When i close & reopen the dialog the map is empty
- Strangely, when i resize the screen (browser) the map finally loads but slightly off position (center is in top-left)

I tried to get the map options to see what's happening, i found that `NgMap.getMap()` doesn't find the map (all the time not just the first one)
Please Help,
Thank you.

**Comment by allenhwkim** [comment]
This has been discussed several times. 
Google map, not ng-map,  does not re-display image properly when an element is redrawn.
You need to resize for the map, and also recenter it. It's not ng-map does, it's how Google map does.
If this answer still does not help you, please create another issue with **plunker example**.

**Comment by Sofianio** [comment]
What worked for me is that i added the ng-map to the layout after the dialog opens & the position is received (ws)
```
$timeout(function(){
    //add map
}, 0);
```
