### ISSUE TITLE
Draw outline around a city

### ISSUE THREAD

**Issue by celsomtrindade** [allenhwkim/angularjs-google-maps#534]
I've seen some people using it but didn't found anything about it.

Is there a way to draw an outline around a specific city? Or even, as a complement, to draw an outline and fill the city?

If this answer could expand to cover how to do the same thing but in an specific area on the map, such as a postal code, region on the city, etc.. 

Thanks!

**Comment by allenhwkim** [comment]
You can use kml layer, http://ngmap.github.io/#/!layer-kml.html

You can find kml layer file for a city form here.
http://stackoverflow.com/questions/29565764/any-way-to-get-a-kml-file-of-city-boundaries

You can find more details about kml here 
https://developers.google.com/maps/tutorials/kml/#overview
