### ISSUE TITLE
Warning Tried to load angular more than once.

### ISSUE THREAD

**Issue by chiptus** [allenhwkim/angularjs-google-maps#535]
When using ngmap in a webpack build, angular is loaded twice, by the map and by the main app. 
Since ngmap is always loaded in an angular app, I don't think it is necessary to load angular again.
What do you think?

Thanks for a great package!

**Comment by allenhwkim** [comment]
ngMap is designed to used(included) by your main app. 
Please use ngmap as a module not as an app for your case.

e.g.
`angular.module('mainMap', ['ngMap'])`

**Comment by chiptus** [comment]
I didn't think otherwise. But I get this warning when I require the ngmap
module, using webpack.
