### ISSUE TITLE
Bind marker to external link and vice-versa?

### ISSUE THREAD

**Issue by brotherman1** [allenhwkim/angularjs-google-maps#537]
I have posted this question to SO: http://stackoverflow.com/questions/35954701/bind-marker-and-link-together-in-google-maps

Any ideas as to how i achieve this?

**Comment by allenhwkim** [comment]
Do you want to set marker positions from a remote http call?
Use {{variable}} and set that variable after remote http call promise is complete.

You want to store marker position to remote server?
use a marker events callback `on-xxxxxx` to send position to a server. e.g. `on-postion_changed`.

If you do not get answer from any others, please create a plunker and repost your question.
