### ISSUE TITLE
Drawing a polygon for an area on the map (for example, New York)

### ISSUE THREAD

**Issue by ReinisV** [allenhwkim/angularjs-google-maps#538]
Is there a way to draw an n-point (where n is a very big number) polygon on the map based on an object returned by Places API? 
Basically, what I want is for my custom map to have [this functionality](https://www.google.lv/maps/place/New+York,+NY,+USA/@40.7105161,-74.0000023,10z/data=!4m2!3m1!1s0x89c24fa5d33f083b:0xc80b8f06e177fe62).

When the user enters a location, it is retrieved using the Places API and then, if the entered location is not a specific address but rather an area (for example, New York), I want to be able to draw it. No matter how many points it has (and you can see that the New York area polygon has many, many points).

In the Wiki I've only found ways to put down specific markers or draw custom polygons, but these areas seem to be completely different objects drawn differently than regular polygons.

**Comment by allenhwkim** [comment]
You can find a KML data and draw on the map.
https://github.com/allenhwkim/angularjs-google-maps/issues/534
