### ISSUE TITLE
places-auto-complete debounce

### ISSUE THREAD

**Issue by extravagangsta** [allenhwkim/angularjs-google-maps#539]
Hi!

Is there a quick way to set debounce on the places-auto-complete element?

I have model-options="{ debounce: 700 } on the input field. The model updates as expected with the delay specified but requests are sent to the Google API for every additional letter typed in (10 letters in the word = 10 requests) which seems to be redundant.
I want to reduce the number of calls to the API.

Thanks!

**Comment by allenhwkim** [comment]
I do not see that options in Google API
https://developers.google.com/maps/documentation/javascript/3.exp/reference#AutocompleteOptions

I think event handler is added by Google API, not by Angular.

**Comment by allenhwkim** [comment]
Closing this for out of scope
