### ISSUE TITLE
different mapoptions vs multiple maps

### ISSUE THREAD

**Issue by flc** [allenhwkim/angularjs-google-maps#540]
http://plnkr.co/edit/CxDcsGkIMAUEuDY9HuFI?p=preview

Map 1 specifies no options.
Map 2 specifies the following options (you can see it in map2.html):
```draggable="false" disable-default-u-i="true" scrollwheel="false" pan-control="false" disable-double-click-zoom="true"```

When the page loads, Map 1 loads correctly, you can zoom, pan, double click zoom, use the scroll wheel etc.
If you change to Map 2 the new options are taken into account. You cannot zoom, pan, etc.
However if you click back to Map 1 the options seem to remain, applying the Map 2 options to Map 1. Is this the intended behavoir? If yes, it's pretty weird. I would expect to get the same Map 1 with the same options.

**Comment by allenhwkim** [comment]
Thanks for reporting this. This happens because map instance is shared between two instances. It's not an intended behaviour, and I am looking for solution. e.g., map instance by id only.

**Comment by flc** [comment]
seems to be fixed with 1.17.1

**Comment by allenhwkim** [comment]
nice :)

**Comment by flc** [comment]
thanks Allen!
