### ISSUE TITLE
All your demos are down

### ISSUE THREAD

**Issue by beatelite** [allenhwkim/angularjs-google-maps#543]
Just a heads up.

**Comment by joshkopecek** [comment]
This is because RawGit is down.

On Fri, Mar 18, 2016 at 2:49 PM Thomas <notifications@github.com> wrote:

> Just a heads up.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/allenhwkim/angularjs-google-maps/issues/543>
>
-- 
https://echoes.xyz

**Comment by allenhwkim** [comment]
thanks @joshkopecek it's back now. I cannot control rawgit.com.
