### ISSUE TITLE
Doesn't work with AngularJS 1.4.9 or 1.5.0

### ISSUE THREAD

**Issue by Eruditus** [allenhwkim/angularjs-google-maps#545]
ng-map seems to work with 1.3.15 (also the one included in the plunker that's in the README), but it simply shows nothing when calling ng-map with AngularJS 1.4.9 or 1.5.0. Is there support coming for this in the near future?

**Comment by joshkopecek** [comment]
Have been using it in production with 1.4.7-9 for some months, and recently
1.5.0. No problems whatsoever.

Here's a plunkr: http://embed.plnkr.co/Nte0YmcTH6pdh1oXYtqo/

On Wed, Mar 23, 2016 at 12:14 PM Sander van Dam <notifications@github.com>
wrote:

> ng-map seems to work with 1.3.15 (also the one included in the plunker
> that's in the README), but it simply shows nothing when calling ng-map with
> AngularJS 1.4.9 or 1.5.0. Is there support coming for this in the near
> future?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/allenhwkim/angularjs-google-maps/issues/545>
>
-- 
https://echoes.xyz

**Comment by allenhwkim** [comment]
Closing this. I am very sure it work with 1.4 and 1.5. If still not working, please create another issue with **plunker example**, so that I can see the errors.
