### ISSUE TITLE
Build folder through Bower

### ISSUE THREAD

**Issue by NicolasBonduel** [allenhwkim/angularjs-google-maps#547]
Hi.

When I try to install ngmap through bower, I don't get the build folder. Is there a reason for that, or is it a problem on my side?

**Comment by allenhwkim** [comment]
I don't have any issue. and bower should not ignore build directory.

**Comment by NicolasBonduel** [comment]
Well, now it's working. A couple hours ago, both on my laptop and my server, it wouldn't download that specific folder. Weird, I close the issue.
