### ISSUE TITLE
Suggestions for testing modules that use ngmap?

### ISSUE THREAD

**Issue by jeffrom** [allenhwkim/angularjs-google-maps#549]
It seems difficult to test modules that require ngmap as a dependency, particularly directives. Directives that include ngmap directives try to pull in google maps js api, which causes my tests to break. Do you have any suggestions/examples for how to test? Ideally I shouldn't have to run any ngmap code when testing my modules. I've tried to mock out the NgMap service, but so far I've been unsuccessful.

**Comment by allenhwkim** [comment]
I guess you need to mock 3rd party module as described here

http://stackoverflow.com/questions/26244172/cant-get-tests-to-work-in-presence-of-third-party-module

and here

http://stackoverflow.com/questions/17554727/mocking-angular-module-dependencies-in-jasmine-unit-tests?rq=1

**Comment by jeffrom** [comment]
thanks for your reply. Do you have any suggestions on how I might mock out your module? I tried to replace the methods in the NgMap service with noop methods, which is definitely a rushjob, and didn't work. When I have a bit of breathing room I'd be happy to do a proper mock. Hopefully next week i will have a chance.

**Comment by allenhwkim** [comment]
Closing this for out of scope.
