### ISSUE TITLE
heatmap -  fusion and weighted points

### ISSUE THREAD

**Issue by guizmo51** [allenhwkim/angularjs-google-maps#551]
Hi, thanks for your library very usefull !
Is it possible to add a "weighted" option for the fusion table layer ?

**Comment by allenhwkim** [comment]
Can you be more specific with an example? AFAIK, heatmap uses data, and if it's about data, it's out of scope.

**Comment by guizmo51** [comment]
sorry for the missing additional informations. https://developers.google.com/maps/tutorials/visualizing/earthquakes#heatmaps
For heatmap you can use "a weighted location". Is it possible to use it with ngMap or not ? I didn't find it in your documentation, it's maybe not implemented ? thks :)

**Comment by allenhwkim** [comment]
Yes, you can use weighted data like this, https://developers.google.com/maps/documentation/javascript/heatmaplayer#load_the_visualization_library

ngMap does not manipulate any data about heatmap, it just accepts options from attributes, and pass it to Google HeapmapLayer.

Please check this example also. http://ngmap.github.io/#/!layer-heatmap.html

**Comment by allenhwkim** [comment]
Closing this. If you have more questions, please create an issue with plunker example
