### ISSUE TITLE
angular.js:13424 TypeError: Cannot read property 'addObject' of null

### ISSUE THREAD

**Issue by idrenski** [allenhwkim/angularjs-google-maps#552]
I got 
angular.js:13424 TypeError: Cannot read property 'addObject' of null

 at linkFunc (http://localhost:63342/.../bower_components/ngmap/build/scripts/ng-map.js:1676:18)

I see there was a similar bug with 'deleteObject'.

Any idea how to workaround it?

**Comment by idrenski** [comment]
I use ui.router and get the error when I go to the template which calls the controller.
The template is:

```
<ng-map center="current-location" zoom="16">
    <marker ng-repeat="p in addCtrl.positions" position="{{p}}"></marker>

</ng-map>
```

**Comment by allenhwkim** [comment]
Please create a plunker example for your issue, so that I can identify problem and possibly fix it quickly

**Comment by allenhwkim** [comment]
Closing it. It will be reopened when a plunker example is added.
