### ISSUE TITLE
terrain map type on iOS

### ISSUE THREAD

**Issue by wsenjer** [allenhwkim/angularjs-google-maps#554]
Hello, 
I used ngMap to build an iOS app using PhoneGap. 
The issue is that I added the three mapTypes satellite, roadmap and terrain. Using this line of code.

```
map.setOptions({mapTypeControlOptions: {
   mapTypeIds: [google.maps.MapTypeId.ROADMAP, google.maps.MapTypeId.SATELLITE, google.maps.MapTypeId.TERRAIN],
}});
```
The issue is the terrain type doesn't appear in the map types at all in the iOS app, but it appears in the Android app without any problem.
Any ideas on how would I fix this issue? 

Many Thanks.

**Comment by allenhwkim** [comment]
This is pure google map API 3 question, which is out of scope.

ngMap uses the following code to control map type.
```
      map-type-control-options='{position:"top_right",
         style:"dropdown_menu", 
        mapTypeIds:["HYBRID","ROADMAP","SATELLITE","TERRAIN"]
    }'
```
http://ngmap.github.io/#/!map_control.html

**Comment by allenhwkim** [comment]
Closing it for "out of scope"
