### ISSUE TITLE
Marker Cluster 

### ISSUE THREAD

**Issue by Barathwaja** [allenhwkim/angularjs-google-maps#556]
What exactly is NgMap.getMap() ??? and marker cluster accepts only first 11 .. after over query limit i redirected to a function for geocoding but markers are placed but not shown in cluster. kindly throw some light on that. $timeout also been set but nothing works.. where exactly "NgMap.getMap() " to be used?? either inside geocoding or in controller???

**Comment by allenhwkim** [comment]
How do you get map instance from angular directive?
NgMap.getMap() is used to get map instance.

You can do whatever you like to do with map instance.

**Comment by Barathwaja** [comment]
oh Thanks allen.. Actually from your example only i found and tried. sometimes what it does is it goes to extreme values like 2000k's but my data contains only 30-40 Json data's. .. i tried to edit markercluster.js but no luck..
