### ISSUE TITLE
working with AngularjS2?

### ISSUE THREAD

**Issue by DirkPersky** [allenhwkim/angularjs-google-maps#559]
Hello,

first of all, nice work dude i love this module.

Actual i want to go forward to AngularJS2, is there a way to get your module working with AngularJS2? Becouse i am planing to update all older AJ1 developments to AJ2.

Please let my know.

Greeting
Dirk

**Comment by allenhwkim** [comment]
I have a plan to move to angular2 as soon as I found a way to pakage this in angular2
