### ISSUE TITLE
Unable to inject ngMap: Error: [$injector:unpr] Unknown provider: ngMapProvider <- ngMap <- LayerHeatmapCtrl

### ISSUE THREAD

**Issue by tnat93** [allenhwkim/angularjs-google-maps#560]
I added ngMap as a dependency to my app, however, I keep getting this error:

- Error: [$injector:unpr] Unknown provider: ngMapProvider <- ngMap <- LayerHeatmapCtrl

I am not sure how else to define ngMap. Please provide assistance as soon as possible.

**Comment by allenhwkim** [comment]
There is lots of example at ngmap.github.io

**Comment by tnat93** [comment]
Thank you. However, I am unsure what you mean. 
I'm using your layer-heatmap.html.
I've defined ngMap as a dependency in my app: "angular
      .module('lima.controller', ['pusher-angular', 'ngMap']);".
In my controller, I have: "LayerHeatmapCtrl.$inject = ['$scope', 'ngMap', 'tweetData', 'Search'];
  function LayerHeatmapCtrl($scope, NgMap, tweetData, Search) {...}".
I've also included "ng-map.min.js" in my script.
Do you happen to know what's causing that error?

**Comment by allenhwkim** [comment]
Take a look at this example, which is "Run in plunker" clicked from this url, http://ngmap.github.io/#/!layer-heatmap.html

http://plnkr.co/edit/PKSbv5?p=preview
