### ISSUE TITLE
Can zoom-to-include-markers dynamically work to reflect markers change ?

### ISSUE THREAD

**Issue by sean72kimo** [allenhwkim/angularjs-google-maps#561]
I have a map such as
```
<ng-map zoom-to-include-markers={{vm.zoom}} 
        id="map-canvas"          
        center="[{{vm.centerLat}}, {{vm.centerLng}}]" >
    <marker ng-repeat="p in vm.positions" position="{{p.pos}}" title="pos: {{p.pos}}"></marker>
</ng-map>
```
after getting my search result from first page, I will redirect to second page to show the map and markers. 

In second page, there is also a search bar. I would like to stay at the same page but change markers if I search again in second page.

According to different second search results, my vm.centerLat, vm.centerLng and vm.positions will be updated and ng-map can reflect the results with no problem. 

However, zoom-to-include-marker will stay at the zoom level for the first time and won't change zoom level again according to markers change. I have tried both "true" and "auto", they both don't reflect zoom level after my second search.

Thanks,
Sean

**Comment by allenhwkim** [comment]
zoomToIncludeMarkers are only called when marker or customMarker is added through a directive. If you  add markers manually without using a directive,  the following won't be called. 

https://github.com/allenhwkim/angularjs-google-maps/blob/master/controllers/map-controller.js#L26

You can create a small function and call it manually if your markers are handled manually.

```
   function zoomToIncludeMarkers(markers) {
      var bounds = new google.maps.LatLngBounds();
      for (var k1 in markers) {
        bounds.extend(markers[k1].getPosition());
      }
      vm.map.fitBounds(bounds);
    }
```
