### ISSUE TITLE
mouse over to change marker color

### ISSUE THREAD

**Issue by sean72kimo** [allenhwkim/angularjs-google-maps#562]
Hi,

Does ngMap support mouse over to highlight a marker?

Thanks,
Sean

**Comment by allenhwkim** [comment]
ng-map exactly follow google map api reference. Thus the following method will always work
1. google this 'google maps api v3  reference marker  events'
2. on [google site](https://developers.google.com/maps/documentation/javascript/reference), find 'marker class'
3. Scroll down until you see 'Events', you will see 'mouseover'

Now, you know marker has mouseover and mouseout event

implement that one into your code using 'on-mouseover' attribute with function name. For example

```
  <marker ... on-mouseover="vm.myFunction()"></marker>
```

myFunction will look like this

```
  vm.myFunction(event) {
     this.setXXXXXX(); // this means marker
  } 
```

Now you need to know what method a marker has. On the same api reference, you will see methods when you scrollup little. For highlight, you can use different icon, so `setIcon` is a way to go, I think.

This shows how to set Icon.
http://stackoverflow.com/questions/26587533/how-to-highlight-map-marker-upon-selection-of-an-html-element
