### ISSUE TITLE
unable to get map

### ISSUE THREAD

**Issue by calidion** [allenhwkim/angularjs-google-maps#567]
it has been very frequently
ng map fail to get the map object.

**Comment by calidion** [comment]
solved by the following code:

```js
      var getMap = false;
      var timer;
      getMap: function(cb) {
        function repeat() {
          NgMap.getMap().then(function(map) {
            if (!getMap) {
              getMap = true;
              cb(map);
              clearInterval(timer);
            }
          });
        }
        timer = setInterval(repeat, 1000);
      }
```

**Comment by allenhwkim** [comment]
As you see here, it should find a map in 2 seconds. If not, it returns error.
If your network is good, and google map is downloaded 2 seconds are good enough, I think.

```

  var getMap = function(id) {
    id = typeof id === 'object' ? id.id : id;
    id = id || 0;

    var deferred = $q.defer();
    var timeout = 2000;

    function waitForMap(timeElapsed){
      if(mapControllers[id]){
        deferred.resolve(mapControllers[id].map);
      } else if (timeElapsed > timeout) {
        deferred.reject('could not find map');
      } else {
        $window.setTimeout( function(){
          waitForMap(timeElapsed+100);
        }, 100);
      }
    }
    waitForMap(0);

    return deferred.promise;
  };
```

**Comment by derkoe** [comment]
Could be a duplicate of #614

**Comment by neolectron** [comment]
i've got simmilar issues. 2seconds aren't enough...
i have other modules loading at the same time, it takes me some CPU.
if I add throttling, i've got this error 100% of the time.

**Comment by solidevolution** [comment]
Same here, map breaks while slow network connections

**Comment by justus-alex** [comment]
Hello, @allenhwkim.

> If your network is good, and google map is downloaded 2 seconds are good enough, I think.

.. and if it's not?
What's the point to impose 2 seconds timeout since you're using a promise anyway?

**Comment by tintin1343** [comment]
Hi @allenhwkim : Is there a fix for this? 
Thanks!

**Comment by allenhwkim** [comment]
@tintin1343 There should be a fix. It's just terribly busy. PR would be appreciated. Closing this as duplicate.

**Comment by allenhwkim** [comment]
Duplicate to #614
