### ISSUE TITLE
how to get marker object generated in marker directive?

### ISSUE THREAD

**Issue by sean72kimo** [allenhwkim/angularjs-google-maps#569]
I would like to achieve an action as this http://jsfiddle.net/7w6gh4we/1/
(when clicking on table, the marker will react, vise versa)
Is there a way to have access to the marker object that I can do other controls to the marker when needed?

Thanks,
Sean

**Comment by allenhwkim** [comment]
`map.markers` as in README.md?
```
app.controller('MyController', function(NgMap) {
  NgMap.getMap().then(function(map) {
    console.log(map.getCenter());
    console.log('markers', map.markers);
    console.log('shapes', map.shapes);
  });
});
```

**Comment by sean72kimo** [comment]
I am pretty new to web and programming

Thank you so much for your patient answering all the questions 
NgMap is a very helpful and easy to use module.
Many thanks again

Sean
