### ISSUE TITLE
parameters in attribute "on-place-change" not being sent

### ISSUE THREAD

**Issue by lwj5** [allenhwkim/angularjs-google-maps#571]
Is it possible to send parameters in the function provided in the attr "on-place-change"

HTML:
```
<input places-auto-complete ... on-place-changed="placeChanged('PARAMETER')" />
```

Controller:
```
function placeChanged(parameter) {
// parameter is undefined
}
```

The reason for this is to use a single method that accept different parameters to process multiple input fields like this.

**Comment by drixie** [comment]
+1 - I just noticed this. 

The demo uses this.getPlace() in the callback function in the controller, and this fetches all the information about the address. But passing back the address selected as a parameter will be very useful.

**Comment by allenhwkim** [comment]
Sorry for the late(very late) response. However `autocomplete.getPlace()` is the Google's way to do, so I would like to follow it.
