### ISSUE TITLE
Preventing duplicate icons when using UI router

### ISSUE THREAD

**Issue by dtrinh50** [allenhwkim/angularjs-google-maps#575]
I am trying to do something like the provided example below: 

https://ngmap.github.io/#/!ui-router2.html

The issue with my app and the example is that it creates a duplicate icon when it changes state. For example, in the above example, when you click on route 2, then go back to route 1, another icon suddenly appears. 

I am not sure if this was intentional or not, but is there a way to prevent duplicate icons when a user switches routes?

**Comment by allenhwkim** [comment]
the example works fine. Please provide me your non-working example.

**Comment by dtrinh50** [comment]
A working example would be the same working example that I posted up there, but I just want the route to not add additional markers after switching states. For example, if I was to go from route 1 to route 2 and come back, I don't want an additional marker to be added. Is there a way to do this?

**Comment by allenhwkim** [comment]
That happens because when map is initialized, it adds marker 

      var latLng = new google.maps.LatLng(40.74, -74.18);
      var marker = new google.maps.Marker({
        position:latLng, draggable: true
      });
      marker.setMap(map);

If you change it doing raw programming but using `<marker>`,there won't be any problem.

**Comment by dtrinh50** [comment]
@allenhwkim thanks for the help. I have actually tried using the `<marker>` directive, but it gave me a digest error when I would switch states (I opened an issue [here](https://github.com/allenhwkim/angularjs-google-maps/issues/574), but closed it since doing the current way prevents the digest errors). Should I reopen the issue? Thanks again for the help.

**Comment by allenhwkim** [comment]
This works fine for me.
http://plnkr.co/edit/AuQWfyPHZVtktticKpOl?p=preview

**Comment by dtrinh50** [comment]
I get this error in the console when running the Plunker: `Error: $digest already in progress`

**Comment by allenhwkim** [comment]
I do not see the error when running the plunker. This won't be repoened until you provide a plunker.

**Comment by Rusticman** [comment]
Hey allenhwkim, I was having the same problem as dtrinh50, so I changed to use the ```marker``` directive as per your instructions above.  The problem is that I wanted to use the marker clusterer package: https://googlemaps.github.io/js-marker-clusterer/docs/examples.html 

Unfortunately, it requires that I create an array of marker objects ```new google.maps.Marker``` which creates duplicates again. Is there any way of using the ```marker``` directive and also using the marker clusterer package?
