### ISSUE TITLE
Broken label on bouncing markers

### ISSUE THREAD

**Issue by kputh** [allenhwkim/angularjs-google-maps#576]
Problem:
![google map marker](https://cloud.githubusercontent.com/assets/8649002/14557522/fc47c6e4-02fd-11e6-9f8d-83085b7aba56.gif)

Source Code:
![marker source code](https://cloud.githubusercontent.com/assets/8649002/14557527/00c31156-02fe-11e6-991d-f856abfee704.png)
I'm using ngMap 1.16.0

**Comment by allenhwkim** [comment]
This is the problem of Google Map itself. Please report this bug to Google.
