### ISSUE TITLE
Map not loaded correctly on view with multiple tabs

### ISSUE THREAD

**Issue by taufansatrio** [allenhwkim/angularjs-google-maps#577]
In my site, I have a page with multiple tabs, let's say tab A and B, the NgMap is loaded on tab A.

The problem occurs when I try to navigate to/reload the page with hash url that points to tab B, e.g '/page#tabB'. When I navigate to tab A without reloading, the map sometimes loads but has an unusual zoom level and most often not loaded. For both conditions I have tried adding callback with `map-initialized` but in both cases it is called and has same results.

I'd really appreciate some pointers on this problem. I could not find the root cause, whether it's the map, the tabs, or the ui router. 

I'm using `angular 1.3.20`, `ngmap 1.16.7`, `angular-ui-router 0.2.18`

**Comment by allenhwkim** [comment]
Please follow this example if you are using ui-router, http://ngmap.github.io/#/!ui-router.html

If not, you need to `resize` the map, also you need to recenter when DOM is re-created. This is known issue of Google maps. Please search issue with `resize`
