### ISSUE TITLE
Multiple rotues in the same map with different colors and number order

### ISSUE THREAD

**Issue by AlexVKO** [allenhwkim/angularjs-google-maps#579]
Hi guys, thanks for the awesome work.

I have a feature that I need to display several routes at the same time, like the image below... it is possible with this directive?  please notice the different colors and the order number.

<img width="1130" alt="screen shot 2016-04-18 at 10 14 37 am" src="https://cloud.githubusercontent.com/assets/8848152/14605481/2112202a-054f-11e6-9321-ce297a5311a3.png">

I'll appreciate advices, any source code or article related.

**Comment by AlexVKO** [comment]
Hey, I just figured out.

![screen shot 2016-04-18 at 11 07 54 am](https://cloud.githubusercontent.com/assets/8848152/14606934/d56a6950-0555-11e6-977f-63a668b998b2.png)

As you can see in the image above, "directions" tag has an attributes called polyline-options, which you can check the options [here](https://developers.google.com/maps/documentation/javascript/examples/polyline-simple)

Many thanks.

**Comment by OmarTag** [comment]
Hello Alex, I would be grateful if you send or tell me how you have done it because I cannot draw multiple routes on the same map from an array of routes it only draws the last route in the array. I use directions component with ng-repeat
