### ISSUE TITLE
Wrong address with dynamic address

### ISSUE THREAD

**Issue by tareku** [allenhwkim/angularjs-google-maps#580]
This one: https://ngmap.github.io/#/!map_with_dynamic_address.html

**Comment by allenhwkim** [comment]
That lat/lng from address is given from Google. NgMap can do not much about thar

**Comment by tareku** [comment]
Thank you, for your response.

**Comment by larissaleite** [comment]
In my case what happens is that if I put the **exact same** coordinates or text in the center field manually or dynamically, I get different results. I have been trying exhaustively to find a work around but I haven't managed so far..
