### ISSUE TITLE
Problem on second render. Map is partically visible. Everything else just gray area

### ISSUE THREAD

**Issue by askucher** [allenhwkim/angularjs-google-maps#59]
Quickfix:

``` javascript
...
ngMap.directives.infoWindow.$inject = ["Attr2Options"], ngMap.directives.map = function(e, t, n, r) {
    var o = e;
    return {
        restrict: "AE",
        controller: ngMap.directives.MapController,
        link: function(e, t, i, a) {
            e.google = google;
            var s = document.createElement("div");

            s.style.width = "100%", s.style.height = "100%", t.prepend(s), e.map = new google.maps.Map(s, {});
//START   
         var timeout =
                setTimeout(function() {
                    clearTimeout(timeout);
                    google.maps.event.trigger(e.map, 'resize')

                }, 1000);
//END
            var c = o.filter(i),
                p = o.getOptions(c, e),
                l = o.getControlOptions(c),
                g = o.getEvents(e, c),
                v = angular.extend(p, l);
...
```

**Comment by realph** [comment]
@dmitriz I've put this inside a custom directive. Works perfectly fine when I change the view, but not on initial page load or browser refresh Any ideas?

**Comment by allenhwkim** [comment]
There is a way to delay the initialization of the map using `init-event`.

https://github.com/allenhwkim/angularjs-google-maps/blob/82b5c10b6b00763f940430d95e8cb084105e3fce/testapp/map_lazy_init.html

**Comment by salefission** [comment]
I solved the problem by adding
$scope.render = false;
$timeout(function () {
        $scope.render = true;
}, 1000);
in the controller and binding ng-if="render" in the html. Nothing else worked for me.

**Comment by keep-faith** [comment]
i did it like @salefission

**Comment by kakerisn** [comment]
`            NgMap.getMap().then(function(map){
                google.maps.event.addListener(map, "idle", function(){
                    google.maps.event.trigger(map, 'resize'); 
                });
            });`

**Comment by avinashbhujan** [comment]
This one worked for me (Typescript Version):

**HTML:**
`<ng-map zoom="14" center="[0,0]" trigger-resize="true" map-initialized="modalController.onMapLoaded()" >
                    <shape  id="circle" name="circle" centered="true"
                            center="{{modalController.address}}"
                            stroke-color='#FF0000' stroke-opacity="0.8" stroke-weight="2"
                            radius="800" editable="false"></shape>
                </ng-map>`

**Controller Method:**
`public onMapLoaded() {
        var self = this;
        self.ngMap.getMap().then(function (map) {
            self.gMap = map;
            google.maps.event.trigger(self.gMap, 'resize');
        });
    }`

If using Typescript, make sure you have the file google.maps.d.ts and if some types are not available just set them to `any`.
