### ISSUE TITLE
Zoom to Markers and Clustered Markers

### ISSUE THREAD

**Issue by markolbert** [allenhwkim/angularjs-google-maps#591]
I can't get ngMap -- which is an awesome library! -- to zoom to include markers while also clustering them. Here's the html:

    <h1>Marker Cluster</h1>
    <hr />
    <div ng-controller="@ViewBag.AngularController as vm">
        <ng-map zoom-to-include-markers="true" ></ng-map>
    </div>
    
    <script src="https://maps.google.com/maps/api/js"></script>
    <script src="~/lib/ngmap/build/scripts/ng-map.min.js"></script>
    <script src="~/lib/markerclustererplus/dist/markerclusterer.min.js"></script>
    <script src="~/js/markers.js"></script>
    
    <script type="text/javascript">
        var app = angular.module( '@ViewBag.AngularAppName', ['ngMap'] );
    
        app.controller( '@ViewBag.AngularController', function ( $http, $interval, NgMap ) {
            var vm = this;
            vm.dynMarkers = [];
            NgMap.getMap().then( function ( map ) {
                $http.get( '/Chart/GetSites' ).then( function ( siteResp ) {
                    for ( var i = 0; i < siteResp.data.length; i++ ) {
                        var latLng = new google.maps.LatLng( siteResp.data[i].lat, siteResp.data[i].lng );
                        vm.dynMarkers.push( new google.maps.Marker( { position: latLng } ) );
                    }
                    vm.markerClusterer = new MarkerClusterer( map, vm.dynMarkers, {} );
                } );
            } );
        } );
    </script>
    }

When the page opens I get a beautiful display of ocean :). 

FYI, the calls to @ViewBag... are part of the ASPNET5 MVC6 view in which ngMap runs.

If I leave out the zoom-to-include-markers attribute, and substitute zoom and center attributes, everything works fine.

**Comment by allenhwkim** [comment]
With MarkerClusters, you are on your own. Sorry. Closing this issue as `out of scope`
