### ISSUE TITLE
Distance Matrix for Markers with radius

### ISSUE THREAD

**Issue by gtolan** [allenhwkim/angularjs-google-maps#592]
Hello Allen,
Thank you for your great work. I am just hoping you can help with a ngmaps distance matrix from a particular address such as "Ontario, Canada". Using a radius of miles/ kilometres to filter results.
Any direction would be appreciated.
Thanks,
Gerard

**Comment by allenhwkim** [comment]
Please take a look at this.
https://github.com/allenhwkim/angularjs-google-maps/issues/298
