### ISSUE TITLE
google is not defined

### ISSUE THREAD

**Issue by RyanEaves** [allenhwkim/angularjs-google-maps#598]
I have seen the previous posts about this. I don't want to lazy load the map. Here is the exact message:

angular.js:13550

ReferenceError: google is not defined
    at new t (ng-map.min.js:25)
    at Object.invoke (angular.js:4665)
    at R.instance (angular.js:10115)
    at n (angular.js:9033)
    at g (angular.js:8397)
    at n (angular.js:9088)
    at g (angular.js:8397)
    at n (angular.js:9088)
    at g (angular.js:8397)
    at angular.js:8277

I am not sure what you might need to troubleshoot this. It seems to happen intermittently- maybe 50% of the time, so my guess is that something is getting initialized slightly too early. Another clue is that when I click the refresh button (Chrome) it happens quite a bit. But then if I click the address bar and hit enter, it usually works. Any ideas?

**Comment by allenhwkim** [comment]
Racing condition.

1. ng-map needs google.
2. google maps is loaded

If #1 happens before #2, you will see that error. 
Did you disable cache? If so, it happens more often I think.

Can you load google maps before your angular app loads? If so, that would be great.
There is nothing much we can do about it AFAIK.

If I were you I would not put google maps on the first page of the app to prevent this message.

**Comment by RyanEaves** [comment]
Based on your explanation, I removed the async and defer keywords from the google maps script tag and added defer to my app.js script tag. That looks like it resolved it, so you were exactly right.

**Comment by RyanEaves** [comment]
Also, for others, here is a pretty complete explanation of how to control the order that scripts load. 

http://www.html5rocks.com/en/tutorials/speed/script-loading/
