### ISSUE TITLE
How to access gmap direction obj in my js using direction directive

### ISSUE THREAD

**Issue by elarion** [allenhwkim/angularjs-google-maps#600]
Hello,

Would know how to access `map.directionsRenderers[0].directions.routes[0]` after direction directive has calculated the route, is there the possibility to make a callback with this directive ?
My point is that I need to store some info from the obj such as distance and duration each time the route is updated.

Thanks

**Comment by allenhwkim** [comment]
there is event for that. `directions_changed`

https://developers.google.com/maps/documentation/javascript/reference#DirectionsRenderer

**Comment by elarion** [comment]
Thanks, but what is the best way to set this event?

**Comment by allenhwkim** [comment]
on-directions_changed="myFunction(evt)"

https://github.com/allenhwkim/angularjs-google-maps/blob/master/road-trip.md
