### ISSUE TITLE
Clustering Icons are broken?

### ISSUE THREAD

**Issue by Oztrea** [allenhwkim/angularjs-google-maps#602]
I think google moved the icons to another repository...
See the example here:
https://rawgit.com/allenhwkim/angularjs-google-maps/master/testapp/marker-clusterer.html

https://code.google.com/p/google-maps-utility-library-v3/

for example this url returns 404 not found.
http://google-maps-utility-library-v3.googlecode.com/svn/trunk/markerclustererplus/images/m2.png

Any idea how we can fix that? Does someone has a workaround?

**Comment by allenhwkim** [comment]
There are issues with markerclusterer. https://github.com/googlemaps/js-marker-clusterer/issues/54

**Comment by tmpduarte** [comment]
indeed they forgot to update the path to their icons.
What I did was to store the icons on my project and then pass the _imagePath_ in the markerCluster instantiation:

`new MarkerClusterer(map, markers, {imagePath: './images/MapsCluster'});      `

With this you need to have inside your /images folder 5 images: MapsCluster1.png, MapsCluster2.png ... MapsCluster5.png

**Comment by SbstnErhrdt** [comment]
Solution

`Line 1614 in markercluser.js `
**OLD**
`MarkerClusterer.IMAGE_PATH = "https://google-maps-utility-library-v3.googlecode.com/svn/trunk/markerclustererplus/images/m";`
**NEW**
`MarkerClusterer.IMAGE_PATH = "https://cdn.rawgit.com/googlemaps/js-marker-clusterer/gh-pages/images/m";`

**Comment by allenhwkim** [comment]
Closing since I can't do any for this issue.
