### ISSUE TITLE
Put a label over a map marker and apply css on it 

### ISSUE THREAD

**Issue by NishantDesai1306** [allenhwkim/angularjs-google-maps#603]
I was using Angular Maps but i found it complex so I switched to ngMap

In Angular Map i was able to assign Label to a marker and apply a css class to it, but i don't know how to do it using ngMap.

In Angular Map i had used label and label-class to achieve my goal

![image](https://cloud.githubusercontent.com/assets/18420157/15268599/90b083c8-1a02-11e6-859e-36fefdfee00a.png)

Any help is appreciated.

**Comment by uguryilmaz** [comment]
+1

**Comment by Simon-Graham-ila** [comment]
+1

**Comment by ElPsyCongro** [comment]
+1

**Comment by monasha-s** [comment]
+1

**Comment by Joystan** [comment]
+1

**Comment by fvukovic** [comment]
+1

**Comment by fvukovic** [comment]
U cant do that with <custom-marker><div> </div></custom-marker.. Then u can style that div and put a image of marker that u wish.

**Comment by softwarenacho** [comment]
Is there a solution for this problem? Using custom-marker I seem to lose the dragging capabilities. Thanks.

**Comment by fvukovic** [comment]
Hmm.. I didnt need dragging capabilities, so i dont know is it lost with it..But the label is showed over the marker and it works for me..

**Comment by softwarenacho** [comment]
Yes I have 2 differents type of maps, view only and edit, 

in the view only maps a custom-marker is indeed the solution and works perfectly fine,

the problem are the ones where I need to edit, my users need to drag a marker to a position and in dragend take lat-lng and apply it to my object, but I don't get to apply draggable in custom-marker
