### ISSUE TITLE
Unable to show an InfoWindow automatically (without ng-click)

### ISSUE THREAD

**Issue by riples** [allenhwkim/angularjs-google-maps#604]
I am trying to work out how to automatically open an InfoWindow due to some event or property in the controller.

For example, I want to open an InfoWindow at a particular marker after a timeout.  I am trying to follow both the `infowindow-simple.html` and `event-properties.html` examples where you have shown an InfoWindow automatically (without a click event), but I cannot get this to work.

The only way I seem to be able to get an InfoWindow to appear is to attach it to an `ng-click` event.

Curently I am trying this:
```
NgMap.getMap( {id:"map"} ).then(function(map) {
    vm.map = map;	      
});
	    
 var showDetail = function(e) {
    vm.map.showInfoWindow( 'bar', '1' );
 }
	    
$timeout(showDetail, 3000);
```

If I compile this, it seems to work once, but if I refresh the page, from then on I get the following error:
`TypeError: vm.map.showInfoWindow is not a function`

Is there an example of this somewhere?

**Comment by riples** [comment]
Does anyone have any feedback on this?
The website example `infowindow-simple.html` shows an info window as soon as the page loads.  Looking at the code, I cannot see any evidence where this is handled.

Is there a simple method of simulating this please.

**Comment by mtpultz** [comment]
@riples what does your markup look like for ng-map?  As for the error does vm.map exist at the point it is being invoked, or is it undefined?  Seems like it will likely be undefined.

**Comment by allenhwkim** [comment]
Duplicate to #648
