### ISSUE TITLE
Label on polygons

### ISSUE THREAD

**Issue by mynd-paula** [allenhwkim/angularjs-google-maps#606]
Do you have a sample for adding/writing labels on the map? I am drawing polygon overlays using the drawing manager. I would like to be able to add labels for each of those polygons. Will appreciate any feedback. Thank you

**Comment by Xyroid** [comment]
You can use https://github.com/googlemaps/js-map-label. Here's [fiddler](http://jsfiddle.net/geocodezip/yN29Z/316/) example. You can use it with ng-map.

**Comment by allenhwkim** [comment]
Polygone itself does not have label AFAIK. 
You can add  circled marker with label. 

http://stackoverflow.com/questions/33455257/google-maps-api-v3-label-and-color-for-marker
```
 new google.maps.Marker({
    map: map,
    position: latlng,
    label: "0",
    icon: pinSymbol('red')
}
```
