### ISSUE TITLE
Updating map if location marker changes?

### ISSUE THREAD

**Issue by galenp** [allenhwkim/angularjs-google-maps#61]
Hello,

I may be blind but I have not seen any documentation on how to update/refresh the map if the location marker changes.

E.g.

``` html
<map zoom="16" center="[-16.298145, 128.755701]">
   <marker position="{{location}}" title="{{location}}" centered="true"></marker>
</map>
```

If the user changes $scope.location is there a mechanism to force the map to update?

**Comment by CodeBreaker30** [comment]
Hello @allenhwkim , so sorry to bring this up once again but I need to make this work for version 1.16.8 and I couldn't find the examples you refered above, can you give me a hand please?

**Comment by allenhwkim** [comment]
@CodeBreaker30 please find all examples here, http://ngmap.github.io/

**Comment by yashgautami** [comment]
[usePanning]="true" works for me
