### ISSUE TITLE
Add a ID brokes marker

### ISSUE THREAD

**Issue by anagas** [allenhwkim/angularjs-google-maps#612]
Hello,

when i add an id like this:

```
ng-map center="[x,x]" zoom="15" class="cst-map-height" id="status" .
```

The marker does not appear on the map. I need this ID to check whether the map is not available.

Is it not possible to add an id?

**Comment by allenhwkim** [comment]
Thanks for reporting this.

Its seems like a bug, and I will look into it. Meanwhile, can you use something instead of `id`. e.g., `map-id` to make yours to work?

**Comment by allenhwkim** [comment]
This seems fixed. Please reopen if this is not fixed.
