### ISSUE TITLE
Geolocation only works over HTTPS

### ISSUE THREAD

**Issue by francisrath** [allenhwkim/angularjs-google-maps#613]
Hi there,

thank you for your samples, but you should consider linking to the HTTPS version of the site for the demo, as geolocation only works on HTTPS now apparently. See [http://ngmap.github.io/#/!map-geolocation.html](http://ngmap.github.io/#/!map-geolocation.html) and check the developer console.

**Comment by Pheonix929** [comment]
YIP! So now i have to build a fallback forcing my users to add their location using Geocoder before they can run my angular app. Google should have built an exception...

> getCurrentPosition() and watchPosition() are deprecated on insecure origins. To use this feature, you should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.

**Comment by allenhwkim** [comment]
The whole site should be `https` instead of `http`. Since this is using github account, I don't know how to force `https`. Suggestions are welcomed.

**Comment by francisrath** [comment]
I sent you a pull request to change the link from `http` to `https` on this repo, and if I may suggest you can look into something like this on the demo repo? [http://stackoverflow.com/questions/4723213/detect-http-or-https-then-force-https-in-javascript](http://stackoverflow.com/questions/4723213/detect-http-or-https-then-force-https-in-javascript)

**Comment by chozzz** [comment]
Geolocation will require https as of chrome >= 50, 
src: http://stackoverflow.com/questions/37959791/does-google-map-geo-location-require-secure-ssl-connection/37959856#37959856

**Comment by allenhwkim** [comment]
This is fixed.
