### ISSUE TITLE
getMap Promise is not resolving: 'could not find map'

### ISSUE THREAD

**Issue by kpgarrod** [allenhwkim/angularjs-google-maps#614]
I have been using ngMap (1.17.1) for some time in a project.

Today I upgraded node and npm and some related packages and suddenly NgMap.getMap() is rejecting with an error 'could not find map' , although the map is clearly loaded on the page.

I am using angularjs 1.5.3 with the new component syntax, but that has been true for a while, so I don't suppose that's the cause.

I'm sorry this is a very vague problem description but the upgrade of Node required for my app to build  correctly on Heroku led to a string of changes, none of which appear to have any relevance to NgMap and I didn't notice the map issue until a few hours into the process, so I'm confused!

Any suggestions about how I might go about debugging this issue?

**Comment by allenhwkim** [comment]
can you create a plunker example that produces `could not find map`? It could be a network issue.

**Comment by kpgarrod** [comment]
I resolved this issue by downgrading from 1.17.1 (the latest in npm) to 1.17.0.

**Comment by tmpduarte** [comment]
had the same problem and the fix @kpgarrod did also worked for me

**Comment by derkoe** [comment]
The same here - 1.17.1 seems to be broken

**Comment by dieguezz** [comment]
+1

**Comment by sadiq-mc** [comment]
The same here with 1.17.7..
It was working fine till yesterday... 

This error happens only for first launch after an idle state. And later routing to same page wont throw this error.
I tried both the ways but the issue still happens.. :(
```
NgMap.getMap('gmap').then(function(map) {
            console.log('map initialized');
        }).catch(function(map){
            console.error('map error: ', map);
        });
```

```
NgMap.getMap({id: 'gmap'}).then(function(map) {
            console.log('map initialized');
        }).catch(function(map){
            console.error('map error: ', map);
        });
```

**Comment by crazyabdul** [comment]
@sadiq-mc I had the same issue yesterday too. Have you solved it yet?

**Comment by allenhwkim** [comment]
It waits only for two seconds. If it does not resolove the google object in two seconds, it will throw an error. 
https://github.com/allenhwkim/angularjs-google-maps/blob/master/services/ng-map.js#L47v

**Comment by sadiq-mc** [comment]
@crazyabdul Just update the timeout to 15-20sec (which is really bad but more than enough) in the ng-map.js to get this issue resolved.
https://github.com/allenhwkim/angularjs-google-maps/blob/master/services/ng-map.js#L52v

**Comment by blandfried** [comment]
I get this error on Angular 1.6.2 but if I bump down to 1.5.9 it goes away. I am also using ngMaps 1.18.0

**Comment by allenhwkim** [comment]
1.18.1 release with timeout 10 seconds in default. This can be also configured.
```
NgMap.getMap('gmap', {timeout: 20000}).then(function(map) {
            console.log('map initialized');
        }).catch(function(map){
            console.error('map error: ', map);
        });
