### ISSUE TITLE
Directions - Alternate routes

### ISSUE THREAD

**Issue by ercseypeter** [allenhwkim/angularjs-google-maps#616]
Hey Andy!

I'm wondering that is there any way to display the route alternatives as well?

I'm pretty sure that the directions directive only shows the first alternative.

Thanks,

Peter

**Comment by allenhwkim** [comment]
Who is Andy?
I am not sure about that we can display route alternatives.

As per here, it just shows the response from Google. I am not sure Google provides us alternative route.
https://github.com/allenhwkim/angularjs-google-maps/blob/8e15800c6be7aa932e9cc3a8820425f529078a0e/directives/directions.js#L67

I am thinking that those advanced features are for Google only. :(

**Comment by ercseypeter** [comment]
Hey Allen!

Thanks! :)

I found some solutions with the directions API and those can provide alternate routes. I'm pretty sure that not just 'Google' can provide it. I'm going deeper to figure it out.

Thanks,

Peter

**Comment by ercseypeter** [comment]
I just found:

https://developers.google.com/maps/documentation/javascript/directions#DirectionsRequests

You need to set 'provideRouteAlternatives' true if you want to receive alternative routes.

**Comment by ercseypeter** [comment]
I just modified 

var showDirections = function(request) {
     
      request.provideRouteAlternatives=true;
      directionsService.route(request, function(response, status) {
        if (status == google.maps.DirectionsStatus.OK) {
          $timeout(function() {
            renderer.setDirections(response);
          });
        }
      });
    };

And now it returns alternate routes as well

**Comment by ZhangHoward** [comment]
Hi, @ercseypeter? Have you solved the problem of showing alternative routes on the map? Can you share the HTML file?

**Comment by mohamedchibani** [comment]
Have you solved the problem of showing alternative routes on the map? Can you share the HTML file?
