### ISSUE TITLE
Display duration + miles over directions routes 

### ISSUE THREAD

**Issue by elarion** [allenhwkim/angularjs-google-maps#619]
Hi,

I would know if there is any way to display natively the duration and miles needed between two points, such as google map does while finding itineraries
<img width="298" alt="capture d ecran 2016-05-26 a 14 56 44" src="https://cloud.githubusercontent.com/assets/1688293/15575319/70b465e0-2352-11e6-9538-e6cbc648c474.png">
 
Thanks

**Comment by allenhwkim** [comment]
I think this is out of scope. Please look into Google Maps API and find a solution from it. ngMap is just a wrapper of Google Maps API.
