### ISSUE TITLE
geo-callback only run once.

### ISSUE THREAD

**Issue by fcostarodrigo** [allenhwkim/angularjs-google-maps#622]
Changes in the value of position or center moves the marker or map, but the function in geo-callback is called only once.

**Comment by fcostarodrigo** [comment]
Example

    <!DOCTYPE html>
    <html lang="en" ng-app="app">
      <head>
        <meta charset="UTF-8">
        <link rel="stylesheet" href="style.css">
      </head>
      <body ng-controller="controller as ctrl">
        <div map-lazy-load="https://maps.google.com/maps/api/js">
          <ng-map center="{{ctrl.location}}"
                  geo-callback="ctrl.print('geo-callback')">
          </ng-map>
        </div>
        <input ng-model="ctrl.location"></input>
        <script src="https://opensource.keycdn.com/angularjs/1.5.3/angular.min.js"></script>
        <script src="ng-map.min.js"></script>
        <script>
          angular
            .module('app', ['ngMap'])
            .controller('controller', function () {
              this.location = 'Statue of Liberty';
              this.print = function (message) {
                console.log(message);
              };
            });
        </script>
      </body>
    </html>

**Comment by quentinhayot** [comment]
I have the same problem, here is an exemple: http://plnkr.co/edit/mijd1N?p=preview
The geo-callback is called only once, when the script loads.

**Comment by quentinhayot** [comment]
I am trying to find the source of this bug.
It seems that the whole linkFunc function (doesn't matter which directive it belongs to - map, marker...) is only called once, whatever you try.

**Comment by quentinhayot** [comment]
I found something interesting. When options are modified on a directive (like the position of a marker), callbacks will not be triggered. But if you delete this marker and create a new one with the new position, it will work just fine... once.

**Comment by allenhwkim** [comment]
`geo-callback` is not designed to be used to callback of all geo related properties. It's only used for once when map or marker is loaded.

Other properties can be watched with `{{` `}}` because it can be mapped to google function.
`position` -> `setPosition`
`center` -> `setCenter`

However geo-callback is not done that way. I cannot put all `geo-callback` to all possible `geo` related properties. It's simply too much. :(

PR would be appreciated though.
