### ISSUE TITLE
InvalidValueError: setZoom: not a number

### ISSUE THREAD

**Issue by Sephen** [allenhwkim/angularjs-google-maps#624]
When create the map like this with a fixed zoom level everything works.
`<ng-map id="map" zoom="11" ... >...</ng-map>`

But when i create a map with:
```
$scope.zoom = 11; //in main.js
<ng-map id="map" zoom="{{zoom}}" ... >...</ng-map> //in main.html
```

The first time it runs it will always return this error but the map works correctly.
`InvalidValueError: setZoom: not a number`

I noticed there was a previous issue (https://github.com/allenhwkim/angularjs-google-maps/issues/413) with this error but for some reason mine still persists.

I'm using v1.17.3

Am I doing something wrong?

**Comment by allenhwkim** [comment]
It seems like there is racing condition. 
zoom is recognized as changed, but the value is not a number initially then changed back to real number.

FYI, this example works fine. http://plnkr.co/edit/YUwNZN3iwmbEaIitlB77?p=preview
