### ISSUE TITLE
Move maps lazy loading into service

### ISSUE THREAD

**Issue by ctaepper** [allenhwkim/angularjs-google-maps#627]
If the logic for lazy-loading is moved into a seperate angular service, the directive can still use that service in order to do its job. But now, i could also use that service to preload google as dependency within a route definition, for example

``` js
// routes.js
...
resolve: {
  google: function(GoogleLazyLoadService) {
    return GoogleLazyLoadService.load();
  }
}
...
```

**Comment by ctaepper** [comment]
i quickly put together a service:
```js
'use strict';

import angular from 'angular';

// @ngInject
function NgMapLazyLoad($q, $timeout) {

	this.load = function (mapsUrl) {

		var deferred = $q.defer();

		if (window.google === undefined || window.google.maps === undefined) {

			window.lazyLoadCallback = function() {
				$timeout(function() { /* give some time to load */
					deferred.resolve(window.google)
				}, 100);
			};

			var scriptEl = document.createElement('script');
			scriptEl.src = mapsUrl +
				(mapsUrl.indexOf('?') > -1 ? '&' : '?') +
				'callback=lazyLoadCallback';

			if (!document.querySelector('script[src="' + scriptEl.src + '"]')) {
				document.body.appendChild(scriptEl);
			}
		} else {
			deferred.resolve(window.google)
		}

		return deferred.promise;
	}
}

export default angular.module('services.maps-loader', [])
	.service('NgMapLazyLoad', NgMapLazyLoad)
	.name;

```
i forked this project, but i can't get the tests to work (without adding any code)
so i didn't bother adding the code and creating PR
I'm sure, you get the idea from my code and you can add it yourself?

**Comment by amritk** [comment]
I tried to do something similar as well, the problem I'm having is as soon as you inject NgMap into the component, it gives the `google is undefined` error. Maybe move whatever is in the constructor to be run when you use one of the service methods such as `NgMap.getMap()`

**Comment by allenhwkim** [comment]
A service has been added as `GoogleMapsApi`
```
          GoogleMapsApi.load(myUrl).then(function() {
            console.log('google map has been loaded')
          });
```
