### ISSUE TITLE
How do i redraw a map using ngmap

### ISSUE THREAD

**Issue by marcio81** [allenhwkim/angularjs-google-maps#628]
I comment and put my problem in the link below: 
http://stackoverflow.com/questions/37737431/how-do-i-redraw-map-unsing-ngmap

When i change the sceen and come back the map dont redraw propely. 

Sorry for my bad english. Thanks

**Comment by Saajan** [comment]
use this solution 
http://stackoverflow.com/questions/34886358/how-to-render-maps-within-ng-hide-divs-using-ngmap-without-getting-a-gray-rectan

**Comment by marcio81** [comment]
Hi, thanks for reply, and sorry if im wrong but i dont use ng-hide, and i have only one map i want to show him every time.

**Comment by allenhwkim** [comment]
There have been so many discussions on this. It's not about `ngMap`, but it's about google not drawing a map without fixed width and height.

You need to resize map, the recenter the map. Try add the following code after your page has been loaded.

```
NgMap.getMap({id: 'myMapId' }).then(function(map) {
    google.maps.event.trigger(map, 'resize');
});
```

Any better ideas are welcome
