### ISSUE TITLE
Center and Zoom level ignored when no markers exist and "zoom-to-include-markers" is used

### ISSUE THREAD

**Issue by SErfkamp** [allenhwkim/angularjs-google-maps#630]
Hi,

I am not sure if this is intended behavior, but I don't think so.

When using "zoom-to-include-markers" without initial markers, the center and zoom property will be ignored.

Plunker (its the [example](https://ngmap.github.io/#/!map_zoom_to_include_markers.html) one with the marker array emptied: )
http://plnkr.co/edit/0coxiYEODq5HnZVBN2g3?p=preview

**Comment by SErfkamp** [comment]
@xavierjohn 
Do you maybe know something about this?

**Comment by SErfkamp** [comment]
@allenhwkim 
Any idea about this issue?

**Comment by allenhwkim** [comment]
This is desired behaviour to ignore `center` and `zoom` to include all markers.
Please do not use to `zoom-to-include-markers` if you want to have fixed `center` and `zoom`
Closing it for now. Please reopen this does not answer your question.
