### ISSUE TITLE
Best way to access map services (E.g. PlacesService)?

### ISSUE THREAD

**Issue by JCarran0** [allenhwkim/angularjs-google-maps#631]
I'm trying to make use of the PlaceService nearbySearch method.  Currently I'm making use of $window as I can't figure out from the documentation how else to do this.  This seems to work fine, but I'm guessing there's a better way?

```
NgMap.getMap().then((map) => {
  var placeService = new $window.google.maps.places.PlacesService(map);
  placesService.searchNearby({...}, (results, status) => {...});
});
```

**Comment by allenhwkim** [comment]
You can have your own `PlaseService, but I don't see a way to avoid window.

There is similiar service GeoCode. https://github.com/allenhwkim/angularjs-google-maps/blob/master/services/geo-coder.js

You may take a look at that to see how it is coded.
