### ISSUE TITLE
Polygon color one way binding

### ISSUE THREAD

**Issue by samehraban** [allenhwkim/angularjs-google-maps#632]
I know that polygon attributes like color does not support two way binding. I'm wondering if this is a meant-to-work-this-way features of ngmap or simply has not been implemented yet?

**Comment by allenhwkim** [comment]
In default, ngmap supports one-time binding, not even one-way binding.
Some options are supported with one-way binding only if `set` method is supported by Google Api V3. e.g. zoom -> setZoom
There is no two-way binding in ngmap, and has never been implemented and won't be.

**Comment by samehraban** [comment]
> In default, ngmap supports one-time binding, not even one-way binding.
That was something I was confused about.

What I'm looking for is a way to get one way binding for polygon color. 

> Some options are supported with one-way binding only if set method is supported by Google Api V3. e.g. zoom -> setZoom

Is this another policy of ngmap like never having two way binding or it's not just implemented?

**Comment by allenhwkim** [comment]
Go to here, https://developers.google.com/maps/documentation/javascript/reference

1. find polygon class, https://developers.google.com/maps/documentation/javascript/reference#Polygon
2. find options to set color. If not found, you can not set color="{{color}}".
3. you still can use `setOptions`, then use it . e.g. http://plnkr.co/edit/HqVTI2?p=preview

**Comment by samehraban** [comment]
@allenhwkim Thanks. `setOptions` was exactly what I was looking for.
