### ISSUE TITLE
Hide Google Menu

### ISSUE THREAD

**Issue by MrPallaBall** [allenhwkim/angularjs-google-maps#635]
Hi to all,
is it possible to hide all google map menu?
I use ngmap in a hybrid application, so i would like to hide zoom menu and Map/satellite menu.

Thanks for all

EDIT:
The only way I found is to add a css role to hide all elements that my customer want

Es:

`.gmnoprint {
display: none;
}` 

http://plnkr.co/edit/VLkYVv?p=preview

**Comment by allenhwkim** [comment]
There are controls, and set the control parameters to false. Google Maps API v3 reference will show you how to hide all menus.
