### ISSUE TITLE
Binding shape editable events on polygon

### ISSUE THREAD

**Issue by chozzz** [allenhwkim/angularjs-google-maps#637]
I am having issue on binding events such as `insert_at, remove_at, and set_at` on my shape. Please have a look at https://developers.google.com/maps/documentation/javascript/shapes#editable_events

What I am basically trying to achieve is that I want to update my polygon paths when its been edited.

**Comment by allenhwkim** [comment]
Please create a plunker example to re-produce your issue in public. Without it, it's hard to help.

**Comment by chozzz** [comment]
Here's the plunker http://plnkr.co/edit/Yo5RuK?p=preview
If you notice, the `insert_at` event is never fired.

**Comment by anaumov** [comment]
Check out hint in [docs](https://developers.google.com/maps/documentation/javascript/shapes#editable_events):
> The listener must be set on the polygon's path. If the polygon has multiple paths, a listener must be set on each path.

How we can set listener on path?

**Comment by noushad-pp** [comment]
you can try this. This function will return an array of path cordinates as googlemap LatLngLiterals

```
app.controller( 'MyController',  function(NgMap) {
    NgMap.getMap().then(function(map) {
        map.shapes[0].getPath().getArray();
    });
});
```

**Comment by chozzz** [comment]
@noushad-pp I don't quite get it.. I am trying to get a use of `insert_at` event here. While your solutions is about to get a shape's paths

**Comment by noushad-pp** [comment]
@chozzz  you are anyway trying to update the polygon's path right? Sorry i couldnt find an exact solution that you require.

**Comment by noushad-pp** [comment]
@chozzz  true that. How i managed my requirement which is similar to you is that i get the array coordinates, by using the above code, after the user had done editing the polygon and triggering the update action.

**Comment by dhazan2** [comment]
@chozzz 
`NgMap.getMap().then(function(map) {
				map.shapes[0].getPaths().forEach(function(path, index){

					google.maps.event.addListener(path, 'insert_at', function(){
						var bounds = map.shapes[0].getPath().getArray();
						NewPolygons = bounds;
					});

					google.maps.event.addListener(path, 'remove_at', function(){
						
					});

					google.maps.event.addListener(path, 'set_at', function(){
						var bounds = map.shapes[0].getPath().getArray();
						NewPolygons = bounds;
					});

				});
			});`

**Comment by allenhwkim** [comment]
Closing this since there is no plan to add this listeners into path level. If so, it's too much wrapping, I think.
