### ISSUE TITLE
Current location after enabling GPS

### ISSUE THREAD

**Issue by Jocika1990** [allenhwkim/angularjs-google-maps#638]
Hi,

I am trying to show the current location after user enable his location. 

I tried to use $cordovaGeolocation.watchPosition but I cant update the map.

How can I achieve this?

Thanks

**Comment by allenhwkim** [comment]
try `center=""`

**Comment by Jocika1990** [comment]
center is working fine if the location is already "on" when I open the map but if I open the map and show "geo-fallback-center" and then turn on GPS on mobile it is not updating the current location...

any suggestion? thank you

**Comment by allenhwkim** [comment]
You should get then map instance first
then `map.setCenter( new google.maps.LatLng(lat, long))` within your callback.

**Comment by roskoff** [comment]
@Jocika1990 I call `window.location.reload(true);` after coming back from settings.

**Comment by allenhwkim** [comment]
`geo-fallback-center` is not watchable event, and there is no off-line feature handled by this module. Please re-center your map manually when gets on-line from off-line mode.
