### ISSUE TITLE
Places Autocomplete - Able to preventDefault when selecting a location

### ISSUE THREAD

**Issue by whnunlife** [allenhwkim/angularjs-google-maps#639]
I'm using the Places Autocomplete directive. It's sitting inside a form, and when a user starts typing an address, then selects the address and hit's enter on the keyboard, the form is submitting. If the user just selects the location, then clicks out of the field, everything works correctly.

Is there a way to preventDefault the submit since most users are a use to hitting return once they select an address in the typeahead?

**Comment by aschaible** [comment]
I would like this too!

Thanks

**Comment by allenhwkim** [comment]
You can add another listener to the input field and when it is enter key(13), just simply return false.
It's out of scope question, I think.

**Comment by scaryguy** [comment]
I think it'd be better if the default behavior is set to this. Even novice internet users use arrow keys / enter to navigate through dropdown items nowadays.
