### ISSUE TITLE
How To clear Directions

### ISSUE THREAD

**Issue by Pheonix929** [allenhwkim/angularjs-google-maps#644]
Is there a set directions Display to true or false option in ngmaps or the possibility to clear a route completely off of the map.

**Comment by allenhwkim** [comment]
Please look into the directionsRendered api reference. https://developers.google.com/maps/documentation/javascript/3.exp/reference#DirectionsRenderer,  If it's not there, it's not in ng2-map either.

**Comment by Pheonix929** [comment]
Thanks for the feedback i will post back what my findings are.

**Comment by allenhwkim** [comment]
You can also remove the directive using `ng-if` or try it manually.
http://stackoverflow.com/questions/5645920/remove-directions-from-google-map-api-v3
