### ISSUE TITLE
I always get "his service requires an API key."

### ISSUE THREAD

**Issue by xochilpili** [allenhwkim/angularjs-google-maps#646]
Hi all, 
# In index.html i have

`<script src="https://rawgit.com/allenhwkim/angularjs-google-maps/master/build/scripts/ng-map.js"></script>`
# In the html template i have the directive:

```
<div class="row margin-bottom" map-lazy-load="https://maps.google.com/maps/api/js" map-lazy-load-params="{{mapUri}}">
    <ng-map zoom="8" center="{{hotel.HotelInfo.Street}}" style="margin: 0 auto;">
    <marker position="{{hotel.HotelInfo.Latitude+','+hotel.HotelInfo.Logitude}}" title="{{hotel.Name}}"></marker>
    </ng-map>
</div>
```
# Then in my controller:

$scope.mapUri = 'https://maps.google.com/maps/api/js?v=3.21&key=**ApiKey**';
# console output:

js?callback=lazyLoadCallback:35 This service requires an API key.  For more information on authentication and Google Maps Javascript API services please see: https://developers.google.com/maps/documentation/javascript/get-api-key

I have been searching without any success, any hand?

**Comment by grudelsud** [comment]
my best guess here, @xochilpili check that your template has access to the controller's scope. e.g. I don't see where you declare `ng-controller` and you might as well be using the "controller as" syntax. easy check would be to print `{{ mapUri }}` in the dom to see if it's rendered correctly

**Comment by arch1v1st** [comment]
Same problem over here using the latest version.  Not using 'controller as' syntax.  I am able to print my {{googleMapsUrl}} variable directly in the html template, so the $scope doesn't seem to be an issue, and the only way I could get lazy-load to work was include '?key=XXX' in the map-lazy-load string (and not 'map-lazy-load-params').  Similarly I tried setting a 'styles' parameter inside of the ng-map tag; this approach also would not work when using another custom variable I have defined as $scope.googleMapsStyle named {{googleMapsStyle}}, but works if I put the full style object in the html template...

**Comment by allenhwkim** [comment]
Please update example with a plunker example, so that we need to see the issue easily. FYI, ng2-map does not need to have an API key, and if you see that, it's just a warning

**Comment by yshing** [comment]
Since 22th June 2016 they stop supporting keyless access...
http://googlegeodevelopers.blogspot.hk/2016/06/building-for-scale-updates-to-google.html

**Comment by returnvoid** [comment]
Hi, I'm having the same problem. In your example:

<div map-lazy-load="https://maps.google.com/maps/api/js"
  map-lazy-load-params="{{googleMapsUrl}}">
  <ng-map center="41,-87" zoom="3"></ng-map>
</div>

I don't understand why you are using both at the same time. I tried both, one each but I still get the same warning: No apikey. My tempate have access to the var 'googleMapsUrl' who is the js file+key

Thank you

**Comment by idrenski** [comment]
1. Go to Google Developers and register your app. Take your APP_KEY. Read carefully the instructions there.
2. Add in your index.html 
 <script src="https://maps.google.com/maps/api/js?v=3&key=<APP_KEY>&libraries=placeses,visualization,drawing,geometry,places"></script>

It works for me.

**Comment by allenhwkim** [comment]
Google maps require API key if your site is new.
