### ISSUE TITLE
How to implement search box?

### ISSUE THREAD

**Issue by Jeevanandanj** [allenhwkim/angularjs-google-maps#647]
Hi, 
The following implementation I have found in the google map.

How to implement this in the directive?
https://developers.google.com/maps/documentation/javascript/examples/places-searchbox

**Comment by allenhwkim** [comment]
Google maps places API has not been implemented.

**Comment by Jeevanandanj** [comment]
Will this be implemented in future?

**Comment by talent3310** [comment]
function initSearchBox(map) {
      searchBox.addListener('places_changed', function() {
          var places = searchBox.getPlaces();
          if (places.length == 0) {
            return;
          }
          // Clear out the old markers.
          markers.forEach(function(marker) {
            marker.setMap(null);
          });
          markers = [];
          // For each place, get the icon, name and location.
          var bounds = new google.maps.LatLngBounds();
          places.forEach(function(place) {
            if (!place.geometry) {
              console.log("Returned place contains no geometry");
              return;
            }
            var icon = {
              url: place.icon,
              size: new google.maps.Size(71, 71),
              origin: new google.maps.Point(0, 0),
              anchor: new google.maps.Point(17, 34),
              scaledSize: new google.maps.Size(25, 25)
            };

            // Create a marker for each place.
            markers.push(new google.maps.Marker({
              map: map,
              icon: icon,
              title: place.name,
              position: place.geometry.location
            }));

            if (place.geometry.viewport) {
              // Only geocodes have viewport.
              bounds.union(place.geometry.viewport);
            } else {
              bounds.extend(place.geometry.location);
            }
          });
          map.fitBounds(bounds);
        });
    }

// setUp the search box in the controller
NgMap.initMap('myNgMap-dashboard');
NgMap.getMap().then(function(map) {
  map.setCenter(bounds.getCenter());
  map.fitBounds(bounds);
  initSearchBox(map);
});
