### ISSUE TITLE
Want to Zoom with Directions on Map Marker

### ISSUE THREAD

**Issue by KproApps2** [allenhwkim/angularjs-google-maps#652]
Would like to request 

That I can zoom in on my marker for current position on the map and follow it as I move 

**IMPORTANT**: 

This repository's issues are reserved for feature requests and bug reports. 
Do not submit support questions or request here. Please use stackoverflow instead

**Steps to reproduce and a minimal demo(Plunker Example)**

  - _What steps should we try in your demo to see the problem?_

**Current behavior**

  - 

**Expected/desired behavior**

  - 

**Other information**

  -

**Comment by allenhwkim** [comment]
It is a good request, but I think it's out of scope,

ng2-map does not provide a map feature like this. it's just a wrapper of google maps api v3.

No plan on implementing this, but you can set the marker position and map center by utilizing gogole geo api.
