### ISSUE TITLE
NgMap.getMap()

### ISSUE THREAD

**Issue by tchinou1** [allenhwkim/angularjs-google-maps#653]
Hi, I'm trying to use `NgMap.getMap().then(function(map) {});` but I it end up breaking my controller, and I get this message in the console: "Cannot read property 'getMap' of undefined". In the html page I have a simple ng-map. Am I doing something wrong, or is there a problem with the version ? 
I'm using Yeoman with the Mean.JS generator. 

Thanks !

**Comment by pziegler** [comment]
did you inject NgMap into your controller?

**Comment by tchinou1** [comment]
Yes I did
`(function () {
  'use strict';

  // Spots controller
  angular
    .module('spots')
    .controller('SpotsController', SpotsController);

  SpotsController.$inject = ['$scope', '$state', '$timeout', '$location', 'Authentication', 'spotResolve', 'Upload', 'NgMap'];

  function SpotsController ($scope, $state, $timeout, $location, Authentication, spot, geolocation, Upload, NgMap, Spot) {

    var vm = this;

    vm.authentication = Authentication;
    vm.spot = spot;
    vm.error = null;
    vm.form = {};
    vm.remove = remove;
    vm.save = save;
    vm.zoom = 3;
    
    NgMap.getMap().then(function(map) {
      vm.map = map;
    });
    `

**Comment by tchinou1** [comment]
Nevermind I just find out that it was because of the order of the injection....
