### ISSUE TITLE
zoom-to-include-markers & center

### ISSUE THREAD

**Issue by jongmin92** [allenhwkim/angularjs-google-maps#654]
first.. I can't speek English very well.. but I have question. so I'm writing...

I see demo -> http://ngmap.github.io/#/!map_zoom_to_include_markers.html

I want to set center position when vm.position is empty, but when vm.position is **empty**, map center is not [40.74, -74.18] ... this is bug?

**Comment by pziegler** [comment]
where do you store the value for center?
do you mean
```
if vm.position is empty:
   set center to xxx
else:
  dont set center
```
?

**Comment by allenhwkim** [comment]
It works as expected. 
```
  <ng-map zoom="3" center="[40.74, -74.18]"
    scrollwheel="false"
    zoom-to-include-markers="true">
    <marker ng-repeat="p in []"
      position="{{p.pos}}" title="pos: {{p.pos}}"></marker>
  </ng-map>
```

If the problem continues, please add an MVC example to reopen this.
