### ISSUE TITLE
Very slow rendering

### ISSUE THREAD

**Issue by ericjames** [allenhwkim/angularjs-google-maps#658]
**Steps to reproduce and a minimal demo(Plunker Example)**

Load a map with many markers using custom-marker say over 500 stops. 
Make custom-marker a background color div.
Try moving the map around and specifically zooming.
VERY SLOW. 

**Current behavior**

  - SLOW rendering and zooming. There's clearly a severe delay.

**Expected/desired behavior**

  - Some smoother action, not sure what the problem is.

**Other information**

  -  When loading many markers using traditional marker in Google Maps, it can handle hundreds of stops okay.  What's different with custom-marker that makes it perform so bad on Chrome?

**Comment by allenhwkim** [comment]
I believe that Angular watcher and bindings makes it slower. Try 'no-watcher' for your marker for faster performance.

**Comment by ericjames** [comment]
I need watcher because it is required! I decided to simplify my custom-marker divs and css and load less markers at a time (~300).   It appears this is problem inherent with Firefox, that it can't handle many markers.
