### ISSUE TITLE
How to disable zoom on scroll?

### ISSUE THREAD

**Issue by imevro** [allenhwkim/angularjs-google-maps#66]
Hello. Thank you for your module.

I want disable zoom, when user scrolling, but I don't see in documentation anything about it. How I can do this?

**Comment by rhtvma** [comment]
Just add :   scrollwheel: false,
 ================================================

angular.module('mapModule', [])
        .controller('mapCtrl', function ($scope) {
              
              var mapOptions = {
                  zoom: 50,
                  scrollwheel: false,
                  center: new google.maps.LatLng(40.6700, -73.9400),
                  mapTypeId: google.maps.MapTypeId.HYBRID
              }
                
              $scope.map = new google.maps.Map(document.getElementById('map'), mapOptions);

**Comment by peterWilson34** [comment]
Simply add the scrollwheel attribute to ng-map directive 
`<ng-map  center="28.0320508,26.2443901"  zoom="5" scrollwheel="false">`
