### ISSUE TITLE
How to get existing markers froms the map

### ISSUE THREAD

**Issue by intrepido** [allenhwkim/angularjs-google-maps#663]
How to get all markers that have been created with the ng-repeat. Is there any function inside map instance, to access the created markers? I have this code:

```
<ng-map center="{{vm.searchParameters['hotel_city']}}" zoom="12" ng-if="vm.showMap" class="fx-fade-normal fx-dur-483 fx-ease-sine">
        <marker ng-repeat="hotel in vm.listHotelsFiltered"
                            position="{{[hotel.position.latitude/100000, hotel.position.longitude/100000]}}"
                            data="{{hotel}}"
                            on-click="vm.markerMapHotelDetail()"
                            title="{{hotel.hotel_name}}"
                            >
       </marker>            
</ng-map>
```

Maybe something like this?

```
NgMap.getMap().then(function(map) { //Create the instance of map
        vm.map = map;
        var markers = vm.map.getMarkers(); //?
});
```

**Comment by allenhwkim** [comment]
map.markers would do the job

**Comment by bishtpradeep** [comment]
Hi @allenhwkim , sometimes markers are not accessible after I create them using data obtained from a remote server. But when I put the following $timeout then they are available. Can you please tell why this is happening ?
```

$timeout(function(){
  NgMap.getMap().then(function(map) { //Create the instance of map
          var markers = map.markers;
 });
});

Thanks.
```

**Comment by Petah** [comment]
@bishtpradeep did you figure this out?

**Comment by bishtpradeep** [comment]
@Petah : Unfortunately no. As I mentioned under "EDIT", I loop multiple times to make sure I map.markers length is equal to the one I expect.
