### ISSUE TITLE
Custom Markers For Directions 

### ISSUE THREAD

**Issue by MrGregSithole** [allenhwkim/angularjs-google-maps#664]
My Code looks like this....

`<map ng-if = "showDetails" id="NewMap" zoom="14" center="{{FirstAddress}}" style="height:300px; width: 100%;">
   <directions
    draggable="false"
    travel-mode="DRIVING"
    origin="{{FirstAddress}}"
    waypoints = "{{waypointsClientTrack}}"
    destination="{{FinalAddress}}">
  </directions>
  <custom-marker id="start"
    position="{{FirstAddress}}">
    <div>
      <img src="images/icon.png">
    </div>
  </custom-marker>
</map>`

But my custom icon appears as follows

![screen shot 2016-08-16 at 1 38 47 pm 1](https://cloud.githubusercontent.com/assets/19221410/17697798/362153d4-63b7-11e6-9bb6-88cbd1a7a2bd.png)

Please Help or is there a way to hide the Start Marker

**Comment by abrahamjoseph** [comment]
I do have the same issue but not able find a solution for this. I also want to change the map style i mean to make the map look grey.

**Comment by blalond** [comment]
You'd need to add in the directions tag <directions suppress-markers=true> and then add a marker for the destination like you added the truck on the start.

**Comment by allenhwkim** [comment]
thanks @blalond 

ngMap cannot go further than Google Maps API does.
Only you can do is to remove marker, and add your own if you don't like Google Maps API maker.

However, it would require more code to maintain those markers.
