### ISSUE TITLE
Get driving distance between markers

### ISSUE THREAD

**Issue by Programm3r** [allenhwkim/angularjs-google-maps#665]
Hi,

This is actually more a question than an issue, but how would one plot various coordinates (markers) and then show the driving directions and distance between each marker?

Your assistance is greatly appreciated!
Kind regards,

**Comment by nq2916** [comment]
+1 for this, can't seem to work this one out. Need to get the distance between two markers from map.

**Comment by jelifish** [comment]
vm.map.directionsRenderers[0].directions.routes[0].legs[0].distance.text

**Comment by allenhwkim** [comment]
Please search "distance" on issues. You may find some answers
https://github.com/allenhwkim/angularjs-google-maps/issues/298
