### ISSUE TITLE
How to close infowindow when clicking outside/map?

### ISSUE THREAD

**Issue by raviji** [allenhwkim/angularjs-google-maps#666]
How to close infowindow when clicking map or outside of the map... 

Ex: 
google.maps.event.addListener(map, "click", function(event) {
    infowindow.close();
});

how to implement this code in ng-map?

**Comment by alitto** [comment]
Hi @raviji, in this [plunkr](http://plnkr.co/edit/dwlity2l2mEWlXuQTOat?p=preview) you can see how to create an InfoWindow using the `<info-window>` element and how to close it clicking anywhere on the map.

**Comment by raviji** [comment]
Thanks a lot @alitto you just saved my day!

**Comment by allenhwkim** [comment]
@alitto you ARE the best :)
