### ISSUE TITLE
google map is now loaded async by default and always require api key. Which breaks existing examples.

### ISSUE THREAD

**Issue by yshing** [allenhwkim/angularjs-google-maps#667]
Notice from google: 
[Updates to Google Maps APIs Standard Plan](http://googlegeodevelopers.blogspot.hk/2016/06/building-for-scale-updates-to-google.html)

> 1. **We no longer support keyless access** (any request that doesn't include an API key). Future product updates are only available for requests made with an API key. API keys allow us to contact developers when required and help us identify misbehaving implementations.

Much troublesome to setup new demos >_< ..

And besides requiring an API key, the google map JS libraries are now loaded async by default...
For old demo to work on new sites.. need to add both API `key=xxx` and `aysnc=false`

Like this...

```
<script src="https://maps.google.com/maps/api/js?key=<YOUR API KEY>&async=false"></script>
```

Thanks for such a nice ngDirective  👍

**Comment by Tom951** [comment]
Thanks, but I don't manage to have the autocomplete example/demo working with the key and the async=false
Did you manage to have it working too?
