### ISSUE TITLE
Make the google map look grey. Change the color of the map

### ISSUE THREAD

**Issue by abrahamjoseph** [allenhwkim/angularjs-google-maps#669]
In the current version of the map we don't have option to style the map. Especially change the map colour to grey also an option to change the icons for directions. Please fix that issue or suggest some solutions for  this.

![helpmate_03](https://cloud.githubusercontent.com/assets/11293903/17964809/88d83a3e-6ad8-11e6-85cd-66298b7dd06b.png)

**Comment by allenhwkim** [comment]
Please create a plnkr example for this.

**Comment by allenhwkim** [comment]
out of scope. closing.
