### ISSUE TITLE
Custom markers disappear on second load

### ISSUE THREAD

**Issue by Vatsov** [allenhwkim/angularjs-google-maps#670]
**Minimal demo**
- [Codepen](http://codepen.io/Vatsov/pen/zBgvOR)

**Current behavior**
- Load the map with custom markers
- Press back button
- Load the previous map
- Мarkers are loaded just for the few milliseconds and after that disappear. (They are in html but with display none);

**Expected/desired behavior**
- Markers should not disappear

**Other information**
- On initial map load custom markers are loaded and everything works fine
- With regular markers everything works
- If repeat manually one by one the custom markers in order to exclude ng-repeat  everything works.

**Comment by allenhwkim** [comment]
It's strange for me. as soon as I zoom in or out, marker shows up again.
I need some more research on this.

Meanwhile, why don't you try removing element approach again?

**Comment by alitto** [comment]
Adding `zoom-to-include-markers="auto"` to the `ng-map` element causes some markers to be displayed (4 on my browser) but not all of them: [Codepen](http://codepen.io/anon/pen/wWVdZk)

**Comment by Vatsov** [comment]
Yes, on my browser also are displaying only 4 of 5 markers after first time.
The fifth marker also is visible but with very strange position: 
`left: 4139px; top: -43040px;`

**Comment by alitto** [comment]
I think i found the underlaying issue in the custom-marker directive. There was a 300ms delay between the calculation of the final position for the overlay's div and the update of its top/left coordinates which caused those strange positions for the markers. 
I created PR #674 to fix this scenario.

**Comment by Vatsov** [comment]
Thanks a lot
