### ISSUE TITLE
How can I show bounday points of a region like country or state or city

### ISSUE THREAD

**Issue by krushnachandra** [allenhwkim/angularjs-google-maps#671]
I have the collections of boundary points of a particular places. So how can I will be able to display the region in the map...

**Comment by alitto** [comment]
Hi @krushnachandra, 
You can use the `<shape>` directive to render a polygon that covers the region circumscribed by those points. Here's an [example](http://ngmap.github.io/#/!polygon-simple.html) of a shape that covers the area inside 3 lat/lng points (the fourth point is the same as the first one), but you can provide an arbitrary number of coordinates in the `paths` attribute.

**Comment by krushnachandra** [comment]
Thanks @alitto I have implemented polygon shape  it working as my requirement.

**Comment by allenhwkim** [comment]
The second issue is because google maps are loading in async mode. please use async=false when load it.

For city boundraies, try to look at KML layer.
http://stackoverflow.com/questions/31861822/google-maps-how-to-show-city-or-an-area-outline
