### ISSUE TITLE
Move to marker animation

### ISSUE THREAD

**Issue by di3orlive** [allenhwkim/angularjs-google-maps#672]
It will be cool if on click i can move to next marker with some animation
can u make this feature? (if this is not yet implemented, cuz I did not find)

lol. just understand that i can just add  
```html
.ng-map-info-window{
    transition: all 200ms linear;
}
```

but i found issue https://youtu.be/XXbF57WGKfA
did u know, why it jumping? why it change position 2 times 

(and anyway i tink it will be nice if we have some function )

**Comment by allenhwkim** [comment]
sorry, I don't have plan to implement this feature.
