### ISSUE TITLE
Change marker icon on click

### ISSUE THREAD

**Issue by nkdweb** [allenhwkim/angularjs-google-maps#675]
Hi,

I have one issue.

In map i have default icons, when the user click on the icon it should change into different marker icon to represent that user selected that marker.

Please let me know how to do this.

**Comment by cxnunes** [comment]
Hi, 
the way I am using is:
in the you have the property icon that you can set as an image for example. Also marker object has the function setIcon that you can use to change the marker icon when you want.

You can check google documentation: https://developers.google.com/maps/documentation/javascript/markers

Hope this helps

**Comment by allenhwkim** [comment]
Here is the example. Please use `this.setIcon` on click method
```
<!DOCTYPE html>
<html ng-app="ngMap">
<head>
<meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
<script src="script-tags-for-development.js"></script>
<script>
angular.module('ngMap').controller('MyCtrl', function() {
  var vm = this;
  var icon2 = { url:'images/spinner.gif', scaledSize:[100,100], origin: [10,10], anchor: [50,50] };
  vm.toggleIcon = function(event) {
    console.log('this', this);
    this.setIcon('https://developers.google.com/maps/documentation/javascript/examples/full/images/beachflag.png');
  }
});
</script>
</head>

<body ng-controller="MyCtrl as vm">>
  <ng-map center="-25.363882,131.044922" zoom="4">
    <marker position="-25.363882,131.044922" title="Hello World!"
      optimized="false"
      on-click="vm.toggleIcon()"
      icon="{ url:'images/spinner.gif', scaledSize:[50,50], origin: [10,10], anchor: [50,50] }"></marker>
  </ng-map>
</body>
</html>
```
