### ISSUE TITLE
Link google map and html div

### ISSUE THREAD

**Issue by nkdweb** [allenhwkim/angularjs-google-maps#676]
Hi

I have list of shop list, that is displayed as marker in map and list of shop details in DIV displayed outside of the map.

When i click on the shop detail list DIV, corresponding marker should get activated and icon of the selected shop location will change to another icon.

Will this is possible, please let me know.

**Comment by allenhwkim** [comment]
Yes, possible. However, you need to read through all Google Maps API. It seems your requirements are very advanced.
