### ISSUE TITLE
Why put 2000ms timeout on getMap?

### ISSUE THREAD

**Issue by ywplee** [allenhwkim/angularjs-google-maps#677]
https://github.com/allenhwkim/angularjs-google-maps/blob/master/services/ng-map.js#L52

this line might potentially cause a race condition, is there any reason why there is 2000ms timeout on `getMap()`? I'm happy to contribute but just wanted to confirm with you first.

**Comment by allenhwkim** [comment]
That's maximum timeout. The google map has to be initialised within 2 seconds(long enough). 
Unless the map can be initialised and resolved immediately, we cannot avoid to use promise.
We may find a better way :)

**Comment by ywplee** [comment]
I believe the google map can be failed to initialize within 2000ms depending on the device and network speed. I cannot repro this problem consistently but with different network throttle setting, it's possible to repro it (I've encountered into this race condition on a project personally).

 Would it be helpful if `getMap`  takes something like `maximumWaitTime` as a param?

**Comment by allenhwkim** [comment]
Yes it will be helpful.

**Comment by allenhwkim** [comment]
This has been modified. Now you can use timeout option like `{timeout: 60000}`
