### ISSUE TITLE
Do we have an option to find the Closest marker

### ISSUE THREAD

**Issue by abrahamjoseph** [allenhwkim/angularjs-google-maps#679]
I want to find the closest marker on the map to the current position. Do we have any option to find the most closest marker among a group of markers marked as custom.

**Comment by allenhwkim** [comment]
Sorry, we don't have. Please follow Google API documentation and use it accordingly. ngmap is a just a wrapper of Google Maps API. distance api would be useful or you need to calculate distance by yourself.
