### ISSUE TITLE
First time map come fine but if we redirect from other screen it map not coming some time.

### ISSUE THREAD

**Issue by rahulgupta20nov** [allenhwkim/angularjs-google-maps#680]
Hi,
If we load screen first time using refresh then map is working fine, if we come google-map screen from other screen then google-map is not coming fine. I am attached screen shot with this. in last snapshop, after redirect to map screen, map is coming fine maximum time.

<img width="905" alt="screen shot 2016-09-06 at 4 10 35 pm" src="https://cloud.githubusercontent.com/assets/10140041/18270834/946241a6-744c-11e6-9e73-19fabda9ebe8.png">
<img width="910" alt="screen shot 2016-09-06 at 4 11 04 pm" src="https://cloud.githubusercontent.com/assets/10140041/18270835/94892942-744c-11e6-85b9-fb05f3dcdc56.png">

**Comment by allenhwkim** [comment]
Please take a look at this discussion, https://github.com/allenhwkim/angularjs-google-maps/issues/59
'

**Comment by rahulgupta20nov** [comment]
Thanks Allenhkim, I got the solution.
