### ISSUE TITLE
Google Maps API error: MissingKeyMapError

### ISSUE THREAD

**Issue by playUruguay** [allenhwkim/angularjs-google-maps#681]
Hi !

In the template I have
`<div map-lazy-load="https://maps.googleapis.com/maps/api/js" map-lazy-load-params="{{vm.googleMapsUrl}}" >`

and controller I have set the vm.googleMapsUrl variable as:
vm.googleMapsUrl= 'https://maps.googleapis.com/maps/api/js?key=MY_KEY';

When I load the map, this error appears on the console:
Google Maps API error: MissingKeyMapError https://developers.google.com/maps/documentation/javascript/error-messages#missing-key-map-error

I already tried this same key in the URL on the site and works perfectly
```
<script async defer
      src="https://maps.googleapis.com/maps/api/js?key=MY_KEY&callback=initMap">
    </script>
```

Any idea to solve this problem? Thank you all.

**Comment by allenhwkim** [comment]
http://plnkr.co/edit/4Qp94D76whmnnnQcor3y?p=preview

1. you need to remove `<script>` tag related to google map.

**Comment by evildj67** [comment]
I have the exact problem described above. There are no script tags for google. My key value is correct, but it always gives me Google Maps API error: MissingKeyMapError

**Comment by elenat82** [comment]
I have this problem too, as per example found here: https://github.com/allenhwkim/angularjs-google-maps#lazy-loading-of-google-maps-javascript
- in index.html no Google Maps script tag 
- in template 
`<div map-lazy-load="https://maps.google.com/maps/api/js"
  map-lazy-load-params="{{googleMapsUrl}}">
<div class="map-container">
      <ng-map><marker></marker></ng-map>
    </div>
</div>
`
in controller
`NgMap.getMap().then(function(map){
map.googleMapsUrl="https://maps.google.com/maps/api/js?key=xxxxxxxxxxxx";
})`
the console complains "Google Maps API warning: NoApiKeys"
