### ISSUE TITLE
Cannot remove Traffic layer after adding it

### ISSUE THREAD

**Issue by jesserchow** [allenhwkim/angularjs-google-maps#682]
I am unable to remove the traffic layer after adding it to the map.

See [plunker](http://plnkr.co/edit/24wj3AoaxRRDQ9H9ZUte?p=preview)

Steps to reproduce:
1. check the checkbox to add the traffic layer
2. uncheck the checkbox to remove the traffic layer

**Current behavior**
traffic is still showing on the map

**Expected/desired behavior**
traffic is removed from the map

**Comment by allenhwkim** [comment]
It's a bug because it does not have `on destroy` function assigned like the following as the marker has. https://github.com/allenhwkim/angularjs-google-maps/blob/master/directives/marker.js#L108

```
    element.bind('$destroy', function() {
      mapController.deleteObject('markers', marker);
    });
```

Any volunteer to implement this?

**Comment by jesserchow** [comment]
The destroy function appears to exist:
https://github.com/allenhwkim/angularjs-google-maps/blob/master/directives/traffic-layer.js#L47

```
element.bind('$destroy', function() {
  mapController.deleteObject('trafficLayers', layer);
});
```

**Comment by allenhwkim** [comment]
@jesserchow thanks, interesting. then, it should call this line.

https://github.com/allenhwkim/angularjs-google-maps/blob/10892d7bd5d515cbdb29f6e33b782a293e1a2eab/controllers/map-controller.js#L66

**Comment by jesserchow** [comment]
Yes, I can confirm that it does call that line.

**Comment by jesserchow** [comment]
Any other ideas why this has suddenly stopped working?

**Comment by allenhwkim** [comment]
it turns out that we cannot remove traffic layer unless we reload tiles.

http://stackoverflow.com/questions/25687831/refreshing-google-maps-api-v3-layers

Closing as out of scope.

**Comment by nbadiganti** [comment]
Please try this, it worked for me. 
Call this method to toggle the traffic on the map.  

```
trafficLayerOnMap() {
    if (this.isTrafficEnabled) {
      this.trafficLayer.setMap(null);
      this.isTrafficEnabled = false;
    } else {
      this.trafficLayer = new google.maps.TrafficLayer();
      this.trafficLayer.setMap(this.map);
      this.isTrafficEnabled = true;
    }
  }
```
