### ISSUE TITLE
rightclick is not available for maker?

### ISSUE THREAD

**Issue by mkgn** [allenhwkim/angularjs-google-maps#683]
on-rightclick doesn't seem to work on any type of marker (normal or custom). on-rightclick only works if you apply it to the map itself.

**Comment by allenhwkim** [comment]
http://plnkr.co/edit/firfJw?p=preview

**Comment by mkgn** [comment]
Hi,

This works for standard markers. But if you use it with custom marker,
right click event doesn't work.

                <custom-marker ng-repeat="pos in vm.positions"
position="{{pos.lat}}, {{pos.lng}}" on-rightclick="vm.foo($event)">
                    <div>
                        <img src="
http://simpleicon.com/wp-content/uploads/map-marker-8.png" />
                    </div>
                </custom-marker>

this won't work in plunker.

**Comment by allenhwkim** [comment]
Cusotom marker is accetping DOM listener, not marker events.

https://github.com/allenhwkim/angularjs-google-maps/blob/master/directives/custom-marker.js#L175

However, I do not think Google api accepts contextmenu, which is right cick. 

Closing this as `out of scope`.
