### ISSUE TITLE
marker zIndex doesn't work

### ISSUE THREAD

**Issue by sean72kimo** [allenhwkim/angularjs-google-maps#685]
according to google api, marker options zIndex
https://developers.google.com/maps/documentation/javascript/3.exp/reference#MarkerOptions

I set zIndex in marker tag, but it doesn't work. Belwo is Plunker.
http://plnkr.co/edit/UDrjsMEs37IVNTAHZWcS?p=preview
I set yellow-dot zIndex to 100000, and tried both with or without double quotes around 100000, 
but is is still covered by red-dot. 
Thanks

**Comment by allenhwkim** [comment]
`z-index` not `zIndex`. All attribute values must be dasherized.
