### ISSUE TITLE
Switch language dynamically

### ISSUE THREAD

**Issue by solidevolution** [allenhwkim/angularjs-google-maps#686]
Hello,

is there a possibilty to switch the language dynamically (async)

We use ng-map 1.17.2 with lazy-load but when I switch between "de" and "en", no language switch on map happens. It only works with a reload ...

Here a simplified example how we use it:

HTML

```
<div id="course-map" ng-if="vm.showMap">
    <div class="map" map-lazy-load="https://maps.google.com/maps/api/js" map-lazy-load-params="{{vm.mapService.getGoogleMapsUrl()}}">
        <ng-map
            id="mainMap"
            disable-default-u-i="true"
            center="[{{vm.mapService.geolocation.lat}}, {{vm.mapService.geolocation.lng}}]"
            zoom="{{vm.mapService.zoom}}"
            zoom-control="true"
            zoom-control-options="{style:'SMALL'}"
            pan-control="false"
            street-view-control="false"
            map-type-control="false"
            scrollwheel="true"
            keyboard-shortcuts="false"
            on-zoom_changed="vm.mapService.mapZoomChanged()"
            on-bounds_changed="vm.mapService.mapBoundsChanged()"
            on-idle="vm.mapIdle()"
            min-zoom="5"
        >
        </ng-map>
    </div>
</div>
```

JS

```
NgMap.getMap({id:'mainMap'}).then(function(response) {
                vm.mapService.mainMap = response;

                 [...]
}

function getGoogleMapsUrl() {
    var language = 'en';
    if(angular.isDefined($rootScope.language)) {
        language = $rootScope.language.short;
    }

    return $rootScope.googleMapsConfig.url + '&language=' + language;
}
```

**Comment by allenhwkim** [comment]
It seems possible with re-initializing the directive using `ng-if` condition.

Why don't you try to set vm.showMap as false then change the language then set it to true.

**Comment by solidevolution** [comment]
I tried that but it doesn't work. It only works on refresh, map-lazy-load doesn't fetch the new language if I toggle ng-if condition.

**Comment by solidevolution** [comment]
Any news here?

**Comment by allenhwkim** [comment]
I do not think I would support changing language dynamically soon. Sorry. Furthmore, I am not sure it's possible either since `google` instance is controlled by Google, not me. 

I haven't found any resource that I can change google map language dynamically.

If it's ok, please refresh your page to change language.

**Comment by solidevolution** [comment]
Ok, thanks your your help. I came to the same result. I refresh now after locale switch.

**Comment by nicholaspretorius** [comment]
Good day @solidevolution, 

I realise it has been quite some time since this issue was closed, however I was wondering how you implemented the refresh after the locale switch? 

I am able to change language before map initialisation, but once the map is initialised I have not yet been able to change it.

**Comment by solidevolution** [comment]
@nicholaspretorius I was talking about page refresh, so you init your map again and it works.

After 2 years of trouble with missing application hooks etc. causing such problems, we kicked angular and rebuild/build our projects now with VueJS.
