### ISSUE TITLE
A feature lots of people want

### ISSUE THREAD

**Issue by rexchungrs24** [allenhwkim/angularjs-google-maps#688]
Hello, Kim and all,

Recently, I am running a project using ng-map, it is strong and easy to use.
But now I am facing a issue which I want to combine the features between ng-map and link below:
http://www.geocodezip.com/v3_SO_closestPlaces10.html
I want to compare the distances between markers and search point and order them, I use <directions but it is not successful, I can not figure out.
The project is very important to me and I think this issue that lots of people are facing it, and it would rich ng-map also,  hope any good men make it possible.

Best regards.

**Comment by allenhwkim** [comment]
Thanks

This is out of scope of ng-map question, but  I suggest the possible solutions;

**Solution 1 : Calculate the distance between two points without geo-graphical consideration**

http://stackoverflow.com/a/1502821/454252

**Solution 2:  calculate distance using google spherical api**

`google.maps.geometry.spherical.computeDistanceBetween(latLng1, latLng2)`

**Solution 3: Use google distance matrix api**

https://developers.google.com/maps/documentation/javascript/examples/distance-matrix
