### ISSUE TITLE
Ortography error on page

### ISSUE THREAD

**Issue by leandroluk** [allenhwkim/angularjs-google-maps#690]
Hello, 

I'm using ngMap and ended up finding a misspelling in https://rawgit.com/allenhwkim/angularjs-google-maps/master/build/docs/info-window.html page... the table where you set the dependencies, the text related to Attr2MapOptions is written gogole and not google.

**Comment by allenhwkim** [comment]
Thanks for report it. It will be fixed soon

**Comment by allenhwkim** [comment]
Fixed
