### ISSUE TITLE
Some changes don't seem to be in the build for 1.17.6

### ISSUE THREAD

**Issue by harryj** [allenhwkim/angularjs-google-maps#694]
The change made in  this commit:

https://github.com/allenhwkim/angularjs-google-maps/commit/202fadb7fa779a39d54dd00a295b3fccdfa12856

Doesn't seem to have made it to the build version (build/scripts/ng-map.js). Not sure if it wasn't supposed to be there or if something else happened.

**Comment by allenhwkim** [comment]
The release has not been made. I will make it soon.

**Comment by allenhwkim** [comment]
1.17.7 is released
