### ISSUE TITLE
center coords being geolocated loses precision... and a typo

### ISSUE THREAD

**Issue by TonyWilk** [allenhwkim/angularjs-google-maps#695]
**There's a typo I think:**
line 2491 in ng-map.js of of current build:
`(options.key == 'center' || options.key == 'center') &&`
I believe this is what was intended:
`(options.key == 'center' || options.key == 'position') &&`

**centre of map with injected text coordinates problem:**

```
    <ng-map 
        center="53.738245, -0.331122"      this is ok
        center="{{main.siteLoc}}"           this causes geolocation
```

Geolocation loses lots of precision to create latLng for the map center 
esp. when the map is zoomed in (1/2 a mile at zoom=17). 
Using the above values the geolocated position is:
        lat: 53.7383807  lng: -0.33307490000004236

**Expected/desired behavior:**
Should create latLng directly from the injected string

**I've patched it like this:**
line 208.. in ng-map.js of current build is:

```
 if (!mapOptions.center ||
    ((typeof center === 'string') && center.match(/\{\{.*\}\}/))
  ) {
    mapOptions.center = new google.maps.LatLng(0, 0);
 } else if (!(center instanceof google.maps.LatLng)) {
     ... ends up here to use NgMap.getGeoLocation()
```

note: at this point 'center' is a latLng if a fixed string was used, if it's injected then it's still a string.

```
my patch:
if (!mapOptions.center ||
    ((typeof center === 'string') && center.match(/\{\{.*\}\}/))
  ) {
     mapOptions.center = new google.maps.LatLng(0, 0);
  } else if( (typeof center === 'string') && center.match(/[0-9.-]*,[0-9.-]*/) ){// *NEW*
     mapOptions.center = new google.maps.LatLng(center);                         // *NEW*
  } else if (!(center instanceof google.maps.LatLng)) {
```

Thanks for the great module... hope this is useful to you.
Yours,
  TonyWilk

**Comment by allenhwkim** [comment]
Thanks. 
I would really appreciate if you make a PR for this.

**Comment by TonyWilk** [comment]
I have never used git before (other than downloading useful stuff), however...
after reading lots of help, I guess you want a Pull Request.

I'm reasonably confident that I've managed that but I also seem to have created a 'fork'
- I don't know if that's a good thing or not ;)

Hope I got it right,
  Yours,
     TonyWilk

**Comment by allenhwkim** [comment]
Yes, welcome to git `open source` world. your PR has been merged.
