### ISSUE TITLE
info-window is not well positioned when using custom markers

### ISSUE THREAD

**Issue by fedealconada** [allenhwkim/angularjs-google-maps#697]
When having a CUSTOM marker, the info-window appears in a way that is over the marker.

**Steps to reproduce it

  - You can go into your own [example](https://ngmap.github.io/#/!custom-marker-ng-repeat.html) 
  - Click on any marker, you will se that the info-window appear over the marker.

**Current behavior**

  - info-window is placed over the marker

**Expected/desired behavior**

  - info-window should let the user see the marker and above him display the window

**Comment by allenhwkim** [comment]
I don't think I can do much about this. If I can fix the height of custom marker, I can display info-window above the marker, but custom maker is pure html with dynamic height.

Any suggestions and solutions would be appreciated.

**Comment by fedealconada** [comment]
I have found the way to make it :) No code changes needed. I can send the `icon` attribute to the `<marker>` directive (with and url pointing the the icon image I want) and, when Google Maps API does `new google.maps.Marker(options)` it will create the CustomMarker. Actually, in your examples, what you call CustomMarker should be called something like CustomHtmlMarker or simply HtmlMarker, because it is an OverlayView...
Hope this helps!

**Comment by allenhwkim** [comment]
Ok if your intention is to use diffreent image for marker. `icon` is the way to go.
Yes custom marker is an overlayview, so is the marker. It is not as fully featured as marker though.
I will close this one, and I will consider renaming in the future.
