### ISSUE TITLE
Some of the "ng-map" directive's attributes won't work

### ISSUE THREAD

**Issue by quentinhayot** [allenhwkim/angularjs-google-maps#699]
Hi,

I can't get some features of the `ng-map` directive to work. For exemple (not exhaustive):
- `geo-callback` (the callback is not called when geocoding is done)
- `geo-fallback-center` (those coordinates are not used when geocoding fails)
- `trigger-resize` (the map does not resize itself when set to true)

-`map-initialized`**works well**

```html
<div map-lazy-load="https://maps.googleapis.com/maps/api/js" map-lazy-load-params="{{googleMapsUrl}}">
 <ng-map center="{{fullAddress}}" map-initialized="mapInit()" geo-callback="geoCallback()" geo-fallback-center="[40.74, -74.18]" zoom="1">
     <marker id="marker" geo-callback="geoCallback()" position="{{fullAddress}}"></marker>
 </ng-map>
</div>
```

If I use the `geo-callback` attribute on a marker for example, it works.
I suspect a bug but since nobody else seems to complain I may be wrong.

**Comment by allenhwkim** [comment]
please create a plunker example.for this. You can create plunker example easily from ngmap.github.io

**Comment by quentinhayot** [comment]
I figured out that the callback is actually called once. I close this issue and bump #622 . I posted a plunker example there.

**Comment by quentinhayot** [comment]
I am trying to find the source of this bug.
It seems that the whole `linkFunc` function (doesn't matter which directive it belongs to - map, marker...) is only called once, whatever you try.
