### ISSUE TITLE
bug in showInfoWindow 

### ISSUE THREAD

**Issue by PavleO** [allenhwkim/angularjs-google-maps#701]
in line 1175 ther is 'else if' statement that checks if customMarkers exists:

else if (
                //additionally check if that marker is a custom marker
            typeof mapController.map.customMarkers
            && typeof mapController.map.customMarkers[marker] != "undefined") {
              marker = mapController.map.customMarkers[marker];
            } 

'typeof mapController.map.customMarkers' should also check if it is '!= "undefined"'
 otherwise it always returns true.

kind regards,
Pavle Ozretic

**Comment by allenhwkim** [comment]
Fixed
