### ISSUE TITLE
(Suggestion) Performance comparison between this and the other Angular Maps Module

### ISSUE THREAD

**Issue by stephengardner** [allenhwkim/angularjs-google-maps#703]
It would be interesting if anyone evaluated the performance comparisons between this module and https://github.com/angular-ui/angular-google-maps as far as watchers, observers, and JS profiling for an app with the map and markers.  I've noticed some added choppiness with the other module and the rest of my page.  Not enough to make me switch, but if this one was more performant, I'd do so.

**Comment by sebrojas14** [comment]
I tested ui-angular one yesterday, and on iOS was a desaster in performance

**Comment by frequencydesign** [comment]
I am running into an issue once I have to display over 75 markers on a map. Looking for a solution. Happy with module overall though.

**Comment by allenhwkim** [comment]
You can use `no-watcher` if performance matters
https://github.com/allenhwkim/angularjs-google-maps/blob/master/directives/marker.js#L22
