### ISSUE TITLE
TRANSIT as a travel mode doesn't change the map unless marker is moved

### ISSUE THREAD

**Issue by jmona789** [allenhwkim/angularjs-google-maps#705]
TRANSIT does not work right away, I'm currently using a scope variable to define the travel mode and I have a function that changes it to different types, walking and biking works but changes to TRANSIT doesn't change the map. I've noticed that if I move one the markers slightly after changing it to TRANSIT it works then, do I need to somehow reload the map after changing the travel mode or there another way to fix this?

**Comment by allenhwkim** [comment]
@jmona789 thanks for reporting this, but i do not think this is related to this module, but it is related to Google Maps.
