### ISSUE TITLE
Offset center of the map

### ISSUE THREAD

**Issue by MrJoeXu** [allenhwkim/angularjs-google-maps#706]
Is there any way to offset the center of the entire map? In the Google Map API, I can directly use panBy(offsetX, offsetY) to achieve this, but is there any good way to do this in ngMap?
Thanks!

**Comment by allenhwkim** [comment]
Thanks, but this is out of scope question. ngMap does not provide any method different than Goolgle Maps API3 provides except the made-up attributes https://rawgit.com/allenhwkim/angularjs-google-maps/master/build/docs/ngMap.ng-map.html.
