### ISSUE TITLE
Wrong source code wrapped in last version (1.7.6)

### ISSUE THREAD

**Issue by pcsantana** [allenhwkim/angularjs-google-maps#707]
Hi, thank you for the amazing library.

I'm facing the same problem in this [issue](https://github.com/allenhwkim/angularjs-google-maps/issues/78), and after spend some time trying to find out the problem, I figured out that the last release ([1.7.6](https://github.com/allenhwkim/angularjs-google-maps/releases/tag/v1.17.6)) has the source code from 1.7.3 version.
Only in master branch have the correct one! 
Please correct it when possible.

Thank you!

**Comment by allenhwkim** [comment]
Weird. The current release is 1.17.6
Anyway, I have rebuild and released 1.17.8. Please check
And, thanks for reporting this.
