### ISSUE TITLE
Update the markers in marker-cluster as no effect

### ISSUE THREAD

**Issue by rbecheras** [allenhwkim/angularjs-google-maps#71]
I followed your example marker-cluster https://rawgit.com/allenhwkim/angularjs-google-maps/master/build/marker_clusterer.html

It works, but when the markersData is updated, nothing changes. Adding or removing markers has no effect on the map.

I don't know if it is an issue or I am doing something wrong.

**Comment by FMRiggio** [comment]
@allenhwkim Hi, can you repost this example: https://rawgit.com/allenhwkim/angularjs-google-maps/master/build/marker_cluster.raw.html
In my case, I load a set of custom markers from remote, then they are rendered into the map. Now I have to make a marker cluster with these custom markers from remote, but is not working. Can you paste me a quick example on how to manage markers from remote with the marker clusters?

Thanks
Filippo

**Comment by benediktdertinger** [comment]
Hey @allenhwkim the examples you provided aren't available anymore. I'm building a custom marker cluster and have to dynamically update the custom markers (and the cluster) several times after the cluster has been initialized. How can I accomplish this? Thanks in advance!

**Comment by allenhwkim** [comment]
@benediktdertinger That example has been removed because of it's out of scope. This module does not and cannot provide support for marker clusterer.

**Comment by benediktdertinger** [comment]
@allenhwkim thanks for your fast reply. Two weeks ago I started to switch (from leaflet) to your maps integration in a quite complex project I'm developing. I'm really in need of a reliable solution dealing with clusters as I've rewritten almost all functionalities. Is there any example you could provide to show how your integration can handle adding dynamic custom markers, applying a cluster and redraw markers and the cluster after markers changed? I really tried a lot of examples and created [this plunker](https://plnkr.co/edit/A3ayZ6REt9Yiyn9fCTG2?p=preview) to show the problem I'm facing (check the _resetMarkers_ fnct): The clusters won't stop to be drawn on the current map (but they should be removed and new markers should be added). Also I don't understand when I have to retrieve the map by _getMap()_ or if it its okay to manipulate the instance that lives on _$scope_ (where i set it before). I'm really stuck here. Thanks in advance!!

**Comment by allenhwkim** [comment]
@benediktdertinger Please find this as useful(I hope)
https://rawgit.com/allenhwkim/angularjs-google-maps/master/testapp/marker-clusterer.html

It's very simple code
```
    NgMap.getMap().then(function(map) {
      for (var i=0; i<1000; i++) {
        var latLng = new google.maps.LatLng(markers[i].position[0], markers[i].position[1]);
        vm.dynMarkers.push(new google.maps.Marker({position:latLng}));
      }
      vm.markerClusterer = new MarkerClusterer(map, vm.dynMarkers, {});
    });
```
But you need to remember is that
 * you need to remove all markers from map before you build a new one because, I believe that, MarkerClusterer adds those markers into the map.
* You also need to setMap as null for each marker
* any more(I don't know, and that's another reason we do not officially support this)

Also I found this
http://stackoverflow.com/questions/8229827/update-markercluster-after-removing-markers-from-array

**Comment by benediktdertinger** [comment]
Hey @allenhwkim thanks for your answer! 
I made it work by not using your provided directives but creating the markers with the google lib directly as supposed in your given examples. My mistake was to suppose that I could achieve this by using your directives which seemed to me as a more clean and angular-way of structuring it. For those struggling with marker clusterer: Simply create all markers the _google-way_ and **do not use directives for markers** aimed to be clustered. Than you can simply access and work with the clusterer instance like so:
```javascript
// In your controller...
var mapMarkerClusterer;
// Items you're watching
$scope.items = [
  { id: 1, lat: 1, lng: 1 },
  { id: 2, lat: 1.1, lng: 1.1 }
];
// E.g. items changed event triggers...
NgMap.getMap().then(function(map) {
  var bounds = new google.maps.LatLngBounds(),
      dynMarkers = [];
  // Add markers, listeners and get bounds
  angular.forEach($scope.items, function(item) {
    var marker = google.maps.Marker({
      position: new google.maps.LatLng(item.lat, item.lng),
      id: item.id
    });
    marker.addListener('click', function() {
      // ...
    }
    bounds.extend(marker.getPosition());
  });
  // Set or refresh cluster
  if (mapMarkerClusterer) mapMarkerClusterer.clearMarkers();
  mapMarkerClusterer = new MarkerClusterer(
    map,
    dynMarkers, 
    {}
  );
  // Center and fit bounds
  map.setCenter(bounds.getCenter());
  map.fitBounds(bounds);
  // Apply map changes to scope
  $scope.map = map;
});
```
