### ISSUE TITLE
ReferenceError: google is not defined

### ISSUE THREAD

**Issue by darwinrc** [allenhwkim/angularjs-google-maps#710]
I'm getting the following error trying to use the geocoder service:
```
angular.js:13642 ReferenceError: google is not defined
    at Object.t [as geocode] (http://localhost:6240/Scripts/ng-map.min.js:25:28246)    
```

I'm injecting the service into my controller 
```
 appModule.controller('myController', ['$scope', 'NgMap', 'NavigatorGeolocation', 'GeoCoder', 
    function ($scope, NgMap, NavigatorGeolocation, GeoCoder) {
        GeoCoder.geocode({address: 'Avenida Calle 26 # 40-40, Bogotá'}).then(function (result) {
            //... do something with result
            console.log('RESULT GEOCODER: ', result);
        });
    }]);
```` 

I also tested with NgMap function getting the same reference error
```
 NgMap.getGeoLocation('Avenida Calle 26 # 40-40, Bogotá').then(function (result) {
                console.log('GETGEOLOCATION: ', result);
            }, function (error) {
                console.log('Error getting geolocation: ', error);
            });  
```
As shown in the snippet, I have successfully used other NgMap and NavigatorGeolocation services. 

Here is the code of my page
```
<div map-lazy-load="https://maps.google.com/maps/api/js" map-lazy-load-params="{{ $ctrl.googleMapsUrl }}">
    <div class="row">
        <div class="col-md-6">
            <ng-map id="map"
                    center="{{ $ctrl.mapCenter }}"
                    street-view="{{ $ctrl.svp }}"></ng-map>
        </div>
        <div class="col-md-6">
            <ng-map id="sv" />
        </div>
    </div>
</div>
```

And in the corresponding controller/component
```
 $ctrl.googleMapsUrl = "https://maps.googleapis.com/maps/api/js?key=MY-API-KEY";
 $ctrl.mapCenter = 'current-location';
```

I'm using AngularJS v1.5.6

**Comment by stranger26** [comment]
I am facing the same issue.
Am using this in the mean time: `https://maps.googleapis.com/maps/api/geocode/json?address=1600+Amphitheatre+Parkway,+Mountain+View,+CA&key=YOUR_API_KEY
`.
[Geocoding API Documentation](https://developers.google.com/maps/documentation/geocoding/start#sample-request)

**Comment by darwinrc** [comment]
Thanks @stranger26 I'll take a look at that partial solution. Does it mean this is a confirmed issue?

**Comment by stranger26** [comment]
I'm not sure as it throws another error `InvalidValueError` when I implement map-lazy-load in my HTML. I implemented GeoCoder in JS without any NgMap dependency previously.

**Comment by darwinrc** [comment]
The solution was posted in https://stackoverflow.com/questions/40193036/referenceerror-google-is-not-defined-using-ng-map-geocoder-service

It just a matter of getting the map and using the geocoder service within the result promise. 

I'm closing the issue.
