### ISSUE TITLE
NgMap.getMap()

### ISSUE THREAD

**Issue by phishy** [allenhwkim/angularjs-google-maps#712]
This is shared state between controllers. If I have two maps in two different routes, it shares all the same markers. Is this the intended behavior? I understand this is how Angular services work, but I don't see any way to force different IDs for maps.

**Comment by jeudywr** [comment]
I'm having this issue. How did you solve it?

**Comment by allenhwkim** [comment]
Take a look at this example. `getMap` take an id as optional.

https://github.com/allenhwkim/angularjs-google-maps/blob/792043a36ab4a2fb42eb5dc0a1df80e3a0d31db4/testapp/ui-router.html
