### ISSUE TITLE
current-position not working in Safari

### ISSUE THREAD

**Issue by wiseoldman** [allenhwkim/angularjs-google-maps#713]
**Steps to reproduce and a minimal demo(Plunker Example)**

I'm using Safari Version 9.0.2 (11601.3.9) on my MacBook Pro and the newest version on my iPhone, both browsers are having the same issue.

I used this example: https://rawgit.com/allenhwkim/angularjs-google-maps/master/testapp/map_with_current_position.html 

**Current behavior**

The map always uses the geo-fallback-center when I'm trying to get the current-position in Safari browsers. If no geo-fallback-center is set, the map is just grey.

**Expected/desired behavior**

 Centering the map around the users current location.

**Comment by allenhwkim** [comment]
I think you need to allow the webpage to find your location

**Comment by wiseoldman** [comment]
I'm aware of that and I have of course given the necessary permission. It happens across multiple devices on the Safari browser: http://i.imgur.com/CTlwWQe.gif

**Comment by allenhwkim** [comment]
Can't do much about it.  It's browser geo location failing.
Hope this problem does not continue.

![image](https://cloud.githubusercontent.com/assets/1437734/23692844/2cca4966-039f-11e7-86b9-c325a8654b58.png)

http://stackoverflow.com/questions/41137594/network-location-provider-at-https-www-googleapis-com-returned-error-code
