### ISSUE TITLE
Anyway to remove regular markers on map when using custom markers for directions?

### ISSUE THREAD

**Issue by jmona789** [allenhwkim/angularjs-google-maps#715]
I am using ng-map for directions and I am putting in custom markers, but the default markers show up behind the custom ones, is there anyway to hide the default markers?

**Comment by abhayONS** [comment]
Yes I have the same query. How to remove that

**Comment by hefler** [comment]
Late reply but it might help someone else:
```<directions origin="'New York'" destination="'New Jersey'" suppress-polylines="true" suppress-markers="true"></directions>```
