### ISSUE TITLE
Need help with custom overlay

### ISSUE THREAD

**Issue by manish2535** [allenhwkim/angularjs-google-maps#720]
Hi, I have been trying to create a custom label on a Polyline for a while now and am unable to. Something like this - 

![image](https://cloud.githubusercontent.com/assets/4663798/20485316/f532f162-afc8-11e6-9593-3c24348b2e0b.png)

I know how to get the Polyline showing but cant figure out how or if its even possible to have a label like the one highlighted in the image. I am trying to insert custom messages inside the overlay and style it with CSS.  Any help would be much appreciated. Thanks.

**Comment by allenhwkim** [comment]
I think you can use custom marker, which is a custom overlay,  with custom CSS. 
Or, you can build your own custom overlay.

In either way, you have to learn and practice deeply about custom overlay.

**Comment by manish2535** [comment]
OK thanks.
