### ISSUE TITLE
Unable to see marker (TypeError: Cannot read property 'addObject' of null)

### ISSUE THREAD

**Issue by mikias10** [allenhwkim/angularjs-google-maps#723]
I am not able to see the marker on the map:

```
<div class="col-md-6">
          <ng-map center="{{latLng}}" zoom="11"></ng-map>
          <marker position="{{latLng}}"></marker>
</div>
```

I get the following error in the console:
**TypeError: Cannot read property 'addObject' of null**

I could't find a reason or a solution here or anywhere else.

**Comment by allenhwkim** [comment]
`marker` must be inside `ng-map`
