### ISSUE TITLE
Maximum number of markers?

### ISSUE THREAD

**Issue by JacoboDB** [allenhwkim/angularjs-google-maps#725]
I am trying to show a lot of custom markers in the map but the map only shows as maximum 11 markers, any idea why?

**Comment by frequencydesign** [comment]
I have used this recently for over 300, using multiple a custom marker images. The performance slows down after about 75, but I found no issues. Are you getting errors or is there a code gist you could share?

**Comment by allenhwkim** [comment]
With `no-watcher`, you can add more than 1000 markers.

 * @attr {Boolean} no-watcher if true, no attribute observer is added.
