### ISSUE TITLE
Marker Cluster Example PNG's broken

### ISSUE THREAD

**Issue by genericlady** [allenhwkim/angularjs-google-maps#727]
Cluster Images aren't loading
https://rawgit.com/allenhwkim/angularjs-google-maps/master/testapp/marker-clusterer.html

**Comment by allenhwkim** [comment]
Thanks for reporting this. I believe that those images are from google. I will see what I can do about it

**Comment by ZippoRays** [comment]
Any solutions yet? Can we change the cluster's img URL somehow?

**Comment by allenhwkim** [comment]
Ok, fixed it by specifying image path

```
  <script>
    MarkerClusterer.prototype.MARKER_CLUSTER_IMAGE_PATH_ 
      = 'https://raw.githubusercontent.com/googlemaps/js-marker-clusterer/gh-pages/images/m';  //changed image path
  </script>
```

https://rawgit.com/allenhwkim/angularjs-google-maps/master/testapp/marker-clusterer.html
