### ISSUE TITLE
Locations within radius from database

### ISSUE THREAD

**Issue by sagargulati** [allenhwkim/angularjs-google-maps#728]
We have data in database as 

```
{
    "status": "ok",
    "id": 1,
    "name": "Lousie Restraunt",
    "description": "Some restraunt description",
    "owner": "Owner Name",
    "phone": "Restraunt Phone 123456",
    "email": "restaunt email",
    "address": "Restraunt Address",
    "location": "Sydney",
    "country": "AU",
    "coordinates": {
        "latitude": "30.33",
        "longitude": "30.33"
    },
    "placeId": "googlePlaceIdForMap"
}
```
So we have coordinates, User is here on website, share their browser location, it gets their cordinates.
So how do we match/find areas or locations within 10m of radius which we have in our database from the user's current location?

Help appreciated.

**Comment by allenhwkim** [comment]
Please take a look at this. 
https://github.com/allenhwkim/angularjs-google-maps/issues/298
Closing as out of scope.

**Comment by sagargulati** [comment]
How is this out of scope? :)

**Comment by allenhwkim** [comment]
ng-map is just a angular version wrapper of google maps api 3. Thus, if it is not related to Angular, the answer should be found at more deeper level google maps api 3. That's why it's out of scope.
If you know more about Google maps api 3, ng-map is a lot easier to use.

**Comment by sagargulati** [comment]
So the features should be implimated via API?

**Comment by allenhwkim** [comment]
You are asking distance between two Lat/Lngs, and it can be calculated using Google Maps API v3 using distance matrix or any, not from ng2-map. #298 will give you some ideas.
