### ISSUE TITLE
Map not displaying on options change from another tab in tab view

### ISSUE THREAD

**Issue by sadiq-mc** [allenhwkim/angularjs-google-maps#730]
I am using this directive in my hybrid app developing with ionic v1.3.2.

**Current behavior**
Well, I have a tabbed design in which one tab is displaying the ngMap and other a list of location. Initially when I open the locations view, the map is displayed with the locations plotted on the map and the view bounds to visible all markers. The locations for plotting in the map as well as listing in the list tab are obtained from back-end service call. I have a select option which contains the types of locations which updates the location in the map as per the option selects. In the initial load, while I change the location type from the select option, the map updates with the locations under the selected type and updates the bounds as well. Now when I switch the tab to List and change the select options (which is a common option for both tabs), the list in the List tabs changes successfully and also logs the change in google map. But now when I switch the Map tab, the map is not displaying but a gray background. Now when I change the type from select options 3 times, the map displays, but the bounds doesn't work as expected.
 

**Expected/desired behavior**
 The map should be displaying and the location should be plotted with the bounds set.

**HTML Code Snippet**
```
<div id="map_canvas" map-lazy-load="https://maps.google.com/maps/api/js" map-lazy-load-params="{{googleMapsUrl}}">
        <ng-map default-style="false" center="25.40,55.51" zoom="8" min-zoom="5" map-type-id="TERRAIN" map-type-control="false" street-view-control="false" options="mapOptions" ng-style="{height: mapHeight + 'px'}">
        <marker id="mark_{{locationInfo.Id}}" ng-repeat="locationInfo in filteredLocations.LocationInfo" position="[{{locationInfo.Latitude}}, {{locationInfo.Longitude}}]" icon="images/ic_location.png" on-click="showLocationInfo(locationInfo)"></marker>
        <info-window id="location-info">
            <div ng-non-bindable>
                <span><strong>Name:</strong> {{markerInfoWindow.Name}}</span>
                <br/>
                <span ng-if="markerInfoWindow.Address"><strong>Address:</strong> {{markerInfoWindow.Address}}</span>
            </div>
        </info-window>
    </ng-map>
</div>
```

**Controller Code snippet**
```
NgMap.getMap().then(function(map) {
    $scope.map = map;
    google.maps.event.addListener(map, "idle", function() {
        google.maps.event.trigger(map, 'resize');
    });

    $scope.setupMapClickListener();
    angular.forEach($scope.locationDetails, function(value, index) {
        if (index == 0) {
            // sets the radio checked by default
            $scope.choice = value.LocationType;
            $scope.selectedLocationType = value.LocationType;
            $scope.filterSelectedLocation(value.LocationType);
        }
    });
});
```

**Comment by allenhwkim** [comment]
The duplicate to Issue #530 and #577

Please follow this example if you are using ui-router, http://ngmap.github.io/#/!ui-router.html

If not, you need to resize the map, also you need to recenter when DOM is re-created. This is known issue of Google maps. Please search issue with resize

**Comment by sadiq-mc** [comment]
@allenhwkim Thanks for the comment.. But still I face the same even after adding the ```trigger.resize``` in the ```<ng-map/>``` and added below code in the controller too.
```
$scope.zoomToIncludeMarkers = function() {
            logService.log('zoomToIncludeMarkers');
            var bounds = new google.maps.LatLngBounds();
            $scope.filteredLocations.LocationInfo.forEach(function(c) {
                var latLng = new google.maps.LatLng(c.Latitude, c.Longitude);
                bounds.extend(latLng);
            });
            $scope.map.fitBounds(bounds);
            if ($scope.filteredLocations.LocationInfo.length == 1) {
                $scope.map.setZoom(5);
            }
        };

$scope.filterSelectedLocation = function(locationType) {
    $scope.filteredLocations = {};
    logService.log('filterSelectedLocation');

    $scope.filteredLocations = $filter('filter')($scope.locations, function(d) {
        return d.LocationType === locationType;
    })[0];

    $scope.zoomToIncludeMarkers();
};
```

Adding the above code, the map is been displayed and location is been plotted while switching from list tab to map tab (the location type was changed from list tab), but the fitBounds() is not responding. When I change the location type from map tab, the map is updating with locations and the fitBounds() as expected. Can you please help with more suggestions.

**Comment by sadiq-mc** [comment]
Resolved this issue [here](https://github.com/allenhwkim/angularjs-google-maps/issues/734)
