### ISSUE TITLE
[REQUEST] Change map theme

### ISSUE THREAD

**Issue by heliojuniorkroger** [allenhwkim/angularjs-google-maps#741]
Hi, i want to change the map theme, like this:
https://mapstyle.withgoogle.com/

**Comment by allenhwkim** [comment]
Sorry, that's too much for me. PR would be appreciated.

**Comment by nloyola** [comment]
This can be done by setting the `styles` option. Eg:

```
<ng-map center="{{vm.centre}}" zoom="{{vm.zoom}}" styles="{{vm.styles}}"></ng-map>
```

And in the controller, assign `vm.styles` to the value given in the JSON string shown after pressing the <kbd>Finish</kbd> button.
