### ISSUE TITLE
popup/sidenav: map center in upper left corner

### ISSUE THREAD

**Issue by exchsac** [allenhwkim/angularjs-google-maps#742]
When the container is initially hidden the maps center is in the upper left corner when the map is drawn for the first time, even when explicitly calling setCenter() and sending 'resize' event.

http://codepen.io/exchsac/pen/PbreYZ
(drag to see the marker in the upper left corner)

**Comment by parmindersingh1** [comment]
same issue marker in the upper left corner

**Comment by parmindersingh1** [comment]
map.setCenter after resize event fixed my problem

**Comment by allenhwkim** [comment]
I have added FAQ section for this. 
![image](https://cloud.githubusercontent.com/assets/1437734/23711622/61996772-03ee-11e7-903f-6df636a02c36.png)
