### ISSUE TITLE
[$compile:ctreq] Controller 'leaflet', required by directive 'center', can't be found!

### ISSUE THREAD

**Issue by SangeetAgarwal** [allenhwkim/angularjs-google-maps#743]
I'm getting the following error on the console
`Error: [$compile:ctreq] Controller 'leaflet', required by directive 'center', can't be found!
http://errors.angularjs.org/1.5.10/$compile/ctreq?p0=leaflet&p1=center
    at http://localhost:9001/vendor/js/angular/angular.js:68:12
    at getControllers (http://localhost:9001/vendor/js/angular/angular.js:9628:17)
    at nodeLinkFn (http://localhost:9001/vendor/js/angular/angular.js:9551:33)
    at compositeLinkFn (http://localhost:9001/vendor/js/angular/angular.js:8806:13)
    at nodeLinkFn (http://localhost:9001/vendor/js/angular/angular.js:9541:11)
    at http://localhost:9001/vendor/js/angular/angular.js:9882:13
    at processQueue (http://localhost:9001/vendor/js/angular/angular.js:16692:28)
    at http://localhost:9001/vendor/js/angular/angular.js:16708:27
    at Scope.$eval (http://localhost:9001/vendor/js/angular/angular.js:17990:28)
    at Scope.$digest (http://localhost:9001/vendor/js/angular/angular.js:17804:31) undefined`

This happens when I declaratively center the map as so
`<ng-map default-style="false" zoom="3" center="[45.6650000, -95.4103000]" style="height: 500px; display:block;" min-zoom="2">
  <info-window id="myInfoWindow">
    <div ng-non-bindable>
      <a ng-href="#/practice/{{selectedValue.id}}">{{selectedValue.name}}</a>
    </div>
  </info-window>
</ng-map>`

The centering as well as the zooming everything works perfectly - but as long as I have the center defined as above the error message shows in the console. On the other hand if I set the center as so

`NgMap.getMap().then(function (map) {       
            var myLatLng = new google.maps.LatLng(45.6650000, -95.4103000);
            map.setCenter(myLatLng);
            map.setZoom(3);
$scope.map = map;
          }`

instead (and, remove the declarative centering) then I do _not_ get the error but the map moves to a location to the west of African continent before zooming to the center of the United States, so the user experience is not very good.

The Ng-Map is in a practicesMapEnhanced directive which I then consume as so
`  <div class="practices__map" practices-map-enhanced style="height:500px"></div>`

BTW - this is an excellent library and except for this one error being displayed on the console, it seems to be working very well.

**Comment by allenhwkim** [comment]
I do not think this is ng-map error. https://github.com/tombatossals/angular-leaflet-directive/issues/535. Closing as out of scope. Thanks for using it though.
