### ISSUE TITLE
15$ for solving +++ Adding and removing points with directions doest work properly

### ISSUE THREAD

**Issue by martinmakesitwork** [allenhwkim/angularjs-google-maps#744]
+++ 15$ for the one who solves this issue on bountysource +++
https://www.bountysource.com/issues/40802861-adding-and-removing-points-with-directions-doest-work-properly

_The library im using is ngmap https://ngmap.github.io/_

@allenhwkim:
Im not the first one who had this problem.
https://github.com/allenhwkim/angularjs-google-maps/issues/460

But i have created a plunker:
http://plnkr.co/edit/oHtF6sTY5KOujWM8Vj3G?p=preview

So if you play around with the add buttons on the bottom of the map, you will see that the directions will produce failures after a while. The markers than doesnt match to the directions. 

I would be really grateful if anyone could help me.

![image](https://cloud.githubusercontent.com/assets/19605697/22027819/4b7095be-dcd5-11e6-8d27-cd666f935052.png)

The yellow markers are on the route. As you can see, the origin, the destination and the waypoints are correct, but somehow it doesnt update it on the map.

**Comment by bonemx** [comment]
Heres our solution!!
http://plnkr.co/edit/hC47rBNQkVGTgYw4J137?p=preview

The problems is that the ngMap don't refresh correctly, so we just add a ng-if with a variable to refresh the directions directive, hopes this helps you!
