### ISSUE TITLE
Street-view-panorama doesn't work when ng-map has an id 

### ISSUE THREAD

**Issue by AhmedAYAT** [allenhwkim/angularjs-google-maps#745]
The street view panorma was not displayed when i specify an id for my map. Please check this plunker , I wait your response.
http://plnkr.co/edit/PRvHkmvtr3hFOqLG0mzg?p=preview
Thanks.

**Comment by allenhwkim** [comment]
Thanks for reporting this. There is bug, which does not accept id to get a map. https://github.com/allenhwkim/angularjs-google-maps/blob/master/directives/street-view-panorama.js#L67

**Comment by AhmedAYAT** [comment]
Thanks for you reply. that's solve my problem.

**Comment by allenhwkim** [comment]
This has been fixed
