### ISSUE TITLE
dynamically show/hide shapes

### ISSUE THREAD

**Issue by jcmag** [allenhwkim/angularjs-google-maps#747]
Hi,
I display several shapes using ng-repeat, and I set: visible="{{displayShape}}" for each shape.
At start, displayShape=false, so no shape is displayed, fine.
Then, I have a button to set displayShape to true, but no shape is displayed when I click on it....
Should I call a refresh method on the map, or something else?

**Comment by allenhwkim** [comment]
It works for me, http://plnkr.co/edit/jEeTB2DGjWaOJr43FSoJ?p=preview
Please follow the example.

**Comment by jcmag** [comment]
found it!
I had no-watcher="false" set on my <shape> tag. It works by removing it.
(btw, it's strange, adding no-watcher, either true or false, breaks the visible switch...)
