### ISSUE TITLE
directions do not show when ng-map has an id

### ISSUE THREAD

**Issue by samunt** [allenhwkim/angularjs-google-maps#748]
There seems to be a bug when an id is added to ngMap and you are trying to show directions. Please see [this link](http://plnkr.co/edit/dEvwxHeKv7C2cUXEruLf?p=preview) . If you remove the id, the directions show fine. When you add the id, directions don't show. I wonder if its connected with [this bug](https://github.com/allenhwkim/angularjs-google-maps/issues/745)

**Comment by allenhwkim** [comment]
This has been fixed with 1.18.2
