### ISSUE TITLE
Error: $injector:unpr Unknown Provider on MEAN stack app

### ISSUE THREAD

**Issue by kurtdaveting** [allenhwkim/angularjs-google-maps#752]
Encountering the Error: $injector:unpr Unknown Provider on a MEAN stack app
The error seems to be isolated on the MEAN stack. No problem using ngmap on simple angular plunker.
Fixes tried prior to submitting the issue

- tried using var name `ngMap` and `NgMap`

- installed with either `bower` and `npm`

- reinstalled `node_module`

Controller:
```
(function() {
  'use strict';

  angular
    .module('visualization')
    .controller('VisualizationController', VisualizationController);

  VisualizationController.$inject = ['NgMap'];

  function VisualizationController(NgMap) {


    var ctrl = this;

    NgMap.getMap().then(function(map){
      ctrl.map = map;
    });
  }
})();
````
Thanks

**Comment by allenhwkim** [comment]
Did you add ngmap as your module dependency?

**Comment by kurtdaveting** [comment]
Issue solved by adding the dependency as `ngMap`

controller injection must be `NgMap`
