### ISSUE TITLE
Directions optimize

### ISSUE THREAD

**Issue by petrind** [allenhwkim/angularjs-google-maps#753]
In Google Maps API, directions can have "optimize" (bool) properties.
It is better if Ngmap has way to add this.

**Current behavior**
No way to add optimize properties on Directions as seen on https://ngmap.github.io/#/!directions.html

**Expected/desired behavior**
attribute optimize to set the optimize properties to call Google maps directions API
**Other information**
https://developers.google.com/maps/documentation/directions/#JSON tab waypoints

**Comment by allenhwkim** [comment]
There is no `optimize` options here

https://developers.google.com/maps/documentation/javascript/3.exp/reference#DirectionsRendererOptions

I only see is `optimizeWaypoints` at  https://developers.google.com/maps/documentation/javascript/3.exp/reference#DirectionsRequest

If so, please add `directions-waypoints="true"`
