### ISSUE TITLE
change language of the map

### ISSUE THREAD

**Issue by sonicwong** [allenhwkim/angularjs-google-maps#760]
May I know how to change the language of the map?

I tried below, but none of them work:

`<div map-lazy-load="https://maps.google.com/maps/api/js" map-lazy-load-params="language=en" >`

`<div map-lazy-load="https://maps.google.com/maps/api/js?language=en" >`

`<ng-map language="en" ... >`

**Comment by allenhwkim** [comment]
Once you have google maps api already loaded as English, your lazy load won't affect any because it uses the pre-loaded language.

To make use of lazy-load, please remove `<script>` tag

```
    <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&callback=initMap&language=ja&region=JP"

```
