### ISSUE TITLE
Wrong git tag breaks updating to latest with Bower

### ISSUE THREAD

**Issue by johanalkstal** [allenhwkim/angularjs-google-maps#761]
For instance, `npm` recognizes the version `1.18.0` because it's specified in `package.json` but Bower doesn't because you haven't created a `1.18.0` tag but a `0.18.0` one.

**Comment by johanalkstal** [comment]
@allenhwkim It's been pretty silent for a couple of weeks. Have you seen this?

**Comment by neslinesli93** [comment]
Please fix this @allenhwkim

**Comment by allenhwkim** [comment]
Sorry about that. I pushed the tag.
