### ISSUE TITLE
Custom Control transclude error

### ISSUE THREAD

**Issue by hefler** [allenhwkim/angularjs-google-maps#764]
After PR #755 I started getting an error with customControl.
`Error: content.appendTo is not a function. (In 'content.appendTo(customControlEl)', 'content.appendTo' is undefined)`. You can check the same error happens in the examples page: https://ngmap.github.io/#/!control-custom-state.html

**Comment by allenhwkim** [comment]
@stillgbx Can you take a look into this issue?

**Comment by allenhwkim** [comment]
@hefler do you have a fix for this in your mind in case of @stillgbx is busy?

**Comment by allenhwkim** [comment]
My Findings, http://teropa.info/blog/2015/06/09/transclusion.html

**Comment by stillgbx** [comment]
It seems that `appendTo()` is not always defined, maybe according to angular version.  We can perhaps replace https://github.com/allenhwkim/angularjs-google-maps/blob/master/directives/custom-control.js#L43 by `customControlEl.append.apply(customControlEl, content.toArray());`.

**Comment by hefler** [comment]
Angular has not `appendTo` we have to use `append`. So: `angular.element(customControlEl).append(content);`

**Comment by hefler** [comment]
I forked and implementing it.

**Comment by stillgbx** [comment]
Not officially you're right, but sometimes...  
![sometimes](https://cloud.githubusercontent.com/assets/15780237/23718359/79b3ff72-0437-11e7-9627-9a65267fd337.png)

**Comment by stillgbx** [comment]
I rapidly investigated why in my (complex) context this function is defined... and I found that the project use jQuery...

**Comment by allenhwkim** [comment]
1.18.4 released with this fix.

**Comment by jamendub** [comment]
Hello, I ran into that exact same issue.
I installed package via NPM and version is 1.18.4
The build/scripts/ngmap.js indicates a version of 1.18.3 though, I think the NPM build version is incorrect, could you confirm and debug this please ?

Thank you very much, this library is much appreciated !
