### ISSUE TITLE
Script broken on home page

### ISSUE THREAD

**Issue by nloyola** [allenhwkim/angularjs-google-maps#766]
The `marker-remove.html` script on the [home page](https://ngmap.github.io/#/!marker-remove.html) does not work. Pressing the <kbd>Hide Markers</kbd> button does nothing. Same with <kbd>Delete Markers</kbd> button.

What is the correct way to hide markers?

**Comment by allenhwkim** [comment]
This has been fixed.

**Comment by nloyola** [comment]
The fix wascommitted in 5e238353c9c053e533e819dcb6742df3e7cd8222.
