### ISSUE TITLE
Maximum number of markers (Same as #725)

### ISSUE THREAD

**Issue by crkjl** [allenhwkim/angularjs-google-maps#769]
Hi, I've the same problem that issue #725.
Only 11 markers are show.

They are created by ng-repeat, and in Chrome devtools -> AngularJS -> Scopes appear all ng-repeat but only 11 are painted on map.

This is my marker code:

`<marker position="{{item.address | normalizeAddress}}; {{item.zipCode | removeNull}} {{item.city}}" title="{{item.policyHolder}} - {{item.address | normalizeAddress}}" ng-repeat="item in itemsNearAssigned | orderBy:'item.address'" no-watcher="true" geo-callback="direcciones()"></marker>`

geo-callback function is called only 11 times.

No errors in console.

Any idea?
Regards

**Comment by allenhwkim** [comment]
This is related to Google API Usage limit for geo coding, and for more markers, please use lat/lng instead of using address if possible.
Please attach your console log for more details.

**Comment by crkjl** [comment]
Nothing about maps in log. Attached
[localhost-1489426975795.txt](https://github.com/allenhwkim/angularjs-google-maps/files/839138/localhost-1489426975795.txt)

**Comment by allenhwkim** [comment]
http://stackoverflow.com/questions/10762839/javascript-google-maps-displays-only-10-markers-out-of-100-is-there-a-limit

Please take a look at this.
