### ISSUE TITLE
fit bounds By event listener 

### ISSUE THREAD

**Issue by NahidaHK** [allenhwkim/angularjs-google-maps#770]
Hello 

i tried to create a listener for bounds changed event by this piece of code :

    google.maps.event.addListenerOnce(map, "bounds_changed", function () {
       map.setCenter(bounds.getCenter());
       map.fitBounds(bounds);
    });

but i got this Error :

Error: a is undefined

I need Help for this plz

**Comment by allenhwkim** [comment]
Please create a plunker example for this to be debugged properly. 
Sorry for the late response. I just saw this.

**Comment by allenhwkim** [comment]
Please take a look at this example.
https://plnkr.co/edit/DAYL2phmIq1VKbWL78oj?p=preview
closing it for now.

**Comment by NahidaHK** [comment]
thnx  @allenhwkim ,  i was trying to add a plunker for my code but i have a terrible internet connection -_-

i will check it thnx again :)
