### ISSUE TITLE
Malware injection in the repo

### ISSUE THREAD

**Issue by swingerman** [allenhwkim/angularjs-google-maps#774]
YOUR REPO CONTAINS A MALVARE

**Steps to reproduce and a minimal demo(Plunker Example)**

/testapp/scripts/markerclusterer_packed.js

  - _What steps should we try in your demo to see the problem?_

**Current behavior**

  - Opens popup with malware that causes the site uses your package blacklists. Thank You!

**Expected/desired behavior**

  - No malware

**Other information**

  -

**Comment by allenhwkim** [comment]
I do not understand what you are saying

**Comment by swingerman** [comment]
Your test app has a malware script

**Comment by allenhwkim** [comment]
That's copied from Google site, http://google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js

It's very interesting.

**Comment by swingerman** [comment]
Yes, the packed file is an injector. I found that injector in another repo as well. I suggest you to remove the file.

**Comment by charles-boyd** [comment]
I unpacked the file and didn't see anything suspicious about it. 

http://pastebin.com/aVbnExft

How does this function as an injector?

**Comment by allenhwkim** [comment]
Closing this until I got a proof that markerclusterer_packed.js is a malware
