### ISSUE TITLE
How to display coordinates on mouse move over the map?

### ISSUE THREAD

**Issue by dharmeshpurohit** [allenhwkim/angularjs-google-maps#775]
Hi ,

I have just seen this repo today and it seems very good. 

I am trying to figure out how can see the coordinates when I move the mouse over the map?

Is there any demo example or an easy way to achieve this? I am hoping some like this 

https://jsbin.com/gumuvu/1/edit?html,css,js,output

but in the ng-map form.

Regards,

Dharmesh

**Comment by allenhwkim** [comment]
https://ngmap.github.io you can find many examples there

**Comment by dharmeshpurohit** [comment]
Hi Allen,

I have gone through these examples but I didn't found anything which has demo to display coordinates on mouse move over the map.

Dharmesh

**Comment by allenhwkim** [comment]
https://ngmap.github.io/#/!events.html. You can simply change on-click to `on-mousemove`.

**Comment by dharmeshpurohit** [comment]
This is good. when I check this does this also display lat-long values? I haven't seen anything that displays lat-long.

**Comment by allenhwkim** [comment]
Please take a look at this example.. It displays the event on the console.
https://plnkr.co/edit/rlqmifFZxp83MqoRmcfa?p=preview
Closing it for now.
