### ISSUE TITLE
How to destroy or reset map?

### ISSUE THREAD

**Issue by andreworks** [allenhwkim/angularjs-google-maps#776]
Hello everyone,

I have a grid and I´m trying load a map with the last user position. The map is loaded on modal, and I do a request every time, the plugin is creating instance of top of instance.

I´m trying to destroy the instance before load a new map, but without success.

```
$scope.gMaps = function () {
        NgMap.getMap('lastposition-map').then(function (map) {
            vm.map = map;
            NgMap.deleteMap(vm);
        });
    }
```

Anyone can help me?
Tks!

![map](https://cloud.githubusercontent.com/assets/4095186/24475907/e0473fee-14a7-11e7-8306-3448412c1f59.PNG)

**Comment by allenhwkim** [comment]
Please look into this answer. Google maps is different than others on this matter, IMO.

http://stackoverflow.com/questions/10485582/what-is-the-proper-way-to-destroy-a-map-instance

**Comment by allenhwkim** [comment]
closing out of scope.
