### ISSUE TITLE
two way data binding for zoom 

### ISSUE THREAD

**Issue by samtidbit** [allenhwkim/angularjs-google-maps#780]
hey i have used code in index.html
`  <ng-map on-click="mapmarkerclicked()" center="33.343469,-84.507196" zoom="12">
                <marker ng-repeat="pos in vm.selectedvalue" position="{{pos.lat}}, {{pos.lng}}" "></marker>
            <marker ng-repeat="pos in vm.positions|filter:vm.searchText" position="{{pos.lat}}, {{pos.lng}} "" icon="{path:'CIRCLE', scale: 10, strokeColor: 'red', zIndex:10}"></marker>
            
            </ng-map>`
and in index.js
` NgMap.getMap().then(map => vm.map = map);
    vm.stated = true;
    $scope.titleclick = function(_id) {
        vm.stated = false;
        vm.selectedvalue = [];
        filtered = $filter('filter')(vm.items_list, { _id: _id });
        console.log(filtered);
        vm.selectedvalue = [{ lat: filtered[0].lat, lng: filtered[0].lng }];

        // vm.selectedvalue.push({lat:filtered.lat, lng: filtered.lng});

        vm.map.markers[0].setMap(vm.map);

    }
    $scope.gn = function() {
        if (vm.stated == true) {
            vm.positions = $filter('filter')(vm.items_list, { title: $scope.searchText });
            console.log(vm.positions.length);
        }

    }
    $scope.mapmarkerclicked = function() {
      console.log("value clicked");
    }
    $interval($scope.gn, 500);`
now i want when anyone zoom in and out then i my controller function should called
may be we can do using events but i do not know what every i listen for zoom

**Comment by allenhwkim** [comment]
please take a look at this example
https://ngmap.github.io/#/!map_events.html

`zoom_changed` seems the one you are looking for
