### ISSUE TITLE
how do i chack the zoom level when zoom changes

### ISSUE THREAD

**Issue by samtidbit** [allenhwkim/angularjs-google-maps#781]
my code is 
controller
$scope.zoomChanged = function(){
        console.log(vm.zoom);
    }
html
<ng-map  event-ready="vm.mapready($ngMap)" on-zoom-changed="zoomChanged()" on-center-changed="centerChanged()" zoom-to-include-markers="auto" zoom={{vm.zoom}}>
                <marker ng-repeat="pos in vm.selectedvalue" position="{{pos.lat}}, {{pos.lng}}" "></marker>
...
</ng-map>

I just want to know how to doi get current zoom level when zoom changed every being called

**Comment by allenhwkim** [comment]
`map.getZoom()`?

**Comment by samtidbit** [comment]
ya i done different way but i solved it.
second i like the support of ng-map.
thanks
