### ISSUE TITLE
Pass the directive element within the callback

### ISSUE THREAD

**Issue by stevenanthony** [allenhwkim/angularjs-google-maps#782]
Would it be possible to pass the directive element to the callback method (especially with the places autocomplete, and directions directives)?

E.g. when a user selects the place using the autocomplete, the element gets the place name, and the call back gets the latitude and longitude, but I can't see any way to associate the two. And when the directions are changed (or if it fails to find directions), I'd like the callback to know which direction changed or failed (I may have multiple directions directives in a single map).

Thanks.

**Comment by allenhwkim** [comment]
I am sorry, but can you explain more in detail?

**Comment by stevenanthony** [comment]
Sorry, I should have been clearer. 

I have this code using the places-auto-complete directive:

<div ng-repeat="location in locations">
		      	<input places-auto-complete size=80
    				ng-model="location.address"
    				on-place-changed="placeChanged()" />
    		</div>

When the placeChanged() method is called, I'd like to be able to access the element or model, so I can associate the latlng in the placeChanged method with the location in the model.

I also have this code using the directions directive:

<div ng-repeat="dir in directions track by trackByFunction(dir)">
		  	  <directions
	            draggable="true"
	            suppress-markers="true"
	            travel-mode="DRIVING"
	            panel="{{dir.panelName}}"
	            origin="{{dir.origin.latLng}}"
	            destination="{{dir.destination.latLng}}"
	            on_directions_changed="directionsChanged()">
	          </directions>
		  	</div>

When the directionsChanged method is called (or the directions failed, when that gets implemented), I'd like to be able to access the direction that failed/changed, so I can handle it appropriately.

Does that make more sense?

Thanks.

**Comment by allenhwkim** [comment]
@stevenanthony sorry, not much. An example would be better for me.

```
angular.module('myApp', ['ngMap']).controller('MyCtrl', function(NgMap) {
  var vm = this;
  vm.types = "['establishment']";
  vm.placeChanged = function() {
    vm.place = this.getPlace();
    console.log('location', vm.place.geometry.location);
    vm.map.setCenter(vm.place.geometry.location);
  }
  NgMap.getMap().then(function(map) {
    vm.map = map;
  });
 });
```

You are saying `this` is not enough?
And why autocomplete is related to directions? directions is a different directive. If you want directions, please use `map.directions` as you see in README.md

**Comment by stevenanthony** [comment]
Sorry, for some reason the examples I added didn't show up. I wasn't actually relating autocomplete to directions, they were separate examples. 

I'll start with autocomplete. I have a $scope.locations object, which is an array of "locations" objects. And this html:
```
<div ng-repeat="location in locations">
		      	<input places-auto-complete size=80
    				ng-model="location.address"
    				on-place-changed="placeChanged()" />
    			
    		</div>
```

When placeChanged is called, I use this.getPlace() to get the latitude and longitude of the place. And I want to set those on the location object (so each location has an address, and a latitude and longitude). But I can't see any way of finding the correct location within the placeChanged method. 

Thanks.

**Comment by allenhwkim** [comment]
locations[$index] is the location. I hope you are not asking that one. That's an Angular matter. Btw, are you making multiple autocomplete for each location ?  Please create a plunker example if you really want to get the help.

**Comment by stevenanthony** [comment]
I've created a plunker here: http://plnkr.co/edit/VCwDgIRPbkJO0YN0u14B?p=preview

I only have one autocomplete for a location, but I have an array of locations, and I create the autocomplete by using an ng-repeat on the locations, so I don't see anyway to find the correct location in the placeChanged callback.

I have a workaround, by storing the current location using on-blur, but I'd prefer to be able to get it within the placeChanged callback instead. 

Thanks.

**Comment by allenhwkim** [comment]
@stevenanthony I try not to manipulate autocomplete with my own stuff in there, by strictly following google api as much as possible. Please use your workaround at this time. However, who khows, if this kind of request is very common, I can make an exception.

**Comment by stevenanthony** [comment]
Ok, thanks. I'm guessing you'd feel the same about changing the directions directive? I have a similar case for that. I have an array of directions, and when the on-directions-changed callback is called I'd like to know which direction it was.

I do have a workaround for that too (although it's a slightly more complicated work around). 

But I might even look at extending or wrapping the directives myself, since my use case is probably somewhat unusual. 

Thanks,

**Comment by anilbk009** [comment]
vm.placeChanged = function() {
    vm.place = this.getPlace();
    console.log('location', vm.place.geometry.location);
    vm.map.setCenter(vm.place.geometry.location);
  }

Can please anyone help me out how the ' this.getPlace()' is get called to get the location information
