### ISSUE TITLE
Using custom marker clusterer with infowindow

### ISSUE THREAD

**Issue by Joystan** [allenhwkim/angularjs-google-maps#785]
Hi @allenhwkim,

First of all, thank you for this amazing package, really appreciate the work you've put in this.

I'm facing a problem with using a `custom-marker` along with an `infowindow`. can you please assist me with this?

I've created a [plunker](http://plnkr.co/edit/0Y89X4xhSaUrdYgsJaqC?p=preview) of how I'm going about with this. Would really appreciate some assistance.

Thanks

**Comment by allenhwkim** [comment]
Please follow the example provided from ngmap.github.io.

https://ngmap.github.io/#/!custom-marker-ng-repeat.html

**Comment by Joystan** [comment]
I've finally managed to get this working but yet the `infowindow` overlaps the  `custom-marker` which should open above the `custom-marker`. Linking [plunker](http://plnkr.co/edit/0Y89X4xhSaUrdYgsJaqC?p=preview) for reference.

**Comment by allenhwkim** [comment]
@Joystan nice. 
If you can make a PR with your example would be great other people.

Can you close this?

**Comment by Joystan** [comment]
@allenhwkim but there is still a bug in this as the `infowindow` opens on top of the `custom-marker`. Which instead should open above the `custom-marker` in a normal senario. Is there a way we could fix this?

**Comment by allenhwkim** [comment]
You may try using `pixelOffset` of infowindow.
http://stackoverflow.com/questions/31064916/how-to-change-position-of-google-maps-infowindow
