### ISSUE TITLE
how to find current zoom ?

### ISSUE THREAD

**Issue by samtidbit** [allenhwkim/angularjs-google-maps#788]
hey
`$scope.zoom=0;
  $scope.zoomChanged = function(){
        console.log(vm.zoom);
    }`
and in ng-map
` <ng-map event-ready="vm.mapready($ngMap)" on-zoom-changed="zoomChanged()" on-center-changed="centerChanged()" zoom-to-include-markers="auto" zoom={{vm.zoom}}>
</ng-map>`
my first work is complete that when some one zoom in or out then one function should call. now for completing i just want to get current zoom level in zoomchanged function
Please solve my problem because i can not complete my project without finding current zoom ?

**Comment by allenhwkim** [comment]
@samtidbit 
#1. Please take a look at examples at ngmap.github.io. This may help you. https://ngmap.github.io/#/!events.html
#2. "Please solve my problem" will never happen in open source community :)

**Comment by samtidbit** [comment]
hmm i know map.getZoom() but the problem i am getting is that i use zoom-to-include-markers="auto" then when i put take marker data from api the zoom level autometically called and start the loop of getting new zoom type data. so how can i find that this zoom effect user do and other zoom effect map autometically do?

**Comment by samtidbit** [comment]
with reference to other issue in this i have find out way .
thanks
