### ISSUE TITLE
Marker position doesn't update

### ISSUE THREAD

**Issue by roomm** [allenhwkim/angularjs-google-maps#789]
I have a map and below a bootstrap tabs (UI-bootsrap) where I have buttons to change a marker position.
The marker position is stored in a variable. The problem comes when I change the value of that variable because the marker position doesn't update until I click to another tab.
I don't know what i should do or what I'm ding wrong.

**Comment by allenhwkim** [comment]
@roomm please create a plunker example to look into your issue.

**Comment by roomm** [comment]
Here's the plunker https://embed.plnkr.co/rP27Y5Se3YFdx0jkkhGQ/. Seems to work perfect, so the problem will be something else... Thank you anyway!
