### ISSUE TITLE
Marker gets hidden behind the another marker.

### ISSUE THREAD

**Issue by snehshah** [allenhwkim/angularjs-google-maps#790]
**IMPORTANT**: 

Hello, I am trying to implement two markers in the map, One marker is the red google map marker and another marker is the icon for different events on the map. The issue that is happening is sometimes the red google map marker comes in front of the another event marker and sometimes it comes behind the event marker. Please let me know how can I ensure the red google map marker always stays on the front than all the other markers.

**Steps to reproduce and a minimal demo(Plunker Example)**

`
<ng-map center="{{mapcenter}}" on-zoom-changed="zoomChanged()" zoom="{{vm.zoom}}">
            <marker ng-repeat="pos in vm.selectedvalue" position="{{pos.lat}}, {{pos.lng}}" "></marker>
            <marker ng-repeat="pos in vm.positions|filter:vm.searchText " position="{{pos.lat}}, {{pos.lng}} " icon="{{icons}}" on-mouseover="MshowInfoWindow(pos)" on-click="showdetails(pos)"  id='{{pos._id}}'></marker>
             <info-window id="foo-iw ">
                    <div ng-non-bindable=" ">
                    <table>
                        <thead>
                            
                        </thead>
                        
                        <tr ng-show="currentType==='location'">
                        
                             <div class="row no-padding " style="margin-bottom: 0 !important; ">
                                <div class="col-sm-9 no-padding ">
                                    <div class="event-box-title">{{vm.svalue.title}}</div>
                                    <p class="x-sml ">{{vm.svalue.start_time?vm.svalue.start_time:vm.svalue.likes + " Likes"}}</p>
                                    <p class="x-sml ">{{vm.svalue.checkins?vm.svalue.checkins + " Checkins" : ""}}</p>
                                    <p class="x-sml ">{{vm.svalue.address?vm.svalue.address:vm.svalue.checkins + " Checkins"}}</p>
                                    <p class="x-sml ">{{vm.svalue.attending_count?vm.svalue.attending_count+" Attending":""}} </p>
                                </div>
                                
                                <div class="col-sm-3 no-padding ">&nbsp;<img ng-src="{{vm.svalue.image}} " width="80px " height="92px " style=""></div>
                            </div>
                        </tr>
                    </table>
                   
                    </div>
                  </info-window>
            </ng-map>`

**Current behavior**

![screen shot 2017-04-19 at 3 54 18 pm](https://cloud.githubusercontent.com/assets/10560096/25175530/b8881bdc-2518-11e7-9351-6059d658718a.png)
  

**Expected/desired behavior**

![screen shot 2017-04-19 at 3 54 18 pm](https://cloud.githubusercontent.com/assets/10560096/25175572/ece74e3e-2518-11e7-836c-9d15cd439dfb.png)

**Other information**

http://www.webclueslab.com/qa/webclues-iti/

**Comment by allenhwkim** [comment]
Have you tried `zIndex`?  https://developers.google.com/maps/documentation/javascript/3.exp/reference#MarkerOptions

**Comment by snehshah** [comment]
no i do not use z-index but it sound like i can use z-index in marker but problem is where i use z-index 
` <marker z-index="89888" ng-repeat="pos in vm.selectedvalue" position="{{pos.lat}}, {{pos.lng}}"">
</marker>`
or 
` <marker style="z-index:89888" ng-repeat="pos in vm.selectedvalue" position="{{pos.lat}}, {{pos.lng}}"">
</marker>`
i am just confused that your provided link says i have to use first method but html says i have to use second method

**Comment by allenhwkim** [comment]
@snehshah the first one.

**Comment by snehshah** [comment]
@allenhwkim Thanks Done.
