### ISSUE TITLE
angularjs-google-maps always asks for location permission 

### ISSUE THREAD

**Issue by jarekskuder** [allenhwkim/angularjs-google-maps#798]
I have my cordova app with agularjs-google-maps. I don't need that my app asked for location permission every time user comes to map state. Of course if user allows the location permission - it's all ok. But when user don't want to give location permission it always ask's for it. I even did the native android app and added google maps to see is there is the same, but no, google maps don't ask for permission, it works without and never asks.

If there is the way that this map stop to ask for location???

**Comment by allenhwkim** [comment]
Please specify location with lat/lng, not blank or string. It won't ask. It only asks when it is required.

**Comment by jarekskuder** [comment]
Thx for your reply, i made a check that if GPS allowed then <ng-map center="current-position"... else if deny then <ng-map center="[55.1947157, 24.6297574]"... 

So i think i did what you have told

**Comment by jarekskuder** [comment]
Even if i just place the <ng-map center="[55.1947157, 24.6297574]"... it still asks the permission always...

**Comment by jarekskuder** [comment]
I'm sorry, i forgot that i had current-location not only in ng-map center tag, but in my current location marker and direction tags.
