### ISSUE TITLE
Map with dynamic address error 

### ISSUE THREAD

**Issue by davecyen** [allenhwkim/angularjs-google-maps#80]
Hi, thanks for creating this. I prefer this over the other angular-google-maps library. However I'm getting an error when creating a map with dynamic address and need help.

I'm following your example that you provided:
https://github.com/allenhwkim/angularjs-google-maps/blob/master/build/map_with_dynamic_address.html 

In my HTML, I've created the same elements
input type="text" ng-model="address" 
map center="{{address}}" 

However, for each character I type in the input field, I'm getting an error in the console:

Error: setCenter: not a LatLng or LatLngLiteral: not an Object

I've also tried removing the input field, and defining $scope.address = "San Francisco, CA" in the controller, but receive the same error. 

When I hardcode an address in the map directive, e.g. map center="San Francisco, CA", it works fine.

Can you help me? Thanks

**Comment by ananthhh** [comment]
Thanks for this awesome tool. But this problem is real tricky one 
Here is the plunker http://plnkr.co/edit/qofAE1CkzFCSFdOw1aLR?p=preview
