### ISSUE TITLE
Heatmap dynamic point data

### ISSUE THREAD

**Issue by kurtdaveting** [allenhwkim/angularjs-google-maps#806]
Greetings!

From:
`<heatmap-layer id="foo" data="mapData"></heatmap-layer>`

How do you make `mapData` dynamically changeable so the heatmap points update without refreshing the page?

Changing the value of `$scope.mapData` the controller doesn't seem to work.

Only work around for this is not to use `id="foo"`:
`heatmap = new google.maps.visualization.HeatmapLayer({data: $scope.mapData, radius: 20});`

By doing so, the default `<heatmap-layer>` parameters are lost (radius, gradient, opacity, etc)

Any help will be greatly appreciated. Also what parameter values are being used by the default `<heatmap-layer>` (radius, maxIntensity, opacity, etc) Thanks!

**Comment by allenhwkim** [comment]
Please try this.
Google heatmap is designed differently from marker. 
https://stackoverflow.com/questions/13479514/updating-heatmap-data-simple-google-heatmap

**Comment by kurtdaveting** [comment]
Thank you for the fast response. Changed all my operations to `push()` and `pop()` instead of instantiation/assignment and everything worked fine. Cheers!
