### ISSUE TITLE
places-auto-complete "Can't find variable: google"

### ISSUE THREAD

**Issue by uberspeck** [allenhwkim/angularjs-google-maps#819]
**Steps to reproduce and a minimal demo(Plunker Example)**

  - Use `places-auto-complete` and the `map-lazy-load`
  - https://plnkr.co/edit/jYJu9jw5DnkKTsgCV3pL?p=preview

**Current behavior**

  - Using `places-auto-complete` and the `map-lazy-load` approach causes a `Can't find variable: google` error.

**Other information**

  - I'd rather not load the google maps api in the HTML header as it's only needed on one page of a very large application. Not sure what else I can do?

**Comment by uberspeck** [comment]
@allenhwkim , oops...forgot to include my plnkr initially. Sorry about that...

**Comment by allenhwkim** [comment]
Please move `place-auto-complete` into `map-lazy-load` to resolve this issue.

https://plnkr.co/edit/dfRz1BKJJF7aIRdpYAxd?p=preview

**Comment by uberspeck** [comment]
That's pretty obvious now that you mention it. Should have thought of that :-P Thanks for your help!
