### ISSUE TITLE
how to update map after model change.

### ISSUE THREAD

**Issue by drrv10** [allenhwkim/angularjs-google-maps#825]
am using ng-map to draw a map:
_`**<div_ class="content" style="height:500px" id="mapDiv"> <ng-map zoom="15" id="mapId" center="{{start.lat}},{{start.lng}}" style="height:100%" >    <directions draggable="false" panel="directions-panel" travel-mode="DRIVING" origin="{{start.lat}},{{start.lng}}"  waypoints="{{waypoints}}" destination="{{end.lat}},{{end.lng}}"  >  </directions> </ng-map></div>**`

If I update my model for start, end or waypoints , map is not getting refresh(show first initialized values). What can be done to solve this(is there something like dorebuildall="true" modelsbyref="false" ) which can update map based on model.

**Comment by allenhwkim** [comment]
Please take a look at this example https://ngmap.github.io/#/!directions.html

**Comment by drrv10** [comment]
Thanks, it solved my problem
