### ISSUE TITLE
'map' directive restriction as attribute and element?

### ISSUE THREAD

**Issue by dicbrus** [allenhwkim/angularjs-google-maps#826]
map directive is defined with restrict: AE

```
 var mapDirective = function () {
    return {
      restrict: 'AE',
      controller: '__MapController',
      controllerAs: 'ngmap'
    };
};
```

Is it correct? 
Any tag containing attribute `map` are detected as map directive
like 
```
<div map=""></div>
```

Seems restriction should be only for Elements?

**Comment by allenhwkim** [comment]
This is correct. `map` tag is HTML reserved word. If people wants to use as an attribute, they are also  allowed to use it as an attribute.

**Comment by xandedj** [comment]
Good afternoon.

How can I change the height of the map, soon I'm only half the screen and I need the whole screen

Thank you very much in advance.

**Comment by allenhwkim** [comment]
@xandedj 
There is a fullscreen control. you can make use of it
https://developers.google.com/maps/documentation/javascript/controls
