### ISSUE TITLE
When the map inside a modal is opened for the second time, the map center position gets changed.

### ISSUE THREAD

**Issue by shirazz** [allenhwkim/angularjs-google-maps#828]
When i opens the map inside a modal for the second time, the map center gets changed. You can see this here http://plnkr.co/edit/01o6Rt8BDoTFNBp5kpdJ?p=preview

**Comment by allenhwkim** [comment]
This may help you.

https://github.com/allenhwkim/angularjs-google-maps#grey-area-in-google-maps

**Comment by shirazz** [comment]
Thank you @allenhwkim for the quick reply
