### ISSUE TITLE
I'm getting map that fit all markers but with beige background

### ISSUE THREAD

**Issue by slillo** [allenhwkim/angularjs-google-maps#833]
**Steps to reproduce and a minimal demo(Plunker Example)**
I'm trying to use ngmap as simple as possibile with zoom-to-include-markers and async markers.

I've tried to reproduce on plunker, but in plunker the map is not shown at all:
[plunkr](https://plnkr.co/edit/JHCVop9DwXCgyLPMbhJO?p=preview)

**Current behavior**
I'm getting map that fit all markers but with beige background. Satellite view works fine. 
The problem is not solved if I resize browser window.

![mappabeige](https://user-images.githubusercontent.com/12492340/29870915-17fb5a6e-8d8a-11e7-8672-fe0da901b11b.png)

![satelliteview](https://user-images.githubusercontent.com/12492340/29870964-4b9f4e02-8d8a-11e7-8aa2-f4f3ecdf2d43.png)

**Comment by allenhwkim** [comment]
The given plunker is not working. Please provide a new one.

**Comment by slillo** [comment]
I've tried to reproduce on plunker, but in plunker the map is not shown at all without error, however it was just a matter of zoom in a zone without streets or label.
