### ISSUE TITLE
Add options to DirectionsRenderer

### ISSUE THREAD

**Issue by igler** [allenhwkim/angularjs-google-maps#834]
I'd like to add options to DirectionsRenderer through an attribute in directions-element. I thought maybe as an object that is passed to the DirectionsRenderer:

In markup:
<pre>
<code>&lt;directions ... renderer-options="'{routeIndex: 1}'"...></code>
</pre>

In code:
<pre>
<code>var showDirections = function(request) {
    directionsService.route(request, function(response, status) {
        if (status == google.maps.DirectionsStatus.OK) {
            $timeout(function() {
                renderer.setDirections(response);
                renderer.setOptions(rendererOptions);
                ...
</code>
</pre>

The routeIndex is stored in an entity when the user clicks through the different routes. Is that possible?

**Comment by allenhwkim** [comment]
This approach is little different from the original design, getting options from attribute individually.
Please try it with `route-index` or `options`.

**Comment by igler** [comment]
Have tried both but they don't make it into the options variable in updateRoute-function (line 740) where I could pick them up.

**Comment by igler** [comment]
Have found another solution which does not require any changes on ngMap-code.
