### ISSUE TITLE
Compatibility  with angular 5  remove OpaqueToken

### ISSUE THREAD

**Issue by vivex** [allenhwkim/angularjs-google-maps#853]
**IMPORTANT**: 

While using with angular 5 its giving following error: 

ERROR in node_modules/ng2-map/dist/services/config.d.ts(1,10): error TS2305: Module '"/home/vivex/Desktop/xyz/node_modules/@angular/core/core"' has no exported member 'OpaqueToken'.

**Steps to reproduce and a minimal demo(Plunker Example)**

  - _What steps should we try in your demo to see the problem?_

**Current behavior**

  - 

**Expected/desired behavior**

  - 

**Other information**

  -

**Comment by ssenechal5** [comment]
You closed this issue , dis you find how to fix it ?
