### ISSUE TITLE
Disabling "View on Google Maps" info windows?

### ISSUE THREAD

**Issue by langdonx** [allenhwkim/angularjs-google-maps#865]
Is there a way to disable the "places" from being interactive?  I like that they are there, but I don't want the Google to show the info window for them when clicked, because I'm using "map click" to let the user move an existing marker and those things are interfering.

![image](https://user-images.githubusercontent.com/441982/38438619-01381044-39a9-11e8-9507-ab589c32dde2.png)

**Comment by allenhwkim** [comment]
please try custom style
https://plnkr.co/edit/BipjcwNat3T8XAMU74EF?p=preview

**Comment by langdonx** [comment]
Works wonderfully btw, thank you!
