### ISSUE TITLE
Markers way off the real location

### ISSUE THREAD

**Issue by joelcipriano** [allenhwkim/angularjs-google-maps#866]
All markers are being applied at locations far from the correct coordinates.

[This is a modified Plunker](https://plnkr.co/edit/kQOjuD65TxlDnrsvJovS) of one of the official demos. I just changed the coordinates of the "[marker-simple](https://ngmap.github.io/#/!marker-simple.html)" demo.

Below is a screenshot of the Plunker above. Note that the correct point is where it has a blue dot, but the marker is being added well above and to the left of where it should be.

![screen shot 2018-04-12 at 14 46 09](https://user-images.githubusercontent.com/12474297/38694918-4227768c-3e61-11e8-9a1b-54fdab51dda5.png)

**Comment by allenhwkim** [comment]
It works for me. Please check your environment and different browsers.
![image](https://user-images.githubusercontent.com/1437734/38696122-37b71e3c-3e5c-11e8-8021-52ced3dde3a2.png)

**Comment by allenhwkim** [comment]
I think you need to ask Google, why the marker location is not correct.

**Comment by joelcipriano** [comment]
Can you please use [your official marker simple demo](https://ngmap.github.io/#/!marker-simple.html) with coordinates from a place that you know very well to see if you can reproduce this?

**Comment by allenhwkim** [comment]
The position is he exactly the same as google shows.

https://www.google.com/maps/place/8%C2%B003'34.8%22S+34%C2%B052'22.5%22W/@-8.0593644,-34.8739464,17.95z/data=!4m5!3m4!1s0x0:0x0!8m2!3d-8.0596563!4d-34.8729266

The location you are looking for is different, 8°03'38.9"S 34°52'17.7"W, according to Google

I am closing this, and if you are sure about the location, please report to Google. https://productforums.google.com/forum/#!forum/maps
