### ISSUE TITLE
ng-model values not updating when moving markers in directions directives

### ISSUE THREAD

**Issue by rajeshsmallarc** [allenhwkim/angularjs-google-maps#870]
Hi,

When i am dragging marker from a location to another, ng-model values are not updating.

Please help me.

**Comment by allenhwkim** [comment]
`angularjs-google-maps` does not provide two way binding. Please use on-drag function.

**Comment by rajeshsmallarc** [comment]
Thanks for reply @allenhwkim 

Can i use on-drag on directions directive ?
