### ISSUE TITLE
Console Error: Cannot read property 'parentElement' of null when using maps-lazy-load-params on NgMap page

### ISSUE THREAD

**Issue by nicholaspretorius** [allenhwkim/angularjs-google-maps#879]
Good day Allen, 

When viewing the NgMap demo page at: https://ngmap.github.io/#/!map-lazy-load-params.html 

A console error is displayed when clicking on the map marker to open the info window. 

**Steps to reproduce - no plunker provided as this exists on the NgMap demo page**

- Load url above with map-lazy-load-params example
- Open developer tools in Chrome
- Click on map marker to open an info window

**Current behavior**
- When clicking on the map marker, a console error is displayed with the message: 
TypeError: Cannot read property 'parentElement' of null
    at info-window.js:114
    at angular.js:16299
    at completeOutstandingRequest (angular.js:4924)
    at angular.js:5312" 

Line 114 of info-window.js 

```var infoWindowContainerEl = infoWindow.content.parentElement.parentElement.parentElement;```

![image](https://user-images.githubusercontent.com/805497/47836308-6c8d9200-ddb0-11e8-8768-458bd2cc3481.png)

**Expected/desired behavior**
 - Info window should open without a console error.

**Other information**
  - If you close the info-window and then open it again, there is no console error. 
 - This console error only happens on first load/click of the map marker.

**Comment by madmarcel** [comment]
I'm seeing the same issue. Working on a fix...

**Comment by mdorion1** [comment]
Any update on this?
I have the same problem in my project..

Thank you!

**Comment by allenhwkim** [comment]
I believe this happens because of a racing condition. I think Chrome browser tries perform faster than before. I can wrap like with a if condition
```
if (infoWindow.content.parentElement) {
  var infoWindowContainerEl = infoWindow.content.parentElement.parentElement.parentElement;
  infoWindowContainerEl.className = "ng-map-info-window";
}
```

**Comment by allenhwkim** [comment]
v1.18.5 is released with this fix

**Comment by bishtpradeep** [comment]
> v1.18.5 is released with this fix

HI Allenhwkim, when will you release this version v1.18.5 ? 
Thank you.

**Comment by Rouvo** [comment]
Hi @allenhwkim,
I really like your library, but I ran into the same bug.

When are you going to realease the mentioned version with the bug fix?

**Comment by wholeinsoul** [comment]
For future reference: It is released here.
//cdn.jsdelivr.net/npm/ngmap@1.18.5/build/scripts/ng-map.min.js"

> Hi @allenhwkim,
> I really like your library, but I ran into the same bug.
> 
> When are you going to realease the mentioned version with the bug fix?

**Comment by Rouvo** [comment]
Thanks for the quick reply, enjoy the day and thanks for your great work! 👍
