### ISSUE TITLE
map does not work in dialog on second invocation

### ISSUE THREAD

**Issue by kgignatyev** [allenhwkim/angularjs-google-maps#88]
Thank you for the directive, quite handy!
However when map is displayed in the modal dialog then it works fine on first invocation, but does not work properly on second: here is repro case, please click on 'Adjust Geo Location' to open dialog, then close it and click second time to see the issue
http://plnkr.co/edit/KxN7GoQkGnJBhQCyAiux?p=preview

as a workaround for now I am using timer (that is commented out in the script), but would be nice if that was not necessary.

![image](https://cloud.githubusercontent.com/assets/868783/4446888/303c5046-4806-11e4-83e6-654840a92803.png)

**Comment by axelosorio** [comment]
I have the same issue, and I resolve this with Jquery
I'm using Jquery to remove div code. In my case I was using the jquery dialog, then when I close the dialog I'm replacing the html from the div (where google maps is showing the map) with the original div code.

My original div code was 

    <div id="mapaLocalsub" style="width:500px; height:450px; " ></div>

I notice that after google maps was working it fills the div with a lot of things and style, then in the close function from my Jquery.dialog I'm replacing the html with my original div code:

    $( "#mapaLocal" ).dialog({
          height: 450,
          width: 500,
          modal: true,
          close: function() {
          $( "#mapaLocal" ).html("<div id=\"mapaLocalsub\" style=\"width:500px;     height:450px; \" ></div>");
          }
    });

But of course, you can use the Jquery html method in a function that you call when close the function or before creating your map, hope it helps.

    $( "#mapaLocal" ).html("<div id=\"mapaLocalsub\" style=\"width:500px;     height:450px; \" ></div>");

**Comment by james-bell** [comment]
For those (like me) struggling to find an answer to this:
HTML:
```html
<ng-map ng-if="subView=='map'" center="38,-98" zoom="5"></ng-map>
```
JS in controller init:
```javascript
$scope.$on('mapInitialized', function (event, map)
{
    window.setTimeout(function() {
      window.google.maps.event.trigger(map, 'resize');
      map.setCenter(new google.maps.LatLng(38,-98));
    }, 100)
});
```

**Comment by galenp** [comment]
A minor variation to the above if you don't have a lat/lng within scope to pass into setCenter.

```js
$scope.$on('mapInitialized', function (event, map)
{
    window.setTimeout(function() {
        var center = map.getCenter();
        window.google.maps.event.trigger(map, 'resize');
        map.setCenter(center);
    }, 100)
});
```

**Comment by wessamzaghloul** [comment]
it worked for me like that 
$scope.$on('mapInitialized', function(event, map) {
			var center = map.getCenter();
			google.maps.event.trigger(map,'resize');
			map.setCenter(center);
});

without timeout

**Comment by meysammahfouzi** [comment]
Initializing the map with 1 second delay worked for me:

```
$(document).ready(function () {
    setTimeout(init_map, 1000) 
});
```
