### ISSUE TITLE
how to resize icon?

### ISSUE THREAD

**Issue by ghost** [allenhwkim/angularjs-google-maps#92]
It seems too big for my icon from url for markers:

<marker data-ng-repeat="item in items"
      position="{{item.position}}"
      title="Hello Marker"
      icon="{{item.image}}"

**Comment by tewfik-ghariani** [comment]
Hello, I was confused why the icon of my marker wouldn't adjust to the scaledSize object i have inserted, 

Now i understand ! As a matter of fact, the scaledSize object wasn't an array but rather a json format.
Thanks a lot, this was so helpful

**Comment by nicolas15000** [comment]
Hello ! 
I wonder if somebody could help me : 
This is working well : 

> <marker ng-repeat="p in markersClubs" position="{{p.latitude}},{{p.longitude}}" title="{{p.nom}}" icon="{{p.img}}" on-mouseover="showClub(event,p.identifiant)" ></marker>

But this is not working, i'm trying out to resize my icons ;
`<marker ng-repeat="p in markersClubs" position="{{p.latitude}},{{p.longitude}}" title="{{p.nom}}" icon="{url:'{{p.img}}',scaledSize:[100,100],origin: [10,10],anchor: [50,50]}" on-mouseover="showClub(event,p.identifiant)" ></marker>`

p.img is not interpreted, i wonder if somebody could help me please.
